### ISSUE TITLE
DHCP relay information option circuit-id (DHCP Option 82)

### ISSUE THREAD

**Issue by inetman28** [aristanetworks/ansible-avd#1006]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Describe the solution you'd like**

In our environment we are using dhcp option circuit-id to inform dhcp-server information from which switch dhcp request was relayed. 

**Describe alternatives you've considered**

we have only one option which is create static configlet and assign to device or container

**Additional context**

We would like to have something like below:
```
interface Vlan104
   description PXE
   vrf TEST
   ip address 10.0.1.1/26
   ip dhcp relay all-subnets
   ip helper-address 10.15.0.11
   ip dhcp relay information option circuit-id sw1zone1
```

**Comment by inetman28** [comment]
oh ansible, it has great opportunity to modify anything.

I've resolved this problem like this:
```
custom_structured_configuration_vlan_interfaces:
  Vlan4092:
    shutdown: false
    vrf: INFRA
    ip_address: 10.15.1.146/24
    ip_virtual_router_address: 10.15.1.1
    mtu: 9100
    ip_helpers:
      5.5.5.5:
    eos_cli: ip dhcp relay information option circuit-id {{ inventory_hostname }}
```
