### ISSUE TITLE
custom_structured_configuration_static_routes replace static_routes but has to merge both

### ISSUE THREAD

**Issue by inetman28** [aristanetworks/ansible-avd#1010]
- [x] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

After we create some custom static routes under 
```
custom_structured_configuration_static_routes:
  - vrf: INFRA
    destination_address_prefix: 192.168.0.0/16
    gateway: Null0
```

the default route via vrf MGMT was deleted from configuration.

![image](https://user-images.githubusercontent.com/45913745/121183399-b2fed380-c86c-11eb-8af3-cd4d8cf1977c.png)

## Steps to reproduce
1. add below section to yaml
```
custom_structured_configuration_static_routes:
  - vrf: INFRA
    destination_address_prefix: 192.168.0.0/16
    gateway: Null0
```
2. run main playbook
3. you will see that default route via MGMT vrf was removed

### Expected results

I waited that custom_structured_configuration_static_routes will merged with static_routes in structured_configuration, but not. 

### Actual results
Structure_config don't have default route via MGMT VRF. This has only:
```
static_routes:
- vrf: INFRA
  destination_address_prefix: 192.168.0.0/16
  gateway: Null0
```
