### ISSUE TITLE
Add interface grouping support to eos_cli_config_gen

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1014]
**Issue Type**

- [x] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Related to #922

Given from out uplink/downlink concept of the switches when entering the Maintenance mode we required different port groups to be taken into account depending on the Switch model we use (7280SR2-48YC6 vs 7050CX3-32S).

**SFP+ Model**
```
group interface MM_Int_Group_SFP
   interface Et1-48
   maintenance profile interface downlinks
   exit
```

**QSFP Model**
```
group interface MM_Int_Group_QSFP
   interface Et11/-28/1
   maintenance profile interface downlinks
   exit
```

**Describe the solution you'd like**

Extend the Jinja2 templates from eos_cli_config_gen to support the interface group definition by the following data model:

```yaml
group:
  bgp:
    < group_name >:
      vrf: "< vrf_name >"
      neighbors:
        - "< ip_address >"
        - "< ipv6_address >"
        - "< peer_group_name >"
      maintenance_profile:
        bgp:
          - < profile_name >
  interface:
    < group_name >:
      interfaces:
        - "< interface_or_interface_range >"
      maintenance_profile:
        bgp:
          - < profile_name >
        interface:
          - < profile_name >
```

**Describe alternatives you've considered**

Using `custom_config` or `raw_eos_cli` is considered and implemented as a workaround but once this is implemented, support can be extended for the eos_designs role and the `platform_settings` key.

A PR implementing the above datamodel will follow soon - and of course can then be refined to meet your expectations.
