### ISSUE TITLE
Logging event link_status can't be set to False.

### ISSUE THREAD

**Issue by IDunkn0wn** [aristanetworks/ansible-avd#1026]
## Issue Type

- [x] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary
Ariste eos cli gen role has the following option:

```yaml
      logging:
        event:
          link_status: true
```
The value that link_status takes seems to only work when it's set to false, when setting the value to false, the eos_cli_config_gen  seems to ignore this value.

## Component Name
eos_cli_config_gen >> ethernet _interfaces / port_channel_interfaces

## Steps to reproduce
data model:
```yaml
ethernet_interfaces:
  Ethernet1:
    logging:
      event:
        link_status: false
```

### Expected results

expected generated cli:

```shell
!
interface Ethernet1
   no logging event link-status
   switchport
!
```

### Actual results
```shell
!
interface Ethernet1
   switchport
!
```
