### ISSUE TITLE
timestamp the snapshot directory

### ISSUE THREAD

**Issue by ksator** [aristanetworks/ansible-avd#1039]
**Issue Type**

- [x] Role enhancement

**Is your feature request related to a problem? Please describe.**

`eos_snapshot` role  

currently it uses this default variables: 
```
# defaults file for eos_snapshot
root_dir: '{{ inventory_dir }}'
snapshots_backup_dir_name: 'snapshots'
snapshots_backup_dir: '{{ root_dir }}/{{ snapshots_backup_dir_name }}'
```
```
- name: Create output directory for each EOS device
  file:
    path: "{{ snapshots_backup_dir }}/{{ inventory_hostname }}"
    state: directory
    mode: 0775
  when: ("text" in output_format or "markdown" in output_format)

- name: save collected commands in text files
  template:
    src: device_text_command.j2
    dest: "{{ snapshots_backup_dir }}/{{ inventory_hostname }}/{{ item.item }}.txt"
    mode: 0664
  loop: "{{ cli_output.results }}"
  when: "'text' in output_format"
```
so if you run it several times without changing the value of the var `snapshots_backup_dir_name` (using --extra-vars as example) the new data will erase the previous one because of the same dir name.  

**Describe the solution you'd like**

add by default the date to the directory name, so, you can keep several snapshots.  

```
- name: Setting host facts
  set_fact:
    date: "{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"
  delegate_to: localhost
  run_once: true

- name: Create output directory for each EOS device
  file:
    path: "{{ snapshots_backup_dir }}_{{ date }}"
    state: directory
  when: ("text" in output_format or "markdown" in output_format)
  delegate_to: localhost
  run_once: true
```

and if you want, you can still use extra-vars to control explicitly the directory name.
