### ISSUE TITLE
timestamp the reports directory

### ISSUE THREAD

**Issue by ksator** [aristanetworks/ansible-avd#1040]
**Issue Type**

- [x] Role enhancement

**Is your feature request related to a problem? Please describe.**

`eos_eos_validate_state` role  

currently it uses this default variables: 
```
# Format for path to r/w reports. Sync with default values configured in arista.avd.build_output_folders
root_dir: '{{ inventory_dir }}'
eos_validate_state_name: 'reports'
eos_validate_state_dir: '{{ root_dir }}/{{ eos_validate_state_name }}'

# Reports name
eos_validate_state_md_report_path: '{{ eos_validate_state_dir }}/{{ fabric_name }}-state.md'
eos_validate_state_csv_report_path: '{{ eos_validate_state_dir }}/{{ fabric_name }}-state.csv'
```
```
- name: Create Validation report - CSV
  template:
    src: validate_state_report-csv.j2
    dest: "{{ eos_validate_state_csv_report_path }}"
    mode: 0664
  delegate_to: localhost
  run_once: true
  tags:
    - always
    - report
```
so if you run it several times without changing the value of the var `eos_validate_state_name` (using --extra-vars as example) the new data will erase the previous one because of the same dir name.  

**Describe the solution you'd like**

add by default the date to the directory name, so, you can keep several snapshots.  

and if you want, you can still use extra-vars to control explicitly the directory name.
