### ISSUE TITLE
Support for ip as-path access-list

### ISSUE THREAD

**Issue by burnyd** [aristanetworks/ansible-avd#1042]
## Issue Type

- [X] New Feature

## Summary

In eos_cli_config_gen we have support for both extended and standard access-lists.  We however are requesting support for ip as-path access-lists either permitting a list of AS#'s pr denying a list of AS#'s.

For example,

ip as-path access-list BGP-ACL deny _65400_ any
ip as-path access-list BGP-ACL deny _65400_ any
ip as-path access-list BGP-ACL deny _65200_ any
ip as-path access-list BGP-ACL deny _4200009999_ any
ip as-path access-list BGP-ACL permit .* any
ip as-path access-list BGP-ACL deny _65400_ any
ip as-path access-list BGP-ACL deny _65200_ any
ip as-path access-list BGP-ACL deny _4200009999_ any
ip as-path access-list BGP-ACL permit .* any

I would imagine this would have a dictionary containing the following..

```yaml
as-path:
    - name: string
      action: permit || deny 
      aspath: list 
      any: optional any string 
```

## Component Name

eos_cli_config_gen/templates/eos/acess-lists.j2
eos_cli_config_gen/templates/documentation/acess-lists.j2

If agreed upon I can put through a PR referencing the  eos_cli_config_gen/templates/eos/acess-lists.j2 && 
eos_cli_config_gen/templates/documentation/acess-lists.j2 adding this to the current access-list jinja2 templates unless we want to add a new one?

**Comment by ClausHolbechArista** [comment]
Alternative data model proposal - see inspiration in the other [filters](https://www.avd.sh/en/latest/roles/eos_cli_config_gen/index.html#filters).
```yaml
ip_as_path_access_lists:
  < as_path_acl_1 >:
    - type: < permit | deny >
      regexp: "< string >"
```
