### ISSUE TITLE
Support for link tracking in EVPN environments. 

### ISSUE THREAD

**Issue by burnyd** [aristanetworks/ansible-avd#1043]
## Issue Type

- [X] New Feature

## Summary

In most environments that run EVPN-MH or sometimes EVPN-MLAG we need the capability that if upstream spine links will go down that the MLAG port-channel to downstream interfaces (servers) also goes down and does not forward traffic where it would then be black holed. 

A common CLI would look like the following.

link tracking group FOO
   recovery delay 300
!

! upstream interface
interface Ethernet3
   link tracking group FOO upstream
!

! downstream interface
interface Port-Channel1
   switchport access vlan 30
   !
   evpn ethernet-segment
      identifier 0000:0000:0000:0000:3030
      route-target import 30:30:30:30:30:30
   lacp system-id 3030.3030.3030
   link tracking group FOO downstream
!

Where the Ethernet 3 interface would be the spine uplink and the port-channel1 would be the downstream connection to the server.

I would imagine this would have a dictionary containing the following..

## Component Name

eos_cli_config_gen/templates/eos/port-channel-interfaces.j2
eos_cli_config_gen/templates/eos/ethernet-interfaces.j2
+ eos_cli_config_gen/templates/eos/link-tracking.j2
eos_cli_config_gen/templates/documentation/port-channel-interfaces.j2
eos_cli_config_gen/templates/documentation/ethernet-interfaces.j2
+ eos_cli_config_gen/templates/documentation/link-tracking.j2

I would imagine the model would look like the following.

#### link-tracking
```yaml
link-tracking:
    - group_name: string
      delay: int32 
```

#### ethernet-interfaces
```yaml
ethernet_interfaces:
  <Ethernet_interface_1 >:
    link_tracking: <true | false>
      - name: string 
        direction: upstream | downstream
```

#### portchannel-interfaces
```yaml
port_channel_interfaces:
  < Port-Channel_interface_1 >:
    link_tracking: <true | false>
      - name: string 
        direction: upstream | downstream
```

This is very common within EVPN-MH environments if agreed upon please suggest this model or we can put in a PR to add to the ethernet/port-channel interfaces and potentially add a new j2 template for link-tracking.

**Comment by ClausHolbechArista** [comment]
Alternative proposal. We try to use dicts instead of lists where we can.

#### link-tracking
```yaml
link_tracking_groups:
  < group_name >:
    links_minimum: < number >
    recovery_delay: < 0-3600 >
```

#### ethernet-interfaces
```yaml
ethernet_interfaces:
  <Ethernet_interface_1 >:
    link_tracking_groups:
      < group_name >: < upstream | downstream >
```

#### portchannel-interfaces
```yaml
port_channel_interfaces:
  < Port-Channel_interface_1 >:
    link_tracking_groups:
      < group_name >: < upstream | downstream >
```

If it makes it more clear, we can add the `direction` key under the `group_name` for the interfaces

**Comment by burnyd** [comment]
LGTM!

**Comment by ClausHolbechArista** [comment]
@burnyd Will you work on this, or do you want me to take a stab at it?

**Comment by tgodaA** [comment]
I am working on this.

#### link-tracking
```yaml
link_tracking_groups:
  - group_name: <group_name>
    links_minimum: < number >
    recovery_delay: < 0-3600 >
```

#### ethernet-interfaces
```yaml
ethernet_interfaces:
  <Ethernet_interface_1 >:
    link_tracking_groups:
      - group_name: < group_name >
        direction: < upstream | downstream | default -> upstream >
```

#### portchannel-interfaces
```yaml
port_channel_interfaces:
  < Port-Channel_interface_1 >:
    link_tracking_groups:
      - group_name: < group_name >
        direction: < upstream | downstream | default -> downstream >
```

Should we add this to eos_designs to automatically enable this feature by default for EVPN MH?
