### ISSUE TITLE
eos_designs: 7280R/R2 platform default mlag reload delay too low

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#1046]
## Issue Type

- [x] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

I have experienced a topic during EOS updates done by CVP change control yesterday.
I included the CVP MLAG Health Check in CC but it failed with all 7280R/R2 switches.

I recognized the "show mlag issu warnings" in the logs that the reload-delay is too low.
```bash
show mlag issu warnings
The configured reload delay of 780 seconds is below the recommended
value of 900 seconds. A longer reload delay allows more time to
rollback an unsuccessful upgrade due to incompatibility.
```

The current AVD default value for 7280R/R2 is at 780 seconds but should be at least at 900 seconds based on the latest EOS.

```yaml
platform_settings:
    <snip>
  - platforms: [ 7800R3, 7500R3, 7500R, 7280R3, 7280R2, 7280R ]
    tcam_profile: vxlan-routing
    lag_hardware_only: true
    reload_delay:
      mlag: 780
      non_mlag: 1020
```

Could you please doublecheck this settings, if it would be useful to adjust your default values too.

## Component Name
eos_designs

## Steps to reproduce

```yaml

```

### Expected results

```shell
$
```

### Actual results

```shell

```
