### ISSUE TITLE
eos_designs - mtu applied on subinterfaces instead of parent interface

### ISSUE THREAD

**Issue by ernestoherrerab** [aristanetworks/ansible-avd#1051]
## Issue Type

- [X] EOS Configuration rendering error

## Summary

When adding subinterfaces to l3_interfaces on the network services variables, the mtu is applied to the sub interface and not to the parent interface which results in an error when applying the configuration.

This has been tested on vEOS instances.

## Component Name
arista.avd.eos_designs

## Steps to reproduce

add mtu to a subinterface under the relevant tenant and relevant vrf.

```
tenants:
  tenant_1:
    vrfs:
      GENERAL: 
        l3_interfaces:
          - interfaces: [Ethernet6.1, Ethernet6.1]
             mtu: 1500
```

### Expected results

```
The mtu value is applied to the parent interface.
interface Ethernet6
  mtu 1500
```

### Actual results

T

```
The mtu value is applied to the subinterface.
interface Ethernet6.1
  mtu 1500

```

**Comment by ClausHolbechArista** [comment]
The MTU setting on a sub-interface is only applicable to some platforms like the R-Series. Since we cannot ensure if the platform has a certain capability or not, we supply the option to define it on both levels.
With switches like 7050SX3 you should instead define the underlying interface yourself:
```yaml
tenants:
  tenant_1:
    vrfs:
      GENERAL: 
        l3_interfaces:
          - interfaces: [Ethernet6, Ethernet6]
             mtu: 1500
          - interfaces: [Ethernet6.1, Ethernet6.1]
            <...>
```
I will add a comment to the mtu field under subinterface section in the documentation. Thank you for pointing this out!
