### ISSUE TITLE
Check if vxlan needs to be enabled before setting the vxlan-routing tcam profile

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#1055]
## Issue Type

- [ ] Bug Report

## Summary

Configuring Spines with the platform 7500 configures automatically vxlan-routing tcam profile. We should check if vxlan is enabled first. In my scenario this platform is used in the Spines which are not vteps, and they do not neeed this tcam profile.

## Steps to reproduce

1. Configure any of this platforms: 7800R3, 7500R3, 7500R, 7280R3, 7280R2, 7280R
2. vxlan tcam profile is automatically enabled

```
  - platforms: [7800R3, 7500R3, 7500R, 7280R3, 7280R2, 7280R]
    tcam_profile: vxlan-routing
    lag_hardware_only: true
    reload_delay:
      mlag: 780
      non_mlag: 1020
```

### Expected results
Check if the device is a vtep or has vxlan enabled, otherwise leave the default tcam profile.

**Comment by onurgashi** [comment]
Hey @dgonzalez85 these are the default vars. You can always override them in your `FABRIC.yml`

```
  - platforms: [7800R3, 7500R3, 7500R]
    lag_hardware_only: true
    reload_delay:
      mlag: 780
      non_mlag: 1020
```

Or make custom ones

```
  - platforms: [7280R3, 7280R2, 7280R]
    tcam_profile: vxlan-routing
    lag_hardware_only: true
  - platforms: [7800R3, 7500R3, 7500R]
    lag_hardware_only: true
    reload_delay:
      mlag: 780
      non_mlag: 1020

```

I understand that probably to have some logic makes sense, but that should help for a start.
