### ISSUE TITLE
When vlan4093 is not used for the mlag ibgp peering, BGP neighbour addressing is not updated

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#1057]
## Issue Type

- [x] Bug Report

## Summary
Even when setting the option below to the vlan4094, SVI 4093 and L2 4093 vlan is not defined in the config files. However, addressing of vlan4093 is still used to peer over the MLAG:

## Steps to reproduce
1.  Set vlan 4094 for the mlag peering:
```
mlag_peer_l3_vlan: 4094
```
2. BGP Peering should use the addressing now of vlan 4094, but still uses the one from vlan 4093 even if its not defined:
```
neighbor 10.255.253.1 peer group MLAG-IPv4-UNDERLAY-PEER
neighbor 10.255.253.1 description DC1-LEAF1B
```

### Expected results
Addressing from vlan4094 should be used instead:
```
interface Vlan4094
   description MLAG_PEER
   no shutdown
   mtu 9214
   no autostate
   ip address 10.255.254.0/31
```

### Actual results
Addressing defined in the fabric.yml file for vlan 4093 is used instead.

**Comment by ClausHolbechArista** [comment]
@dgonzalez85 This is not something we claim support for today, but it may still work, if you set the same IP scope for both vlans. 
From the `Fabric Variables` documentation:
```
# IP address summary used for MLAG Peer Link (control link) and underlay L3 peering | *Required
# * When MLAG leafs present in topology.
# Assign range larger then total: L3 Leafs + 2 ]
mlag_ips:
  leaf_peer_l3: < IPv4_network/Mask >
  mlag_peer: < IPv4_network/Mask >
```

You may see wrong descriptions on vlan and SVI with this trick, since the data model for peer_vlan is simply overwritten by the l3_peer_vlan definitions.

We can convert this to a feature request, if we should build a more robust implementation. Example we could detect if the vlan is the same and adapt the generated config.
