### ISSUE TITLE
Add filters using prefix lists for router OSPF on cli config gen

### ISSUE THREAD

**Issue by ernestoherrerab** [aristanetworks/ansible-avd#1062]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**
Sort of, we are migrating to EVPN/VXLAN and some of our existing OSPF areas are using prefix lists using route maps, since route maps are seemingly not supported on EOS, prefix lists can be a substitute. It would help a lot with the translation of these filters if this feature already existed.

There is no structured data in the router ospf configuration on the cli config gen for filter-list using prefix-list

**Describe the solution you'd like**
It would be great to have the support for:

- filter-list
- filter list using prefix-list
- filter list specifying the direction

**Describe alternatives you've considered**

add the following structured data as below (for example):

```yaml
router_ospf:
process_id:
        '2':
          area:
            0.0.0.1:
              filter_list:
              - direction: out
                prefix_list: block_all_route_out
              - direction: in
                prefix_list: allow_only_host_in
```

**Additional context**
