### ISSUE TITLE
Add OSPF timers in Cli config gen

### ISSUE THREAD

**Issue by ernestoherrerab** [aristanetworks/ansible-avd#1067]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**
No.

There is no structured data in the router ospf configuration on the cli config gen for timers: throttle, lsa, spf, etc

**Describe the solution you'd like**

To have a key in the router_ospf section for timers

**Describe alternatives you've considered**

Add keys for the timers

Something like:

```yaml
router_ospf:
 '2':
   timers:
      throttle:
          sfp: <string as value>
          lsa: <string as value>
      lsa:
         rx: <string as value>
         tx: <string as value>
```

**Additional context**
