### ISSUE TITLE
Add support for  'error-correction encoding' to the eos_cli_config_gen role for Ethernet interfaces

### ISSUE THREAD

**Issue by IDunkn0wn** [aristanetworks/ansible-avd#1079]
**Issue Type**

- [x] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**
when interconnecting arista with cisco, we need to use the following command which is not available on the latest AVD release:
error-correction encoding fire-code

**Describe the solution you'd like**
What we would like, is a data model like the following under the ethernet_interfaces template:

```
error_correction:
  encording: 
  - fire-code
  - reed-solomon
```

**Describe alternatives you've considered**

None found so far.

**Additional context**

the eos_cli_config_gen role on the Ethernet_interfaces template needs to be updated for the changes.

**Comment by ClausHolbechArista** [comment]
A third option is to disable error-correction encoding, so I suggest to modify the model:
```yaml
error_correction_encoding:
  enabled: < true | false | default -> true >
  fire_code: < true | false | default -> true >
  reed_solomon: < true | false | default -> true >
```

**Comment by tgodaA** [comment]
I am working on this model:
```
error_correction_encoding:
  enabled: < true | false | default -> true >
  fire_code: < true | false >
  reed_solomon: < true | false >

```

These are the available options that I could see:
```
CL(config-if-Et5)#error-correction encoding ?
  fire-code     Configure Fire code (BASE-R) forward error correction
  reed-solomon  Configure Reed-Solomon (RS-FEC) forward error correction

```

After configuring:
```
CL(config-if-Et5)#sh active
interface Ethernet5
   error-correction encoding fire-code
   error-correction encoding reed-solomon

```

Other options with ```no```:
```
CL(config-if-Et5)#no error-correction encoding ?
  fire-code     Configure Fire code (BASE-R) forward error correction
  reed-solomon  Configure Reed-Solomon (RS-FEC) forward error correction
  <cr>         
 
```

After configuring:

```
CL(config-if-Et5)#sh ac
interface Ethernet5
   no error-correction encoding

```
