### ISSUE TITLE
OSPF: Missing support for redistribution of BGP routes

### ISSUE THREAD

**Issue by SomaliRaven** [aristanetworks/ansible-avd#1081]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

It is not possible to configure redistribution of bgp routes into ospf.

**Describe the solution you'd like**

Implement redistribution of bgp routes into ospf the same way as with static and connected routes.

```yaml
router_ospf:
  process_ids:
    < process_id >:
      redistribute:
        static:
          route_map: < route_map_name >
        connected:
          route_map: < route_map_name >
        bgp:
          route_map: < route_map_name >

```
