### ISSUE TITLE
Support "transceiver media override" on "ethernet_interfaces" in eos_cli_config_gen

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#1084]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Setting transceiver type manually if EOS is not able to detect it correctly.

**Describe the solution you'd like**

```yaml
ethernet_interfaces:
  < ethernet_interface >:
    transceiver:
      media:
        override: < transceiver_type >
``` 

**Describe alternatives you've considered**

eos_cli

**Additional context**
