### ISSUE TITLE
normalize strings to lower in arista.avd.defined test plugin

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#1089]
**Issue Type**

- [ ] Template enhancement
- [ ] Role enhancement
- [x] Plugin enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

When leveraging the arista.avd.defined() test plugin, always evaluate data in lower cases, to avoid having to use `| lower` filter plugin.

example if 

```yaml
router_ospf:
  process_ids:
    600:
      areas:
        0.0.0.1:
        0.0.10.11:
          type: STUB
          no_summary: true
        0.0.20.20:
          type: NSSA
```

```jinja2
{# with lower filter plugin #}
{%  if router_ospf.process_ids[process_id].areas[area].type is arista.avd.defined | lower == nssa %}

{# Without lower filter plugin #}
{%  if router_ospf.process_ids[process_id].areas[area].type is arista.avd.defined("nssa") %}
```

**Describe the solution you'd like**

Implement `| lower` filter capabilities in arista.avd.defined tests

**Describe alternatives you've considered**

Write tests with `| lower` filter.
