### ISSUE TITLE
config generated fails to deploy when for mac_vrf_vni_base greater than 100,000

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#109]
## Issue Type
- Bug Report

## Summary

When specifying a larger number i.e < 100,000 for mac_vrf_vni_base, the auto-generated route distinguisher and route-target for network defined in l2vlans are not valid EOS syntax.

## Role or Module Name

arista.avd 1.0.1
role: eos_l3ls_evpn

## OS / Environment

EOS 4.22.4M

## Steps to reproduce

```yaml
tenants:
# Tenant A Specific Information - VRFs / VLANs
  Tenant_A:
    mac_vrf_vni_base: 90000
    vrfs:
      Tenant_A_OP_Zone:
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24
        svis:
          110:
            name: Tenant_A_OP_Zone_1
            tags: [ opzone ]
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          111:
            vni_override: 50111
            name: Tenant_A_OP_Zone_2
            tags: [ opzone ]
            enabled: true
            ip_address_virtual: 10.1.11.1/24
    l2vlans:
      160:
        vni_override: 50160
        name: Tenant_A_VMOTION
        tags: [ vmotion ]
      161:
        name: Tenant_A_NFS
        tags: [ nfs ]
```

results in an incompatible configuration

```EOS
   vlan-aware-bundle Tenant_A_NFS
      rd 192.168.255.6:90161
      route-target both 90161:90161
```

### Actual results
From @ the CLI:

```EOS
DC1-LEAF2A(config-if-Vx1)#router bgp 65102
DC1-LEAF2A(config-router-bgp)#   vlan-aware-bundle Tenant_A_NFS
DC1-LEAF2A(config-macvrf-Tenant_A_NFS)#      rd 192.168.255.6:90161
% Ambiguous command
DC1-LEAF2A(config-macvrf-Tenant_A_NFS)#      route-target both 90161:90161
% Invalid input
```
