### ISSUE TITLE
Issue: ntp_servers preferred

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1091]
## Issue Type

- [ ] Bug Report
- [X] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

`ntp_servers` preferred is set by associating the first ntp_server in the list of ntp_servers as the preferred.

This is not how eos would handle or render this config because ntp servers are placed in the config in sorted by IP.  Thus the logic of avd.eos_cli_config_gen contradicts EOS in that if you sort the ntp servers in order of IP, the first IP would automatically be set as the preferred server.

## Component Name

eos_cli_config_gen

## Steps to reproduce

```yaml
ntp_server:
  nodes:
    100.100.100.100: 
      preferred: true
    10.10.10.10: {}
```

### Expected results

I would expect this sort of data model to exist and render:
```cfg
ntp server 10.10.10.10
ntp server 100.100.100.100 prefer
```

### Actual results

```yaml
ntp_server:
  nodes:
    - 100.100.100.100:
    - 10.10.10.10
```

Renders
```cfg
ntp server 100.100.100.100 prefer
ntp server 10.10.10.10
```

**Comment by colinmacgiolla** [comment]
I'm preserving the existing behaviour of first entry is perferred, but addressing the ordering.

Longer term enhancing the data-model to allow flags like `perferred: true` or `iburst: true` is probably a good idea.

**Comment by carlbuchmann** [comment]
@colinmacgiolla - I think now is a good time to change the data model in `eos_cli_config_gen`, since we are going to the new major version and have the ability to introduce data model changes.

We can preserve the abstraction/behavior in the `eos_designs` role.

**Comment by colinmacgiolla** [comment]
Works for me, the pull will fix the issue in the current major version.

What do we think about the following as the new schema:
```yml
ntp:
   authenticate: < true | false >
   authentication_keys:
      - < id (1 - 65535) >:
         hash_algorithm: < md5 | sha1 >
         key: < string >
   trusted_keys: < key ids e.g. 1,2,5>
ntp_server:
    nodes:
      - < IP | hostname >:
            burst: < true | false >
            iburst:  < true | false >
            key: < 1 - 65535 >
            < local-interface | source >: < Ethernet | Loopback | Management | Port-Channel | Tunnel | Vlan >
            maxpoll: < 3 - 17 (logorithmic)>
            minpoll: < 3 - 17 (logorithmic)>
            prefer: < true | false >			
            version: < 1 - 4 >
```
With the requirements that the generated config has;
1. The keys are sorted by ID, numerically, regardless of order of entry
2. The nodes are sorted by IP, then by name, regardless of order of entry
3. The first entry in the node list is no longer considered to be preferred

If this seems agreeable, I'll start a new fork around the new schema. 
I'm inclined to merge the ntp and ntp_servers jinja templates, but I don't feel strongly about it one way or the other - thoughts?
