### ISSUE TITLE
Support for vlan translation 

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#1093]
**Issue Type**

- [X] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

Ability to support overlapping vlans from customers in the same device using vlan translation with EVPN.

Vlan translation gives the user the ability to map packets from one vlan to another internal vlan (only for tagged frames) rewriting the VID field. Then,  this internal vlan can be mapped to a VXLAN Virtual Network Identifier (VNI) thus enabling overlapping customer vlans to participate in different VXLAN segments. 

```
interface Ethernet20/1
   switchport mode trunk
   switchport vlan translation c_vlan internal_vlan1
   switchport vlan translation c_vlan internal_vlan2
```

**Describe the solution you'd like**

Support this natively on the SERVERS.yml file.

**Describe alternatives you've considered**

We can today do the following configuration as a workaround using "raw_eos_cli"
```
  server01:
    rack: RackA
    adapters:
      - type: nic
        server_ports: [Eth0, Eth1]
        switch_ports: [Ethernet20/1, Ethernet20/1]
        switches: [CL-1, CL-2]
        profile: Util_server
        port_channel:
          description: PortChanne1
          mode: active
          short_esi: 0011:1100:0001
          raw_eos_cli:
            switchport vlan translation 10 20
          
            switchport vlan translation 11 21
```

**Comment by ClausHolbechArista** [comment]
Already implemented in `eos_cli_config_gen` by #1071. Can be leveraged on `adapters` in `eos_designs` by using `structured_config`. 
So this Issue is about adding native support to `eos_designs`.

**Comment by dgonzalez-arista** [comment]
Thanks Claus. I missed that was supported, as you said maybe at some point its good to have in eos_designs but great if this is available already via eos_cli_config_gen:

```
vlan_translations:
      - from: < list of vlans as string (only one vlan if direction is "both") >
        to: < vlan_id >
```

https://avd.sh/en/releases-v3.x.x/roles/eos_cli_config_gen/index.html

thanks

**Comment by tgodaA** [comment]
Hi David you can try the below:

```yaml
server01:
  rack: RackA
  adapters:
    - type: nic
      server_ports: [Eth0, Eth1]
      switch_ports: [Ethernet20/1, Ethernet20/1]
      switches: [CL-1, CL-2]
      profile: Util_server
      structured_config:
        vlan_translations:
          - from: < list of vlans as string (only one vlan if direction is "both") >
            to: < vlan_id >
```

**Comment by dgonzalez-arista** [comment]
Hi Tony,

Structured config works for me thanks. However i tried some configuration like this:
```
          structured_config: 
            vlan_translations:
               - from: 10,11,12
                 to: 13,14,15
```

And CLI config generated with AVD is the following with a single command for all mappings:
```
   switchport vlan translation 10,11,12 13,14,15
```
That syntax though does not seem correct, at least im trying it on T3. And also the Arista configuration guide seems to expect a 1:1 mapping and a single link command:

https://www.arista.com/en/um-eos/eos-virtual-lans-vlans#xx1262637
```
switch(config)#interface ethernet 5
switch(config-if-Et5)#switchport vlan translation 50 60
switch(config-if-Et5)#switchport vlan translation 61 71
switch(config-if-Et5)#switchport vlan translation 62 72
```

Not sure if this is a bug or some other platform supports that syntax. is there any way to generate the single vlan translation commands?

thks

**Comment by tgodaA** [comment]
Because your direction is both. Just use one vlan at once instead of a list.

```yaml
structured_config: 
  vlan_translations:
     - from: 10
       to: 13
     - from: 11
       to: 14
     - from: 12
       to: 15
```

![image](https://user-images.githubusercontent.com/88734745/147922170-bdd41068-aa32-4695-bf95-ef97d3369baf.png)
