### ISSUE TITLE
Support for connectivity monitor

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#1094]
**Issue Type**

- [X] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

Looking for a way to monitor reachability of end devices within a VRF and inter-VRF using connectivity monitor and ideally all this configuration can be also automated via AVD:

https://eos.arista.com/eos-4-20-1f/connectivity-monitor/
https://eos.arista.com/toi/cvp-2021-1-0/connectivity-monitor-with-vrf-support/

This configuration should be device specific, could be done in the "host_var" yml file.

Configuration in EOS:
```
monitor connectivity
   vrf red
      host server1
         ip 10.10.10.10
   interval 5
   no shutdown
```
Resulting in continuos monitoring from the switch. This data will be available through CVP and customer is interested in getting notifications when an event occurs:
```
CL-1#show monitor connectivity

VRF: red
Host: server1
Network Statistics:
   IP Address        Local Interface       Latency       Jitter     Packet Loss
----------------- --------------------- ------------- ------------- -----------
   10.10.10.10       none                  0.098ms       0.039ms    0%
```

**Limitation**

Note: for EVPN symmetric in non-default vrf, tipically we will only have a loopback address defined with a unique address to be able to ping, traceroute etc:
```
interface Loopback100
   description red_VTEP_DIAGNOSTICS
   vrf red
   ip address 10.10.6.3/32

ip address virtual source-nat vrf Util_iDMZ address 10.10.6.3
```

As of 4.24.2F:

- Only IPv4 hosts are supported.
- Only source interface is configurable and not egress interface.
- Source interface configuration in connectivity monitor is only supported for physical interfaces.

However currently it is not possible to specify a loopback source interface but it will be automatically picked up when no address is specified:
```
 Arista Networks), ethertype IPv4 (0x0800), length 98: 10.10.10.10 > 10.10.6.3: ICMP echo reply, id 9006, seq 4, length 64
12:56:13.925701 74:83:ef:25:a7:12 (oui Unknown) > 00:1c:73:14:f0:54 (oui Arista Networks), ethertype IPv4 (0x0800), length 98: 10.10.6.3 > 10.10.10.10: ICMP echo request, id 9006, seq 5, length 64
12:56:13.925717 00:1c:73:14:f0:54 (oui Arista Networks) > 00:1c:73:00:dc:01 (oui Arista Networks), ethertype IPv4 (0x0800), length 98: 10.10.10.10 > 10.10.6.3: ICMP echo reply, id 9006, seq 5, length 64
```
Optionally also support to configure physical source interfaces and URLs:
```
monitor connectivity
   vrf vrf1
      interface set IS0vrf1 Ethernet60/1,Ethernet60/4
      interface set IS1vrf1 Ethernet35/1,Ethernet45/1
      local-interfaces IS0vrf1 address-only default
      !
      host hostvrf1
         ip 1.0.7.2
         url http://1.0.7.2
   no shutdown
```

**Comment by sengarth** [comment]
The model for monitor connectivity options such as:
```yaml
monitor:
  connectivity:
    shutdown: false
    interval: 5
    interface_set:
      global_ints: Et1-4
    local_interfaces: global_ints
    hosts:
      global_server:
        description: global server description here
        ip: 4.5.6.7
        url: https://server.global
        local_interfaces: global_ints
    vrfs:
      red:
        interface_set:
          intf_set_range: Et1,2-4
        description: VRF MGMT description here
        local_interfaces: intf_set_range
        hosts:
          server1:
            description: server1 connectivity monitor
            ip: 10.2.3.4
            url: https://server1.local
```

This allows configuration at vrf specific level as well as global configuration level. 

For describing interface sets, I think that it should allow free text definition because EOS can interpret text such as
```yaml
interface_set:
          intf_set_range: Et1,2-4
```
into
```
interface set intf_set_range Ethernet1,Ethernet2,Ethernet3,Ethernet4
```

**Comment by carlbuchmann** [comment]
@sengarth - here's what I would suggest which is a little more compact,a way to better handle default interface set "local-interfaces"
I'm ok with the proposed way of accepting interface ranges - we had something similar recently... will try and find the template @ClausHolbechArista do you remember which one?

```yaml
monitor_connectivity:
  shutdown: < true | false >
  interval: < interval >
  interface_sets:
    < interface_set >:
      interfaces:
          - "< interface_or_interface_range >"
  default_interface_set: < interface_set > # renders local-interfaces  Configure the default interface set for probing
    hosts:
      < host >
        description: < description >
        ip: < ip_address >
        url: < url >
        default_interface_set: < interface_set > # renders local-interfaces  Configure the default interface set for probing
    vrfs:
      < vrf >:
        interface_sets:
          < interface_set >
        description: < description >
        default_interface_set: < interface_set > # renders local-interfaces  Configure the default interface set for probing
        hosts:
         < host >:
            description: < description >
            ip: < ip_address >
            url: < url >
```

@ClausHolbechArista @aphillipps - Can you also provide feedback on data model?

**Comment by ClausHolbechArista** [comment]
So the `default_interface_set` actually renders `local_interface`? Seems like too much interpretation for `eos_cli_config_gen`.
The other one with ranges was maintenance groups.

**Comment by carlbuchmann** [comment]
@ClausHolbechArista - I agree with you it seems like a bit too much interpretation, however, the CLI for this command is a little bit odd! Please let me know what you would suggest!

```shell
EOS-DUT(config-mon-connectivity)#?
  local-interfaces  Configure the default interface set for probing
EOS-DUT(config-mc-test)#local-interfaces ?
  WORD  Interface sets
EOS-DUT(config-mon-connectivity)#local-interfaces test ?
  address-only  Use interfaces for source addresses only
EOS-DUT(config-mon-connectivity)#local-interfaces test address-only ?
  default  Configure the given interface set as default
EOS-DUT(config-mon-connectivity)#local-interfaces test address-only default 
```

For interface range, we should stay with the same model as implemented in PR #1017 - I have updated the data model above accordingly.

**Comment by sengarth** [comment]
Just to highlight 2 (maybe important) CLI behaviors observed here is that it doesn't allow mixing of interface types when specifying ranges, for example:
```eos
ve1(config-mon-connectivity)#interface set test Et1,2-4,Loopback0
% Invalid input
```

Interface set of a single interface type is allowed
```eos
ve1(config-mon-connectivity)#interface set test Loopback0-1
ve1(config-mon-connectivity)#show run sec monitor
monitor connectivity
   interface set test Loopback0,Loopback1
```

this is also consistent through many CLI range commands though, for example it prevents different interface types in global config mode:
```
ve1(config)#interface et1-2,po11-12
% Invalid input
```

2nd behavior (and this is different from group interface range) is the command isn't additive:
```
ve1(config-mon-connectivity)#interface set test et1
ve1(config-mon-connectivity)#interface set test et2
ve1(config-mon-connectivity)#interface set test et3

ve1(config-mon-connectivity)#show run sec monitor connectivity
monitor connectivity
   interface set test Ethernet3
```

Interface group behavior:
```
ve1(config)#group interface testgroup
ve1(config-group-if-testgroup)#interface et1
ve1(config-group-if-testgroup)#interface et2
ve1(config-group-if-testgroup)#interface et3
ve1(config-group-if-testgroup)#show run sec testgroup
group interface testgroup
   interface Et1-3
   exit
```
In effect, this differing interpretation behaviour in CLI for interface set may nullify the need for a list model. For consistency sake however, we can still concatenate all elements to prevent overriding.

@carlbuchmann @ClausHolbechArista With these differences in mind, like to hear your thoughts!

**Comment by tgodaA** [comment]
```
monitor      Monitor configuration commands
```

```
switch(config)#monitor ?
  connectivity     Connectivity monitor configuration
  counters         Monitor counters configuration
  device-health    Health monitor configuration
  ethernet         Ethernet protocol configuration
  hadoop           Monitor Hadoop Configuration
  layer1           Layer 1 monitor configuration
  link-flap        Specify the flap-setting values for link flap errdisable cause
  loop-protection  Monitor Loop Protection Configuration
  server-failure   Server-failure configuration
  session          Monitor configuration commands
  system           system configuration commands
  telemetry        Telemetry configuration
```

So I will add knob for monitor connectivity (monitor_connectivity).

```
switch(config-mon-connectivity)#?
  host              Configure host parameters
  interface         Configure a set of source interfaces
  interval          Configure probe interval in seconds (default is 10 seconds,
                    minimum is 5 seconds)
  local-interfaces  Configure the default interface set for probing
  shutdown          Shutdown connectivity monitor
  vrf               Configure VRF for connectivity probes
  ----------------------------------------
  comment           Up to 240 characters, comment for this mode
  default           Set a command to its defaults
  exit              Leave Connectivity monitor configuration mode
  no                Disable the command that follows
  show              Display details of switch operation
  !!                Append to comment
```

Test example:

```
switch(config-mon-connectivity)#sh active 
monitor connectivity
   vrf red
      interface set intfset1 Ethernet4/1
      local-interfaces intfset1 address-only default
      !
      host srv1
         ip 10.10.20.10
   interface set test1 Ethernet5/1
   interface set test2 Ethernet6/1
   interface set test3 Ethernet7/1
   local-interfaces test3 address-only default
   !
   host test2
      local-interfaces test1 address-only
      ip 10.10.10.10
   !
   host tet2
      local-interfaces test2 address-only
      ip 10.10.11.10
```

I am thinking of the below model:

```yaml
monitor_connectivity:
    shutdown: < true | false >
    interval: <interval>
    interface_sets:
      - name: < interface_set >
        interfaces:
          - < interface_or_interface_range >
    local_interfaces: < interface_set_name >
    hosts:
      - name: < host_name >
        description: < description >
        ip: < ipv4 >
        local_interfaces: < interface_set_name >
        url: < url >
    vrfs:
      - name: < vrf_name >
        description: < description >
        interface_sets:
          - name: < interface_set >
            interfaces:
              - < interface_or_interface_range >
        local_interfaces: < interface_set_name >
        hosts:
          - name: < host_name >
            description: < description >
            ip: < ipv4 >
            local_interfaces: < interface_set_name >
            url: < url >
```
