### ISSUE TITLE
Missing next-hop-unchanged with EVPN on Spines

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#112]
It is mandatory to use next-hop-unchanged in eBGP setups for EVPN as overlay. We can configure this in the address family whether as a default knob or per neighbour.

**Comment by onurgashi** [comment]
This seems True

| Settings | Value |
| -------- | ----- |
| Address Family | evpn |
| next-hop unchanged | True |

But it doesn't come out in the config generated.

**Comment by titom73** [comment]
Hey Onur,

Thanks for reporting.
`next-hop-unchanged` is configured on a per group basis instead of per address family

```
router bgp 65001
   neighbor EVPN-OVERLAY-PEERS peer group
   neighbor EVPN-OVERLAY-PEERS next-hop-unchanged
   neighbor EVPN-OVERLAY-PEERS update-source Loopback0
```

In device data model, this information is already configured on a per group basis so keeping this approach in configuration is easier to translate.

```yaml
### Routing - BGP ###
router_bgp:
  peer_groups:
    EVPN-OVERLAY-PEERS:
      type: evpn
      next_hop_unchanged: true
```

Could you confirm it maked sense for you as well ?

Thanks for this issue.
