### ISSUE TITLE
add eos_cli in vxlan_tunnel_interface model 

### ISSUE THREAD

**Issue by UchihaItachiSama** [aristanetworks/ansible-avd#1120]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [x] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

`eos_cli` to allow addition of CLI commands under `interface Vxlan1` similar to `ethernet_interfaces`, `port_channel_interfaces`, `vlan_interfaces`

**Describe the solution you'd like**

Sample model:

```yaml
vxlan_tunnel_interface:
  Vxlan1:
    description: < description >
    source_interface: < source_interface_name >
    virtual_router:
      encapsulation_mac_address: < mlag-system-id | ethernet_address (H.H.H) >
    vxlan_udp_port: < udp_port >
    # EOS CLI rendered directly on the Vxlan interface in the final EOS configuration
    eos_cli: |
        < multiline eos cli >
    vxlan_vni_mappings:
      vlans:
        < vlan_id_1 >:
          vni: < vni_id_1 >
        < vlan_id_2 >:
          vni: < vni_id_2 >
      vrfs:
        < vrf_name >:
          vni: < vni_id_3 >
        < vrf_name >:
          vni: < vni_id_4 >
```

**Describe alternatives you've considered**

Manually updating the `ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/vxlan-interface.j2` to include:

```jinja
{%     if  vxlan_tunnel_interface.Vxlan1.eos_cli is arista.avd.defined %}
   {{ vxlan_tunnel_interface.Vxlan1.eos_cli | indent(3, false) }}
{%     endif %}
{% endif %}
```

**Additional context**

**Comment by carlbuchmann** [comment]
@UchihaItachiSama - Thanks for submitting this issue - please note, there is already some planned refactoring/data model for vxlan interface discussed in PR #980 - I left the PR open, but the plan was to start a new one based on the latest devel.

This will require updates to `eos_designs` as well.

Would you be comfortable tackling both? And let's make sure we agree on the desired data model before we start working on the PR!

**Comment by UchihaItachiSama** [comment]
@carlbuchmann sounds good to me. From PR #980 I understand the new expected data model is :

```yaml
vxlan_tunnel_interface:
  Vxlan1:
    description: < description >
    vxlan:
      source_interface: < source_interface_name >
      udp_port: < udp_port >
      virtual_router_encapsulation_mac_address: < mlag-system-id | ethernet_address (H.H.H) >
      vlans:
        < vlan_id_1 >:
          vni: < vni_id_1 >
          flood_vteps:
            - < remote_1_ip_address >
            - < remote_2_ip_address >
        < vlan_id_2 >:
          vni: < vni_id_2 >
          flood_vteps:
            - < remote_1_ip_address >
            - < remote_2_ip_address >
      vrfs:
        < vrf_name >:
          vni: < vni_id_3 >
        < vrf_name >:
          vni: < vni_id_4 >
      flood_vteps:
        - < remote_1_ip_address >
        - < remote_2_ip_address >
      flood_vtep_learned_data_plate: < true | false >
```

So the addition as per this request would be to add `eos_cli:` as well.

Let me know if it'd be okay to start off with the changes in the `eos_cli_config_gen` for `vxlan_tunnel_interface` from the latest devel branch.

For the changes in the `eos_design` we can discuss what changes needs to be added.
