### ISSUE TITLE
Change data model for route redistribution

### ISSUE THREAD

**Issue by ankudinov** [aristanetworks/ansible-avd#1126]
## Issue Type

- [x] data model change

## Summary

Currently route redistribution is using data model that is allowing empty keys. For example:

```yaml
redistribute:
        static:
        connected:
        bgp:
```

Instead following or similar data model should be used:

```yaml
redistribute:
    - protocol: static
    - protocol: connected
    - protocol: bgp
      route_map: < route_map_name >
```
