### ISSUE TITLE
Trigger reload after initial provisioning to activate ArBGP

### ISSUE THREAD

**Issue by ankudinov** [aristanetworks/ansible-avd#114]
**Issue Type**
- Role enhancement

**Is your feature request related to a problem? Please describe.**
Enabling ArBGP during initial switch provisioning requires reload after "service routing protocols model multi-agent". That is not happening automatically right now and can create problems.

**Describe the solution you'd like**
Verify if ArBGP is active with "show ip route summary". Reload if not active.

**Describe alternatives you've considered**
Temporary fix - document this limitation in README.

**Additional context**

Example before the reload:
```console
<hostname>#show ip route summary

Operating routing protocol model: ribd
Configured routing protocol model: multi-agent (will apply after next reboot)

<etc.>
```

After reload:
```console
<hostname>#show ip route summary

Operating routing protocol model: multi-agent
Configured routing protocol model: multi-agent

<etc.>
```

Command output available as JSON.

**Comment by ksator** [comment]
This ansible task can be used to check if ArBGP is configured and running: 

```
   - name: validate ArBGP is configured and operating
      eos_command:
        commands: "show ip route summary"
        waitfor: 
          - "result[0] contains 'Operating routing protocol model: multi-agent'" 
          - "result[0] contains 'Configured routing protocol model: multi-agent'"
        retries: 2
        interval: 2
      when: (ansible_version['major'] == 2 and ansible_version['minor']|int >= 9)
 ```
Then we need to update this to trigger a reload
