### ISSUE TITLE
Change platform settings for Jericho devices

### ISSUE THREAD

**Issue by xaviramon** [aristanetworks/ansible-avd#1141]
## Issue Type

- [x] EOS Configuration rendering error

## Summary
Default platform settings today assign incorrectly J2 devices a tcam_profile and lag_hardware only.
New platform should be defined for J2 devices without these settings, and 7500R2 should be added to current platforms.

## Component Name
eos_designs

## Steps to reproduce

```yaml
platform_settings:
  - platforms: [7800R3, 7500R3, 7500R, 7280R3, 7280R2, 7280R]
    tcam_profile: vxlan-routing
    lag_hardware_only: true
    reload_delay:
      mlag: 780
      non_mlag: 1020
```

### Expected results

```yaml
platform_settings:
  - platforms: [7500R2, 7500R, 7280R2, 7280R]
    tcam_profile: vxlan-routing
    lag_hardware_only: true
    reload_delay:
      mlag: 780
      non_mlag: 1020
  - platforms: [7500R3, 7280R3, 7800R3]
    reload_delay:
      mlag: 780
      non_mlag: 1020
```

### Actual results

Configuration generated for J2 devices:

```yaml
hardware tcam
   system profile vxlan-routing
```
