### ISSUE TITLE
Support list of -cvopt for terminAttr configuration (cluster requirements)

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#1153]
### Enhancement summary

support config cli generation for terminAttr with the following option:

```
-cvopt cluster.option=value

         Set options for streaming to additional CloudVision clusters. Each cluster needs a unique name. “primary” is reserved for the main CloudVision cluster and non-cvopt CloudVision options always apply to the “primary” cluster.

         Format: -cvopt cluster.option=value

         Options:

                  addr: see -cvaddr

                  auth: see -cvauth

                  sourceip: see -cvsourceip

                  vrf: see -cvvrf

                  obscurekeyfile: see -cvobscurekeyfile

                proxy: see -cvproxy

         Example, configure a primary cluster and secondary cluster foo:

                  -cvaddr=10.1.0.1:1234 -cvauth=none -cvopt foo.addr=1.2.3.4:5678 -cvopt foo.auth=none

         Equivalently:

                  -cvopt primary.addr=10.1.0.1:1234 -cvopt primary.auth=non -cvopt foo.addr=1.2.3.4:5678 -cvopt foo.auth=none

         The cluster names can be arbitrary, so the following is also equivalent:

                  -cvopt alpha.addr=10.1.0.1:1234 -cvopt alpha.auth=non -cvopt beta.addr=1.2.3.4:5678 -cvopt beta.auth=none

         More details can be found in https://eos.arista.com/sending-telemetry-data-from-terminattr-to-multiple-cvp-instances/
```

This is a comonly used option for cluster setups

### Which component of AVD is impacted

- eos_cli_config_gen
- eos_designs

### Use case example

Configuration of the terminAttr daemon for CVP cluster configurations

### Describe the solution you would like

Sample config output:

```
daemon TerminAttr
   exec /usr/bin/TerminAttr -cvopt=primary.addr={{ fabric.cvp_server_a.primary.ipv4_1 }}:9910,{{ fabric.cvp_server_a.primary.ipv4_2 }}:9910,{{ fabric.cvp_server_a.primary.ipv4_3 }}:9910 -cvopt=primary.auth={{ fabric.cvp_server_a.primary.auth }} -cvopt=primary.vrf={{ fabric.management_vrf }} -cvopt secondary.addr={{ fabric.cvp_server_a.secondary.ipv4_1 }}:9910,{{ fabric.cvp_server_a.secondary.ipv4_2 }}:9910,{{ fabric.cvp_server_a.secondary.ipv4_3 }}:9910 -cvopt secondary.auth={{ fabric.cvp_server_a.secondary.auth }} -cvopt=secondary.vrf={{ fabric.management_vrf }} -cvcompression=gzip -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -taillogs
   no shutdown
```

**NOTE**: Variable names in the above example are made up as an example to show the intended result.

### Describe alternatives you have considered

Leave "daemon_terminattr" undefined and provide a custom template to generate these configs. However seems like eos_designs generates this as part of the base configs, so I guess I would need to generate custom structure config to override the generated configs with an empty value for that key.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
We already have another issue #505 and an open PR #1064 in flight to update eos_cli_config_gen with the complete model.
Part of the PR is also to update the current eos_designs abstraction to use the new optional available. Depending on your exact needs, this may be sufficient. I will leave this issue open until, so you can adjust to specify which gaps that should be addressed.

**Comment by carlbuchmann** [comment]
@gusmb - following up on this, I believe PR #1064 addresses the cluster configuration requirements in eos_cli_config gen. We didn't create any specific abstraction for eos_designs for CVP cluster setup, so you would simply use the eos_cli_config_gen model natively.

Here's an example cluster configuration:
 
```yaml
daemon_terminattr:
  clusters:
      DC1:
          cvaddrs:
              - 10.20.20.1:9910
          cvauth:
              method: "key"
              key: "arista"
          cvvrf: mgt
      DC2:
          cvaddrs:
              - 10.30.30.1:9910
          cvauth:
              method: "token"
              token_file: "/tmp/tokenDC2"
          cvvrf: mgt
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
```
I have closed this issue, but please let us know if there is anything else that needs to be addressed!
