### ISSUE TITLE
eos_cli_conf_gen: maintenance: documentation issue for maintenance units

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#1154]
### Issue Summary

eos_cli_conf_gen docs for maintenance show the following syntax:
```
maintenance:
  units:
    < unit_name_1 >:
      quiesce: < true | false >
      profile: < unit_profile_1 >
      bgp_groups:
        - < bgp_group_1>
        - < bgp_group_2>
      interface_groups:
        - < interface_group_1>
        - < interface_group_2>
```
But looking at this ```https://github.com/aristanetworks/ansible-avd/pull/1020/files#diff-6b400b3d23a2fdd9e33e66f55d9d15bb262e0737e3c9778a319282e2b07e4c94``` tells a different syntax which is working well:
```
  units:
    UNIT1:
      profile: UP1
      groups:
        bgp_groups:
        - BGP_GROUP_1
        - BGP_GROUP_2
        interface_groups:
        - INTERFACE_GROUP_1
  ```
  
  Look for ```groups:``` under ```UNIT1```
  

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Rendering this will fail to get the correct CLI:


maintenance:
  units:
    MM_Peerlink:
      interface_groups:
        - MM_Intf_Peerlink
```

but this will do it correct:
```
maintenance:
  units:
    MM_Peerlink:
      groups:
        interface_groups:
          - MM_Intf_Peerlink
´´´
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
