### ISSUE TITLE
eos_cli_conf_gen: maintenance: interface profiles option shutdown not rendered to cli

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#1155]
### Issue Summary

Maintenance interface profiles offer two options: rate-monitoring and shutdown

```
maintenance:
  interface_profiles:
    < interface_profile_1 >:
      rate_monitoring:
        load_interval: < seconds >
        threshold: < kbps >
      shutdown:
        max_delay: < seconds >
```

When using the following yaml config the ```shutdown```option is not rendered into cli.

```
maintenance:
  interface_profiles:
    MM_Prof_Downlinks:
      shutdown:
        max_delay: 3
 ```
 
I cannot find any part for ```shutdown```in the J2 file ```https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/maintenance.j2```

 

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell

maintenance:
  interface_profiles:
    MM_Prof_Downlinks:
      shutdown:
        max_delay: 3
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
