### ISSUE TITLE
Community Lists

### ISSUE THREAD

**Issue by volk331** [aristanetworks/ansible-avd#1161]
### Issue Summary

Issue
```
ip community-list EXAMPLE permit 64110:512
ip community-list EXAMPLE permit 64120:512
ip community-list EXAMPLE permit 64130:512
ip community-list EXAMPLE permit 64210:512
```
in yml

 ```
  CL_EXAMPLE:
   action: "permit 64110:512"
  CL_EXAMPLE:
   action: "permit 64120:512"
  CL_EXAMPLE:
   action: "permit 64130:512"
  CL_EXAMPLE:
   action: "permit 64210:512"`
```
Duplicate Key Entry Error

It seems that Extended Communities has a structure that addresses this.

```
ip_extcommunity_lists:
  TEST1:
    - type: permit
      extcommunities: "65000:65000"
    - type: deny
      extcommunities: "65002:65002"
  TEST2:
    - type: deny
      extcommunities: "65001:65001"
```

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI with AVD Runner

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
