### ISSUE TITLE
Support for EVPN Single-active Multihoming

### ISSUE THREAD

**Issue by UchihaItachiSama** [aristanetworks/ansible-avd#1163]
### Enhancement summary

Add support to allow configuring EVPN single-active multihoming.

- [x] Template enhancement
- [ ] Role enhancement
- [x] Documentation enhancement (avd.sh)

CLI 

```yaml
interface Port-Channel1
   switchport mode trunk
   switchport trunk allowed vlan 100-200
   evpn ethernet-segment
      identifier 0123:0123:0123:0123:0123
      route-target import 12:34:12:34:12:34
      redundancy single-active
```

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

Allow user to configure Single-Active multihoming, instead of the default Active-Active multihoming.

### Describe the solution you would like

In connected endpoints we already have `short_esi` key, in addition to that we can have a `redundancy_mode` key to facilitate configuring active-active or single-active multihoming.

```yaml
servers:
  server01:
    rack: RackB
    adapters:
      - endpoint_ports: [ E0, E1 ]
        switch_ports: [ Ethernet10, Ethernet10 ]
        switches: [ DC1-SVC3A, DC1-SVC4A ]
        profile: VM_Servers
        port_channel:
          description: PortChanne1
          mode: active
          short_esi: 0303:0202:0101
          redundancy_mode: <single-active | active-active> # default active-active
```

The same can be used for `port_channel_interfaces`

```yaml
port_channel_interfaces:
   < Port-Channel_interface_1 >:
            esi: < EVPN Ethernet Segment Identifier (Type 1 format) >
            rt: < EVPN Route Target for ESI with format xx:xx:xx:xx:xx:xx >
            lacp_id: < LACP ID with format xxxx.xxxx.xxxx >
            redundancy_mode: <single-active | active-active> # default active-active
```

### Describe alternatives you have considered

For `eos_cli_config_gen` we can use `eos_cli` under `port_channel_interfaces` to currently configure single-active mode.

### Additional context

https://eos.arista.com/eos-4-26-0f/evpn-single-active-multihoming-preference-based-df-election/

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
