### ISSUE TITLE
Support for ip address virtual secondary addresses

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#1170]
### Issue Summary

Documentation suggests this can be configured via svi_profiles:
https://avd.sh/en/releases-v3.x.x/roles/eos_designs/doc/l3ls-evpn/network-services.html

However the following did not work:
```
svi_profiles:
  45secondary:
    ip_address_virtual_secondary: 10.10.40.1/24  

          svis:
            45:
              name: V45-T-UTIL-IDMZ-HSBC-APP-BACK-FW
              tags: [VH_UTIL_IDMZ]
              enabled: true
              ip_address_virtual: 10.10.30.1/24
              profile: 45secondary   

```
structured_configs file looks good:
```
  Vlan45:
    tenant: T_UTIL_USVHI3W6
    tags:
    - VH_UTIL_IDMZ
    description: V45-T-UTIL-IDMZ-HSBC-APP-BACK-FW
    shutdown: false
    vrf: VRF-UTIL-IDMZ-USVHI3W6
    ip_address_virtual: 10.10.30.1/24
    ip_address_virtual_secondary: 10.10.40.1/24
```

But config generated misses the secondary address:
```
	interface Vlan45
	   description V45-T-UTIL-IDMZ-HSBC-APP-BACK-FW
	   no shutdown
	   vrf VRF-UTIL-IDMZ-USVHI3W6
	   ip address virtual 10.10.30.1/24

```

In addition to this, it would be better if we support directly configuring the ip address virtual secondary under the SVI instead.

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Define an SVI profile with an ip address virtual secondary and apply it to an SVI.
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
