### ISSUE TITLE
ansible-avd should honor VEOS-LAB platform (not) capabilities

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1194]
### Enhancement summary

Only render CLI commands (or YAML syntax in the structured configuration part) that are allowed on the target platform.

### Which component of AVD is impacted

eos_designs

### Use case example

We have a 1:1 replication of our physical network in an EVE-NG environment running VEOS-LAB switches. We constantly use this lab to see hop upgrading EOS or CVP behaves before moving onto production.

While upgrading to CVP 2021.2.0 and VEOS-LAB 4.26.2F I noticed that it is no longer possible to configure the storm-control settings on an interface (it's useless in a lab anyway but we wan't to check that our generated configuration is correct).

What happened? I can no longer deploy our configuration to VEOS-LAB as storm-control is no longer supported (this was also the case with ACL and queue monitor in 4.25.4M).

### Describe the solution you would like

With the platform type beeing available in ansible-avd l3ls design this key/value pair should be honored when rendering the structured configuration.

If a vEOS lab system is detected - the keys should not be embedded into the configuration when processing https://github.com/aristanetworks/ansible-avd/blob/790d69febb52b10ffe32968f413aa7f682ba8338/ansible_collections/arista/avd/roles/eos_designs/templates/connected_endpoints/ethernet-interfaces.j2#L102-L111 - an additional if-expression could check for vEOS-LAB devices

### Describe alternatives you have considered

Splitting the port profiles into multiple files for QA and PROD seems to be the wrong approach as we managed to single-source 98% of our codebase.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by c-po** [comment]
@mpergament @kmueller68

**Comment by ClausHolbechArista** [comment]
Last time, we implemented a feature knob under platform_settings:
```yaml
platform_settings:
  - platforms: [ < Arista Platform Family >, < Arista Platform Family > ]
    feature_support:
      queue_monitor_length_notify: < true | false | default -> true >
```
I believe this worked well for the use case, so I suggest that we add other knobs like this for the concerned features. Please help produce a list of features we need to limit. Then we can find out who can work on each.

**Comment by c-po** [comment]
Hi @ClausHolbechArista,

that would work out for me, too. Those are the features we are using but found out they are not (or no longer) available in vEOS-LEAB:
* Interface based ACLs, YAML keys in eos_cli_config_gen: `access_group_in` , `access_group_out`, `ipv6_access_group_in`, `ipv6_access_group_out`
* `storm_control`

If this is the way to go I can try to implement something for:
```yaml
platform_settings:
  - platforms: [ < Arista Platform Family >, < Arista Platform Family > ]
    feature_support:
      interface_storm_control: < true | false | default -> true >
```
