### ISSUE TITLE
L2 vlans marked with a tag are not imported

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#1195]
### Issue Summary

When tagging some SVIs and l2vlans with a tag in the tenant file:
```
          svis:
            255:
              name: V255-T-UTIL-IDMZ-APP_UTIL_OPER
              enabled: true
              tags: [ VH_UTIL_IDMZ ]

      l2vlans:
        55:
          name: V55-T-UTIL-IDMZ-Back-FW-to-VPN
          tags: VH_UTIL_IDMZ
```
With the same tag, vlan 255 gets imported, but not vlan 55.

After removing the filter tags, both get imported in the configuration. Could you please check?

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Tag l2vlans and filter based on the tags.
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
