### ISSUE TITLE
SVI in default routing table

### ISSUE THREAD

**Issue by ninnux** [aristanetworks/ansible-avd#1203]
### Enhancement summary

In current implementation SVIs have to be configured in a specific VRF.
Is it possible to make AVD able to add SVI interface in default routing table?

### Which component of AVD is impacted

eos_designs

### Use case example

```
interface Vlan110
   description Tenant_A_OP_Zone
   ip address 172.16.100.2/24
   ip virtual-router address 172.16.100.1
```

### Describe the solution you would like

In inventory/group_vars/DC1_TENANTS_NETWORKS.yaml

```yaml
tenants:
  # Tenant A Specific Information - VRFs / VLANs
 TenantA:
    mac_vrf_vni_base: 10000
    vrfs:
     Tenant_A_OP_Zone:  <----- HERE IT SHOULD BE POSSIBLE TO USE "default" FOR DEFAULT ROUTING INSTANCE
        vrf_vni: 123
        svis:
          # Service One
          100:
            name: Service_100
            tags: [pub, servers]
            enabled: true
            ip_virtual_router_address: 172.16.100.1
            nodes:
              DC1_LEAF1:
                ip_address: 172.16.100.2/24
              DC1_LEAF2:
                ip_address: 172.16.100.3/24
              DC1_LEAF3:
                ip_address: 172.16.100.4/24
              DC1_LEAF4:
                ip_address: 172.16.100.5/24
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ninnux** [comment]
Hello,
we tried the new feature  but It seems that something is wrong for our network:

1. no peering are in "IPv4-UNDERLAY-PEERS peer group".
2. The new network (of the service)  is not announced on main routing table.
3. vrf default are defined like it is a normal vrf and not main routing table.

Our service file is
```
---
tenants:
  # Tenant A Specific Information - VRFs / VLANs
  Infra:
    mac_vrf_vni_base: 10000
    vrfs:
      default:
        vrf_vni: 1009 
        svis:
          # default vrf test
          1009:
            name: DEFAULT-VRF-TEST
            tags: [pub, servers]
            enabled: true
            ip_virtual_router_addresses: 
              - 10.0.9.254 
            nodes:
              RM1_LEAF1:
                ip_address: 10.0.9.253/24
              RM1_LEAF2:
                ip_address: 10.0.9.252/24`

```
Here an intended config extract:

```
vlan 1009
   name DEFAULT-VRF-TEST
interface Vlan1009
   description DEFAULT-VRF-TEST
   no shutdown
   ip address 10.0.9.253/24
   ip virtual-router address 10.0.9.254
interface Vxlan1
...
   vxlan vlan 1009 vni 11009
   vxlan vrf default vni 1009

ip prefix-list PL-SVI-VRF-DEFAULT
   seq 10 permit 10.0.9.0/24

route-map RM-BGP-UNDERLAY-PEERS-OUT deny 10
   match ip address prefix-list PL-SVI-VRF-DEFAULT
!
route-map RM-BGP-UNDERLAY-PEERS-OUT permit 20
!
route-map RM-CONN-2-BGP permit 30
   match ip address prefix-list PL-SVI-VRF-DEFAULT
!
route-map RM-EVPN-EXPORT-VRF-DEFAULT permit 10
   match ip address prefix-list PL-SVI-VRF-DEFAULT


router BGP XXXX
router-id 10.2.20.3
   update wait-install
   no bgp default ipv4-unicast
   distance bgp 20 200 200
   graceful-restart restart-time 300
   graceful-restart
   maximum-paths 4 ecmp 4
   neighbor EVPN-OVERLAY-PEERS peer group
   neighbor EVPN-OVERLAY-PEERS remote-as 64741
  ...
   neighbor EVPN-OVERLAY-PEERS maximum-routes 0
   neighbor IPv4-UNDERLAY-PEERS peer group
   neighbor IPv4-UNDERLAY-PEERS route-map RM-BGP-UNDERLAY-PEERS-OUT out
   neighbor 10.2.20.1 peer group EVPN-OVERLAY-PEERS
   neighbor 10.2.20.1 description RM1_SPINE1
   neighbor 10.2.20.2 peer group EVPN-OVERLAY-PEERS
   neighbor 10.2.20.2 description RM1_SPINE2
   !

   vlan-aware-bundle default
      rd 10.2.20.3:1009
      route-target both 1009:1009
      redistribute learned
      vlan 1009
   !
   vrf default
      rd 10.2.20.3:1009
      route-target import evpn 1009:1009
      route-target export evpn 1009:1009
      route-target export evpn route-map RM-EVPN-EXPORT-VRF-DEFAULT
   !
```


We manually create a configuration that do what we need:

```
vlan 1009
   name JumpHost

interface Vlan1009
   description JumpHost
   ip address 10.0.9.252/24
   ip virtual-router address 10.0.9.254
   isis enable EVPN_UNDERLAY
   isis metric 1000
   
interface Vxlan1
  vxlan vlan 1009 vni 11009


router bgp 64740
   vlan-aware-bundle JumpHost
      rd 10.1.20.3:11009
      route-target both 11009:11009
      redistribute learned
      vlan 1009

```
Is it possible to have a way to manage it by AVD?
Thank you
Nino Ciurleo
