### ISSUE TITLE
Platform specific management security entropy source settings

### ISSUE THREAD

**Issue by melkypie** [aristanetworks/ansible-avd#1226]
### Enhancement summary

Some platforms do not support using (for example vEOS, 7010T-48):
```
management security
   entropy source hardware
```
If set using custom_strucutured_configuration, the variable will be global which is not optimal because 
if the option is set on an unsupported platform, it will disrupt SSH connections to these specific platforms as it is placed above the SSH configuration.

### Which component of AVD is impacted

eos_designs

### Use case example

```
platform_settings:
  - platforms: [default]
    reload_delay:
      mlag: 300
      non_mlag: 330
    management_security:
      entropy_source: hardware
  - platforms: [7010T, vEOS]
    reload_delay:
      mlag: 300
      non_mlag: 330
```

### Describe the solution you would like

```
platform_settings:
  - platforms: [default]
    reload_delay:
      mlag: 300
      non_mlag: 330
    management_security:
      entropy_source: hardware
```

### Describe alternatives you have considered

Using `raw_eos_cli` on platform specific settings, but this will place it at the bottom of configuration which makes CVP create a task with no changes, if the option was already set before.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
