### ISSUE TITLE
SNMP: trap configuration is too static and restrictive

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1231]
### Enhancement summary

The current ansible-avd repository only allows a consumer to enable or disable SNMP traps entirely. This might not be suitable for every user.

```yaml
snmp_server:
  contact: < contact_name >
  location: < location >
  ...
  traps:
    enable: < true | false >
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

On the L3LS fabrics we operate it would be nice to make use of SNMP traps but just diable the `bridge` trap to not flood our syslog receiver.

### Describe the solution you would like

Rename "traps enable" to "traps all"
```yaml
snmp_server:
  contact: < contact_name >
  location: < location >
  ...
  traps:
    all: < true | false >
```

```yaml
snmp_server:
  contact: < contact_name >
  location: < location >
  ...
  traps:
    all: < true | false >
    bgp: < true | false >
    bridge: < true | false >
    capacity: < true | false >
    entity: < true | false >
    external-alarm: < true | false >
    isis: < true | false >
    lldp: < true | false >
    mpls-ldp: < true | false >
    msdp: < true | false >
    ospf: < true | false >
    ospfv3: < true | false >
    pim: < true | false >
    snmp: < true | false >
    snmpConfigManEvent: < true | false >
    switchover: < true | false >
    vrrp: < true | false >
```

### Describe alternatives you have considered

Using RAW eos_cli commands

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
