### ISSUE TITLE
ACL: add "counters per-entry" support

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1232]
### Enhancement summary

> The counters per-entry (ACL configuration modes) command places the ACL in counting mode.

The current ACL YML definition does not support enabling the "counting" option

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

The counters per-entry (ACL configuration modes) command places the ACL in counting mode.

### Describe the solution you would like

Add `enable_counters: < true | false >` per ACL type

#### IP Extended Access-Lists

```yaml
access_lists:
  < access_list_name_1 >:
    enable_counters: < true | false >
    sequence_numbers:
      < sequence_id_1 >:
        action: "< action as string >"
      < sequence_id_2 >:
        action: "< action as string >"
  < access_list_name_2 >:
    sequence_numbers:
      < sequence_id_1 >:
        action: "< action as string >"
```

#### IPv6 Standard Access-Lists

```yaml
ipv6_standard_access_lists:
  < ipv6_access_list_name_1 >:
    enable_counters: < true | false >
    sequence_numbers:
      < sequence_id_1 >:
        action: "< action as string >"
      < sequence_id_2 >:
        action: "< action as string >"
  < ipv6_access_list_name_2 >:
    sequence_numbers:
      < sequence_id_1 >:
        action: "< action as string >"
```

#### IP Standard Access-Lists

```yaml
standard_access_lists:
  < access_list_name_1 >:
    enable_counters: < true | false >
    sequence_numbers:
      < sequence_id_1 >:
        action: "< action as string >"
      < sequence_id_2 >:
        action: "< action as string >"
  < access_list_name_2 >:
    sequence_numbers:
      < sequence_id_1 >:
        action: "< action as string >"
```

#### IPv6 Extended Access-Lists

```yaml
ipv6_access_lists:
  < ipv6_access_list_name_1 >:
    enable_counters: < true | false >
    sequence_numbers:
      < sequence_id_1 >:
        action: "< action as string >"
      < sequence_id_2 >:
        action: "< action as string >"
  < ipv6_access_list_name_2 >:
    sequence_numbers:
      < sequence_id_1 >:
        action: "< action as string >"
```

### Describe alternatives you have considered

- none

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
