### ISSUE TITLE
BGP does not support prefix filters inside the VRF statement

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1248]
### Enhancement summary

Add support for prefix filters inside a BGP VRF statement

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

We need prefix filtering support in a VRF.

### Describe the solution you would like

Same as for "regular" neighbors
```yaml
router_bgp:
  vrfs:
    < vrf_name_1 >:
      neighbors:
        < neighbor_ip_address >:
          remote_as: < asn >
          prefix_list_in: < prefix_list_name >
          prefix_list_out: < prefix_list_name >
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
