### ISSUE TITLE
Feat(eos_cli_config_gen): PBR extension for routed ports

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1260]
### Enhancement summary

This extends #890.

It is not possible to specify a service-policy on a routed ethernet port.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

please detail your use case

### Describe the solution you would like

```yaml
ethernet_interfaces:
  <Ethernet_interface_1 >:
    description: < description >
    service_policy:
      pbr:
        input: < policy-map name >

port_channel_interfaces:
  < Port-Channel_interface_1 >:
    description: < description >
    service_policy:
      pbr:
        input: < policy-map name >
```

### Describe alternatives you have considered

none

### Additional context

This issue affects production traffic - PR will follow shortly

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
