### ISSUE TITLE
eos_designs: add option shutdown/no shutdown to connected_endpoints

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#1266]
### Enhancement summary

It is currently not possible to put leaf switch ports or port-channels to manually shutdown to which endpoints are connected to.
It is sometimes necessary and helpful to have this option available.
 

### Which component of AVD is impacted

eos_designs

### Use case example

It is sometimes necessary to temporarily (days, weeks) shutdown certain leaf edge ports to which an server or any other device is connected to.

## connected_endpoints
```
servers:
  server01:
    rack: RackB
    adapters:
      - endpoint_ports: [ E0 ]
        switch_ports: [ Ethernet5 ]
        switches: [ DC1-LEAF1A ]
        profile: MGMT
        enabled: true | false
  ```

### Describe alternatives you have considered

# alternative 1
comment out all lines of the endpoint in the connected_endpoints yaml.
This will cause the whole config being deleted from the leaf switch(es) in case

# alternative 2
## connected_endpoints
```
servers:
  server01:
    rack: RackB
    adapters:
      - endpoint_ports: [ E0 ]
        switch_ports: [ Ethernet5 ]
        switches: [ DC1-LEAF1A ]
        profile: MGMT
        raw_eos_cli: |
          shutdown
```
will render
```
interface Ethernet5
   description server01_E0
   no shutdown
   <snip>
   shutdown
```

### Additional context

If you agree on the feature request we will try to implement it.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
