### ISSUE TITLE
Add support for interface based shaping parameters

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1268]
### Enhancement summary

Arista EOS supports rate limiting on a per interface basis.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

please detail your use case

### Ethernet Interfaces
```yaml
ethernet_interfaces:
  <Ethernet_interface_1 >:
    shape_rate: < Kbps or rate percent >
```

### Port-Channel Interfaces
```yaml
port_channel_interfaces:
  < Port-Channel_interface_1 >:
    shape_rate: < Kbps or rate percent >
```

This renders the EOS CLI configuration:

```
interface Ethernet37
   shape rate 10 percent
```

### Describe alternatives you have considered

`eos_cli:` commands

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
