### ISSUE TITLE
Feat(eos_cli_config_gen): router_bgp rib-in pre-policy retain missing features in eos_cli_config_gen

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1288]
### Enhancement summary

rib-in pre-policy retain options are missing for router_bgp neighbors, peer-groups, etc

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
router bgp 65000
   neighbor test peer group
   neighbor test rib-in pre-policy retain all
   neighbor 10.10.10.10 rib-in pre-policy retain
```

### Describe the solution you would like

```yaml
router_bgp:
  peer_groups:
    test:
         rib_in_pre_policy_retain:  < enabled | disabled | all | default (enabled) >
  neighbors:
    10.10.10.10:
         rib_in_pre_policy_retain:  < enabled | disabled | all | default (enabled) >
```

### Describe alternatives you have considered

Do not enable EOS feature parity

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Looks good. Please remove the `default` here since we should just render the command with or without `no` accordingly. If you don't want the command in output config, just don't set the key. UPDATE: To avoid mixing types we should add separate keys.
```yaml
router_bgp:
  peer_groups:
    test:
         rib_in_pre_policy_retain:
           enabled: < true | false >
           all: < true | false >
  neighbors:
    10.10.10.10:
         rib_in_pre_policy_retain:
           enabled: < true | false >
           all: < true | false >
```
