### ISSUE TITLE
Feature request: router_bgp allowas-in missing features in eos_cli_config_gen

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1289]
### Enhancement summary

allowas-in options are missing for router_bgp neighbors, peer-groups, etc

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
router bgp 65000
   neighbor test peer group
   neighbor test allowas-in 1
   no neighbor 10.10.10.10 allowas-in 10
```

### Describe the solution you would like

```yaml
router_bgp:
  peer_groups:
    test:
         allowas_in:  < enabled | disabled | 1-10 | default (enabled) >
  neighbors:
    10.10.10.10:
         allowas_in:  < enabled | disabled | 1-10 | default (enabled) >
```

### Describe alternatives you have considered

Do not enable EOS feature parity

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I would prefer not to mix types.
```yaml
router_bgp:
  peer_groups:
    test:
         allowas_in:
           enabled: < true | false >
           number_of_local_asns_allowed: < 1-10 >
  neighbors:
    10.10.10.10:
         allowas_in:
           enabled: < true | false >
           number_of_local_asns_allowed: < 1-10 >
```

The key name `number_of_local_asns_allowed` is not great, so suggestions are welcome.
