### ISSUE TITLE
Router BFD does not support singlehop configuration

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1291]
### Enhancement summary

BFD multihop values are required to be adjusted when simulating a vEOS-LAB L3LS-EVPN-VXLAN fabric.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Unfortunately it is not possible to also configure BFD values for singlehop session when Wide Area Network links are simulated where BFD is required (because of a ton of active fiber equipment where the link state never goes down).

### Describe the solution you would like

```yaml
router_bfd:
  interval: < rate in milliseconds >
  min_rx: < rate in milliseconds >
  multiplier: < 3-50 >
  multihop:
    interval: < rate in milliseconds >
    min_rx: < rate in milliseconds >
    multiplier: < 3-50 >
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
