### ISSUE TITLE
eos_cli_config_gen - Add LLDP documentation section

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#1306]
### Enhancement summary

Add LLDP documentation templates

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Currently we have no documentation templates covering LLDP

### Describe the solution you would like

Add LLDP documentation templates covering both global config and interfaces where lldp knobs have been set.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ccsnw** [comment]
Can I try this one?

As far as I can see, the datamodel for lldp will need to be updated for the next major version (in order to not break compatibility right now). e.g. todays model doesn't allow to configure multiple mgmt addresses or vrfs, but that's doable in EOS cli. Also we miss the option to define optional TLVs.

I can add support for "lldp timer reinitialization" and "lldp.receive_packet_tagged_drop" into the existing model. I think this should work without breaking compatibility (lldp timer reint. will need to be key<->value on its own for now, in the new model, timer would have "time in seconds" and "reinitialization in seconds" as suboptions).

The documentation I'd split in  parts:

LLDP Global Settings

| LLDP Enabled | LLDP Timer | LLDP Timer Reinit. | LLDP Hold-Time | LLDP Management Address | LLDP Drop Tagged Packets |
| True/False       | Time in s    | Time in s                 | Time in s            | VRFNAME/INTERFACENAME/IP | True/False                      |

LLDP Special Interface Settings

By default LLDP is enabled on all interfaces in both directions (TX/RX). The following interfaces are configured differently

| Interface | LLDP Tx | LLDP Tx |
| Ifname    | True/false | True/false |

Does that make sense?

**Comment by ClausHolbechArista** [comment]
Since the table is under a dedicated LLDP section we don't need LLDP in every column title. Try to keep it short a close to the variable name.
Please write the data model out, so it is easier to understand what you mean.
Also some cli examples would be great to compare.

**Comment by ccsnw** [comment]
Suggested minor change (compatible to what we have today):
```
lldp:
  timer: < transmission_time >
  timer_reinitialization: < re-init_time >
  holdtime: < hold_time_period >
  management_address: < all | ethernetN | loopbackN | managementN | port-channelN | vlanN >
  vrf: < vrf_name >
  receive_packet_tagged_drop: < true | false >
  run: < true | false >
```

Suggested major change for future versions:
```
lldp:
  timers:
    lldp_timer: < transmission_time >
    lldp_reinitialization_timer: < re-init_time >
  holdtime: < hold_time_period >
  vrf: < vrf_name >
  management_address: 
    - < all | ethernetN | loopbackN | managementN | port-channelN | vlanN >
    - < all | ethernetN | loopbackN | managementN | port-channelN | vlanN >
  receive_packet_tagged_drop: < true | false >
  tlv_transmit:
    link-aggregation: < true | false >
    management-address: < true | false >
    max-frame-size: < true | false >
    med: < true | false >
    port-description: < true | false >
    port-vlan: < true | false >
    power-via-mdi: < true | false >
    system-capabilities: < true | false >
    system-description: < true | false >
    system-name: < true | false >
  run: < true | false >
```

If no vrf is defined, the default vrf will be used. 
We can define multiple IPs per VRF to be included in the LLDPDU, current model doesnt support this.
If only vrf an not specific interface is defined,  "all" should be used ( advertising all ips in the vrf)

TLV_transmit allows us to exclude certain values from the LLDPDU if desired. 

=============================

Regarding the current LLDP config per interface.:

According to README, we have:

```
# Routed Interfaces
ethernet_interfaces:
  <snip>
   lldp:
      transmit: < true | false >
      receive: < true | false >
```

But I think this should be under "#Switched interfaces" instead, as LLDP is a L2 Protcol. I'll move this?

**Comment by ClausHolbechArista** [comment]
- When I check on EOS 4.26.1F I cannot enter more than one management address (or `all`).
- VRF is set in EOS with `lldp management-address vrf ...` so if we change the model at some point, it should reflect that.
- management-address also supports ipv6 keyword, so it should probably be a dict with `interface`, `vrf`, `ipv6` keys.
- `tlv_transmit` could be added now without any breaking changes to existing model.
- I would not go with your suggestion of adding a `timers` dictionary. While it makes sense to group these, we try to reflect EOS CLI as closely as possible in `eos_cli_config_gen`.

**Comment by ClausHolbechArista** [comment]
For this issue, the main objective is just to add a documentation section for LLDP. It is fine if you add some extra knobs and options under lldp while you work on it, but no breaking changes.

**Comment by ccsnw** [comment]
- I was checking on a 4.24.3M, but you are right: EOS will overwrite any second address/interface you specify. I'm not sure what I saw yesterday.. however what EOS allows you is to specify a VRF as the source + an Interface/IP that is not on that vrf. e.g.:

```
sh run | i lldp
lldp management-address Loopback0
lldp management-address vrf management
```
Is possible, even though Loopback0 is not in vrf management. In this case "lldp management-address Loopback0" is just ignored. Maybe this behaviour has changed in newer EOS versions though. Could you check on 4.26? Maybe this could be reported as something to be fixed in EOS (if its still present)

- TLV Transmit: True, I can add this to the code
- Regarding the timers: I was thinking wrong here. I interpreted "lldp timer" as a "section" but instead you see "lldp timer timeInS" and "lldp timer reinitialization timeInS" as independent commands

```
(config)#lldp timer ?
  reinitialization  Configure the delay before LLDP re-initialization is attempted
  <1-32768>         Configure the period at which we transmit LLDPDUs (in seconds)
```

========================

Minor model change then:

```
lldp:
  timer: < transmission_time >
  timer_reinitialization: < re-init_time >
  holdtime: < hold_time_period >
  management_address: < all | ethernetN | loopbackN | managementN | port-channelN | vlanN >
  vrf: < vrf_name >
  receive_packet_tagged_drop: < true | false >
  tlv_transmit:
    link-aggregation: < true | false >
    management-address: < true | false >
    max-frame-size: < true | false >
    med: < true | false >
    port-description: < true | false >
    port-vlan: < true | false >
    power-via-mdi: < true | false >
    system-capabilities: < true | false >
    system-description: < true | false >
    system-name: < true | false >
  run: < true | false >
```

Major model change: 

```
lldp:
  run: < true | false >
  timer: < transmission_time >
  timer_reinitialization: < re-init_time >
  holdtime: < hold_time_period >
  receive_packet_tagged_drop: < true | false >
  tlv_transmit:
    link-aggregation: < true | false >
    management-address: < true | false >
    max-frame-size: < true | false >
    med: < true | false >
    port-description: < true | false >
    port-vlan: < true | false >
    power-via-mdi: < true | false >
    system-capabilities: < true | false >
    system-description: < true | false >
    system-name: < true | false >  
  management_address:
    ipv4_interface: < all | ethernetN | loopbackN | managementN | port-channelN | vlanN >
    ipv6_interface: < all | ethernetN | loopbackN | managementN | port-channelN | vlanN >
    vrf: < vrfname >
```
