### ISSUE TITLE
Revisit eos_cli_config_gen BGP data model

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#1323]
### Enhancement summary

Refactor of router_bgp data model to be consistent for global and discrete VRF, as raised by @c-po 

```yaml
router_bgp:
  as: "100"
  address_family_ipv4:
    networks:
      10.0.0.0/8:
    neighbors:
      192.168.6.34:
        prefix_list_in: "wan-in"

  vrfs:
    FooMPLS:
      address_families:
        ipv4:
          networks:
            192.168.72.0/29:
          neighbors:
            192.168.82.72:
              activate: true
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Refactor router_bgp data model - TBD.

### Describe the solution you would like

Refactor data model - TBD.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
