### ISSUE TITLE
Support for stp root primary/secondary commands

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#1329]
### Enhancement summary

Asking to add support for the following STP CLI commands:

```
spanning-tree root primary/secondary
spanning-tree mst <0-4094> root primary/seconday
```
Today it is possible to set the priority manually to a value but it would be useful to add support also for these commands:
https://avd.sh/en/releases-v3.x.x/roles/eos_cli_config_gen/index.html#spanning-tree

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

I would like to set these commands for an active-standby scenario and align the active PE with the primary STP root without the need of setting the priority explicitly.

### Describe the solution you would like

Something along these lines:
```
spanning_tree:
  root: < primary | secondary >
  mst:
     root: < primary | secondary >
```

### Describe alternatives you have considered

Setting the priority value is an alternative and it is supported.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
This will not render the configuration 1:1, since these commands are EOS "scripts" that render different configuration depending on the spanning-tree mode. Unfortunately it only works for MST and RSTP. For rapid-pvst it still produces MST priority command.
Trying to replicate this script into AVD will not make it simpler to understand, and would require significant effort to protect about multiple commands generating overlapping output.
Can you elaborate on what we will solve by having these knobs? I don't see how setting one or the other key to one or the other value will make it significantly easier.
```yaml
spanning_tree:
   mst_instances:
      0:
        priority: 8192
```
vs.
```yaml
spanning_tree:
   mst_instances:
      0:
        root: primary
```
