### ISSUE TITLE
Setting Password Minimum Length on Management Security (eos_cli_config_gen)

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#1343]
This is a feature request for the `eos_cli_config_gen` role
The current data model for the **Management Security** scope:

```
management_security:
  entropy_source: < entropy_source >
  password:
    encryption_key_common: < true | false >
  ssl_profiles:
    - name: <ssl_profile_1>
      tls_versions: < list of allowed tls versions as string >
      certificate:
        file: < certificate filename >
        key: < key filename >
    - name: <ssl_profile_2>
      tls_versions: < list of allowed tls versions as string >
```

I need to set the password minimum length as well, which I am currently doing using `eos_cli` as a workaround, but would like to do it properly using this data model. I am thinking about the following change to the data model:

```
management_security:
  entropy_source: < entropy_source >
  password:
    minimum_length: <length>
    encryption_key_common: < true | false >
  ssl_profiles:
    - name: <ssl_profile_1>
      tls_versions: < list of allowed tls versions as string >
      certificate:
        file: < certificate filename >
        key: < key filename >
    - name: <ssl_profile_2>
      tls_versions: < list of allowed tls versions as string >
```
