### ISSUE TITLE
Setting aaa authentication policy lockout

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#1345]
### Enhancement summary

Additional coverage for `aaa_authentication`

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

I need to generate the following, which is not supported by the current data model, and I can only generate it using `eos_cli`:

```
aaa authentication policy lockout failure 3 window 300 duration 900
```

### Describe the solution you would like

Modify the corresponding data models accordingly:

```
aaa_authentication:
  login:
    default: < group group_name | local | none > < group group_name | local | none >
    console: < group group_name | local | none > < group group_name | local | none >
  enable:
    default: < group group_name | local | none > < group group_name | local | none >
  dot1x:
    default: < group group_name >
  policies:
    on_failure_log: < true | false >
    on_success_log: < true | false >
    local:
      allow_nopassword: < false | true >
    lockout:
      failure: <min-max>
      window: <min-max>
      duration: <min-max>
```

### Describe alternatives you have considered

using `eos_cli` to render the CLI directly

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
