### ISSUE TITLE
Support disable logging console

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#1347]
### Enhancement summary

Support  deactivating console logging on logging settings

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Need to apply the following commands to a switch:

`no logging console`

However the logging datamodel does not support this. I am using `eos_cli` for now, but requesting support for this feature

### Describe the solution you would like

Data model update, to look like the following (relevant change on the console settings):

```
logging:
  console: 
    enable: <true, false | default --> true>
    level:  < severity_level >
  monitor: < severity_level >
  buffered:
    size: < messages_nb (minimum of 10) >
    level: < severity_level >
  trap: < severity_level >
  synchronous:
    level: < severity_level | default --> critical >
  format:
    timestamp: < high-resolution | traditional >
    hostname: < fqdn | ipv4 >
    sequence_numbers: < true | false >
  source_interface: < source_interface_name >
  vrfs:
    < vrf_name >:
      source_interface: < source_interface_name >
      hosts:
        < syslog_server_1 >:
          protocol: < tcp | udp (default udp) >
          ports:
            - < custom_port_1 >
            - < custom_port_2 >
        < syslog_server_2 >:
          ports:
            - < custom_port_1 >
  policy:
    match:
      match_lists:
        < match_list >:
          action: < discard >
```

### Describe alternatives you have considered

using `eos_cli`

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ccsnw** [comment]
I think it would make more sense to introduce sth. like:

```
logging:
  console: 
    level:  < severity_level >
<snip>
  "disable" | "no_logging":
    - < string >
```

under "disable" or "no_logging" we could list: "console", "monitor" or whatever else we want to disable?

**Comment by gusmb** [comment]
Seems a bit less intuitive than having an enable: book K:V pair under the specific key (console or monitor). There's other places in the same Datamodel where the "level" key is used, so it would look more consistent to keep it like that.
Furthermore, the "enable": true|false is used extensively as well in other parts of the config, that is why I was proposing it with that format. That's just my opinion.

**Comment by ccsnw** [comment]
I agree to what you're saying. The "problem" with what your suggestion is, that it would break currently running installations (at least for console, monitor and trap) because they are not dictionaries today.

We could extend the current datamodel to something like:

```
logging:
  no_logging_console: < true | false >
  console: < severity_level >

  no_logging_monitor: < true | false >
  monitor: < severity_level >

  buffered:
    enable: < true | false >
    size: < messages_nb (minimum of 10) >
    level: < severity_level >

  no_logging_trap: < true | false >
  trap: < severity_level >

  synchronous:
    enable: < true | false >
    level: < severity_level | default --> critical >
```

But this would result in a mix.

Of course we could add a "no_logging_xxx" for all of them.. this way it would be harmonized.

Or create a list for disabling like I've initially suggested.

=========

Remodeling, like you suggest, will most likely be part of a new major release.

Ohter opinions & ideas?
