### ISSUE TITLE
Support shape rate percent under qos_profiles

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#1348]
### Enhancement summary

Add support for following CLI:

```
qos profile EXAMPLE
  tx-queue 5
    shape rate 25 percent
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

As part of fabric switch standard config I need to apply the above config to some switches

### Describe the solution you would like

Following enhanced data model:

```
qos_profiles:
  < profile-1 >:
    trust: < dscp | cos >
    cos: < cos-value >
    dscp: < dscp-value >
    tx-queues:
      < tx-queue-id >:
        bandwidth_percent: < value >
        priority: < string >
        shape_rate_percent: < value >
      < tx-queue-id >:
        bandwidth_percent: < value >
        priority: < string >
        shape_rate_percent: < value >
  < profile-2 >:
    trust: < dscp | cos >
    cos: < cos-value >
    dscp: < dscp-value >
    tx-queues:
      < tx-queue-id >:
        bandwidth_percent: < value >
        priority: < string >
        shape_rate_percent: < value >
      < tx-queue-id >:
        bandwidth_percent: < value >
        priority: < string >
        shape_rate_percent: < value >
```

### Describe alternatives you have considered

using `eos_cli` to solve it, however it would be much better to use the data model and structured data

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
