### ISSUE TITLE
Support additional configuration options under `router_multicast`

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#1349]
### Enhancement summary

Need to configure multipathdeterministic to the router_id value and software forwardinf sfe under `routing_multicast.ipv4`

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

I need to apply the following CLI:

```
router multicast
  ipv4
    routing
    multipath deterministic router-id
    software-forwarding sfe
```

### Describe the solution you would like

Following supported data model:

```
router_multicast:
  ipv4:
    routing: < true | false >
    multipath_deterministic: <value>
    software_forwarding: <value>
```

### Describe alternatives you have considered

using `eos_cli`, however it would be much better if the data model supports it, to monimize the use of ad-hoc commands in CLI directly

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
