### ISSUE TITLE
Configure IGMP settings on SVIs

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#1357]
### Enhancement summary

Enhance `vlan_interfaces` data model to support IGMP configuration settings according to the documentation:

https://www.arista.com/en/um-eos/eos-igmp-and-igmp-snooping#xx1142409

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

For my use case, I only need to activate IGMP inside the SVI, however the data model enhancement should map the rest of the CLI options for IGMP

Example:

```
interface Vlan30
  ip igmp
```

### Describe the solution you would like

The following is the proposed data model enhancement (adding the igmp part at the end): 

```
vlan_interfaces:
  < Vlan_id_1 >:
    description: < description >
    shutdown: < true | false >
    vrf: < vrf_name >
    arp_aging_timeout: < arp_timeout >
    ip_address: < IPv4_address/Mask >
    ip_address_secondaries:
      - < IPv4_address/Mask >
      - < IPv4_address/Mask >
    ip_virtual_router_addresses:
      - < IPv4_address/Mask | IPv4_address >
      - < IPv4_address/Mask | IPv4_address >
    ip_address_virtual: < IPv4_address/Mask >
    ip_address_virtual_secondaries:
      - < IPv4_address/Mask >
      - < IPv4_address/Mask >
    ip_helpers:
      < ip_helper_address_1 >:
        source_interface: < source_interface_name >
        vrf: < vrf_name >
      < ip_helper_address_2 >:
        source_interface: < source_interface_name >
    ipv6_enable: < true | false >
    ipv6_address: < IPv6_address/Mask >
    ipv6_address_link_local: < link_local_IPv6_address/Mask >
    ipv6_nd_ra_disabled: < true | false >
    ipv6_nd_managed_config_flag: < true | false >
    ipv6_nd_prefixes:
      < IPv6_address_1/Mask >:
        valid_lifetime: < infinite or lifetime in seconds >
        preferred_lifetime: < infinite or lifetime in seconds >
        no_autoconfig_flag: < true | false >
      < IPv6_address_2/Mask >:
    access_group_in: < access_list_name >
    access_group_out: < access_list_name >
    ipv6_access_group_in: < ipv6_access_list_name >
    ipv6_access_group_out: < ipv6_access_list_name >
    multicast:
      ipv4:
        source_route_export:
          enabled: < true | false >
          administrative_distance: < 1-255 >
    ospf_network_point_to_point: < true | false >
    ospf_area: < ospf_area >
    ospf_cost: < ospf_cost >
    ospf_authentication: < none | simple | message-digest >
    ospf_authentication_key: "< encrypted_password >"
    ospf_message_digest_keys:
      < id >:
        hash_algorithm: < md5 | sha1 | sha 256 | sha384 | sha512 >
        key: "< encrypted_password >"
    pim:
      ipv4:
        sparse_mode: < true | false >
        local_interface: < local_interface_name >
    ipv6_virtual_router_address: < IPv6_address >
    isis_enable: < ISIS Instance >
    isis_passive: < boolean >
    isis_metric: < integer >
    isis_network_point_to_point: < boolean >
    mtu: < mtu >
    vrrp:
      virtual_router: < virtual_router_id >
      priority: < instance_priority >
      advertisement_interval: < advertisement_interval>
      preempt_delay_minimum: < minimum_preemption_delay >
      ipv4: < virtual_ip_address >
      ipv6: < virtual_ip_address >
    ip_attached_host_route_export:
      distance: < distance >
    bfd:
      interval: < rate in milliseconds >
      min_rx: < rate in milliseconds >
      multiplier: < 3-50 >
    service_policy:
      pbr:
        input: < policy-map name >
    pvlan_mapping: "< list of vlans as string >"
    igmp:
      enable: <true, false>
      version: <1-3 | default --> 2>
      startup_query_interval: <10-317440 >
      startup_query_count: <1-65535>
      query_interval: <1-3175 >
      query_max_response_time: <1-31744 >
      last_member_query_interval: <10-317440>
      last_member_query_count: <0-3>
      static_groups:
        - <group_address [SOURCE_ADDRESS] >
        - <group_address [SOURCE_ADDRESS] >
    # EOS CLI rendered directly on the VLAN interface in the final EOS configuration
    eos_cli: |
      < multiline eos cli >
```

### Describe alternatives you have considered

using `eos_cli`

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by UchihaItachiSama** [comment]
Proposed data model is:

```yaml
vlan_interfaces:
  < Vlan_id_1 >:
    igmp:
      enable: <true, false>
      version: <1-3 | default --> 2>
      startup_query_interval: <10-317440 >
      startup_query_count: <1-65535>
      query_interval: <1-3175 >
      query_max_response_time: <1-31744 >
      last_member_query_interval: <10-317440>
      last_member_query_count: <0-3>      
      static_groups:
        - <group_address [SOURCE_ADDRESS] >
        - <group_address [SOURCE_ADDRESS] >
```

Also, do we also add `host-proxy` and `router-alert` to be consistent with the CLI.

```bash
#ip igmp ?
  host-proxy                  IGMP host-proxy information
  last-member-query-count     IGMP last member query count
  last-member-query-interval  IGMP last member query interval
  query-interval              Time between IGMP queries
  router-alert                IGMP router-alert options
  startup-query-count         IGMP startup query count
  startup-query-interval      IGMP startup query interval
  static-group                Configured IGMP group membership
  version                     IGMP version
  <cr>
```

**Comment by gusmb** [comment]
This is still relevant, should keep open

**Comment by ClausHolbechArista** [comment]
@gusmb if there is a few specific knobs you are looking for, please specify. Then we can make a smaller PR with those.

**Comment by gusmb** [comment]
> @gusmb if there is a few specific knobs you are looking for, please specify. Then we can make a smaller PR with those.

It would be the following:

```yaml
vlan_interfaces:
  < Vlan_id_1 >:
    igmp:
      enable: <true, false>
      version: <1-3 | default --> 2>
      startup_query_interval: <10-317440 >
      startup_query_count: <1-65535>
      query_interval: <1-3175 >
      query_max_response_time: <1-31744 >
      last_member_query_interval: <10-317440>
      last_member_query_count: <0-3>      
      static_groups:
        - <group_address [SOURCE_ADDRESS] >
        - <group_address [SOURCE_ADDRESS] >
  ```

For my use case I only need:

```yaml
vlan_interfaces:
  < Vlan_id_1 >:
    igmp:
      enable: <true, false>
      version: <1-3 | default --> 2>
  ```

**Comment by ClausHolbechArista** [comment]
The current data model has
```yaml
vlan_interfaces:
  < Vlan_id_1 >:
    ip_igmp: < true | false >
```
So any change would be breaking to the existing model.
I suggest that we just add a new `ip_igmp_version` knob to solve this now, without introducing breaking changes.
