### ISSUE TITLE
Support EVPN L2 DCI Gateway Functionality in eos_cli_config_gen

### ISSUE THREAD

**Issue by emilarista** [aristanetworks/ansible-avd#1361]
### Enhancement summary

FI-PROJECT-01 customer would like us to support EVPN L2 DCI GW feature in eos_cli_config_gen for multi-domain EVPN fabrics.

Here is the configuration we need to support this:

```
router bgp < asn >
   ...
   vlan < vlan >
      rd evpn domain < all | remote > < rd >
      route-target import evpn domain < all | remote > < rt >
      route-target export evpn domain < all | remote > < rt >
   ...
   address-family evpn
      neighbor < peer-group > domain remote
      neighbor default next-hop-self received-evpn-routes route-type ip-prefix
      neighbor default next-hop-self received-evpn-routes route-type ip-prefix inter-domain
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

EVPN L2 DCI Gateway feature is used to segment EVPN domains.

### Describe the solution you would like

Proposed data model:

```yaml
router_bgp:
  vlans:
    <vlan>:
      domain_rd:
        - domain: < all | remote >
           rd: < rd > 
      route_targets:
        import_evpn_domain:
          - domain: < all | remote >
            rt: < rt >
        export_evpn_domain:
          - domain: < all | remote >
            rt: < rt >
        all:
          rd: <rd>
          route_targets:
            import:
              - <rt>
            export:
              - <rt>

  address_family_evpn:
    peer_groups:
      < peer group >:
        domain_remote: < true | false >
    neighbor_default:
      next_hop_self_received_evpn_routes:
        enable: < true | false >
        inter_domain: < true | false >
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
