### ISSUE TITLE
Enhance `router_bgp` data model to support the remove-private-as feature on peer group

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#1362]
### Enhancement summary

Add support for the following command (for a BGP peer group definition)

```
neighbor PEER-GROUP-NAME remove-private-as
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

BGP connection with an extranet device where we advertise internal routes.

### Describe the solution you would like

Enhanced BGP data model to suport new key `remove_private_as:  true` under `peer_groups` definition:

```
router_bgp:
  as: < bgp_as >
  router_id: < IPv4_address >
  bgp_defaults:
    - "< bgp command as string >"
    - "< bgp command as string >"
  bgp:
    bestpath:
      d_path: < true | false >
  peer_groups:
    < peer_group_name_1>:
      remove_private_as: <true | false>

[OMITTED]

```

Might also consider for other address-families where it makes sense

### Describe alternatives you have considered

using `eos_cli` (not ideal)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
