### ISSUE TITLE
Support VRF multicast group in VXLAN interface

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#1363]
### Enhancement summary

Enhance data model for `vxlan_interface` to support multicast group definition at vrf level

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Need to apply the following CLI:

```
interface vxlan1
  vxlan vrf VRF1 multicast group 232.0.0.10
```

### Describe the solution you would like

Data model enhancement to include multicast group:

```
vxlan_interface:
  Vxlan1:
    description: < description >
    vxlan:
      source_interface: < source_interface_name >
      udp_port: < udp_port >
      virtual_router_encapsulation_mac_address: < mlag-system-id | ethernet_address (H.H.H) >
      vlans:
        < vlan_id_1 >:
          vni: < vni_id_1 >
          flood_vteps:
            - < remote_vtep_1_ip_address >
            - < remote_vtep_2_ip_address >
        < vlan_id_2 >:
          vni: < vni_id_2 >
          flood_vteps:
            - < remote_vtep_1_ip_address >
            - < remote_vtep_2_ip_address >
      vrfs:
        < vrf_name_1 >:
          vni: < vni_id_3 >
          multicast_group: <group>
        < vrf_name_2 >:
          vni: < vni_id_4 >
          multicast_group: <group>
      flood_vteps:
        - < remote_vtep_1_ip_address >
        - < remote_vtep_2_ip_address >
      flood_vtep_learned_data_plane: < true | false >
    # EOS CLI rendered directly on the Vxlan interface in the final EOS configuration
    eos_cli: |
      < multiline eos cli >

```

### Describe alternatives you have considered

using `eos_cli` (not ideal)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
