### ISSUE TITLE
eos_designs: l3ls: svi_profiles should support referencing a base svi_profile

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1370]
### Enhancement summary

Similar to #875 but instead of a port profile support for SVI profiles should be extended to support 2 stage nested profiles.

### Which component of AVD is impacted

eos_designs

### Use case example

We use multiple SVI "groups" sharing more or less but not all equal parameters. The base configuration should be applied via the base profile and per-svi/tenant configs should just be extended.

### Describe the solution you would like

```yaml
svi_profiles:
  < profile_name >:
    parent_profile: < parent svi profile name >
    ...
```

### Additional context

Use the same approach as for #875 (implemented in #895)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
