### ISSUE TITLE
documentation missing for no autostate in vlan interfaces

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#1371]
### Issue Summary

The documentation in ```eos_cli_config_gen - interfaces - Vlan interfaces``` for configuration of no autostate for an interface vlan, especially for MLAG interface vlan, is missing.

Option is availabe in the J2 template.
```
vlan_interfaces.j2
{%     if vlan_interfaces[vlan_interface].no_autostate is arista.avd.defined(true) %}
   no autostate
```

available YAML syntax:
```
  Vlan4094:
    description: MLAGPEERING
    no_autostate: true
    shutdown: false
```

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
