### ISSUE TITLE
Add Router_bgp default_originate for neighbors.

### ISSUE THREAD

**Issue by ifoughal** [aristanetworks/ansible-avd#1379]
### Enhancement summary

Add the option to set default-originate for neighbors directly, thus bypassing IP address family neighbors.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

The possibility to group router_bgp neighbors by IPv4 address families for example, and set the specific default_originate command in a granular manner, to avoid applying it to all the neighbors group.

### Describe the solution you would like

been able to set in a granular manner the default originate command. 
```yaml
router_bgp:
  peer_groups:
    neighbors:
      1.1.1.1:
        description: example_device
        default_originate:
          always: true
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
