### ISSUE TITLE
Missing mlag stanza in for server downlink ports

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#138]
## Issue Type

- Bug Report

## Summary

When using AVD with server ports configuration for a dual homed on a mlag vtep, `mlag` stanza is missing 

## Role or Module Name

`arista.avd` collection and Python libraries version using `devel` at a01f0a4

## OS / Environment

__EOS Version__

`4.24.0F`

__Cloudvision version__

N/A

## Steps to reproduce

From server.yml

```yaml
servers:
  DCI_RTR01:
    rack: DCI_POD
    adapters:
      - server_ports: [Eth1]
        switch_ports: [Ethernet5]
        switches: [SITE01-BL01A]
        profile: DCI_IX
        port_channel:
          state: present
          description: PortChannel5
          mode: active
      - server_ports: [Eth2]
        switch_ports: [Ethernet5]
        switches: [SITE01-BL01B]
        profile: DCI_IX
        port_channel:
          state: present
          description: PortChannel5
          mode: active
```

### Expected results

```
interface Port-Channel5
   description POD01-SRV_PortChannel5
   switchport access vlan 110
   mlag 5
!
```

### Actual results

```
interface Port-Channel5
   description POD01-SRV_PortChannel5
   switchport access vlan 110
!
```

**Comment by titom73** [comment]
Misconfiguration

Fomr @carlbuchmann 

```yaml
DCI_RTR01:
    rack: DCI_POD
    adapters:
      - server_ports: [Eth1, Eth2]
        switch_ports: [Ethernet5, Ethernet5 ]
        switches: [SITE01-BL01A, SITE01-BL01B]
        profile: DCI_IX
        port_channel:
          state: present
          description: data
          mode: active
```
