### ISSUE TITLE
Add IGMP snooping querier

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#1382]
### Enhancement summary

Enhance `ip_igmp_snooping` data model to support igmp querier settings

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Need to implement the following CLI:

```
!
ip igmp snooping vlan $VLAN-ID$ querier
ip igmp snooping vlan $VLAN-ID$ querier address $IPV4-ADDRESS$
```

### Describe the solution you would like

Proposed datamodel:

```
ip_igmp_snooping:
  globally_enabled: < true | false (default is true) >
  vlans:
    < vlan_id >:
      enabled: < true | false >
      querier:
        enabled: <true | false>
        address: <value>
```

### Describe alternatives you have considered

using `eos_cli`  (not ideal)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
