### ISSUE TITLE
Add Tenant VRF OSPF support in eos_designs

### ISSUE THREAD

**Issue by emilarista** [aristanetworks/ansible-avd#1400]
### Enhancement summary

Implement OSPF data model eos_designs tenant vrfs and relevant ospf commands for l3_interface and svis.

### Which component of AVD is impacted

eos_designs

### Use case example

Use case is having tenant OSPF routing on l3_interfaces and SVIs.

### Describe the solution you would like

```yaml
tenants:
  TENANT_A:
    vrfs:
      TEN_A_VRF1:
        ospf:
          < ... >
    svis:
      1:
        ospf:
          < ... >
    l3_interfaces:
     - interfaces: [ ... ]
        ospf:
          < ... >
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
