### ISSUE TITLE
Improve data model for extended IP ACLs

### ISSUE THREAD

**Issue by ankudinov** [aristanetworks/ansible-avd#1411]
### Enhancement summary

Currently AVD supports basic extended ACL data model as the list of strings under `access_lists` key.
The data model must be improved to support more advance use cases. For example, integration with 3rd party policy controllers.

As part of the change AVD must allow to deploy port ACLs without producing the rest of the configuration (3rd party policy controller use case).

PS: the existing [ arista.eos.eos_acls ]( https://docs.ansible.com/ansible/latest/collections/arista/eos/eos_acls_module.html ) data model will not be considered, as it looks a bit suboptimal.

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

Integration with 3rd party policy controllers and other advanced use cases.

### Describe the solution you would like

Proposed data model brainstormed with @ClausHolbechArista 

```yaml
ip_access_lists:
  - name: "< access_list_name >"
    counters_per_entry: < true | false >
    entries:
      - sequence: < sequence_id >
        remark: "<Comment, up to 100 characters >"
        action: < "permit" | "deny" | "remark" >
        protocol: < "ip" | "tcp" | "udp" | "<protocol name or number>" >
        source: < "IPv4Address/Mask" | "host <IPv4Address>" | "any" >
        source_ports: [ "< port name or number >", ]
        source_ports_match: < "eq"(default) | "gt" | "lt" | "neq" | "range" >
        destination: < "IPv4Address/Mask" | "host <IPv4Address>" | "any" >
        destination_ports: [ "< port name or number >", ]
        destination_ports_match: < "eq"(default) | "gt" | "lt" | "neq" | "range" >
        tcp_flags: [ "< tcp flags >", ]
        fragments: < true | false >
        log: < true | false >
        ttl: < 0-255 >
        ttl_match: < "eq"(default) | "gt" | "lt" | "neq" >
```

### Additional context

This feature request focuses on IPv4 and extended ACLs only.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
