### ISSUE TITLE
Add option for port mirroring

### ISSUE THREAD

**Issue by melkypie** [aristanetworks/ansible-avd#1412]
### Enhancement summary

Currently the only way to achieve port mirroring is by using the `eos_raw_cli` option in `eos_designs`, it would be nice if it had a dedicated option inside `connected_endpoints.adapters`

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

Port mirroring is useful for monitoring and network probes.

### Describe the solution you would like

Something similar to this :
```yaml
servers:
  server1:
    adapters:
      - switch_ports: [Ethernet1]
        server_ports: [eth0]
        switches: [switch1]
        sessions:
           - name: 1
             type: source
             direction: tx
```
that would grab the interface/s from the switch_ports or port_channel, if one is defined, and assign it with the specified session.
This would be generated in EOS as:
```
monitor session 1 source Ethernet1 tx
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
