### ISSUE TITLE
Add support for L2 port security

### ISSUE THREAD

**Issue by PhirePhly** [aristanetworks/ansible-avd#1426]
### Enhancement summary

Tracking my work on adding port-security support for Internet Exchange Point application.

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

Internet Exchange Points provide a large L2 peering fabric between ASNs, and use port security to limit each customer port to a single router MAC address to prevent multiple routers per port or accidentally looping traffic back into the fabric L2.

### Describe the solution you would like

I only need basic 1 MAC shutdown support, but it seems pretty straight forward to support protect mode and different number of MAC addresses as well:

```
ethernet_interfaces:
  <Ethernet_interface_1 >:
    port_security:
      violation: < protect | shutdown, default: shutdown >
      mac_address_maximum: <1 - 1000 | disabled, default: 1 >
      log: <true | false, only supported in protect mode >
```

This ignores the VLAN based port security option. I have no interest in that and supporting it seems to add more complexity.

### Describe alternatives you have considered

Currently using raw_eos_cli to inject port sec

### Additional context

Relevant TOIs:
* https://eos.arista.com/eos-4-15-3f/portsec/
* https://eos.arista.com/eos-4-18-1f/port-security-preserve-macs-on-link-flapreload/
* https://eos.arista.com/eos-4-24-0f/port-security-protect-mode/
* https://eos.arista.com/eos-4-24-2f/port-security-protect-mode-enhancements/
* https://eos.arista.com/eos-4-26-1f/vlan-based-port-security/

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
