### ISSUE TITLE
Knob to enable bfd under router bgp vrf neighbors

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#1436]
### Enhancement summary

Enable in bfd under router bgp vrf neighbors under both eos_cli_config_gen and eos_designs network services.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```eos
router bgp 65511
   vrf ZONE_A
      neighbor 10.1.1.1 bfd
```

### Describe the solution you would like

Proposed data models:

**eos_cli_config_gen:**

add bfd on vrf/neighbor:

```yaml
router_bgp:
  vrfs:
    < vrf_name_1 >:
      neighbors:
        < neighbor>:
            bfd: < true | false >
```

**eos_designs**

Add bfd to bpg_peer.

```yaml
tenants:
    vrfs:
      # VRF name | Required
      < tenant_a_vrf_1 >:
        bgp_peers:
          < IPv4_address or IPv6_address >:
            bfd: < true | false >
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by tgodaA** [comment]
@carlbuchmann, I am trying the model below:

```yaml
router_bgp:
  vrfs:
    < vrf_name_1 >:
      neighbors:
        < neighbor>:
            bfd: < enabled | disabled | c-bit >
```

enabled: neighbor 10.10.10.1 bfd
disabled: no neighbor 10.10.10.1 bfd
c-bit: neighbor 10.10.10.1 bfd c-bit

I have tried to configure c-bit then applied disabled command and it worked! (removed the bfd config). So ```no``` command works without c-bit as well.

I don't like to mix and match boolean with a string. So came up with this model. I wanted to support c-bit as well for future use. Let me know your opinion!

@ClausHolbechArista any comments on this?

**Comment by ClausHolbechArista** [comment]
I would do
```yaml
bfd:
  enabled: < true | false >
  c_bit: < true | false >
```
