### ISSUE TITLE
Add support for AES-256-GCM when configuring tacacs keys

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1456]
### Enhancement summary

Currently TACACS keys are stored as password 7 which can be converted back from this pseudo hash to plain text.

Support should be added for `AES-256-GCM`

```
veos(config)#tacacs-server host 1.2.3.4 vrf MGMT key ?
  0     Indicates that the key string is not encrypted
  7     Specifies that a HIDDEN key will follow
  8a    Specifies that a AES-256-GCM encrypted key will follow
  LINE  Unobfuscated key string
```

https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/tacacs-servers.j2#L19-L21

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Harden config security

### Describe the solution you would like

```yaml
tacacs_servers:
  hosts:
    - host: 1.2.3.4
      vrf: MGMT
      key: '132112111915143E2E200A363030'
      key_type: < 0 | 7 | 8a | default -> 7 >
```

Speciy key type and key in one line.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
