### ISSUE TITLE
Add support for igmp snooping vlan querier

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#1461]
### Enhancement summary

Add support for IGMP vlan querier

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

CLI example:

```bash
no ip igmp snooping vlan 1-4, 9 querier
ip igmp snooping vlan 1-100 querier
```

### Describe the solution you would like

Data model TBD

current data model:

```yaml
ip_igmp_snooping:
  globally_enabled: < true | false | default -> true >
  vlans:
    < vlan_id >:
      enabled: < true | false >
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
