### ISSUE TITLE
Add support for reversiable encryption algorithm

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1468]
### Enhancement summary

See https://eos.arista.com/eos-4-27-0f/aes-gcm-encryption-of-eos-secret-configuration/

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Support for AES-GCM has been added as a method for storing symmetric secrets in EOS. This applies to secrets that must be used to remote systems, as found in NTP, TACACS+, and other places. Using this, the configuration can be secured since the secrets cannot be easily reversed or decrypted by copying the configuration out of the box.

### Describe the solution you would like

```yaml
management_security:
  password:
    encryption_reversible: < aes-256-gcm >
```

Using key `encryption_reversible` as the current design also utilizes a two stage CLI node in one key named `encryption_key_common`.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I can't decide if we should allow for the `custom` keyword to be included. In case someone adds their own key with other means, we will have to configure `custom` to use that key.
```yaml
management_security:
  password:
    encryption_key_common:
      enabled: < true | false >
      custom: < true | false >
    encryption_reversible: < aes-256-gcm >
```
