### ISSUE TITLE
bgp: add support to shutdown individual VRF neighbors

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1475]
### Enhancement summary

At the moment it is not possible to specify `shutdown` on a BGP peer when peer is located inside a VRF

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Temporary disable a neighborships for e.g. maintenances.

### Describe the solution you would like

```yaml
router_bgp:
  vrfs:
    foo:
      neighbors:
        2001:db8::1:
          shutdown: true
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
