### ISSUE TITLE
molecule eos_designs_unit_test fatal error

### ISSUE THREAD

**Issue by sengarth** [aristanetworks/ansible-avd#1479]
### Issue Summary

molecule eos_designs_unit_tests has a fatal error:
```
TASK [arista.avd.eos_designs : Set AVD facts] **********************************
fatal: [cvp-instance-ips-cvaas]: FAILED! => {"msg": "loopback_ipv4_pool was expected but not set!"}
```

The current `cvp-instance-ips-cvaas.yml` seems to have incorrect format for `loopback_ipv4_pool` parameter:
https://github.com/aristanetworks/ansible-avd/blob/d39775df7ce98b3bf0c364243ccfb393fc3bfc5f/ansible_collections/arista/avd/molecule/eos_designs_unit_tests/inventory/host_vars/cvp-instance-ips-cvaas.yml#L1-L7
Fatal error is resolved if `loopback_ipv4_pool` is moved to defaults section:
```
type: spine
spine:
  defaults:
    loopback_ipv4_pool: 1.2.3.4/24
  nodes:
    cvp-instance-ips-cvaas:
      id: 1
      bgp_as: 1234
```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
molecule test --scenario-name eos_designs_unit_tests
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
