### ISSUE TITLE
segment-routing policy configuration under router traffic-engineering

### ISSUE THREAD

**Issue by sengarth** [aristanetworks/ansible-avd#1480]
### Enhancement summary

Currently not able to configure segment-routing policy using eos_cli_config_gen. 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Create SRTE policies with structured formats under router traffic-engineering. For example a snippet as follows for a basic functional SRTE policy:

```
router traffic-engineering
   segment-routing
      rib system-colored-tunnel-rib
      !
      policy endpoint 1.2.3.4 color 70810
         binding-sid 970810
         name SRTE-1.2.3.4-70810
         description SRTE POLICY FOR 1.2.3.4 COLOR 70810
         !
         path-group preference 80
            segment-list label-stack 900002 900003 900005 900006
      !
      policy endpoint 5.6.7.8 color 20320
         binding-sid 978320
         !
         path-group preference 80
            explicit-null ipv6
            segment-list label-stack 900002 900003 900005 900006
            segment-list label-stack 900002 900004 900007 900006
   router-id ipv4 10.0.0.1
```

### Describe the solution you would like

Based on working configuration, below matching data format for a possible solution that provide for the same configurability with SRTE

```yaml
router_traffic_engineering:
  router_id:
    ipv4: 10.0.0.1
  segment_routing:
    colored_tunnel_rib: true
    policy_endpoint:
      1.2.3.4:
        color:
          70810:
            binding_sid: 970810
            description: "SRTE POLICY FOR 1.2.3.4 COLOR 70810"
            name: "SRTE-1.2.3.4-70810"
            path_group:
              - preference: 80
                segment_list:
                  - label_stack: "900002 900003 900005 900006"
      5.6.7.8:
        color:
          20320:
            binding_sid: 978320
            path_group:
              - preference: 80
                explicit_null: "ipv6"
                segment_list:
                  - label_stack: "900002 900003 900005 900006"
                  - label_stack: "900002 900004 900007 900006"
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
