### ISSUE TITLE
Support for link-tracking in port_profiles 

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#1500]
### Enhancement summary

Customer wants to be able to set link-tracking "downstream" ports at the port profile level in eos_designs role. Support for link-tracking groups in this role have been added recently:

Currently we can do the following:
```
   adapters:

      # Example of stand-alone adapter

..
        # Configure the downstream interfaces of a respective Link Tracking Group | Optional
        # If port_channel is defined in an adapter then port-channel interface is configured to be the downstream
        # else all the ethernet-interfaces will be configured as downstream -> to configure single-active EVPN multihomed networks
        link_tracking:
          enabled: < true | false >
          # The default group name is taken from fabric variable of the switch, link_tracking.groups[0].name with default value being "LT_GROUP1".
          # Optional if default link_tracking settings are configured on the node.
          name: < tracking_group_name >

```

### Which component of AVD is impacted

eos_designs

### Use case example

Customer uses A/A multhoming and must set server ports individually with the link-tracking set to downstream. He would like to set this at the port_profile level.

### Describe the solution you would like

Add link tracking as a setting that can be enabled at the port profile level in eos_designs.

Extend the following to also support link-tracking groups:
```
port_profiles:
  < port_profile_1 >:
    parent_profile: < port_profile_name >
    speed: < interface_speed | forced interface_speed | auto interface_speed >
    enabled: < true | false >
    mode: < access | dot1q-tunnel | trunk >
    mtu: < mtu >
    l2_mtu: < l2_mtu - if defined this profile should only be used for platforms supporting the "l2 mtu" CLI >
    native_vlan: <native vlan number>
    vlans: < vlans as string >
    spanning_tree_portfast: < edge | network >
    spanning_tree_bpdufilter: < "enabled" | true | "disabled" >
    spanning_tree_bpduguard: < "enabled" | true | "disabled" >
    flowcontrol:
      received: < "received" | "send" | "on" >
    qos_profile: < qos_profile_name >
    ptp:
      enable: < true | false >
    storm_control:
      all:
        level: < Configure maximum storm-control level >
        unit: < percent | pps > | Optional var and is hardware dependant - default is percent)
      broadcast:
        level: < Configure maximum storm-control level >
        unit: < percent | pps > | Optional var and is hardware dependant - default is percent)
      multicast:
        level: < Configure maximum storm-control level >
        unit: < percent | pps > | Optional var and is hardware dependant - default is percent)
      unknown_unicast:
        level: < Configure maximum storm-control level >
        unit: < percent | pps > | Optional var and is hardware dependant - default is percent)
    port_channel:
      description: < port_channel_description >
      mode: < "active" | "passive" | "on" >
      lacp_fallback:
        mode: < static > | Currently only static mode is supported
        timeout: < timeout in seconds > | Optional - default is 90 seconds
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
