### ISSUE TITLE
Doc(eos_cli_config_gen): Key exchange under management_ssh incorrectly documented in the README file

### ISSUE THREAD

**Issue by xaviramon** [aristanetworks/ansible-avd#1503]
### Issue Summary

Following structure is shown in README file for eos_cli_config_gen role:
```yaml
management_ssh:
  access_groups:
    - name: < standard_acl_name_1 >:
    - name: < standard_acl_name_2 >:
      vrf: < vrf name >
  ipv6_access_groups:
    - name: < standard_acl_name_1 >:
    - name: < standard_acl_name_2 >:
      vrf: < vrf name >
  idle_timeout: < 0-86400 in minutes >
  cipher:
    - < cipher1 >
    - < cipher2 >
  key-exchange:
    - < method1 >
    - < method2 >
  ```
However, the J2 template uses an underscore instead of hyphen:
```
{%     if management_ssh.key_exchange is arista.avd.defined %}
   key-exchange {{ management_ssh.key_exchange | join(" ") }}
{%     endif %}
```

### Which component(s) of AVD impacted

eos_cli_config_gen

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
