### ISSUE TITLE
Feat(eos_cli_config_gen): interface bfd echo

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1513]
### Enhancement summary

Add bfd echo as an option to any bfd configurable interface.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Add bfd echo as an option to any bfd configurable interface.

### Describe the solution you would like

```
ethernet_interfaces:
  Ethernet1:
    bfd:
      echo: < true | false >
port_channel_interfaces:
  Port-Channel1:
    bfd:
      echo: < true | false >
vlan_interfaces:
  Vlan100:
    bfd:
      echo: < true | false >
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
