### ISSUE TITLE
Feat(eos_cli_config_gen): bgp neighbor & peer_group rib-in pre-policy

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1519]
### Enhancement summary

Allow for the `router_bgp` `neighbor` and `peer_group` config for rib-in pre-policy retain < all | disabled>

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

This would bring further feature parity between EOS and eos_cli_config_gen.

### Describe the solution you would like

```
router_bgp:
  neighbor:
    < neighbor_ip >:
      rib_in_pre_policy_retain: < all | disabled>
  peer_group:
    < peer_group_name >:
      rib_in_pre_policy_retain: < all | disabled>
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
