### ISSUE TITLE
sFlow: add VRF awareness

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#152]
**Issue Type**
- Role enhancement

**Is your feature request related to a problem? Please describe.**
At this point in time it is not possible to configure sflow to run in any VRF. Some providers tend to
also send sFlow traffic via the Management VRF.

**Describe the solution you'd like**
The following YAML statement should render a proper EOS configureation
```
### sFlow ###
sflow:
  vrf:
    MGMT:
      destinations:
        192.0.2.1:
          port: 2222
        192.0.2.2:
      source_interface: Management1

  destinations:
    192.0.2.3:
      port: 3333
    192.0.2.4:

  source_interface: Eth11
  run: true
```

Will render:
```
!
sflow vrf MGMT destination 192.0.2.1 2222
sflow vrf MGMT destination 192.0.2.2
sflow vrf MGMT source-interface Management1
sflow destination 192.0.2.3 3333
sflow destination 192.0.2.4
sflow source-interface Eth11
sflow run
!
```

**Describe alternatives you've considered**
It could also have been deployed via a configlet, but as sFlow templating was already present, it should have been extended instead.

A PR from Rohde&Schwarz will follow.
