### ISSUE TITLE
Add storm-control support

### ISSUE THREAD

**Issue by ankudinov** [aristanetworks/ansible-avd#154]
**Issue Type**
- Template enhancement

**Describe the solution you'd like**
Add storm control support to ethernet-interfaces.j2 and port-channel-interfaces.j2.
The port-profile data model can look like:

```yaml
storm_control:
  <broadcast | multicast | all>:
    level: <storm-control-level>
    unit: <percent | pps>
```
