### ISSUE TITLE
Doc Bug - Internal VLAN order

### ISSUE THREAD

**Issue by bjmeuer** [aristanetworks/ansible-avd#1540]
### Issue Summary

`vlan_internal_order` versus `internal_vlan_order`

Documentation tells to use:

      ```
      vlan_internal_order:
        allocation: < ascending | descending >
        range:
          beginning: < vlan_id >
          ending: < vlan_id >
      ```

But in the Jinja2 Template it uses:

      ```
      vlan_internal_order:
        allocation: {{ internal_vlan_order.allocation }}
        range:
          beginning: {{ internal_vlan_order.range.beginning }}
          ending: {{ internal_vlan_order.range.ending }}
      ```

Either the documentation needs to be changed to:

      ```
      internal_vlan_order:
        allocation: < ascending | descending >
        range:
          beginning: < vlan_id >
          ending: < vlan_id >
      ```

or the jinja2 template needs to be changed to:

      ```
      vlan_internal_order:
        allocation: {{ vlan_internal_order.allocation }}
        range:
          beginning: {{ vlan_internal_order.range.beginning }}
          ending: {{ vlan_internal_order.range.ending }}
      ```

### Which component(s) of AVD impacted

eos_cli_config_gen

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
