### ISSUE TITLE
Add LLDP support

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#155]
**Issue Type**

- Template enhancement

**Describe the solution you'd like**
The following YAML representation should render the switch config:
```
### LLDP ###
lldp:
  timer: 120
  holdtime: 240
  management_address: Management1
  vrf: MGMT
```
```
!
lldp timer 120
lldp hold-time 240
lldp management-address Management1
lldp management-address vrf MGMT
lldp run
!
```

**Describe alternatives you've considered**
This could have been deployed by a configlet, too but that would not fit into the overall system.

PR from Rohde & Schwarz GmbH & Co. KG coming soon
