### ISSUE TITLE
Feat(eos_cli_config_gen): Add dr_priority to pim ipv4 configuration on interfaces

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1552]
### Enhancement summary

Add `dr_priority` to pim ipv4 configuration on interfaces (any interface that currently support pim).

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Currently you cannot set the pim ipv4 dr_priority.  This would add more feature parity with EOS.

### Describe the solution you would like

Add the following model:
```YAML
ethernet_interfaces:
  Ethernet1:
    pim:
      ipv4:
        dr_priority:  <0-429467295>
port_channel_interfaces:
  Port-Channel1:
    pim:
      ipv4:
        dr_priority:  <0-429467295>
vlan_interfaces:
  Vlan100:
    pim:
      ipv4:
        dr_priority:  <0-429467295>
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
