### ISSUE TITLE
bgp neighbor interface peer_filter

### ISSUE THREAD

**Issue by ssc-sagarcia** [aristanetworks/ansible-avd#1553]
### arista.avd. eos_cli_config_gen

 In "Router BGP Configuration". Currently unable to create a config line specifying a peer-filter for neighbor interface config. Looking for the feature to be officially supported via AVD vars.
 
 Current data model for neighbor interface config:
 ```
 router_bgp: 
  neighbor_interfaces:
    < interface >:
      peer_group: < peer_group_name >
      remote_as: < bgp_as >
      description: "< description as string >"
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Example configuration using this feature:
```
router bgp 4201081011
   router-id 1.1.1.11
   no bgp default ipv4-unicast
   bgp default ipv4-unicast transport ipv6
   maximum-paths 2 ecmp 2
   neighbor OL_LEAFS peer group
   neighbor OL_LEAFS next-hop-unchanged
   neighbor OL_LEAFS update-source Loopback0
   neighbor OL_LEAFS ebgp-multihop 3
   neighbor OL_LEAFS send-community
   neighbor OL_LEAFS maximum-routes 0
   neighbor UL_LEAFS peer group
   neighbor UL_LEAFS send-community
   neighbor UL_LEAFS maximum-routes 12000
   neighbor EDGE peer group
   neighbor EDGE send-community
   neighbor EDGE maximum-routes 12000
   neighbor interface Et1-12 peer-group UL_LEAFS peer-filter LEAFS-AS
   ```

### Describe the solution you would like

Additional variables for the `eos_cli_config_gen` data model where this configuration can de defined under:
```
router_bgp: 
  neighbor_interfaces:
    < interface >:
      peer_filter: < peer_filter_name >
      peer_group: < peer_group_name >
      remote_as: < bgp_as >
      description: "< description as string >"
```

### Describe alternatives you have considered

Current workaround is to add config line as part of:
 ```
 router_bgp: 
   bgp_defaults:
    - "< bgp command as string >"
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
