### ISSUE TITLE
Endpoint based EVPN instance filtering

### ISSUE THREAD

**Issue by perimore** [aristanetworks/ansible-avd#1575]
### Enhancement summary

Currently EVPN L2 and L3 instances are configured on a device based upon the assigned "tenants:" and "tags:" definition under the node_type_key:

https://www.avd.sh/en/latest/roles/eos_designs/doc/fabric-topology.html#evpn-services-management

This is problematic in large environment as the user has to track which tenants and tags are required on a device to serve the connected devices. Not only is this slightly cumbersome to manage, it can also lead to tags being missed or left assigned to a device that doesn't have any endpoints connected that require the L2 or L3 EVPN instance. 

The enhancement would introduce the ability to tag connected endpoints or port-profiles with tenant and/or VLAN tags. This will then decide if a VNI has to be configured under the VTI and included in the BGP config. 

It is expected that this will introduce a new tag type as not to interfere with the existing tag logic or introduce a global "endpoint_based" filter setting.

### Which component of AVD is impacted

eos_designs

### Use case example

An example would be the creation of a port profile. This would have an "endpoint_tenant" and/or "endpoint_tag" definition.

AVD would iterate over devices that these tags assigned and only generate the VNI to VRF and VLAN mapping and BGP VLAN and VRF configuration if present.

### Describe the solution you would like

Consider the Tenant definition below:

```
Tenant_A:
  mac_vrf_vni_base: 10000
  vrfs:
    Tenant_A_WEB_Zone:
      endpoint_tags: [ Tenant_A_WEB_Zone ] <-- New tag?
      vrf_vni: 11
      svis:
        120:
          name: Tenant_A_WEB_Zone_1
          tags: [web, erp1]
          enabled: true
          ip_subnet: 10.1.20.0/24
...
Tenant_B:
  mac_vrf_vni_base: 20000
  vrfs:
    Tenant_B_OP_Zone:
      endpoint_tags: [ Tenant_B_OP_Zone ] <-- New tag?
      vrf_vni: 20
      svis:
        210:
          name: Tenant_B_OP_Zone_1
          tags: [opzone]
          enabled: true
          ip_subnet: 10.2.10.0/24
```

The tenant and tags would be assigned to a profile or port as:

```
port_profiles:
  TENANT_A_B:
    endpoint_tags: [Tenant_A_WEB_Zone,Tenant_B_OP_Zone]
    mode: trunk
    vlans: "110-112"
    spanning_tree_portfast: edge
  TENANT_A:
    mode: trunk
    vlans: "110-111,114"
    spanning_tree_portfast: edge
  TENANT_B:
    mode: trunk
    vlans: "210-211"

servers:
  pod01-srv:
    rack: RackA
    adapters:
      - type: nic
        enabled: false
        server_ports: [Eth1]
        switch_ports: [Ethernet5]
        switches: [DC1-L2LEAF1A]
        endpoint_tags: [Tenant_A_WEB_Zone]
        tags: [web]
```

In this case:

1. Devices with any ports that have the profile TENANT_A_B assigned would have the two VRFs configured, VNI to VRF mappings and BGP VRFs configured, plus any VLANs associated with the VRF. VLAN tags can be added to the profile to further "prune" the config but in this case, VLANs 110-112 are trunked as they have been overridden by the "vlan:" definition.
2. DC1-L2LEAF1A will be configured with VRF Tenant_A_WEB_Zone, VNI to VRF mappings and the BGP VRF configured. In addition to this, the tag "web" causes only VLAN 120 to be configured on the trunk but also only the appropriate L2 EVPN instance too.

This will probably mean we cannot use VLAN aware bundles due to the possible ungrouping of VLANs. Or we restrict the port/profile tagging to VRFs and insist that all VLANs associated with the VRF are imported.

### Additional context

This could be used in conjunction with Route-Target Membership / Constraint – RFC4684 to further improve scale.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
