### ISSUE TITLE
Feat(eos_cli_config_gen): router multicast ipv4 counters support

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1581]
### Enhancement summary

Add router_multicast['ipv4']['counters'] to the model

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

This is a default configuration that gets populated / displayed in the running config (not hidden) when you activate router multicast for ipv4.

### Describe the solution you would like

```yaml
router_multicast:
  ipv4:
    counters:
      rate_period_decay: 300
```

```eos
router multicast
   ipv4
      counters rate period decay 300 seconds
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
