### ISSUE TITLE
Fix(eos_cli_config_gen): Router bgp vlan config order

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1605]
### Issue Summary

Router bgp vlan config order.

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```yaml
router_bgp:
    as: 65000
    vlans:
        66:
            rd: 192.168.224.35:66
            redistribute_routes:
            - learned
            route_targets:
                both:
                - 11100:66
        67:
            rd: 192.168.224.35:67
            redistribute_routes:
            - learned
            route_targets:
                both:
                - 11100:67
        400:
            rd: 192.168.224.35:400
            redistribute_routes:
            - learned
            route_targets:
                both:
                - 11100:400
        500:
            rd: 192.168.224.35:500
            redistribute_routes:
            - learned
            route_targets:
                both:
                - 11100:500
        600:
            rd: 192.168.224.35:600
            redistribute_routes:
            - learned
            route_targets:
                both:
                - 10101:600
        666:
            rd: 192.168.224.35:666
            redistribute_routes:
            - learned
            route_targets:
                both:
                - 11100:666
        667:
            rd: 192.168.224.35:667
            redistribute_routes:
            - learned
            route_targets:
                both:
                - 11100:667
        700:
            rd: 192.168.224.35:700
            redistribute_routes:
            - learned
            route_targets:
                both:
                - 10101:700
```

Expected Config:
```eos
router bgp 65000
   !
   vlan 400
      rd 192.168.224.35:400
      route-target both 11100:400
      redistribute learned
   !
   vlan 500
      rd 192.168.224.35:500
      route-target both 11100:500
      redistribute learned
   !
   vlan 600
      rd 192.168.224.35:600
      route-target both 10101:600
      redistribute learned
   !
   vlan 66
      rd 192.168.224.35:66
      route-target both 11100:66
      redistribute learned
   !
   vlan 666
      rd 192.168.224.35:666
      route-target both 11100:666
      redistribute learned
   !
   vlan 667
      rd 192.168.224.35:667
      route-target both 11100:667
      redistribute learned
   !
   vlan 67
      rd 192.168.224.35:67
      route-target both 11100:67
      redistribute learned
   !
   vlan 700
      rd 192.168.224.35:700
      route-target both 10101:700
      redistribute learned
```

Actual Config:
```eos
router bgp 65000
   !
   vlan 66
      rd 192.168.224.35:66
      route-target both 11100:66
      redistribute learned
   !
   vlan 67
      rd 192.168.224.35:67
      route-target both 11100:67
      redistribute learned
   !
   vlan 400
      rd 192.168.224.35:400
      route-target both 11100:400
      redistribute learned
   !
   vlan 500
      rd 192.168.224.35:500
      route-target both 11100:500
      redistribute learned
   !
   vlan 600
      rd 192.168.224.35:600
      route-target both 10101:600
      redistribute learned
   !
   vlan 666
      rd 192.168.224.35:666
      route-target both 11100:666
      redistribute learned
   !
   vlan 667
      rd 192.168.224.35:667
      route-target both 11100:667
      redistribute learned
   !
   vlan 700
      rd 192.168.224.35:700
      route-target both 10101:700
      redistribute learned
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
