### ISSUE TITLE
Can not reference Ansible variables in SSH management for VRFs

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#161]
## Issue Type

- Bug Report / Feature / Change

## Summary

I try to reuse my variables as much as possible. When using a management VRF it should be able for every service to reuse a defined variable as the VRFs name. Thus the name of the Management VRF must be defined only once and is then pulled in automatically.

This does not work with the current design of the `eos_cli_config_gen` role, as the VRF is not specified as `- name: VRFNAME`

When looking at the SNMP implementation this is done in the correct way but not on SSH management. I must define the VRFs name directly:

```
### SSH Management ###
management_ssh:
  idle_timeout: 30 # this value is in minutes
  vrfs:
    MGMT:
      enable: true
```

When using a variable it won't be expanded when rendering the config:

```
### SSH Management ###
management_ssh:
  idle_timeout: 30 # this value is in minutes
  vrfs:
    {{ mgmt_interface }}:
      enable: true
```

Will result in
```
management ssh
   idle-timeout 30
   shutdown
   !
   vrf {{ mgmt_interface }}
      no shutdown
```

## Role or Module Name

eos_cli_config_gen

`arista.avd` collection and Python libraries version

```shell
$ pip3 freeze
ansible==2.9.2
attrs==19.3.0
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
cryptography==2.9.2
idna==2.8
importlib-metadata==1.6.0
Jinja2==2.10.3
MarkupSafe==1.1.1
more-itertools==8.2.0
netaddr==0.7.19
packaging==20.3
pluggy==0.13.1
py==1.8.1
pycparser==2.20
pyparsing==2.4.7
pytest==5.3.4
pytest-html==2.0.1
pytest-metadata==1.9.0
PyYAML==5.3.1
requests==2.22.0
six==1.14.0
treelib==1.5.5
urllib3==1.25.9
wcwidth==0.1.9
zipp==3.1.0
```

I'm happy to implement this change but this will break existing installation thus I wan't to clarify this beforehand.
