### ISSUE TITLE
Adjusting show tech-support outputs

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1617]
### Enhancement summary

According to https://aristanetworks.force.com/AristaCommunity/s/article/inet-edge-config

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Remove certain commands from the 'show tech-support' output so that the size of the archives are drastically reduced.

### Describe the solution you would like

```yaml
management_tech_support:
  policy_show_tech_support:
    exclude_commands:
      - command: < command_to_exclude >
        type: < text | json | default -> text >
    include_commands:
      - command: < command_to_include >
```

Example:

```yaml
management_tech_support:
  policy_show_tech_support:
    exclude_commands:
      - command: show platform fap ip route
      - command: show platform fap ipv6 route
      - command: show ip bgp vrf all
      - command: show ipv6 bgp vrf all
      - command: show kernel ip route vrf all
      - command: show kernel ipv6 route vrf all
      - command: show ip route vrf all detail
      - command: show ipv6 route vrf all detail
      - command: show version detail
        type: json
    include_commands:
      - command: show version detail | grep TerminAttr

```

### Additional context

PR incoming

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
