### ISSUE TITLE
FlexRoute: add support for compression and expansion of prefixes

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1620]
### Enhancement summary

According to https://aristanetworks.force.com/AristaCommunity/s/article/inet-edge-config

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

You can enable FlexRoute compression and expansion of prefixes.  While these commands can be customized for different prefix lengths, Arista has included pre-defined 'internet' profiles for both IPv4 and IPv6 based on the current contents of the Internet routing table.

#### IPv4
```yaml
ip_hardware:
  fib:
    optimize:
      prefix_profile: < internet | urpf-internet >
```

#### IPv6
```yaml
ipv6_hardware:
  fib:
    optimize:
      prefix_profile: < internet >
```

### Additional context

PR incoming

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
