### ISSUE TITLE
Support multiple VRRP VRID per interface

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1636]
### Enhancement summary

Support both IPv4 and IPv6 for VRRP.

Currently only one VRID can be specified per interface - EOS supports multiple VRIDs per interface.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Some networks server multiple IPv4 addresses (one per each VRID) or both IPv4 and IPv6 as FHRP.

In our case we do want to have one VRID for IPv4 and one VRIP for IPv6 - this is currently not possible.

### Describe the solution you would like

```yaml
vlan_interfaces:
  < Vlan_id_1 >:
    vrrp:
      < vrid >:
        priority: < instance_priority >
        advertisement_interval: < advertisement_interval>
        preempt:
          delay:
            minimum: < minimum_preemption_delay >
            reload: < minimum_preemption_delay >
        ipv4: < virtual_ip_address >
        ipv6: < virtual_ip_address >
```

### Additional context

As I have never done a change of CLI commands I am unable to submit a PR here.

In the past we used one VRID for both IPv4 and IPv6 but that made VRRP behave weird as the reload delay was not honored. TAC case will be opened here, too.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by carlbuchmann** [comment]
@c-po - thanks for raising this Issue! looking at the existing data model, I believe we should be able to support both new and old data model simultaneously.

Also note we are changing input schemas across the board to remove wildcards dictionary in favor of list of dictionaries. This will allow us to implement and enforce a schema in later releases. so instead of doing `< vrid >:` we would do `- id: < vrid >` in your suggested data model.

On Monday I’ll suggest proposed data model to support both - your input is welcome too if you have some ideas!

**Comment by carlbuchmann** [comment]
@c-po - here's what I would suggest we implement to support both data models in parallel!

```yaml
vlan_interfaces:
  < Vlan_id_1 >:
    # New improved "vrrp" data model to support multiple IDs
    vrrp_ids:
      - id: < vrid >
        priority: < instance_priority >
        advertisement_interval: < advertisement_interval>
        preempt:
          enabled: < true | false >
          delay:
            minimum: < minimum_preemption_delay >
            reload: < minimum_preemption_delay >
        ipv4:
          address: < virtual_ip_address >
        ipv6:
          address: < virtual_ip_address >
    # The below "vrrp" keys will be deprecated in AVD v4.0 - These should not be mixed with the new "vrrp_ids" key above to avoid conflicts.
    vrrp:
      virtual_router: < virtual_router_id >
      priority: < instance_priority >
      advertisement_interval: < advertisement_interval>
      preempt_delay_minimum: < minimum_preemption_delay >
      ipv4: < virtual_ip_address >
      ipv6: < virtual_ip_address >
```

@ClausHolbechArista @ankudinov - We did something similar to support the new [access-lists construct](https://avd.sh/en/latest/roles/eos_cli_config_gen/index.html#ip-extended-access-lists) - please let me know if you agree with this suggestion!

**Comment by c-po** [comment]
Looks awesome @carlbuchmann - thanks

**Comment by ClausHolbechArista** [comment]
Please add a key for enabled under preempt, so in case you don't want to set the delay, we avoid a "dangling" key.
```yaml
preempt:
  enabled: < true | false >
  delay:
    ...
```
