### ISSUE TITLE
Ability to configure bgp feature remove-private-as per neighbor

### ISSUE THREAD

**Issue by vyelpale** [aristanetworks/ansible-avd#1641]
### Enhancement summary

Support to enable bgp knob "remove-private-as" at the neighbor level.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Customer is going to use AVD to implement VXLAN evpn fabric with multiple external routers(MPLS routers,SDHWAN routers) hanging off of the VTEP and enabling bgp peering with VTEPs. Border leaf (acting as VTEP) will be connecting to the MPLS DCI where customer would like to remove the private ASN that will be used within the VXLAN fabric before routes are advertised into the core . This use case will require configuring remove-private-as bgp knob for the neighbors.

CLI:
neighbor <ip/ipv6/peer-group> remove-private-as <cr/all/ingress> <replace-as>

replace-as extension is not required as of today, but may be required as part of this feature by the customer in future. By implementing replace-as this knob will be fully supported by AVD.

CLI reference guide:
https://docs.google.com/document/d/1XPfwnzSWX_a-KmBpsdAztsgeYqJeuwZ_twwkUlX04GQ/edit

### Describe the solution you would like

```yaml
router_bgp:
 neighbors:
   remove_private_as: 
      enabled: <true | false>
      all: <true | false>
      ingress: <true | false >
      replace-as: <true | false>
 peer_groups:
   remove_private_as: 
      enabled: <true | false>
      all: <true | false>
      ingress: <true | false >
      replace-as: <true | false>
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
