### ISSUE TITLE
Feat(eos_cli_config_gen): router_multicast rpf route

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1671]
### Enhancement summary

Add support for router_multicast rpf routes

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Configure multicast rpf routes

### Describe the solution you would like

model:    
```yaml
router_multicast:
  ipv4:
    rpf:
      routes:
        < IPv4 subnet / netmask >:
          nexthop: < IPv4_network/Mask >
          interface: < interface >  # optional
          distance: < 1 - 255 >  # optional
```

### Describe alternatives you have considered

N/A

### Additional context

N/A

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
