### ISSUE TITLE
Feat(eos_cli_config_gen): router_general routes dynamic prefix-list

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1672]
### Enhancement summary

Add router_general routes dynamic prefix-list

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Add router_general routes dynamic prefix-list

### Describe the solution you would like

model:
```yaml
router_general:
  vrfs:
    < destination-vrf >:
      routes:
        dynamic_prefix_lists:
          - < dynamic_prefix_list_1 >
          - < dynamic_prefix_list_2 >
```

### Describe alternatives you have considered

N/A

### Additional context

N/A

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
