### ISSUE TITLE
Feat(eos_cli_config_gen): add dynamic prefix-lists

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#1673]
### Enhancement summary

Add dynamic prefix-lists

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Add dynamic prefix-lists

### Describe the solution you would like

model:
```yaml
dynamic_prefix_lists:
  < dynamic_prefix_list_name_1 >:
    match_map: < route_map >
    prefix_list:
      ipv4: < prefix_list >
  < dynamic_prefix_list_name_2 >:
    match_map: < route_map >
    prefix_list:
      ipv6: < prefix_list >
```

### Describe alternatives you have considered

N/A

### Additional context

N/A

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
