### ISSUE TITLE
Feat(eos_cli_config_gen): Support for CVX client commands

### ISSUE THREAD

**Issue by sugetha24** [aristanetworks/ansible-avd#1681]
### Enhancement summary

Add support for Management CVX commands on CVX clients
```
management cvx
   no shutdown
   server host 10.90.224.188
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Configure CVX clients

### Describe the solution you would like

Data Model:
```
management_cvx:
  shutdown: false
  server_host:
    - < IPv4_address >
    - < IPv4_address >
```
Eg:
```
management_cvx:
  shutdown: false
  server_host:
  - 10.90.224.188
  - 10.90.224.189
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
