### ISSUE TITLE
Add support for management api models configuration 

### ISSUE THREAD

**Issue by morinpa** [aristanetworks/ansible-avd#1695]
### Enhancement summary

Support for configuring management api models. 

- management api models 
  - set provider
  - set paths

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

we need to be able to configure management api models to be able to subscribe to smash paths

### Describe the solution you would like

These are our required configs

```
management api models
   provider smash
      path bridging
      path routing
```

and here is a very basic data model for this: 

```
management_api_models:
  providers: 
    < provider >: 
      paths:
      - path1
      - path2
      - ...
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by UchihaItachiSama** [comment]
And alternative would be to use [`eos_cli`](https://www.avd.sh/en/latest/roles/eos_cli_config_gen/index.html#eos-cli) to add this to the EOS config.

in the data model we could also consider option of disabling a particular path, which is also available in the CLI.
```yml
management api models
   provider smash
      path forwarding/status
      path routing/status disabled

> show management api models
provider smash
  path /Smash/forwarding/status
  path /Smash/routing/status disabled
```

**Comment by ClausHolbechArista** [comment]
My suggestion for a slightly modified data model:
```yaml
management_api_models:
  providers:
    - name: < provider >
      paths:
      - path: < path1 >
        enabled: < true | false | default -> true >
```

We will no longer implement dictionaries with "wildcard" keys, so above I have converted to list-of-dict.
