### ISSUE TITLE
Feat(eos_cli_config_gen): VRRP timer delay and IPv4 version CLI options

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#1705]
### Enhancement summary

Add support for VRRP timer delay reload command per VRID

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Reload switch in VRRP switch which also consumes a BGP full routing table. As BGP still processes all the routes switch must be prevented to become VRRP master

### Describe the solution you would like

```yaml
   # New improved "vrrp" data model to support multiple IDs
    vrrp_ids:
      - id: < vrid >
        timers:
          delay:
            reload: < integer >
```

### Additional context

PR incoming

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
