### ISSUE TITLE
Add support for multicast config under Ethernet and Vlan interfaces.

### ISSUE THREAD

**Issue by morinpa** [aristanetworks/ansible-avd#1708]
### Enhancement summary

add the capability to configure the following: 
(under Ethernet and Vlan interfaces) 

```
interface < Ethernet | vlan >
   ...
   multicast < ipv4 | ipv6 > boundary < acl-name > out
   multicast < ipv4 | ipv6 > static
   ...
!

```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

We need to be able to configure static multicast and multicast boundaries on Ethernet and Vlan interfaces. 

### Describe the solution you would like

A possible solution would take the following yaml and output the wanted cli configuration

```
ethernet_interfaces: 
  -name: Ethernet1
   ...:
   multicast:
     ipv4:
       static:
       boundary: < acl-name >
```

output

```
interface Ethernet1
   ...
   multicast ipv4 static
   multicast ipv4 acl-name out 
!
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
