### ISSUE TITLE
tacacs and aaa authentication and authorization enhancements

### ISSUE THREAD

**Issue by morinpa** [aristanetworks/ansible-avd#172]
**Issue Type**

- Template enhancement

**Describe the solution you'd like**
The following YAML representation should render the switch config:

```
tacacs_servers:
   policy_unknown_mandatory_attribute_ignore: true

aaa_authentication:`
  policies:
    - on-sucess log
    - on-failure log

aaa_authorization:
  commands: all default local group GROUP
  serial_console: false`
```

```
tacacs server policy unknown-mandatory-attribute ignore

aaa authentication policy on-sucess log 
aaa authentication policy on-failure log 

aaa authorization commands all default local group GROUP
no aaa authorization serial-console
```

**Describe alternatives you've considered**
This could have been deployed by a configlet, too but that would not fit into the overall system. I also considered raising my idea on the mailing list first, but could not find the address. 

**Additional context**
Also, the role eos_l3ls_evpn is using a local template for authorization in base/aaa-authorization.j2 instead of the template in the role eos_cli_config.  I feel this might be an unintended behavior.
