### ISSUE TITLE
(eos_cli_config_gen): Add support for SNMPv3 user localized syntax

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#1720]
### Enhancement summary

As of now the eos_cli_config_gen module only support the following syntax:

```
snmp-server user <USER> <GROUP> v3 [auth <AUTH_ALGORITHM> <CLEARTEXT_AUTH_PASSPHRASE> [priv <PRIV_ALGORITHM> <CLEARTEXT_PRIV_PASSPHRASE>]]
```

(though the documentation indicates "encrypted" passphrases for auth and priv, this is not accurate as the passphrases will be rehashed with the local engineID when configured on the switch.)

This feature request intends to allow the configuration of:

```
snmp-server user <USER> <GROUP> v3 localized <ENGINE-ID> [auth <AUTH_ALGORITHM> <HASHED_AUTH_PASSPHRASE> [priv <PRIV_ALGORITHM> <HASHED_PRIV_PASSPHRASE>]]
```

in addition to the existing options.

Note that it requires a local engine ID to be provided as well (by default the engine ID is derived from the switch system MAC). 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

As it is now, it is not possible to have the auth and priv passphrase NOT in cleartext inside the AVD config as it is not possible to send the command using the localized keyword which is dependent on the engineID (which default value on the switch is unknown to AVD).

The intention is to allow the configuration to be done at eos_cli_config_gen level and to later on leverage this capability from eos_designs role to auto generate the hashed passphrases when required, using a potentially auto-generate engine ID.

### Describe the solution you would like

```
snmp_server:
  engineid:
    local: <ENGINE-ID>
[...]
     - name: < username >
       group: < group_name >
       version: < v1 | v2c | v3 >
       localized: < true | false >
       auth: < hash_algorithm >
       auth_passphrase: < hashed_auth_passphrase if localized is true else cleartext auth_passphrase >
       priv: < encryption_algorithm >
     priv_passphrase: < hashed_priv_passphrase if localized is true else cleartext priv_passphrase >
```

### Describe alternatives you have considered

Using vault to hide the password in the variables YAML file but it will still be present in the end configuration.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
