### ISSUE TITLE
Shutdown ports facing an undeployed device.

### ISSUE THREAD

**Issue by perimore** [aristanetworks/ansible-avd#1744]
### Enhancement summary

The "is_deployed = false" setting excludes a device from being configured in CloudVision. This is intended for when a device is not present in the network. However, as expected, if the device is not present, the ports facing this device on a peer will end up being configured but will be down. Not only is this a security concern but it causes the validate role to raise an error as the port is expected to be up.

This enhancement causes the underlay peer port to be shutdown.

### Which component of AVD is impacted

eos_designs, eos_config_deploy_cvp

### Use case example

Consider the simple topology below:

DC1_SPINE1 <Eth1---Eth1> DC1_BL2

Inventory file:

```
  DC1_BL2:
    hosts:
      DC1-BL2A:
        # Device configuration is generated by AVD
        # Device is not configured on Cloudvision (configlet is uploaded)
        is_deployed: false
```

Expected state on DC1_SPINE1:

```
interface Ethernet1
  shutdown
```

But config for DC1_BL2 is still generated.

### Describe the solution you would like

As per the example. The peer underlay port should be shutdown.

### Describe alternatives you have considered

Perhaps a global setting should be used to determine whether is_deployed = false causes the underlay port to be shutdown but this will add more toggles.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
