### ISSUE TITLE
Feat(eos_cli_config_gen): OSPF redistribute protocol include leaked support

### ISSUE THREAD

**Issue by danieltudares** [aristanetworks/ansible-avd#1766]
### Enhancement summary

Currently `router_ospf > redistribute` doesn't support the option to include leaked routes:

```yaml
      redistribute:
        static:
          route_map: < route_map_name >
        connected:
          route_map: < route_map_name >
        bgp:
          route_map: < route_map_name >
```

Also, only three source protocol are supported (static / connected / bgp) with no support for other protocols (eos also has support for redistribute isis and ip). 

I would like to propose to enhance `router_ospf > redistribute` to include other protocols and the option of including leaked routes.  

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Customer is currently trying to redistribute bgp leaked routes into ospf and needs to use `raw_eos_cli` command

### Describe the solution you would like

Replace the current model for"

```yaml
      redistribute:
        < route_type >:
          include_leaked: < true | false >
          route_map: < route_map_name >
```

AVD 4.0: 

```yaml
      redistribute:
        - source_protocol: < route_type >
          include_leaked: < true | false >
          route_map: < route_map_name >
```

### Describe alternatives you have considered

Change current model to be able to loop over `source_protocol` instead of validating fixed source protocols. 

### Additional context

This is a customer request enhancement. 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
