### ISSUE TITLE
Support OSPF tuning/configuration parameters

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#1768]
### Enhancement summary

Support ospf configuration parameters at the high-level design layer.

### Which component of AVD is impacted

eos_designs

### Use case example

BGP EVPN overlay over a partially-meshed routed OSPF core with a partial mesh between the cores.

### Describe the solution you would like

Add keys to support tuning of ospf, at the high-level design level, similar to: 
   * `ospf_auto_cost_reference_bandwidth`
   * `ospf_maximum_paths`
   * `ospf_log_adjacency_changes_detail`
   * `ospf_max_lsa`
   * `ospf_timers`
     * `lsa`
       * `arrival`
     * `out_delay`
     * `throttle`
       * `lsa`
       * `spf`
   * `ospf_max_metric`
     * `router_lsa`
       * `on_startup`
   * `ospf_bfd_adjacency_state_any`

### Describe alternatives you have considered

This can be rendered today using:
```yaml
custom_structured_configuration_router_ospf:
  process_ids:
    100:
      bfd_enable: true
      max_lsa: 12000
      auto_cost_reference_bandwidth: 1000000
      maximum_paths: 64
      log_adjacency_changes_detail: true
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
