### ISSUE TITLE
Feat(eos_designs): Support OSPF authentication on p2p links

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#1769]
### Enhancement summary

Currently, ospf p2p links do not support authentication.  p2p links should be extended to render either `simple` or `md5` authentication. 

### Which component of AVD is impacted

eos_designs

### Use case example

Ospf authentication across p2p links

### Describe the solution you would like

Currently, core_routers: p2p_networks, renders 
```jinja2
{%         if switch.underlay_routing_protocol in ["ospf", "ospf-ldp"] %}
    ospf_network_point_to_point: true
    ospf_area: {{ underlay_ospf_area }}
{%         endif %}
```
I propose the addition of the following keys (taken from the existing molecule test):
```yaml
    ospf_authentication: message-digest
    ospf_authentication_key: "asfddja23452"
    ospf_message_digest_keys:
      1:
        hash_algorithm: md5
        key: "asfddja23452" 
```

### Describe alternatives you have considered

Structured configuration can be manually added to each side of every p2p link, but seems to be prone to errors. 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
