### ISSUE TITLE
Add support for authenticating only ntp servers

### ISSUE THREAD

**Issue by morinpa** [aristanetworks/ansible-avd#1783]
### Enhancement summary

We would like to have the capability to configure the following 

`ntp authenticate servers`

to force authentication with the servers only and not with clients. 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

In a specific case where an Arista switch is used to distribute NTP in an environment where some clients can't authenticate, but we would still like the connections to the upstream NTP servers to be authenticated. 

### Describe the solution you would like

The following small change to the data model should do the trick. 

```
ntp:
  local_interface:
    name: < source_interface >
    vrf: < vrf_name >
  servers:
    - name: < IP | hostname >
      burst: < true | false >
      iburst: < true | false >
      key: < 1 - 65535 >
      local_interface: < source_interface >
      maxpoll: < 3 - 17 (Logarithmic) >
      minpoll: < 3 - 17 (Logarithmic) >
      preferred: < true | false >
      version: < 1 - 4 >
      vrf: < vrf_name >
  authenticate: <true | false | servers>
  authentication_keys:
    - id: < key_identifier | 1-65534 >
      hash_algorithm: < md5 | sha1 >
      key: "< type7_obfuscated_key >"
  trusted_keys: "< list of trusted-keys as string ex. 10-12,15 >"
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
