### ISSUE TITLE
JSON syntax not supported with Tenants vlans.

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#180]
## Issue Type

- Bug Report

## Summary

When using JSON as language for group_vars, template engine fails to render vars with `EOS_L3LS_EVPN`.

## Role or Module Name

Role: `eos_l3ls_evpn`

## OS / Environment

__EOS Version__

N/A

__Cloudvision version__

N/A

__OS running Ansible__

Docker from avdteam/base:3.6

## Steps to reproduce

[Convert](https://www.convertjson.com/yaml-to-json.htm) following YAML into JSON and save output under `group_vars/TENANT_NETWORKS.json`

```yaml
---
# Documentation of Tenant specific information - Vlans/VRFs
tenants:
  Tenant_test:
    l2vlans:
      111:
        name: v_test_111
        tags:
        - compute
      112:
        name: v_test_112
        tags:
        - compute
      210:
        name: v_test_210
        tags:
        - compute
    mac_vrf_vni_base: 10000
    name: Tenant_test
    vrfs:
      Tenant_test_vrf_a:
        name: Tenant_test_vrf_a
        svis:
          110:
            enabled: true
            id: 110
            ip_subnet: 10.1.110.0/24
            name: Tenant_test_vrf_a_110
            tags:
            - compute
            tenant: Tenant_test
            vrfs: Tenant_test_vrf_a
          120:
            enabled: 1
            id: 120
            ip_subnet: 10.144.100.0/24
            name: Tenant_test_vrf_a_120
            tags:
            - compute
            tenant: Tenant_test
            vrfs: Tenant_test_vrf_a
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24
```

Remove YAML version from your group_vars

```shell
$ mv group_vars/DC1_TENANTS_NETWORKS.yml group_vars/DC1_TENANTS_NETWORKS.orig-yaml
```

### Expected results

Playbook execution should work with no error

### Actual results

Error raised at: `TASK: eos_l3ls_evpn : Generate device configuration in structured format (yaml)`

```shell
[...]

    ### Routing - OSPF ###
    router_ospf:
    {# underlay #}
    {% include 'underlay-overlay/router-ospf.j2' %}

    {# queue monitor streaming #}
    ### Queue Monitor Streaming ###
    queue_monitor_streaming:
    {% include 'base/queue-monitor-streaming.j2' %}

    {# management api http #}
    ### Management API http ###
    management_api_http:
    {% include 'base/management-api-http.j2' %}): unsupported operand type(s) for +: 'int' and 'AnsibleUnicode'
```

### Current Workaround

Force JSON key to be `int` and not `str` which is not pure JSON compliant.

```json
{
    "tenants": {
        "Tenant_test": {
            "l2vlans": {
                111: {
                    "name": "v_test_111",
                    "tags": [
                        "compute"
                    ]
                },
                112: {
                    "name": "v_test_112",
                    "tags": [
                        "compute"
                    ]
                },
                210: {
                    "name": "v_test_210",
                    "tags": [
                        "compute"
                    ]
                }
            },
            "mac_vrf_vni_base": 10000,
            "name": "Tenant_test",
            "vrfs": {
                "Tenant_test_vrf_a": {
                    "name": "Tenant_test_vrf_a",
                    "svis": {
                        110: {
                            "enabled": true,
                            "id": 110,
                            "ip_subnet": "10.1.110.0/24",
                            "name": "Tenant_test_vrf_a_110",
                            "tags": [
                                "compute"
                            ],
                            "tenant": "Tenant_test",
                            "vrfs": "Tenant_test_vrf_a"
                        },
                        120: {
                            "enabled": 1,
                            "id": 120,
                            "ip_subnet": "10.144.100.0/24",
                            "name": "Tenant_test_vrf_a_120",
                            "tags": [
                                "compute"
                            ],
                            "tenant": "Tenant_test",
                            "vrfs": "Tenant_test_vrf_a"
                        }
                    },
                    "vrf_vni": 10,
                    "vtep_diagnostic": {
                        "loopback": 100,
                        "loopback_ip_range": "10.255.1.0/24"
                    }
                }
            }
        }
    }
}
```

Long term approach would be to cast type to int when required by templates
