### ISSUE TITLE
Feat(eos_cli_config_gen): SBFD configuration under Router BFD and SR-TE policy

### ISSUE THREAD

**Issue by sengarth** [aristanetworks/ansible-avd#1802]
### Enhancement summary

Render SBFD configuration under router bfd and SRTE policy under router traffic-engineering.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

When SRTE policy is configured, SBFD may be needed to monitor the policy via router bfd and the destination to be configured as a reflector.

### Describe the solution you would like

Add sbfd section in router_bfd:
```yaml
router_bfd:
  sbfd:
    local_interface:
      name: < interface name >
      protocol: < ipv4 | ipv6 | ipv4 ipv6 >
    initiator_interval: < rate in milliseconds >
    initiator_multiplier: < 3-50 >
    reflector:
      min_rx: < rate in milliseconds >
      local_discriminator: < IPv4_address | u32 format >
```

In SR policy, configure destination (remote discriminator)
```yaml
router_traffic_engineering:
  router_id:
    ipv4: 10.0.0.1
    policy_endpoints:
      - address: 1.2.3.4
        colors:
          - value: 70810
           
            # Add below line to render sbfd configuration under policy endpoint
            sbfd_remote_discriminator: 155.2.1.1
```
This allow the SR node to function as both sbfd headend and reflector

### Describe alternatives you have considered

Using raw eos cli

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
