### ISSUE TITLE
Feat(eos_cli_config_gen):  Add support for Campus ZTP through VLAN advertised from Spine/Aggregation Switch

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#1840]
### Enhancement summary

EOS 4.27.1F adds support for ztp vlan negotiation.  

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

The use case is best explained at: https://www.arista.com/en/support/toi/eos-4-27-1f/14879-campus-ztp-through-vlan-advertised-from-spine-aggregation-switch

### Describe the solution you would like

Extend the lldp key under the interface to support a new key:

```yaml
ethernet_interface:
  lldp:
    tlv_tranmit:
      ztp_vlan: 4090
```

which would render:

```
lldp tlv transmit ztp vlan 4090
```

### Describe alternatives you have considered

This can be rendered today with:

```yaml
ethernet_interface:
  eos_cli: |
    lldp tlv transmit ztp vlan 4090
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
