### ISSUE TITLE
Feat(eos_cli_config_gen): add ip helper addresses to ethernet interfaces

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#1843]
### Enhancement summary

Provide the ability to add a helper address to an Ethernet interface in the same manner as for a Vlan interface.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

bootstrapping infrastructure devices

### Describe the solution you would like

Copy the logic and the rendering used for vlan interfaces.

```yaml
    ip_helpers:
      10.10.96.151:
        source_interface: Loopback0
        vrf: MGMT

```
### Describe alternatives you have considered

apply the configuration via:
```yaml
ethernet_interface:
  eos_cli: |
    ip helper-address <HELPER_IP> vrf <VRF>
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
