### ISSUE TITLE
Feat(eos_cli_config_gen): BGP VPN-IPv4/v6

### ISSUE THREAD

**Issue by sengarth** [aristanetworks/ansible-avd#1845]
### Enhancement summary

Ability to render route-map and route import match failure for VPN-IPv4 and VPN-IPv6 SAFIs.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Currently, we're not able to specify route-maps when configuring VPN-IPv4/6 peerings:
```
   address-family vpn-ipv4
      neighbor MPLS-IBGP-PEERS route-map RM-IBGP-PEER-IN4 in
      neighbor MPLS-IBGP-PEERS route-map RM-IBGP-PEER-OUT4 out
      route import match-failure action discard
   address-family vpn-ipv6
      neighbor MPLS-IBGP-PEERS route-map RM-IBGP-PEER-IN6 in
      neighbor MPLS-IBGP-PEERS route-map RM-IBGP-PEER-OUT6 out
      neighbor 2001:cafe:192:168::4 route-map RM-NEIGHBOR-PEER-IN6 in
      neighbor 2001:cafe:192:168::4 route-map RM-NEIGHBOR-PEER-OUT6 out
      route import match-failure action discard
```

### Describe the solution you would like

Suggested data model:

```yaml
  address_family_vpn_ipv4:
    domain_identifier: 65000:0
    route:
      import_match_failure_action: discard
    peer_groups:
      MPLS-IBGP-PEERS:
        route_map_in: RM-IBGP-PEER-IN4
        route_map_out: RM-IBGP-PEER-OUT4

  address_family_vpn_ipv6:
    route:
      import_match_failure_action: discard
    peer_groups:
      MPLS-IBGP-PEERS:
        activate: true
        route_map_in: RM-IBGP-PEER-IN6
        route_map_out: RM-IBGP-PEER-OUT6
    neighbors:
      2001:cafe:192:168::4:
        route_map_in: RM-NEIGHBOR-PEER-IN6
        route_map_out: RM-NEIGHBOR-PEER-OUT6
```

Stays consistent with route-map config in other SAFI such as EVPN

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
