### ISSUE TITLE
Feat(eos_designs): Add support for multiple dhcp subnets for ztp

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#1859]
### Enhancement summary

Support the configuration of multiple dhcp subnets for ztp provisioning.

### Which component of AVD is impacted

eos_designs

### Use case example

Support topologies where all management interfaces cannot be physically connected to an out-of-band switch.

### Describe the solution you would like

Add a key similar to:

```
ztp_additional_subnets:
  - network: 10.0.0.0
    netmask: 255.255.255.0
    gateway: 10.0.0.1
    <any key from arista.cvp.dhcp_configuration>:
```

### Describe alternatives you have considered

None found.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
