### ISSUE TITLE
Add support for SBFD in traffic-engineering in config_gen

### ISSUE THREAD

**Issue by BouchardClaude** [aristanetworks/ansible-avd#1872]
### Enhancement summary

It would ease config generation if support for sbfd was added in router_traffic_engineering

Would it be possible de consider this addition?

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
router traffic-engineering
   segment-routing
      policy endpoint 1.1.1.1 color 1
         binding-sid 11111
         sbfd remote-discriminator 2222 interval 10 multiplier 2
         !

```

### Describe the solution you would like

Something similar to this:
```
router_traffic_engineering:
  router_id:
    ipv4: < IPv4_address >
    ipv6: < IPv6_address >
  segment_routing:
    colored_tunnel_rib: true
    policy_endpoints:
      - address: < IPv4_address | IPv6_address >
      - sbfd_remote-discriminator:
          - id: < integer >
            interval: < integer >
            multiplier : < integer >
```

### Describe alternatives you have considered

Using EOS_CLI is working but not clean as we need to add the sbfd to the policy itself from scratch :
```
eos_cli: |
  router traffic-engineering
     segment-routing 
      policy endpoint 1111 color 1111
        sbfd remote-discriminator 2222 interval 10 multiplier 2 
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
