### ISSUE TITLE
Support for underlay multicast in eos_designs

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#1873]
### Enhancement summary

Add knobs in eos_designs to easily enable multicast in the underlay.

### Which component of AVD is impacted

eos_designs

### Use case example

Enable multicast all underlay links.

### Describe the solution you would like

New keys to add to global fabric variables:

Enable multicast on all underlay p2p links, including mlag interface.
```yaml
underlay_multicast: < boolean >

# Setting to true would generate the following configuration
# p2p uplink interfaces
ethernet_interfaces:
  Ethernet49/1:
    pim:
      ipv4:
        sparse_mode: true
  Ethernet53/1:
    pim:
      ipv4:
        sparse_mode: true

# mlag l3 peer interface
vlan_interfaces:
  Vlan4093:
    pim:
      ipv4:
        sparse_mode: true
```

Other knobs discussed with @ClausHolbechArista 

```yaml
underlay_mulicast_mode: < ssm (default) | asm >
underlay_mulicast_rps:
  - < rp_hostname >
underlay_mulicast_anycast_rp: < msdp | pim >
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
