### ISSUE TITLE
EVPN overlay variables generated although EVPN_role is none

### ISSUE THREAD

**Issue by vyelpale** [aristanetworks/ansible-avd#1884]
### Issue Summary

tried creating l3 router node type and keys where the router will not be running EVPN. 

Defined the node type as :

```yaml
l3router:
    type: l3router
    connected_endpoints: true
    default_evpn_role: none
    mlag_support: true
    ip_addressing:
      mlag_ip_primary: 'templates/ip_addressing/mlag_ip_primary.j2'
      mlag_ip_secondary: 'templates/ip_addressing/mlag_ip_secondary.j2'
      mlag_l3_ip_primary: 'templates/ip_addressing/mlag_l3_ip_primary.j2'
      mlag_l3_ip_secondary: 'templates/ip_addressing/mlag_l3_ip_secondary.j2'    
    network_services: 
      l2: true
      l3: true
    underlay_router: true
    uplink_type: p2p  
```

So, the **evpn_role** is **None**.

End result which appeared wrong of the device type that is not running EVPN
 Name of the prefix list containing EVPN OVERLAY that could be deceiving to the user and does not seem like there is a way to override this name

```eos
ip prefix-list PL-LOOPBACKS-EVPN-OVERLAY
   seq 10 permit 2.2.2.0/24 eq 32
route-map RM-CONN-2-BGP permit 10
   match ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
```

Also noticed the below under debug vars for this node and appeared in accurate as EVPN role is none:

```yaml
        overlay_address_families:
        - evpn
        overlay_routing_protocol: ebgp
        overlay_routing_protocol_address_family: ipv4
```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
