### ISSUE TITLE
Add vlan state to eos_cli_config_gen

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#190]
**Issue Type**
- Template enhancement

**Is your feature request related to a problem? Please describe.**
Some device hardening guides recommend disable vlan 1 and using something else for native vlans.  In the current state of eos_cli_config_gen, the data model and template does not allow for the eos supported vlan state.

**Describe the solution you'd like**
Update the template for vlans would need to be updated as long as the following data model:
```
vlans:
  < vlan_id >:
    name: < vlan_name >
    state: < active | suspend >
    trunk_groups:
      - < trunk_group_name_1 >
      - < trunk_group_name_2 >
  < vlan_id >:
    name: < vlan_name >
```

**Describe alternatives you've considered**
Not introduce the feature and not have feature parity with EOS vlan functions.

**Additional context**
We could probably get further feature parity for VLANs, ie floodset (I do not see it documented as a feature in 4.24.1F release).
