### ISSUE TITLE
Feat(eos_designs): Fabric variable to enable EVPN multicast

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#1913]
### Enhancement summary

Make it easy to configure fabric to support EVPN Multicast.
Applies to L3LS EVPN Scenario.

### Which component of AVD is impacted

eos_designs

### Describe the solution you would like

Note: Both  `underlay_multicast` and new `evpn_multicast` must be enabled in for L3LS EVPN scenario, this may be different for MPLS for scenario.

**Existing Multicast knob:**

```yaml
# Enable Multicast in the underlay on all p2p uplink interfaces and mlag l3 peer interface.
# Specifically PIM Sparse-Mode will be configured on all routed underlay interfaces.
# No other configuration is added, so the underlay will only support Source-Specific Multicast (SSM)
# The configuration is intended to be used as multicast underlay for EVPN OISM overlay
underlay_multicast: <boolean | default -> false >
```

**New additional knob in fabric services:**

```yaml
# Enable Fabric to support EVPN Multicast
# Requires "underlay_multicast: true" and IGMP snooping enabled globally.
# For MLAG devices Route Distinguisher must be unique since this feature will create multi-vtep configuration.

evpn_multicast: <boolean | default -> false >
```

Pseudocode logic:

avd_facts
```
If node_type_keys.<node_type_key>.vtep_key is true and underlay_multicast is true
   check that igmp snooping is not disable globally  -> provide error
         set_fact -> switch.evpn_multicast: true
```

structured configuration templates

```
if switch.evpn_multicast is  true
```

Configure software-forwarding sfe:
```yaml
router_multicast:
  ipv4:
    routing: true
    software_forwarding: sfe
```

if switch.evpn_multicast is  true and mlag is true

Enable multi-vtep:
```yaml
vxlan_interface:
  Vxlan1:
    vxlan:
      source_interface: Loopback0
      mlag_source_interface: Loopback1
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
