### ISSUE TITLE
Feat(eos_cli_config_gen): Support for "logging event congestion_drops" under ethernet_interfaces and port_channel_interfaces

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#1929]
### Enhancement summary

Add support for configuring "logging event congestion_drops" under ethernet_interfaces and port_channel_interfaces or eos_cli_config_gen

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Regular DC

### Describe the solution you would like

We already have logging.event, so this is just a single new key.
```
ethernet_interfaces:
  <interface>:
    logging:
      event:
        congestions_drops: true
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
