### ISSUE TITLE
Add no-equals-default bgp command

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#195]
**Issue Type**
- Template enhancement

**Is your feature request related to a problem? Please describe.**
To keep clean configs with BGP neighbors, many people leverage the `service routing configuration bgp no-equals-default` command, so that when a `no neighbor < IP > shutdown` is applied to an EOS device, the config is removed as opposed to showing up as `no neighbor < IP > shutdown` in the actually config file.

**Describe the solution you'd like**
Introduce a new template, insert into the master template, and document data model.

**Describe alternatives you've considered**
Expanding to include other service commands in this template (there are a bunch of useful route-map set behavior commands that other people likely use), but they unfortunately would vary in position within the config.

**Additional context**
None

**Comment by ryanmerolle** [comment]
@carlbuchmann @titom73 we could consolidate all `service routing` commands into one template but they are not commands listed in EOS in the config file.  Thinking about this further, I say we expand /redo the service routing template and data model.  to something like:
```
service:
    configuration:
      access_list_symbols: < true | false >
      checkpoint_max_saved: < 0-100 >
      session:
        max_completed: < 0-20 >
        max_pending: < 1-20 >
      verification_qos: < true | false >
    interface:
      inactive_expose: < true | false >
      shutdown_expose: < true | false >
      unconnected_expose: < true | false >
    routing:
      protocols_model: < multi-agent | ribd >
      configuration: 
        bgp_no_equals_default: < true | false >
        route_map: 
          no_set_community_explicit_members: < true | false >
          set_operations: < merged | sequential >
    running-config:
      copy_use_config_session: < true | false >
      timestamp:  < true | false >
    sequence_numbers:  < true | false >
```

This issue would focus on the specific service I mentioned, but the data model and template would allow for further expansion for other service commands as in the above example.

**Comment by ryanmerolle** [comment]
Are such EOS feature parity requests that are auto-closed in the backlog to be reviewed later, or closed for good?

**Comment by carlbuchmann** [comment]
The data model for service routing should be as follows, as they are independent sections in the CLI output.

```yaml
service_routing_configuration_bgp:
  no_equals_default: < true | false >

service_routing_protocols_model: < multi-agent | ribd >

service_routing_configuration_route_map:
  set_operations: < merged | sequential >
  no_set_community: < explicit-members >
```
