### ISSUE TITLE
Feat(eos_cli_config_gen): Support for CVX server commands

### ISSUE THREAD

**Issue by sugetha24** [aristanetworks/ansible-avd#1962]
### Enhancement summary

Add support for MCS services under CVX 

```
cvx
   no shutdown
   !
   service mcs
      redis password 7 070E334ddD1D18
      no shutdown
```
 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Configure MCS services 

### Describe the solution you would like

Data Model:
```
cvx:
    shutdown: < true|false >
    services:
        mcs:
            redis:
                password: 070E334ddD1D18
                encryption: < true|false >
            shutdown: < true|false >
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
