### ISSUE TITLE
Feat(eos_cli_config_gen): Support for MCS client commands

### ISSUE THREAD

**Issue by sugetha24** [aristanetworks/ansible-avd#1963]
### Enhancement summary

Add support for MCS client on CVX
```
mcs client
   no shutdown
   !
   cvx secondary blue
      server host 172.24.86.56
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Configure MCS client on CVX

### Describe the solution you would like

Data Model:
```
mcs_client:
  shutdown: < true|false >
  cvx_secondary:
  - name: blue
    server_host:
       - < IPv4_address >
       - < IPv4_address >
```

Eg:
```
mcs_client:
  shutdown: true
  cvx_secondary:
  - name: blue
    server_host:
       - 172.24.86.56
```
       

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
