### ISSUE TITLE
Add logging format to eos_cli_config_gen 

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#197]
**Issue Type**
- Template enhancement

**Is your feature request related to a problem? Please describe.**
Logging format features are missing from the logging template and data model.

**Describe the solution you'd like**
Update to the following:
```
logging:
  console: < severity_level >
  monitor: < severity_level >
  buffered:
    size: < messages_nb (minimum of 10) >
    level: < severity_level >
  format:
    hostname: < fqdn | ipv4 >
    sequence_numbers: < true | false >
    timestamp: < high_resolution | traditional >
  trap: < severity_level >
  source_interface: < source_interface_name >
  vrfs:
    < vrf_name >:
      source_interface: < source_interface_name >
      hosts:
        - < syslog_server_1>
        - < syslog_server_2>
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
