### ISSUE TITLE
Add support to specify cipher-list in management_security model

### ISSUE THREAD

**Issue by UchihaItachiSama** [aristanetworks/ansible-avd#1973]
### Enhancement summary

Add support to specify the cipher-list in management_security data model in eos_cli_config_gen

```shell
management security
   ssl profile eAPI
      cipher-list ECDHE-RSA-AES256-GCM-SHA384
      certificate eAPI.crt key eAPI.key
```

https://avd.sh/en/stable/roles/eos_cli_config_gen/index.html#management-security

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

This is currently required when using python 3.10 for enabling strong ciphers on EOS side to avoid SSLV3_ALERT_HANDSHAKE_FAILURE error when connecting via eAPI.

### Describe the solution you would like

```yaml
management_security:
  entropy_source: < entropy_source >
  password:
    minimum_length: < 1-32 >
    encryption_key_common: < true | false >
    encryption_reversible: < aes-256-gcm >
  ssl_profiles:
    - name: <ssl_profile_1>
      tls_versions: < list of allowed tls versions as string >
      cipher-list: < valid-cipher-string >        <-------- New addition
      certificate:
        file: < certificate filename >
        key: < key filename >
    - name: <ssl_profile_2>
      tls_versions: < list of allowed tls versions as string >
```

### Describe alternatives you have considered

since there is no `eos_cli` available under `management_security` data model, I have to `eos_cli` to render full management security config under root level.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
