### ISSUE TITLE
Correct logging templates eos_cli_config_gen to match EOS output

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#198]
## Issue Type
- EOS Configuration error

## Summary

__Default VRF hosts:__
 - EOS generated config (4.22.x): `logging host 192.168.1.1`
 - eos_cli_config_gen  generated config: `logging vrf default host 192.168.1.1`

__Logging Buffered default level:__
 - EOS generated config (4.22.x): `logging buffered 64000`
 - eos_cli_config_gen  generated config: `logging buffered 64000 debugging`

__Logging Config order:__
 - EOS generated config (4.22.x): 
```shell
logging buffered 64000
logging console informational
logging host 192.168.1.1
logging source-interface Loopback0
```
 - eos_cli_config_gen  generated config: `logging buffered 64000 debugging`
```shell
logging console informational
logging buffered 64000 debugging
logging source-interface Loopback0
logging vrf default host 192.168.1.1
```

## Role or Module Name

eos_cli_config_gen 

## OS / Environment

__EOS Version__

4.22.6M

__Cloudvision version__

2020.1.1

__OS running Ansible__

2.9.11

## Steps to reproduce

```yaml
logging:
  console: informational
  #monitor: 
  buffered:
    size: 64000
    level: debugging #this is the default
  #trap: < severity_level >
  source_interface: Loopback0
  vrfs:
    default:
      #source_interface: should use logging source_interface
      hosts:
        - 192.168.1.1
```

### Expected results

```shell
logging buffered 64000
logging console informational
logging host 192.168.1.1
logging source-interface Loopback0
```

### Actual results

```shell
logging console informational
logging buffered 64000 debugging
logging source-interface Loopback0
logging vrf default host 192.168.1.1
```
