### ISSUE TITLE
Feat(eos_designs): Support for configurable trunk_group names

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#2003]
### Enhancement summary

`eos_designs` use hardcoded trunk groups `MLAG`, `MLAG_L3`.
When `enable_trunk_groups` is enabled there is also an `UPLINK` trunk group set on l2 switches.
This request is for a data model that will allow the trunk group names to be configurable.

### Which component of AVD is impacted

eos_designs

### Use case example

To match an existing deployment.

### Describe the solution you would like

Similar to `bgp_peer_groups` we use a fixed dict model.
```yaml
trunk_groups:
  mlag:
    name: < trunk_group_name | default -> "MLAG" >
  mlag_l3:
    name: < trunk_group_name | default -> "LEAF_PEER_L3" >
  uplink:
    name: < trunk_group_name | default -> "UPLINK" >
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
