### ISSUE TITLE
Feat(eos_cli_config_gen): Add 'shutdown' knob to MCS client commands 

### ISSUE THREAD

**Issue by sugetha24** [aristanetworks/ansible-avd#2008]
### Enhancement summary

Add `shutdown` knob to MCS Client commands

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
mcs client
   no shutdown
   !
   cvx secondary blue
      no shutdown
      server host 172.24.86.56
```

### Describe the solution you would like

Data Model:
```
mcs_client:
  shutdown: < true|false >
  cvx_secondary:
  - name: blue
    shutdown: < true | false >
    server_host:
       - < IPv4_address >
       - < IPv4_address >
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
