### ISSUE TITLE
Add snmp-server community to snmp-settings template in eos_cli_config_gen 

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#201]
**Issue Type**
- Template enhancement

**Is your feature request related to a problem? Please describe.**
The community option is missing from snmp-settings

**Describe the solution you'd like**
Update to the following:
```
snmp_server:
  contact: < contact_name >
  location: < location >
  local_interfaces:
    - name: < interface_name_1 >
      vrf: < vrf_name >
    - name: < interface_name_2 >
  views:
    - name: < view_name >
      MIB_family_name: < MIB_family_name >
      included: < true | false >
    - name: < view_name >
      MIB_family_name: < MIB_family_name >
      included: < true | false >
  communities:
    - < community_name_1 >:
       access: < ro | rw >
       access_list:
          type: < ipv4 | ipv6 >
          name: 
       view: <view_name >
     - < community_name_2 >:
       access: < ro | rw >
       access_list:
          type: < ipv4 | ipv6 >
          name: 
       view: <view_name >
  groups:
    - name: < group_name >
      version: < v1 | v2c | v3 >
      authentication: < auth | noauth | priv >
      read: < read_view >
      write: < write_view >
      notify: < notify_view >
    - name: < group_name >
      version: < v1 | v2c | v3 >
      authentication: < auth | noauth | priv >
      read: < read_view >
  users:
    - name: < username >
      group: < group_name >
      version: < v1 | v2c | v3 >
      auth: < hash_algorithm >
      auth_passphrase: < encrypted_auth_passphrase >
      priv: < encryption_algorithm >
      priv_passphrase: < encrypted_priv_passphrase >
    - name: < username >
      group: < group_name >
      version: < v1 | v2c | v3 >
  hosts:
    - host: < host IP address or name >
      vrf: < vrf_name >
      users:
        - username: < username >
          authentication_level: < auth | noauth | priv >
          version: < 1 | 2c | 3 >
    - host: < host IP address or name >
      vrf: < vrf_name >
      users:
        - username: < username >
          authentication_level: < auth | noauth | priv >
          version: < 1 | 2c | 3 >
  traps:
    enable: < true | false >
  vrfs:
    - name: < vrf_name >
      enable: < true | false >
    - name: < vrf_name >
      enable: < true | false >
```

**Describe alternatives you've considered**
N/A

**Additional context**
Open to adjusting the model as this data model is already quite long / complex compared to others.
