### ISSUE TITLE
Feat(eos_cli_config_gen): Correct community-list model & template  

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#203]
## Issue Type
- EOS Configuration error

## Summary

1. The current model only allows for 1 action.  EOS allows for several actions to be associated to one community-list.  If you try to workaround this and set multiple community-lists with the same name/key, 1 for each action, Ansible/Jinja will see this a duplicate keys.
2. The current model only allows for an action, for which you can set a string to include whether the community-list is either expanded/regexp or standard(default).  But it is not truly modeling the community-list function of EOS and will cause confusion for users.

## Role or Module Name

eos_cli_config_gen 

## OS / Environment

__EOS Version__

4.22.6M

__Cloudvision version__

2020.1.1

__OS running Ansible__

2.9.11

## Steps to reproduce

```yaml
community_lists:
  test:
    action: "permit 100:100" # assumes standard community-list entry
  test:
    action: "regexp deny 999:999"
  test2:
    action: "deny 999:999 100:100"
```

### Expected results

```shell
# OR match that accepts where either community is tagged on a route
ip community-list test permit 100:100
ip community-list test regexp deny 999:999
# AND match that denies where the two communities are tagged on a route
ip community-list test2 deny 999:999 100:100 
```

### Actual results
Duplicate key error in Ansible & only last key in the dictionary leveraged for `community-list test`
```shell
ip community-list test regexp deny 999:999
ip community-list test2 deny 999:999 100:100 
```

### Additional context
I think regexp is the syntax going forward instead of expanded.

**Comment by ryanmerolle** [comment]
Did this feature just fall off?

I am happy to take this on if needed.

**Comment by carlbuchmann** [comment]
@ryanmerolle we had closed the PR related to this issue it was stale and outdated due to various changes. Let's discuss the suggested data model changes before you start working on a new PR!

**Comment by ryanmerolle** [comment]
I'm happy to take this on.

Keeping close to the current model, would could suggest:

```
community_lists:
  test:
    actions: 
      - "permit 100:100" # assumes standard community-list entry
      - "regexp deny 999:999"
      - "deny 999:999 100:100"
```

Thoughts?

**Comment by ClausHolbechArista** [comment]
EDIT: EOS treads this as one community-list, so we should collapse these models.

EOS cli would not work with this.
```eos
lp032#show ip community-list
ip community-list regexp test permit 123
ip community-list test permit 0:123
```
Note that the name goes _after_ regexp.
~~As I understand it, these are two different community list constructs.~~

In AVD we have covered the variants of extended community lists like this:
```yaml
ip_extcommunity_lists:
  < community_list_name_1 >:
    - type: < permit | deny >
      extcommunities: "< communities as string >"

ip_extcommunity_lists_regexp:
  < community_list_name >:
    - type: < permit | deny >
      regexp: "< string >"
```
EDIT: New collapsed model - maybe we should do the same for extcommunities.
```yaml
ip_community_lists:
  < community_list_name_1 >:
    - action: < permit | deny >
      type: < community | regexp | default -> community >
      match: "< communities as string or regexp >"
```
@ryanmerolle @carlbuchmann @alexander-arista

We should get this in `3.0.0rc2`, which is soon. I have cycles to implement if we all agree.
I will also add upgrade functionality to assist the users in migration to the new data model.

**Comment by ryanmerolle** [comment]
Let me know how you want to tackle this.

**Comment by ClausHolbechArista** [comment]
Until the next major version we cannot do much, since it would break deployments. If you have a specific use case we need to sort out sooner, please share the details here or unicast to holbech@arista.com.

Thanks

**Comment by ankudinov** [comment]
The new and old data model should not conflict, as `community_lists` key will be replaced with `ip_community_lists`.
I'd propose following data model:

```yaml
ip_community_lists:
  - name: "<ip community list name as string>"  # mandatory
    action: "< permit | deny >"  # required
    # possible community strings are (case insensitive):
    # - GSHUT
    # - internet
    # - local-as
    # - no-advertise
    # - no-export
    # - <1-4294967040>
    # - aa:nn
    community_list: [ "< a_community as string >", "< a_community as string >", ... ]  # optional, if defined - standard community list will be configured
    regexp: "< regular expression >"  # if defined, regex community list will be configured
```

That's similar to the data model we have implemented for ip access lists recently. The implementation will be very similar.
I've removed `type` from the data model as well. IMO, it's confusing as it's actually standard vs. extended. But extended may not be meaningful enough for the operator. We can simply define the type based on community_list vs regexp present.

show cli commands output:
```text
[no|default] ip community-list NAME ACTION { ( AANN_FORMAT | COMMUNITY_ENUM | COMMUNITY_U32 ) }
[no|default] ip community-list expanded NAME ACTION REGEX
[no|default] ip community-list regexp NAME ACTION REGEX
[no|default] ip community-list standard NAME ACTION { ( AANN_FORMAT | COMMUNITY_ENUM | COMMUNITY_U32 ) }
```

We could implement same logic for `extcommunity-list` and `large-community-list` inside this PR. But there are 2 caveats:
- is it acceptable from the PR review size perspective?
- `ip_extcommunity_lists` is unfortunately in use. We have to find another name for the key.

@ClausHolbechArista @ryanmerolle Let me know you feedback before I'll implement it.
