### ISSUE TITLE
Incorrect ip-routing template conditional in eos_cli_config_gen

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#204]
## Issue Type
- EOS Configuration error
- Bug Report

## Summary

ip-routing template adds a dependency for `ip routing: true` in order to set other vrf ip routing attributes.  I tested and saw that even if a device has `no ip routing` (ie for the default vrf), you can still set other vrf routing.

I propose the template should be fixed to 

1. Add no to the begining of the command `ip routing` for the default vrf if `ip routing: false` to follow the syntax in EOS
2. Remove the VRF conditional for ip routing from the base ip routing conditional so that the default vrf being enabled for ip routing has nothing to do with any vrf's ip routing.

## Role or Module Name

eos_cli_config_gen 

## OS / Environment

__EOS Version__

4.22.6M

__Cloudvision version__

2020.1.1

__OS running Ansible__

2.9.11

## Steps to reproduce

```yaml
ip_routing: false
vrfs:
  MGMT:
    description: OOB MGMT
    ip_routing: false
  overlay:
    description: Overlay VRF
    ip_routing: true
```

### Expected results

```shell
no ip routing
no ip routing vrf MGMT
ip routing vrf overlay
```

### Actual results

```shell
no ip routing
```

### Additional context
I think it would be rare that this edge case be hit, but I forgot to set ip_routing var, and I uncovered this dependency.
