### ISSUE TITLE
Devices op states validation

### ISSUE THREAD

**Issue by ksator** [aristanetworks/ansible-avd#206]
Adding a new role to validate devices op states. 
- Consumes as input some of the data described in yaml files by the role [eos_cli_config_gen](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen) (this is the desired state)  
- Collects some show commands (json format) on the devices (actual state) 
- Compares the desired state and the actual state 

Exemple: if a device X is supposed to be configured with BGP neighbor a.b.c.d according to the role [eos_cli_config_gen](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen), then this new role will connect on the device X and check if the BGP session with neighbor a.b.c.d is Established.  

- [x] Display devices model and EOS release
- [x] validate environment (fan status) 
- [x] validate environment (power supplies status) 
- [x] validate environment (temperature) 
- [x] validate transceivers manufacturer
- [x] validate last reload cause
- [x] validate NTP status
- [x] validate interfaces admin status
- [x] validate interfaces op status
- [x] validate LLDP topology 
- [x] validate MLAG status
- [x] validate IP reachability (on directly connected interfaces)
- [x] validate ArBGP is configured and operating
- [x] validate BGP sessions state

This role will require an access to the configured devices.

**Comment by ksator** [comment]
This could looks like this (successfully tested):   

playbooks/pb_validate_yml 
```
---
- name: validate states on EOS devices
  hosts: DC1
  connection: httpapi
  gather_facts: false
  tags: 
    - audit

  roles: 
    - validate_eos_state
```

roles/validate_eos_state/tasks/main.yml  
```
---
    - name: run show version on EOS devices
      eos_command:
        commands: "show version | json"
      register: eos_version

    - name: Print some details regarding EOS devices
      debug:
        msg: "The device {{ inventory_hostname }} is a {{eos_version.stdout_lines.0.modelName}} model running EOS version {{eos_version.stdout_lines.0.version}}"

    - name: collect power supplies status
      eos_command:
        commands: "show system environment power | json"
      register: power
      tags: hardware

    - name: validate power supplies status 
      assert:
        that:
          - item.value.state == 'ok'
        quiet: true
      loop: "{{ power.stdout_lines.0.powerSupplies|dict2items }}"    
      ignore_errors: "{{ validation.mode.loose }}"
      tags: hardware

    - name: collect fan status
      eos_command:
        commands: "show system environment cooling | json"
      register: fan
      tags: hardware

    - name: validate fan status (power supplies)
      assert:
        that:
          - item.status == 'ok'
        quiet: true
      loop: "{{ fan.stdout_lines.0.powerSupplySlots }}"    
      ignore_errors: "{{ validation.mode.loose }}"
      tags: hardware

    - name: validate fan status (fan tray) 
      assert:
        that:
          - item.status == 'ok'
        quiet: true
      loop: "{{ fan.stdout_lines.0.fanTraySlots }}"    
      ignore_errors: "{{ validation.mode.loose }}"
      tags: hardware

    - name: validate temperature 
      eos_command:
        commands: "show system environment temperature | json"
        wait_for: result[0].systemStatus eq 'temperatureOk'
      ignore_errors: "{{ validation.mode.loose }}"
      tags: hardware

    - name: collect transceivers inventory
      eos_command:
        commands: "show inventory | json"
      register: inventory
      tags: hardware

    - name: validate transceivers manufacturers
      assert:
        that:
          - "item.value.mfgName in ['Not Present', 'Arastra, Inc', 'Arista Networks']"
        quiet: true
      loop: "{{ inventory.stdout_lines.0.xcvrSlots|dict2items }}"    
      ignore_errors: "{{ validation.mode.loose }}"
      tags: hardware

    - name: validate reload cause
      eos_command:
        commands: "show reload cause | json"
        wait_for: result[0].resetCauses[0].description eq 'The system rebooted due to a Power Loss'
        retries: 2
        interval: 2
      ignore_errors: "{{ validation.mode.loose }}"

    - name: include device intended structure configuration variables
      include_vars: '{{inventory_dir}}/intended/structured_configs//{{ inventory_hostname }}.yml'
      delegate_to: localhost

    - name: validate NTP status
      eos_command:
        commands: "show ntp status"
        waitfor: 
          - "result[0] contains 'synchronised to NTP server'"
        retries: 2
        interval: 2
      when: (ntp_server.nodes is defined) and (ansible_version['major'] == 2 and ansible_version['minor']|int >= 9)
      ignore_errors: "{{ validation.mode.loose }}"

    - name: validate interfaces admin state 
      eos_command:
        commands: "show interfaces {{item.key}} description | json"
        waitfor:
          - result[0].interfaceDescriptions.{{item.key}}.interfaceStatus eq 'up'
        retries: 2
        interval: 2
      loop: "{{ethernet_interfaces|dict2items}}"
      when: (ethernet_interfaces is defined) and ((ansible_version['major'] == 2 and ansible_version['minor']|int >= 9))
      ignore_errors: "{{ validation.mode.loose }}"

    - name: validate interfaces operational state 
      eos_command:
        commands: "show interfaces {{item.key}} description | json"
        waitfor:
          - result[0].interfaceDescriptions.{{item.key}}.lineProtocolStatus eq 'up'
        retries: 2
        interval: 2
      loop: "{{ethernet_interfaces|dict2items}}"
      when: (ethernet_interfaces is defined) and ((ansible_version['major'] == 2 and ansible_version['minor']|int >= 9))
      ignore_errors: "{{ validation.mode.loose }}"

    - name: validate LLDP topology
      eos_command:
        commands: "show lldp neighbors {{item.key}} | json"
        waitfor:
          - "result[0].lldpNeighbors[0].neighborDevice eq {{item.value.peer}}"
          - "result[0].lldpNeighbors[0].neighborPort eq {{item.value.peer_interface}}"
        retries: 2
        interval: 2
      loop: "{{ethernet_interfaces|dict2items}}"
      when: (ethernet_interfaces is defined) and (item.value.peer is defined) and (item.value.peer_interface is defined) and ((ansible_version['major'] == 2 and ansible_version['minor']|int >= 9))
      ignore_errors: "{{ validation.mode.loose }}"

    - name: validate MLAG status 
      eos_command:
        commands: "show mlag detail | json"
        waitfor:  
          - "result[0].state eq 'active'"
          - "result[0].negStatus eq 'connected'"
        retries: 2
        interval: 2
      ignore_errors: "{{ validation.mode.loose }}"
      when: (mlag_configuration is defined)

    - name: validate IP reachability (directly connected)
      eos_command:
        commands: "ping {{ hostvars[item.value.peer]['ethernet_interfaces'][item.value.peer_interface]['ip_address'] | ipaddr('address')}} source {{ item.value.ip_address  | ipaddr('address')}} repeat 1"
        waitfor: result[0] contains '1 received' 
        retries: 2
        interval: 2
      loop: "{{ethernet_interfaces|dict2items}}"
      ignore_errors: "{{ validation.mode.loose }}"
      when: (ethernet_interfaces is defined) and (item.value.type == 'routed')

    - name: validate ArBGP is configured and operating
      eos_command:
        commands: "show ip route summary"
        waitfor: 
          - "result[0] contains 'Operating routing protocol model: multi-agent'" 
          - "result[0] contains 'Configured routing protocol model: multi-agent'"
        retries: 2
        interval: 2
      when: (ansible_version['major'] == 2 and ansible_version['minor']|int >= 9)
      ignore_errors: "{{ validation.mode.loose }}"

    - name: validate BGP sessions state
      eos_command:
        commands: "show ip bgp neighbors {{item.key}} | json"
        waitfor:
          - "result[0].vrfs.default.peerList[0].state eq 'Established'"
        retries: 2
        interval: 2
      loop: "{{router_bgp.neighbors|dict2items}}"
      when: (router_bgp.neighbors is defined) and (item.key is defined) and (item.value |length > 0) and ((ansible_version['major'] == 2 and ansible_version['minor']|int >= 9))
      ignore_errors: "{{ validation.mode.loose }}"
```
inventory/group_vars/DC1.yml

```
ansible_user: 'arista'
ansible_password: 'arista'
ansible_network_os: eos
ansible_become: yes
ansible_become_method: enable

validation: 
  mode: 
    loose: true
```
inventory/intended/structured_configs/switch2.yml 
```
router_bgp:
  neighbors:
    10.10.10.0:
      remote_as: 65001
    10.10.10.5:
      remote_as: 65002
  
ethernet_interfaces:
  Ethernet5:
    peer: switch1
    peer_interface: Ethernet5
    ip_address: 10.10.10.1/31
    type: routed
  Ethernet41:
    peer: switch3
    peer_interface: Ethernet41
    ip_address:  10.10.10.4/31
    type: routed
 
mlag_configuration:
  domain_id: MLAG12
  local_interface: Vlan4094
  peer_address: 172.16.12.2
  peer_link: Port-Channel10
  reload_delay_mlag: 300
  reload_delay_non_mlag: 330

ntp_server:
  local_interface:
    vrf: MGMT
    interface: Management1
  nodes:
    - 0.fr.pool.ntp.org
    - 1.fr.pool.ntp.org
```
