### ISSUE TITLE
Support for dynamic inventories

### ISSUE THREAD

**Issue by msnatepg** [aristanetworks/ansible-avd#2063]
### Enhancement summary

Ansible-cvp should support dynamic inventories

### Which component of AVD is impacted

other

### Use case example

We're using ansible-avd and ansible-cvp in conjunction with our Netbox installation.
The inventory and most of the group_vars are loaded dynamically from there.
While this works perfectly fine for [eos_designs](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/roles/eos_designs) and [eos_cli_config_gen](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen) it does not work for [eos_config_deploy_cvp](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/roles/eos_config_deploy_cvp).
Error message is "Node 'DE_FRA1' is not in the tree."
First investigations revealed that this must be due to the implementation of [inventory_to_container.py](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py) which simply parses the inventory file, in which in our case is only the configuration for the dynamic inventory.

### Describe the solution you'd like

Modify [inventory_to_container.py](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py) so that dynamic inventorys are supported.

### Describe alternatives you've considered

Quick fix for now is to generate a static inventory in a CI stage before the deployment based upon the dynamic inventory.

### Additional context

Currently running ansible-avd 3.7.0 and ansible-cvp 3.4.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by msnatepg** [comment]
While reading the submitted issue I realized that this would fit better in the ansible-avd project.
If you agree feel free to move or clone.

**Comment by carlbuchmann** [comment]
@msnatepg - thank you for submitting this issue. Yes, we will work on refactoring this component of eos_config_deploy_cvp to support dynamic inventories. Once we have the PR ready, could you help test with your scenario?

**Comment by msnatepg** [comment]
@carlbuchmann Sure. I would love to replace my workaround with your PR, just let me know.

**Comment by ClausHolbechArista** [comment]
@msnatepg I have finally gotten around to enhancing the module/role, so we can read from dynamic inventories. I would appreciate if you could test #2395 in your environment.
Thanks

**Comment by msnatepg** [comment]
Hey there,

today I found the time to play with your code.
First of all, thanks for your efforts.

While executing _arista.avd.eos_config_deploy_cvp : Load CVP device information for cv_server_, ansible gives me the following error:
```
    Syntax Error while loading YAML.
      While constructing a mapping from /home/msn/avd-project/inventory/intended/structured_configs/cvp/cv_server.yml, line 3, column 5, found a duplicate dict key (parentContainerName). Using last defined value only.
```

When having a look at the structured config of the cvp, especially cv_server.yaml, I think the cause is obvious:

```
---
CVP_DEVICES:
  - fqdn: DE-FRA1-LEAF1
    parentContainerName: DE_FRA1
    parentContainerName: DE_FRA1_Leaf_Switch
    configlets:
      - DE_FRA1_AVD_DE-FRA1-LEAF1
  - fqdn: DE-FRA1-LEAF2
    parentContainerName: DE_FRA1
    parentContainerName: DE_FRA1_Leaf_Switch
    configlets:
      - DE_FRA1_AVD_DE-FRA1-LEAF2
  - fqdn: DE-FRA1-LEAF3
    parentContainerName: DE_FRA1
    parentContainerName: DE_FRA1_Leaf_Switch
    configlets:
      - DE_FRA1_AVD_DE-FRA1-LEAF3
  - fqdn: DE-FRA1-LEAF4
    parentContainerName: DE_FRA1
    parentContainerName: DE_FRA1_Leaf_Switch
    configlets:
      - DE_FRA1_AVD_DE-FRA1-LEAF4
  - fqdn: DE-FRA1-SPINE1
    parentContainerName: DE_FRA1
    parentContainerName: DE_FRA1_Spine_Switch
    configlets:
      - DE_FRA1_AVD_DE-FRA1-SPINE1
  - fqdn: DE-FRA1-SPINE2
    parentContainerName: DE_FRA1
    parentContainerName: DE_FRA1_Spine_Switch
    configlets:
      - DE_FRA1_AVD_DE-FRA1-SPINE2
CVP_CONTAINERS:
  DE_FRA1:
    parentContainerName: Tenant
  DE_FRA1_Leaf_Switch:
    parentContainerName: DE_FRA1
  DE_FRA1_Spine_Switch:
    parentContainerName: DE_FRA1

```

As our devices are structured into multiple layers in the inventory, the code that generates cv_server.yaml writes parentContainerName multiple times. I think it should do that only for the most specific container in which the device is a member.
