### ISSUE TITLE
eos_designs support for single mlag trunk group

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#2064]
### Enhancement summary

Provide knob to configure single mlag trunk group.

### Which component of AVD is impacted

eos_designs

### Use case example

Generate configuration in a single trunk group for both vlans:

```
vlan4093
   trunk group MLAG
vlan 4094
   trunk group MLAG
```

### Describe the solution you would like

Create knob in fabric topology to influence mlag trunk group: `single_mlag_trunk_group`.

Make this default `true` in AVD 4.0.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
This can be done by configuring
```yaml
# Using the same custom name on mlag & mlag_l3
trunk_groups:
  mlag:
    name: "MLAG"
  mlag_l3:
    name: "MLAG"
```
