### ISSUE TITLE
Allow channel id to be specified for port channels to endpoints

### ISSUE THREAD

**Issue by chetryan** [aristanetworks/ansible-avd#2069]
### Enhancement summary

The current behaviour for Port Channel for Endpoints is that the number of the first interface is used to generate the 
channel id.
This proposal is to support an optional `channel_id` where the specific id can be supplied by the user, similar to how it can be specified for the mlag port channel with `mlag_port_channel_id`.

### Which component of AVD is impacted

eos_designs

### Use case example

In the below example, we need the port channel to have an id of 211 instead of 11  which is the default that AVD would generate 

```yaml
servers:
  Server1:
    rack: Rack1
    adapters:
      - endpoint_ports: [E0, E1]
        switch_ports: [Ethernet1/1, Ethernet1/1]
        switches: [SW-1, SW-2]
        profile: PROFILE_1
        port_channel:
          channel_id: 211
          description: myportchannel
          mode: active
```

The structured_configuration that is generated by eos_designs should have: 

```yml
interface Port-Channel211
   description Server1_myportchannel
   no shutdown
   switchport
   switchport trunk allowed vlan 210,220
   switchport trunk native vlan 220
   switchport mode trunk
   mlag 211
   spanning-tree portfast
!
```

### Describe the solution you would like

Ideally the builtin templates of AVD would support this optional value.

### Describe alternatives you have considered

At the moment we are achieving this using custom jinja templates to override the default AVD eos_designs templates for port-channel configuration. However, with updates to AVD, these templates would not include any other improvements made to the built-in templates. 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
