### ISSUE TITLE
Do not output empty variables for vlan_interfaces and port_channel_interfaces 

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#213]
## Issue Type

- Bug Report

## Summary

When we generate structured_config (YAML) for a device with no SVI like l2leaf not running in MLAG, the output contains an empty variable which has no type and leads to some issues when read by ansible:

```yaml
### Management Interfaces ###
management_interfaces:
  Management1:
    description: oob_management
    vrf: MGMT
    ip_address: 10.73.1.17/16
    gateway: 10.73.0.1

### VLAN Interfaces ###
vlan_interfaces:

### TCAM Profiles ###
tcam_profile:

```

## Role or Module Name

__arista.avd.eos_l3ls_evpn__

## Steps to reproduce

Any config where device is `type:l2leaf` and not configured in mlag

### Expected results

```yaml
```yaml
### Management Interfaces ###
management_interfaces:
  Management1:
    description: oob_management
    vrf: MGMT
    ip_address: 10.73.1.17/16
    gateway: 10.73.0.1

### TCAM Profiles ###
tcam_profile:
```
