### ISSUE TITLE
Add support for T2 devices (7050X2)

### ISSUE THREAD

**Issue by xaviramon** [aristanetworks/ansible-avd#2216]
### Enhancement summary

Add support for Trident 2 devices.
Today, no support in AVD is present. These devices are very similar to T3, with the difference that "trident_forwarding_table_partition flexible" command is not supported.
Devices are still in support, and to keep a difference with T3, we agreed to add a new platform.

### Which component of AVD is impacted

eos_designs

### Use case example

Allow 7050X2 as new platform:
```
l3leaf:
  defaults:
    platform: 7050X2
```

### Describe the solution you would like

Add a new platform under default_platform_settings:
```
default_platform_settings:
  - platforms: ['7050X2']
    reload_delay:
      mlag: 300
      non_mlag: 330
    feature_support:
      queue_monitor_length_notify: false
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
