### ISSUE TITLE
Feat(eos_cli_config_gen): support for tunnel interfaces

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#2232]
### Enhancement summary

Model tunnel interface configuration in eos_cli_config_gen

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Configuring GRE tunnels

### Describe the solution you would like

cf the currently used `custom_template` - it may be incomplete as it is only tailored to the current usage on my project

### Describe alternatives you have considered

using this custom_template for now:

```
{% if tunnel_interfaces is arista.avd.defined %}
{%     for tunnel_interface in tunnel_interfaces %}
interface {{ tunnel_interface.name }}
  description {{ tunnel_interface.description }}
  mtu {{ tunnel_interface.mtu }}
  ip address {{ tunnel_interface.ip_address }}
{%         if tunnel_interface.tcp_mss is arista.avd.defined %}
  tcp mss ceiling ipv4 {{ tunnel_interface.tcp_mss }} egress
{%         endif %}
  ip access-group {{ tunnel_interface.access_group.in }} in
  tunnel source interface {{ tunnel_interface.source_interface }}
  tunnel destination {{ tunnel_interface.destination }}
  tunnel path-mtu-discovery
{%     endfor %}
{% endif %}
```

with these variables

```
tunnel_interfaces:
  - name: Tunnel10
    description: example description
    mtu: 1476
    tcp_mss: 1300
    ip_address: 1.1.1.1/31
    access_group:
      in: example-acl
    source_interface: Ethernet42
    destination: 2.2.2.2
```

(egress in mss could be made an option)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
