### ISSUE TITLE
Feat(eos_designs): support multiple descriptions in network_services l3_interface rather than a unique one

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#2236]
### Enhancement summary

As of today it is possible to declare multiple l3_interfaces in a list on multiple devices but the description is the same across devices:

https://avd.sh/en/stable/roles/eos_designs/doc/network-services.html#tenant-network-service-definitions

```
        # List of L3 interfaces | Optional.
        # This will create IP routed interface inside VRF. Length of interfaces, nodes and ip_addresses must match.
        l3_interfaces:
          - interfaces: [ <interface_name1>, <interface_name2>, <interface_name3> ]
            ip_addresses: [ <IPv4_address/Mask>, <IPv4_address/Mask>, <IPv4_address/Mask> ]
            nodes: [ < node_1 >, < node_2 >, < node_1 > ]
            description: < description >
```

 

### Which component of AVD is impacted

eos_designs

### Use case example

To be able to make the description node specific (e.g. to follow some standard description text for each interface being `<REMOTE_DEVICE>_<REMOTE_INTERFACE>` like we have for connected_endpoints).

### Describe the solution you would like

```
        # List of L3 interfaces | Optional.
        # This will create IP routed interface inside VRF. Length of interfaces, nodes, ip_addresses and descriptions (if used) must match.
        l3_interfaces:
          - interfaces: [ <interface_name1>, <interface_name2>, <interface_name3> ]
            ip_addresses: [ <IPv4_address/Mask>, <IPv4_address/Mask>, <IPv4_address/Mask> ]
            nodes: [ < node_1 >, < node_2 >, < node_1 > ]
            # Backward compatibility
            description: < description >
            descriptions: [<description1>, <description2>, <description3>]
```

### Describe alternatives you have considered

Both the following solutions would work but would imply having a much bigger configuration file which goes against the list.
* having one entry per interface
* using custom_structured_configuration with one entry per interface

### Additional context

The idea is to piggyback on #2175 to implement this.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
