### ISSUE TITLE
Add bfd to router pim sparse mode datamodel

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#2255]
### Enhancement summary

Support the bfd key for the `router_pim_sparse_mode` datamodel

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Need to activate bfd under router pi sparse mode in VRF:

```
router pim sparse-mode
  vrf VRF
    ipv4
      bfd
      rp-address <address>
```

Currently bfd is not supported
    

### Describe the solution you would like

See proposed datamodel with the bfd modification:

```yaml
router_pim_sparse_mode:
  ipv4:
    ssm_range: < range >
    bfd: < true | false  | default -> false >
    rp_addresses:
      < rp_address_1 >:
        groups:
          < group_prefix_1/mask >:
          < group_prefix_2/mask >:
      < rp_address_2 >:
    anycast_rps:
      < anycast_rp_address_1 >:
        other_anycast_rp_addresses:
          < ip_address_other_anycast_rp_1 >:
            register_count: < register_count_nb >
  vrfs:
    - name: < vrf_name >
      ipv4:
        bfd: < true | false  | default -> false >
        rp_addresses:
          - address: < rp_address_1 >
            groups:
              - < group_prefix_1/mask >
              - < group_prefix_2/mask >
```

### Describe alternatives you have considered

custom template

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
