### ISSUE TITLE
`eos_validate_state` does not handle missing loopbacks & vxlan

### ISSUE THREAD

**Issue by chetryan** [aristanetworks/ansible-avd#2259]
### Issue Summary

When running `eos_validate_state`  `interfaces_state` tests on devices that do not have the expected Vxlan1 or Loopback interfaces, the markdown message is not clear and implies something wrong with the tests. 

I believe this happens because the tests assume that the interfaces exist, and we are only checking that status. Example : 

```yaml
assert:
    that:
      - interfaces_state.stdout[0].interfaceDescriptions.Vxlan1.interfaceStatus == 'up'
      - interfaces_state.stdout[0].interfaceDescriptions.Vxlan1.lineProtocolStatus == 'up'
    fail_msg: "Interface status: {{ interfaces_state.stdout[0].interfaceDescriptions.Vxlan1.interfaceStatus | replace('\"','') }} -
      line protocol status: {{ interfaces_state.stdout[0].interfaceDescriptions.Vxlan1.lineProtocolStatus | replace('\"','') }}"
```

In the above example, if the devices does not have a Vxlan1 defined, we get the following msg in the markdown : 

---

| Test ID | Node | Test Category | Test Description | Test | Test Result | Failure Reason |
| ------- | ---- | ------------- | ---------------- | ---- | ----------- | -------------- |
| 37 | Device_name_here | Interface State | Vxlan Interface Status & Line Protocol == "up" | Vxlan1 | :x: | The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'Vxlan1'
The error appears to be in '/projects/.collections/ansible_collections/arista/avd/roles/eos_validate_state/tasks/interface_state.yml': line 82, column 3, but may be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:

- name: Validate Vxlan interfaces state ^ here  |

---

Impact: 

- for an unfamiliar user, this would seems like a bug in the ansible role rather than a missing Vxlan interface on the device
- It breaks the structure of the generated markdown file, making it harder to read, especially for large fabrics.

### Which component(s) of AVD impacted

eos_validate_state

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
- Generate the structured configuration for a fabric that uses Vxlans and/or loopbacks on any device
- Run the eos_validate_state before pushing the configuration on all devices.
```

### Relevant log output

```shell
2022-11-04 09:19:07,413 p=1081 u=avd n=ansible | fatal: [device_name]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'Vxlan1'\n\nThe error appears to be in '/projects/.collections/ansible_collections/arista/avd/roles/eos_validate_state/tasks/interface_state.yml': line 82, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Validate Vxlan interfaces state\n  ^ here\n"}
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
