### ISSUE TITLE
Documentation wrong for `hardware_counters`

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#2264]
### Issue Summary

The actual template logic does not match the documentation. The template looks for a `name` and `direction` keys in 2 different ways inside the list of hardware counter features: https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/hardware-counters.j2

```jinja
{# eos - Hardware counters #}
{% if hardware_counters.features is arista.avd.defined %}
!
{%     for feature in hardware_counters.features %}
{%         if 'name' in feature %}
hardware counter feature {{ feature.name }} {{ feature.direction }}
{%         else %}
{%             for feat in feature %}
hardware counter feature {{ feat.name }} {{ feat.direction }}
{%             endfor %}
{%         endif %}
{%     endfor %}
{% endif %}
```

The documentation only mentions:

```yaml
hardware_counters:
  features:
    - <feature_1>: < direction | in | out >
    - <feature_1>: < direction | in | out >
```

Should be:

```yaml
hardware_counters:
  features:
    - name: <feature_1>
      dirention: < direction | in | out >
    - name: <feature_2> 
      direction: < direction | in | out >
```

I don't really get the content of the "else" statement, looks like it goes to a feature key as if it is a dictionary and inside the dictionary stills looks for name and direction keys??

```yaml
hardware_counters:
  features:
     <feature_1>
        name:  <feature_1_name>
        direction: < direction | in | out >
```

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Basic run of `eos_cli_config_gen` with the `hardware_counters` datamodel
```

### Relevant log output

```shell
N/A
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
The documentation is not wrong, as it describes the AVD 3.x data model. We are preparing a lot of data model changes for AVD 4.x, and as part of that effort, we have converted all the templates to use the new data models (list of dicts), and then run automatic type conversion based on our schemas, before rendering the templates.

Are you seeing issues using the documented data model?

**Comment by gusmb** [comment]
I used this format directly:

```yaml
hardware_counters:
  features:
    - name: <feature_1>
      direction: < direction | in | out >
    - name: <feature_2> 
      direction: < direction | in | out >
```

I got confused since it worked this way and looking at the template I see that it always tries to access the name and direction keys, and the current documentation doesn't mention anything about name and direction, bit rather suggests this format without name and direction keys:

Example:

```yaml
features:
  - "multicast ipv4": {}
```

I haven't tested like this but I thought the other format would need to be documented as it is already supported in avd3.x
