### ISSUE TITLE
route-reflector client only supported under peer-group

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#2280]
### Issue Summary

I need to configure a BGP neighbor as route-reflector client without a peer-group. This is legal in CLI, but `eos_cli_config_gen` doesn't let me, just ignores the key `route_reflector_client` under neighbor (inside VRF or globally)

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Inside router BGP structure:

Renders correctly:


router_bgp:
  as: '65101'
  router_id: 192.168.255.4
  bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart
  - maximum-paths 4 ecmp 4
  peer_groups:
    MLAG-IPv4-UNDERLAY-PEER:
      type: ipv4
      remote_as: '65101'
      next_hop_self: true
      password: vnEaG8gMeQf3d3cN6PktXQ==
      maximum_routes: 12000
      send_community: all
      route_map_in: RM-MLAG-PEER-IN
      route_reflector_client: true
```

Does not render RR client command:

```yaml
router_bgp:
 (... ommitted)
  vrfs:
     VRF1:
        neighbors:
          10.255.251.0:
          description: DC1-LEAF1A
          route_reflector_client: true
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
