### ISSUE TITLE
Management with IPv6 only

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#2309]
### Enhancement summary

We would like to have IPv6 support for management of the switches. A knob to choose between ipv4 or ipv6 stacks would be a good way to take this as people can choose what they want for the OOB.

### Which component of AVD is impacted

eos_designs

### Use case example

```
interface management1
   vrf management
   ipv6 address 2001:db8::1/64

no ipv6 unicast-routing vrf management 
ipv6 route vrf management ::/0 2001:db8::254
```

### Describe the solution you would like

```
spine:
  nodes:
    spine1:
      id: 1
      mgmt_ip: 2001:db8::100/64

mgmt_interface_vrf: management
mgmt_gateway: 2001:db8::254
mgmt_destination_networks:
  - ::/0
```

inventory

```
fabric:
  children:
     dc1:
       children:
          spines_abc:
            hosts:
              spine1:
                ansible_host: '[2001:db8::100]'
```

### Describe alternatives you have considered

There are patches involved to fix this temporarily.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
