### ISSUE TITLE
Feat(eos_designs): Enable sFlow at fabric level

### ISSUE THREAD

**Issue by xaviramon** [aristanetworks/ansible-avd#2311]
### Enhancement summary

We would like a fabric-wise command the enables sflow on all fabric interfaces.

We would like a similar variable like PTP:
```yaml
# Enable PTP on all infrastructure links | Optional
uplink_ptp:
  enable: < boolean | default -> false >
  ```
But allowing sflow variables conveniently.

### Which component of AVD is impacted

eos_designs

### Use case example

Allow sflow monitoring at a fabric level reducing the amount of interfaces involved in sflow and the number of packets sent to the collector.

### Describe the solution you would like

Control of basic sflow parameters at a fabric level, without including host-facing interfaces.

### Describe alternatives you have considered

using eos_cli variable, which is not autocontained.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
