### ISSUE TITLE
IP Locking in eos_cli_config_gen

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#2313]
### Enhancement summary

Implement IP Locking in eos_cli_config_gen

Global knobs and interface level knobs for Campus use case.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Interface level:

```
interface ethernet 1-10
  address locking ipv4 ipv6

interface ethernet 11
  address locking ipv4

interface ethernet 12
  address locking ipv6
```

Global level:

```
address locking
  dhcp server ipv4 1.2.3.4
  dhcp server ipv4 1.2.3.5
  local-interface Loopback0
  disabled
  locked-address ipv4 enforcement disabled
  locked-address ipv6 enforcement disabled
```
  

### Describe the solution you would like

Interface level

```
ethernet_interfaces:
  <Ethernet_interface_1 >:
    address_locking: < ipv4 | ipv6 | ipv4 ipv6 >
```

Global

```
address_locking:
  dhcp_server_ipv4:
    - 1.2.3.4
    - 1.2.3.5
  local_interface: < Loopback0 | Vlan10 | Ethernet1 >
  disabled: < true | false >
  locked_address_ipv4_encforcement_disabled: < true | false >
  locked_address_ipv6_encforcement_disabled: < true | false >
```
  

### Describe alternatives you have considered

Raw cli not very scalable.

### Additional context

.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
