### ISSUE TITLE
Feat(eos_cli_config_gen): extend dot1x with radius av-pair and mac based authentication

### ISSUE THREAD

**Issue by dmilyt** [aristanetworks/ansible-avd#2341]
### Enhancement summary

dot1x global configuration will be extended with missing options for radius av-pair and mac based authentication.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Global dot1x configuration for campus leafs in NAC setup

```
dot1x
  mac based authentication delay 0 seconds
  mac based authentication hold period 1 seconds
  radius av-pair service-type
```

### Describe the solution you would like

```
dot1x:
  mac_based_authentication:
    delay: < 0-300 in seconds >
    hold_period: < 1-300 seconds >
  radius_av_pair
    service_type: < true | false >
    framed_mtu: < 68-9236 >	
```
### Describe alternatives you have considered

This can be accomplished today with cvp configlet or eos_cli:.

### Additional context

I would like to provide the implementation on this

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
