### ISSUE TITLE
Feat(eos_cli_config_gen): extend radius_servers with attribute 32 include in access and dynamic-authorization

### ISSUE THREAD

**Issue by dmilyt** [aristanetworks/ansible-avd#2342]
### Enhancement summary

radius-servers global configuration will be extended with missing options for 

- attribute 32 include-in-access-req
- dynamic-authorization
- host < ip > timeout < seconds > retransmit < seconds >

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
radius-server attribute 32 include-in-access-req hostname
radius-server dynamic-authorization port 1700
radius-server dynamic-authorization tls ssl-profile SSL_PROFILE
radius-server host 10.10.10.10 timeout 1 retransmit 1 key 7 123456789
radius-server host 10.10.10.11 timeout 1 retransmit 1 key 7 123456789
```

### Describe the solution you would like

Following would be nonbreaking extension:

```
radius_servers:
  - attribute_32_include_in_access:
    hostname: < true | false >
    format: < LINE >
  - dynamic_authorisation:
    port: < port_number >
    tls_ssl_profile: < profile >
  - host: < host IP address or name >
    vrf: < vrf_name >
    key: < encrypted_key >
    timeout: < 1-1000 > in seconds
    retransmit: < 0-100 >
```

This looks better for me but would be a breaking change

```
radius_servers:
  attribute_32_include_in_access:
    hostname: < true | false >
    format: < LINE >
  dynamic_authorisation:
    port: < port_number >
    tls_ssl_profile: < profile >
  hosts:
    - host: < host IP address or name >
      timeout: < 1-1000 > in seconds
      retransmit: < 0-100 >
      key: < encrypted_key >
```
 

### Describe alternatives you have considered

This can be accomplished today with cvp configlet or eos_cli:.

### Additional context

I would like to provide the implementation on this

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I agree that the current data model does not allow for extension. I suggest to add a new `radius_server` key with the common settings. And then add the `retransmit` to the existing model.
If you are up for it, you can also add full coverage in that new `radius_server` key, with the full data model you suggest, and then we will deprecate the old one (we need to keep the old one working until 5.0)

**Comment by kmueller68** [comment]
we will go for it in two parallel ways:
1. extend existing ```radius_servers``` with the new host specific options ```timeout```and ```retransmit```
```
radius_servers:
  - host: < host IP address or name >
    vrf: < vrf_name >
    key: < encrypted_key >
    timeout: < 1-1000 > in seconds
    retransmit: < 0-100 >
 ```
 
 2. introduce a new ```radius_server``` with the common options and the extension for ```hosts```
 ```
 radius_server:
  attribute_32_include_in_access:
    hostname: < true | false >
    format: < LINE >
  dynamic_authorisation:
    port: < port_number >
    tls_ssl_profile: < profile >
  hosts:
    - host: < host IP address or name >
      vrf: < vrf_name >
      key: < encrypted_key >
      timeout: < 1-1000 > in seconds
      retransmit: < 0-100 >
```

Does this meet your guidelines?

**Comment by dmilyt** [comment]
Can we start with the implementation or should we open two separate issues?

**Comment by emilarista** [comment]
Hello, some small changes suggested to the data model:

```yaml
radius_server:
 attribute_32_include_in_access_req:  # add _req to match cli command
   ...
 dynamic_authorization:  # we spell authorization with z in the cli
   ...
 ```

**Comment by dmilyt** [comment]
The changes are done:
```
radius_server:
 attribute_32_include_in_access_req:
   hostname: < true | false >
   format: < LINE >
 dynamic_authorization:
   port: < port_number >
   tls_ssl_profile: < profile >
 hosts:
   - host: < host IP address or name >
     vrf: < vrf_name >
     key: < encrypted_key >
     timeout: < 1-1000 > in seconds
     retransmit: < 0-100 >
```
