### ISSUE TITLE
Feat(eos_cli_config_gen): extend aaa_accounting with options for dot1x

### ISSUE THREAD

**Issue by dmilyt** [aristanetworks/ansible-avd#2343]
### Enhancement summary

aaa_accounting global configuration will be extended with missing options for dot1x accounting

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
aaa accounting dot1x default start-stop group < group-name > logging
```

### Describe the solution you would like

```
aaa_accounting:
  dot1x:
    default:
      type: < none | start-stop | stop-only >
      group: < group_name >
      logging: < true | false >
```

### Describe alternatives you have considered

This can be accomplished today with cvp configlet or eos_cli:.

### Additional context

I would like to provide the implementation on this.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
