### ISSUE TITLE
Feat(eos_cli_config_gen): extend ethernet_interface with dot1x eapol authentication_failure_falback

### ISSUE THREAD

**Issue by dmilyt** [aristanetworks/ansible-avd#2344]
### Enhancement summary

Ethernet Interface configuration will be extended with missing options for dot1x eapol authentication_failure_falback mba timeout.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
interface Ethernet1
    dot1x eapol authentication failure fallback mba timeout 0
```

### Describe the solution you would like

I have two data models for discussion to be added:

```
# Switched Interfaces
ethernet_interfaces:
  Ethernet_Interface_2:
    dot1x:
      eapol:
        disabled: < true | false >
        authentication_failure_fallback:
        mba: 
          timeout:  < 0-65535 > in seconds
```

or

```
# Switched Interfaces
ethernet_interfaces:
  Ethernet_Interface_2:
    dot1x:
      eapol:
        disabled: < true | false >
        authentication_failure_fallback_mba: < true | false >
          timeout:  < 0-65535 > in seconds
```

### Describe alternatives you have considered

This can be accomplished today with cvp configlet or eos_cli:.

### Additional context

I would like to provide the implementation on this

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I suggest this model:
```yaml
ethernet_interfaces:
  Ethernet_Interface_2:
    dot1x:
      eapol:
        disabled: < true | false >
        authentication_failure_fallback_mba:
          enabled: < true | false >
          timeout: < 0-65535 > in seconds
```
Note that CLI allows for both options in the config, so you should not collapse them in the template:
```eos
interface Ethernet1
   dot1x eapol disabled
   dot1x eapol authentication failure fallback mba
```
