### ISSUE TITLE
Feat(eos_cli_config_gen): Support shell option for local-users

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#2354]
### Enhancement summary

cf title

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
username service shell /bin/bash secret sha512 $6$24WE.Z7itztZ6X
```

### Describe the solution you would like

```
local_users:
  < user_1 >:
    disabled: < true | false | default -> false >
    privilege: < 1-15 >
    role: < role >
    sha512_password: "< sha_512_password >"
    no_password: < true | do not configure a password for given username. sha512_password MUST not be defined for this user. >
    ssh_key: "< ssh_key_string >"
    shell:  "<shell string>"   
```

Need to change / implement:
* Schema fragment in eos_cli_config_gen role
* Jinja2 template for eos in eos_cli_config_gen role
* Jinja2 template for documentation in eos_cli_config_gen role
* molecule test

### Describe alternatives you have considered

custom_template / eos_cli ...

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
