### ISSUE TITLE
vlan-aware-bundles only map to single VLAN ID

### ISSUE THREAD

**Issue by adietrich-ussignal** [aristanetworks/ansible-avd#2387]
### Issue Summary

If multiple VLANs are configured with the same name, the final configuration generated only creates a vlan-aware-bundle for one of the VLAN IDs.  

It is expected that in this scenario, a range or list of VLANs is added to the vlan-aware-bundle. 

For example:
```
vlan-aware-bundle foo
  rd 1.1.1.1:100
  route-target both 100:100
  vlan 1-10
```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI with AVD Runner

### Steps to reproduce

```shell
Add multiple VLANs with the same name and unique VLAN IDs.


      2201:
        name: name_2200
        tags: ['DC']
      2202:
        name: name_2200
        tags: ['DC']
      2203:
        name: name_2200
        tags: ['DC']
      2204:
        name: name_2200
        tags: ['DC']
```
Push the configuration through AVD.
```


### Relevant log output

```shell
The following relevant lines of configuration are generated in the intended configuration. 

vlan 2200-2204	
   name name_2200
vxlan vlan 2201 vni 15201	
   vxlan vlan 2202 vni 15202	
   vxlan vlan 2203 vni 15203	
   vxlan vlan 2204 vni 15204
vlan-aware-bundle name_2200	  
      rd 10.255.12.7:15204	
      route-target both 15204:15204	      
      redistribute learned	      
      vlan 2204
```
```


### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
This looks like a bug to me. Can you give me a bit more context on the input data?

**Comment by adietrich-ussignal** [comment]
Here is a bit more context to the input data. Let me know if you'd like something more particular. 

```
  TEST_TENANT:
    mac_vrf_vni_base: 13000
    l2vlans:
      2201:
        name: name_2200
        tags: ['DC']
      2202:
        name: name_2200
        tags: ['DC']
      2203:
        name: name_2200
        tags: ['DC']
      2204:
        name: name_2200
        tags: ['DC']
```
