### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for load-interval on Ethernet Interfaces

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#2425]
### Enhancement summary

Be able to specify a load-interval for a port profile.

https://www.arista.com/en/um-eos/eos-data-transfer#xx1135353

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Enhance Ethernet interface to support modifying the load interval.

```
port_profiles:
  phone:
    mode: trunk phone
    structured_config:
      profile: dot1x
      load_interval:  30
```

### Describe the solution you would like

add a new key/value under 
```
ethernet_interfaces: 
  load_interval: < 5 - 600, default - 300 > 
```
That renders the option in the appropriate location under the interface:
```
interface Ethernet1
   profile dot1x
   description Workstation / Phone
   shutdown
   load-interval 30
   switchport trunk native vlan 1234
```

### Describe alternatives you have considered

It can be implemented today with:
```
raw_eos_cli: |
      load-interval 30
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
