### ISSUE TITLE
Configlet attachement to container using CV 2020.2.x

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#245]
## Issue Type

- Bug Report

## Summary

In CV version 2020.2.x, when we configure AVD to attach a configlet to Cloudvision, tasks related to this change are not applied to EOS devices.

With the current version, API after a `validateAndCompareConfiglets.do` only returns tasks generated during this `tempAction` and not previous tasks.

## Role or Module Name

__Role:__ `arista.avd.eos_config_deploy_cvp`

## OS / Environment

__EOS Version__

N/A

__Cloudvision version__

`2020.2.x`

__OS running Ansible__

N/A

## Steps to reproduce

In DC1_FABRIC.yml, configure a configlet to attach

```yaml
cv_configlets:
  containers:
    DC1_FABRIC:
      - ASE_RADIUS-LAB
    DC1_L3LEAFS:
      - ASE_GLOBAL-ALIASES
```
