### ISSUE TITLE
Update data model for hardware counters

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#2451]
### Enhancement summary

Option # 1

```
hardware_counters:
  features:
   - name:
      direction: in | out | both
```

Option # 2
```
hardware_counters:
  features:
   - name: vlan-interface
      in: bool
      out: bool
```

### Which component of AVD is impacted

eos_cli_config_gen

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
