### ISSUE TITLE
Add Trust command for management security ssl profiles

### ISSUE THREAD

**Issue by tgodaA** [aristanetworks/ansible-avd#2470]
### Enhancement summary

Support the Trust command under management_security.ssl_profiles

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Below use case:

<img width="435" alt="image" src="https://user-images.githubusercontent.com/88734745/214994724-4206e32f-dd54-4c6c-b8e7-57c257f61daa.png">

### Describe the solution you would like

```yaml
ssl_profiles:
  - name: < profile name >
     trust_certificates:
       - list of certificate names with options available
```

<img width="501" alt="image" src="https://user-images.githubusercontent.com/88734745/214995419-f6fd57d7-83c4-46c0-9bc1-c90d53a52314.png">

### Describe alternatives you have considered

eos_cli

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by adietrich-ussignal** [comment]
Could we also add 'chain' to this model? That is a current use case that AVD does not meet. 
```
leaf-01a(config-mgmt-sec-ssl-profile-lab-ssl-profile)#?
  certificate     Configure certificate for self authentication
  chain           Configure chained certificate
  cipher-list     Configure a cipher list
  crl             Configure CRLs
  diffie-hellman  Configure diffie-hellman parameters
  fips            Configure FIPS settings
  peer            Configure peer related options
  tls             Configure TLS settings
  trust           Configure trusted certificate
  ----------------------------------------
  comment         Up to 240 characters, comment for this mode
  default         Set a command to its defaults
  exit            Leave SSL profile configuration mode
  no              Disable the command that follows
  show            Display details of switch operation
  !!              Append to comment
```
Could be mirror to the suggested model above. 
```
ssl_profiles:
  - name: < profile name >
     trust_certificates:
       - list of certificate names with options available
      chain_certificates:
       - list of certificate names
```
