### ISSUE TITLE
Feat(eos_cli_config_gen): add new option phone to switchport phone trunk for switched interfaces

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#2479]
### Enhancement summary

the options for ```switchport phone trunk``` currently are ```taggeed | untagged```.

```
# Switched Interfaces
ethernet_interfaces:
  <Ethernet_interface_2 >:
    phone:
      trunk: < tagged | untagged >
 ```
 
 According to the Arista TOI "802.1X on Arista Switches" there is an additional option now:
 till EOS 4.29.1F ```switchport default phone trunk untagged phone```
 
 ```
 (config-if-Et1)#switchport phone trunk untagged ?
  phone  Untagged packets on phone VLAN
  <cr>   
```

 and in addition starting with upcoming EOS 4.30.x ```switchport phone trunk tagged phone```
 
  

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
interface ethernet 1
  switchport mode trunk phone
  switchport phone trunk untagged | tagged phone
 ```

### Describe the solution you would like

```
# Switched Interfaces
ethernet_interfaces:
  <Ethernet_interface_2 >:
    phone:
      trunk: < tagged | tagged phone | untagged | untagged phone>
 ```

### Describe alternatives you have considered

This can be accomplished today with eos_cli:.

```
# Switched Interfaces
ethernet_interfaces:
  <Ethernet_interface_2 >:
    # EOS CLI rendered directly on the ethernet interface in the final EOS configuration
   eos_cli: |
      switchport phone trunk untagged | tagged phone
 ```
 

### Additional context

How could we now handle the option ```switchport phone trunk tagged phone```, which will first be availabe with EOS 4.30.x in some weeks?

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by kmueller68** [comment]
I have received the EFT EOS image supporting the new option ```switchport phone trunk tagged phone``` today.

Here is the CLI output... just to prove that this option will come.

```
nac-710p(config-if-Et1)#switchport phone trunk tagged ?
  phone  Tagged packets on phone VLAN
  <cr>
```

**Comment by ClausHolbechArista** [comment]
I don't have a device to test with, but could you experiement a bit with combinations like 
```eos
switchport phone trunk tagged
switchport phone trunk untagged phone
```
to see if it produces multiple configuration lines. This changes how we need to handle it in the logic. Thanks

**Comment by kmueller68** [comment]
@ClausHolbechArista does this help?

```
nac-710p(config-if-Et2)#switchport phone ?
  trunk  Set trunking characteristics of the interface
  vlan   Details on VLAN operation

nac-710p(config-if-Et2)#switchport phone trunk ?
  tagged    Configure the port to send tagged packets
  untagged  Configure the port to send untagged packets

nac-710p(config-if-Et2)#switchport phone trunk tagged ?
  phone  Tagged packets on phone VLAN
  <cr>

nac-710p(config-if-Et2)#switchport phone trunk untagged ?
  phone  Untagged packets on phone VLAN
  <cr>

nac-710p(config-if-Et2)#show ac

nac-710p(config-if-Et2)#switchport phone trunk tagged
nac-710p(config-if-Et2)#show ac
interface Ethernet2
   switchport phone trunk tagged
nac-710p(config-if-Et2)#switchport phone trunk tagged phone
nac-710p(config-if-Et2)#show ac
interface Ethernet2
   switchport phone trunk tagged phone
nac-710p(config-if-Et2)#switchport phone trunk untagged
nac-710p(config-if-Et2)#show ac
interface Ethernet2
   switchport phone trunk untagged
nac-710p(config-if-Et2)#switchport phone trunk untagged phone
nac-710p(config-if-Et2)#show ac
interface Ethernet2
   switchport phone trunk untagged phone
nac-710p(config-if-Et2)#
```

**Comment by ClausHolbechArista** [comment]
I agree on this:
```
# Switched Interfaces
ethernet_interfaces:
  <Ethernet_interface_2 >:
    phone:
      trunk: < tagged | tagged phone | untagged | untagged phone>
```
We no longer have the README.md for eos_cli_config_gen. Instead we use the schemas to generate documentation. Please make sure to set `valid_values` in the schema as a list of the accepted strings.
