### ISSUE TITLE
Feat: Enhance aaa to support multiple groups where available in EOS

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#2521]
### Enhancement summary

https://github.com/aristanetworks/ansible-avd/pull/2450/files#r1089721034

This EOS CLI is a bit confusing, and the documentation has a couple of typos which does not help :)
logging is a "method" similar to group abc, so it is not a property of a group.
For some reason EOS does not have a guard against repeating the same method multiple times, so that is why logging shows up after every group.
I do not know how the ordering of logging vs. group abc might affect the behavior, so until we know that, I would suggest that we skip expanding for now and just implement what we need (one group with group key similar to the rest of the models).
A future data model should probably be referring to methods which can then either be a group (with or without multicast) or logging.

```
dot1x:
  default:
    type: start-stop
    methods:
      - method: < logging | group >
        group: < group_name >   <-- Only relevant for method group
        multicast: < bool >     <-- Only relevant for method group   
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

no use case today - just tracking the outcome of the other PR.

### Describe the solution you would like

support multiple groups in the future

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
