### ISSUE TITLE
Unable to use CLI option "logging synchronous level all" via AVD due to validtion failure

### ISSUE THREAD

**Issue by jwbensley** [aristanetworks/ansible-avd#2550]
### Issue Summary

This is a valid CLI option: `logging synchronous level all`

For example:
```
r1(config-s-s2)#logging synchronous level ?
  alerts         Immediate action needed           (severity=1)
  all            Log all messages synchronously
  critical       Critical conditions               (severity=2)
  debugging      Debugging messages                (severity=7)
  emergencies    System is unusable                (severity=0)
  errors         Error conditions                  (severity=3)
  informational  Informational messages            (severity=6)
  notifications  Normal but significant conditions (severity=5)
  warnings       Warning conditions                (severity=4)
  <0-7>          Severity level value
```

When I try to use it via AVD as specified [here](https://avd.sh/en/stable/roles/eos_cli_config_gen/index.html#logging) like this:
```
logging:
  synchronous:
    level:  "all"
```

I get the following error when running AVD:
```
TASK [arista.avd.eos_cli_config_gen : Generate eos intended configuration] **********************************************************************************************
[WARNING]: [r1]: 'Validation Error: logging.synchronous.level': 'all' is not one of ['debugging', 'informational', 'notifications', 'warnings', 'errors', 'critical', 'alerts', 'emergencies', 'disabled']
```

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
From `role/foo/tasks/main.yml`:


- name: render templates to structured config
  arista.avd.yaml_templates_to_facts:
    templates:
      - template: "eos/logging.yml"
```
```


### Relevant log output

```shell
TASK [arista.avd.eos_cli_config_gen : Generate eos intended configuration] **********************************************************************************************
[WARNING]: [r1]: 'Validation Error: logging.synchronous.level': 'all' is not one of ['debugging', 'informational', 'notifications', 'warnings', 'errors', 'critical', 'alerts', 'emergencies', 'disabled']
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by UchihaItachiSama** [comment]
It should be a simple fix to add `all` as a valid input value for logging schema fragments

```yaml
      synchronous:
        type: dict
        keys:
          level:
            type: str
            valid_values: ["debugging", "informational", "notifications", "warnings", "errors", "critical", "alerts", "emergencies", "disabled"]
            description: |
              Synchronous logging severity level
            default: "critical"
```

@jwbensley please let us know if will you add this yourself or should we find a volunteer?
