### ISSUE TITLE
list merge with custom_structured_configuration replaces rather than appends

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#2590]
### Issue Summary

using AVD devel 4.0.0-dev5 with default list_merge setting ```custom_structured_configuration_list_merge: append_rp``` 
and trying to merge two lists from ```all.yml``` with additional one from ```DC.yml```. 
But the lists are not merged but replaced by the later one.

```
# /home/avd/.ansible/collections/ansible_collections
Collection        Version
----------------- ----------
ansible.netcommon 4.1.0
ansible.posix     1.5.1
ansible.utils     2.9.0
arista.avd        4.0.0-dev5
```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI with AVD Runner

### Steps to reproduce

```shell
all.yml


aaa_server_groups:
  - name: "AAA_Auth"
    type: radius
    servers:
      - server: 10.5.1.22
        vrf: "{{ mgmt_interface_vrf }}"
      - server: 10.5.1.23
        vrf: "{{ mgmt_interface_vrf }}"
```

DC.yml
```
custom_structured_configuration_aaa_server_groups:
  - name: "ISE_NAC"
    type: radius
    servers:
      - server: 10.10.1.22
        vrf: "{{ mgmt_interface_vrf }}"
      - server: 10.10.1.23
        vrf: "{{ mgmt_interface_vrf }}"
```
```


### Relevant log output

```shell
intended device-debug-vars.yml

aaa_server_groups:
- name: AAA_Auth
  type: radius
  servers:
  - server: 10.5.1.22
    vrf: MGMT
  - server: 10.5.1.23
    vrf: MGMT

custom_structured_configuration_aaa_server_groups:
- name: ISE_NAC
  type: radius
  servers:
  - server: 10.10.1.22
    vrf: MGMT
  - server: 10.10.1.23
    vrf: MGMT


intended device.yml

aaa_server_groups:
- name: ISE_NAC
  type: radius
  servers:
  - server: 10.10.1.22
    vrf: MGMT
  - server: 10.10.1.23
    vrf: MGMT
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
Hello @kmueller68  - this is actually the expected behavior.

`aaa_server_groups` is not an `eos_designs` key  but an `eos_cli_config_gen` key and so as per the custom_structured_configuration variable precedence defined here: https://avd.sh/en/latest/roles/eos_designs/doc/custom-structured-configuration.html#overview you are in scenario 5 of the examples - https://avd.sh/en/latest/roles/eos_designs/doc/custom-structured-configuration.html#eos_cli_config_gen-variables-overwritten-by-eos_designs-custom_structured_configuration

The following is happening:

1. you are running `eos_designs` and the custom_structured_configuration is rendered (not the `eos_cli_config_gen` key in your `all.yml` file)  - so in your structured_config file, the output of `eos_designs` only the key from custom_structured_configuration is present and this is expected

2. when you run `eos_cli_config_gen`, the key from `all.yml` is taken but then the role is loading the structured config and overwriting whatever came as an `eos_cli_config_gen` key.


To achieve what you want you should use the following in the current custom_structured_configuration setup:

all.yml

```
custom_structured_configuration_prefix:
  - global_custom_configuration_
  - custom_structured_configuration_
 
custom_structured_configuration_list_merge: append_rp

global_custom_configuration_aaa_server_groups:
  - name: "AAA_Auth"
    type: radius
    servers:
      - server: 10.5.1.22
        vrf: "{{ mgmt_interface_vrf }}"
      - server: 10.5.1.23
        vrf: "{{ mgmt_interface_vrf }}"
```

DC.yml

```
custom_structured_configuration_aaa_server_groups:
  - name: "ISE_NAC"
    type: radius
    servers:
      - server: 10.10.1.22
        vrf: "{{ mgmt_interface_vrf }}"
      - server: 10.10.1.23
        vrf: "{{ mgmt_interface_vrf }}"
```

This way you are using two prefixes for declaring custom structured configuration and are telling eos_designs to merge the values.

output:

structured_config
```
aaa_server_groups:
- name: AAA_Auth
  type: radius
  servers:
  - server: 10.5.1.22
    vrf: MGMT
  - server: 10.5.1.23
    vrf: MGMT
- name: ISE_NAC
  type: radius
  servers:
  - server: 10.10.1.22
    vrf: MGMT
  - server: 10.10.1.23
    vrf: MGMT
```
