### ISSUE TITLE
Feat(eos_cli_config_gen): add option to identify transceivers on a per interface basis

### ISSUE THREAD

**Issue by RyanM-Arista** [aristanetworks/ansible-avd#2605]
### Enhancement summary

Requesting to add a feature similar to rack: or uplink_structured_config: wherein a user can add information about transceivers to be used on an interface.  

This information would be used for AVD Documentation purposes 

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

ethernet_interfaces:
```
  Ethernet51:
    peer: Other_Side
    peer_interface: Ethernet51
    peer_type: mlag_peer
    description: MLAG_PEER_Other_Side_Ethernet51
    type: switched
    shutdown: false
    channel_group:
      id: 51
      mode: active
    transceiver_type: <user inputted transceiver type>
```

### Describe the solution you would like

Add an optional field in eos_cli_config_gen > ethernet_interfaces to allow the optional input of transceiver type
 `   transceiver_type: <user inputted transceiver type>`

If the feature can be combined with uplink_switch_interfaces: and uplink_interfaces: it can populate both interface ends when generating this datapoint. 
ex `uplink_switch_transceivers: [ list of transceivers matching uplink_switch_interfaces: ]` and `uplink_transceivers: [ list of transceivers matching uplink_interfaces ]`

### Describe alternatives you have considered

Used uplink_structured_config: but it does not apply this custom configuration on individual interfaces when the interface is in a port-channel.  If the uplink_structured_config: feature applies information on individual interfaces this feature request will not be needed

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
