### ISSUE TITLE
Idea: Management settings in eos_designs

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#2631]
Management settings in eos_designs

Ex snmp_server will be consumed in eos_designs and patched with source interfaces according to specific settings:
```yaml
l3leaf:
  nodes:
    myhost:
      mgmt_inband_ip
      mgmt_inband_interface
      mgmt_inband_vrf
      mgmt_ip:
      mgmt_interface
mgmt_vrf
mgmt_interface

management_source_interfaces:
  snmp:
    inband: true
    oob: false

snmp_server:
  $ref: eos_cli_config_gen#keys/snmp_server
```
