### ISSUE TITLE
inventory_to_container module does not process a group with children and host properly

### ISSUE THREAD

**Issue by philippebureau** [aristanetworks/ansible-avd#2654]
### Issue Summary

impact AVD up to 3.8.4.  AVD 4.0.0.dev7 has a refactored inventory_to_container module and does **not** have this issue.  

If a group in the inventory file contains both children and hosts, inventory_to_container does not generate the correct structured_config for CVP which prevent CVP provisionning.  The nodes under the "hosts" key are missing the "parentContainerName" key in the structured_config

inventory section example:
```
            DC1_LEAFS:
              children:
                DC1_L3LEAFS:
                  children:
                    DC1_BORDERS:
                      hosts:
                        s1-brdr1:
                        s1-brdr2:
                  hosts:
                    s1-leaf1:
                    s1-leaf2:
                    s1-leaf3:
                    s1-leaf4:
```

The structured_configs for CVP result is as follow:

```
CVP_DEVICES:
  - fqdn: s1-brdr1
    parentContainerName: DC1_BORDERS
    configlets:
      - AVD_s1-brdr1
  - fqdn: s1-brdr2
    parentContainerName: DC1_BORDERS
    configlets:
      - AVD_s1-brdr2
  - fqdn: s1-leaf1
    configlets:
      - AVD_s1-leaf1
  - fqdn: s1-leaf2
    configlets:
      - AVD_s1-leaf2
  - fqdn: s1-leaf3
    configlets:
      - AVD_s1-leaf3
  - fqdn: s1-leaf4
    configlets:
      - AVD_s1-leaf4
  - fqdn: s1-spine1
    parentContainerName: DC1_SPINES
    configlets:
      - AVD_s1-spine1
  - fqdn: s1-spine2
    parentContainerName: DC1_SPINES
    configlets:
      - AVD_s1-spine2
 ```

expected output :
```
cvp_devices:
  - fqdn: s1-brdr1
    parentContainerName: DC1_BORDERS
    configlets:
      - AVD_s1-brdr1
  - fqdn: s1-brdr2
    parentContainerName: DC1_BORDERS
    configlets:
      - AVD_s1-brdr2
  - fqdn: s1-leaf1
    parentContainerName: DC1_L3LEAFS
    configlets:
      - AVD_s1-leaf1
  - fqdn: s1-leaf2
    parentContainerName: DC1_L3LEAFS
    configlets:
      - AVD_s1-leaf2
  - fqdn: s1-leaf3
    parentContainerName: DC1_L3LEAFS
    configlets:
      - AVD_s1-leaf3
  - fqdn: s1-leaf4
    parentContainerName: DC1_L3LEAFS
    configlets:
      - AVD_s1-leaf4
  - fqdn: s1-spine1
    parentContainerName: DC1_SPINES
    configlets:
      - AVD_s1-spine1
  - fqdn: s1-spine2
    parentContainerName: DC1_SPINES
    configlets:
      - AVD_s1-spine2
 ```

### Which component(s) of AVD impacted

arista.avd.inventory_to_container

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
