### ISSUE TITLE
Feat(eos_cli_config_gen): Global poe configuration options 

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#2663]
### Enhancement summary

Add global poe options to configure the switch behaviour for poe on reboot or interface shutdown:

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Global configuration of the switch behaviour regarding poe supply for all interfaces:

```
poe
   reboot action maintain
   interface shutdown action power-off
```

### Describe the solution you would like

```
poe:
  interface_shutdown_action: < maintain | power-off>
  reboot:
    action: < maintain | power-off>
```

### Describe alternatives you have considered

This can be accomplished today with cvp configlet or eos_cli:.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by kmueller68** [comment]
@pvinci-arista 
I have currently seen your partial request on this:
https://github.com/aristanetworks/ansible-avd/issues/2611

Should we combine both?

**Comment by pvinci-arista** [comment]
sure!

**Comment by kmueller68** [comment]
@pvinci-arista 
Could you please review my yaml model. Which one do you prefer: yours or mine.

**Comment by pvinci-arista** [comment]
Yours is perfect.

**Comment by ClausHolbechArista** [comment]
LGTM. Let us know if you need any help. And thank you for coordinating with the existing issue. I have closed #2611 since this one covers both.

**Comment by jrecchia1029** [comment]
Hey guys,

I'm working on #2683 and it looks like there is also a `link down action`.  It was pointed out that there is an optional `power-off delay` parameter for this action.

```
Leaf1(config-if-Et3)#show cli commands | grep poe
[no|default] poe [disabled]
[no|default] poe legacy detect
[no|default] poe limit ( ( class CLASS_NUM ) | ( NUM_WATTS watts ) ) [ fixed ]
[no|default] poe link down action ( maintain | ( power-off [ NUM_SECONDS seconds ] ) )
[no|default] poe negotiation lldp [disabled]
[no|default] poe pairset ( ( alternative ( a | b ) ) | 4-pair )
[no|default] poe priority PRIORITY
[no|default] poe reboot action ( maintain | power-off )
[no|default] poe shutdown action ( maintain | power-off )
``` 

Since that's the case, for consistency purposes, the interface poe data model we came up with for the poe interface actions looks like:

```
poe:
  reboot:
    action: [maintain, power-off]
  shutdown:
    action: [maintain, power-off]
  link_down:
    action: [maintain, power-off]
    delay: <1-86400> # with a comment that it works only for power-off
```

In speaking with the author of this [TOI](https://www.arista.com/en/support/toi/eos-4-26-1f/14784-power-over-ethernet-poe), he mentioned it's likely possible Arista adds support for configuring `poe interface link down action` at the global level.  Since that's the case, I think we should probably adjust the global poe data model to match the interface data model for these poe interface behaviors.

Maybe
```
poe:
  reboot:
    action: [maintain, power-off]
  interface_shutdown:
    action: [maintain, power-off]
```

Any issues with that?
