### ISSUE TITLE
Feat(eos_cli_config_gen): Add 'transport grpc-tunnel' to 'management api gnmi' configuration

### ISSUE THREAD

**Issue by adietrich-ussignal** [aristanetworks/ansible-avd#2665]
### Enhancement summary

The current management api gnmi implementation in AVD only provides for enabling grpc transport. As of EOS 4.27.0F, transport over grpc-tunnel is now available for dial-out telemetry. 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Example EOS Config:
```
management api gnmi
   transport grpc default
      vrf management
   !
   transport grpc-tunnel gnmic
      vrf management
      destination 10.1.1.10 port 10100
      local interface Management1 port 10200
      gnmi ssl profile test_profile
      tunnel ssl profile test_profile
      target id1
   !
   provider eos-native
```

### Describe the solution you would like

Would like a data model similar to what is provided below added to the management api gnmi model. 

```yaml
management_api_gnmi:
  transport:
    grpc-tunnel:
     - name: <str>
       tunnel_ssl_profile: <str>
       gnmi_ssl_profile: <str> 
       vrf: <str>
       destination:
         ip_address: <int> 
         port: <1-65535> 
       local_interface:
         interface: <str>
         port: <1-65535> 
       target: 
          use_serial_number: default -> False 
          target_id: <str or list>
        enabled: default -> True
```

### Describe alternatives you have considered

Defining the configuration using eos_cli. 

### Additional context

If adding this component is acceptable, I'd be happy to take a stab and submit a pull request for this. 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
