### ISSUE TITLE
Add missing TerminAttr param generation for cvauth method "certs"

### ISSUE THREAD

**Issue by pdiancourt** [aristanetworks/ansible-avd#2669]
### Enhancement summary

The [official documentation](https://avd.sh/en/stable/roles/eos_cli_config_gen/index.html#daemon-terminattr) doesn't propose the "certs" value for "method".

[Here](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/daemon-terminattr.j2#L34-L39) we can see that the cvauth method "certs" is not handled for generating a  TerminAttr parameter.  

This "certs" parameter can be seen documented [here](https://arista.my.site.com/AristaCommunity/s/article/terminattr-most-commonly-used-flags-and-sample-configurations ) when looking for the "cvauth" keyword  

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

After successfully onboarding the switches of my eve-ng lab using [this](https://github.com/aristanetworks/cloudvision-ztpaas-utils/blob/main/BootstrapScriptWithToken/bootstrap.py) ZTP script, I get this running config :  
```
daemon TerminAttr
   exec /usr/bin/TerminAttr -cvaddr=apiserver.arista.io:443 -taillogs -cvauth=certs,/persist/secure/ssl/terminattr/primary/certs/client.crt,/persist/secure/ssl/terminattr/primary/keys/client.key -cvproxy= -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata
   no shutdown
```

Now that the switch is seen in CVaaS, i can push configs successfully with AVD.
Using [the l2ls-fabric template ](https://github.com/aristanetworks/ansible-avd/tree/devel/ansible_collections/arista/avd/examples/l2ls-fabric) works but of course it proposes to overwrite the "daemon TerminAttr" related commands. Which when applied...legitimately stops the streaming to CVaaS.

So, to prevent losing connection to my switches and still push the AVD configs, I want to be able to use the AVD role to generate this same daemon TerminAttr config initially generated by the ZTP process.

### Describe the solution you would like

I'd like to propose a PR with the required changes to make the following possible :  
```
daemon_terminattr:
  cvaddrs:
    - apiserver.arista.io:443
  cvauth:
    method: certs
    crt: /persist/secure/ssl/terminattr/primary/certs/client.crt
    key: /persist/secure/ssl/terminattr/primary/keys/client.key
  cvvrf: MGMT
  taillogs: /var/log/messages
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
```
It would generate this command :  
`exec /usr/bin/TerminAttr -cvaddr=apiserver.arista.io:443 -taillogs=/var/log/messages -cvauth=certs,/persist/secure/ssl/terminattr/primary/certs/client.crt,/persist/secure/ssl/terminattr/primary/keys/client.key -cvproxy= -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata`

Here the only missing piece is the keyword "certs" to be allowed and a new field "crt" to be created.

I would edit both config and documentation files by following [this](https://github.com/aristanetworks/ansible-avd/commit/7d47e7ad4ff7bc574bc515fe1e80335facec030c) pretty similar commit.  

### Describe alternatives you have considered

I considered generating a non destructive config with 
```
daemon_terminattr:
  cvaddrs:
    - apiserver.arista.io:443
  cvauth:
    method: token-secure
    token_file: /tmp/cv-onboarding-token
  cvvrf: MGMT
  taillogs: /var/log/messages
  smashexcludes: ale,flexCounter,hardware,kni,pulse,strata
```  
Even though it makes no sense to switch to the "token-secure" method.  

I've also considered writting a separate configlet just for this daemon config and deploy it to CVaaS with CVP still but it's basically crawling back to old methods of doing things and i'd prefer not when it's easy to extend the current AVD roles.

### Additional context

This request follows email exchanges with support@arista.com.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
