### ISSUE TITLE
Add DCI data model in eos_l3ls_evpn

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#268]
**Issue Type**
- Role enhancement

**Is your feature request related to a problem? Please describe.**
- New data model to support the definition of DCI connectivity.
- Must be flexible to support the various DCI models.

**Comment by ClausHolbechArista** [comment]
Data model from brainstorming session:
```yaml
l3_edge:
  p2p_links_subnet_summaries:
    dci: <subnet/mask>
  p2p_defaults:
    include_in_underlay_protocol: true|false
    mtu: (inherit p2p_uplinks_mtu if not set)
    ip_pool: dci
  p2p_links:
    - id: <int>
      ip_pool: something_else
      subnet: <subnet/mask>
      ip: [ ip_a , ip_b ]
      nodes: [ node_a , node_b ]
      asn: [ node_a , node_b ]
      interfaces: [ node_a_int_1 , node_b_int_1 ]
      include_in_underlay_protocol: true|false
```

**Comment by c-po** [comment]
Happy to test this out as it would definately improve our entire workflow how to pull in the roles.

Would it make sense to start of with an import from https://github.com/arista-netdevops-community/ipspace-webinar-september15-2020/tree/master/roles/eos_dci?

**Comment by ClausHolbechArista** [comment]
@c-po Sounds good that you can test. I already built most of it in PR665, so you can just pull the code from there and try it out

**Comment by c-po** [comment]
@ClausHolbechArista I just gave the mentioned PR a testdrive using the below topology.

AS65101 is DC1 and AS65201 is DC2

![image](https://user-images.githubusercontent.com/25299219/107354242-37fbfb00-6ace-11eb-96d8-199f8de610e4.png)


```yml
### FABRIC DCI ###
l3_edge:
  p2p_links_ip_pools:
    dci_ip_pool: 172.29.0.0/24
  p2p_links_profiles:
    my_dci:
      include_in_underlay_protocol: true
      ip_pool: dci_ip_pool
      mtu: 1600
      bfd: true
      as: [ 65101, 65201 ]
  p2p_links:
    - id: 1
      profile: my_dci
      nodes: [ t-spine-1a7-01, t-spine-2a7-01 ]
      interfaces: [ Ethernet7, Ethernet7 ]
    - id: 2
      profile: my_dci
      nodes: [ t-spine-1a7-01, t-spine-2a7-02 ]
      interfaces: [ Ethernet8, Ethernet8 ]
    - id: 3
      profile: my_dci
      nodes: [ t-spine-1a7-02, t-spine-2a7-01 ]
      interfaces: [ Ethernet8, Ethernet8 ]
    - id: 4
      profile: my_dci
      nodes: [ t-spine-1a7-02, t-spine-2a7-02 ]
      interfaces: [ Ethernet7, Ethernet7 ]
```

BGP sessions ramp up and start information exchange. Looking forward of getting this merged into the `devel` branch.
