### ISSUE TITLE
Interface PoE commands

### ISSUE THREAD

**Issue by jrecchia1029** [aristanetworks/ansible-avd#2683]
### Enhancement summary

Add interface level poe commands to configure common campus interface configurations

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Interface level poe commands to address many of the commands found in this [EOS TOI](https://www.arista.com/en/support/toi/eos-4-26-1f/14784-power-over-ethernet-poe).

### Describe the solution you would like

A data model that resembles the below:

```
ethernet_interfaces:
  - name: <Interface-Name>
    poe:
      disabled: < true | false >
      priority: < critical | high | medium | low >
      reboot_action: < maintain | power-off >
      shutdown_action: < maintain | power-off >
      link_down_action: < maintain | power-off >
      limit:
        class: < 0-8 >
        watts: < 0-90 >
        fixed: < true | false >
      negotiation_lldp: < true | false >
      legacy_detect: < true | false >
```

### Describe alternatives you have considered

This can be accomplished today with eos_cli.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
