### ISSUE TITLE
Allow for same mlag domain on multiple mlag pairs

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#2715]
### Enhancement summary

The schema for node_groups does not allow the same group to be used on multiple MLAG pairs. Either relax this requirement or implement another mlag_domain knob.

### Which component of AVD is impacted

eos_designs

### Use case example

.

### Describe the solution you would like

.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
so the current blocking point is that we can't have multiple time the same group name for a given node_type? (we have under 5clos molecule the same group name across multiple node type and it works afaik)

```
        node_groups:
          type: list
          convert_types:
            - dict
          primary_key: group
          items:
            "$ref": "#/keys/node_type/keys/defaults"
            type: dict
            keys:
              group:
                type: str
                required: true
                description: The Node Group Name is used for MLAG domain.
              nodes:
                "$ref": "#/keys/node_type/keys/nodes"
```

Could you please share a snippet of the use case here? I feel like having multiple times the same group name under a give type would confuse our logic if some parameters are different across node types and would rather prefer to have an extra knob for `mlag_domain` that defaults to the group name.
