### ISSUE TITLE
Feat(eos_cli_config_gen): Global NAT configuration options

### ISSUE THREAD

**Issue by kornoa** [aristanetworks/ansible-avd#2724]
### Enhancement summary

Provide all global NAT configuration options. Including:
- ip nat pool
- ip nat synchronization
- ip nat translation
- ip nat kernel buffer size

> Note: IP NAT on IF level will be handled by dedicated FR.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

EOS configuration example:
````code
ip nat translation address selection hash field source-ip
ip nat translation max-entries 5000
ip nat translation max-entries 1000 host
ip nat translation max-entries 200 198.18.0.2
ip nat translation max-entries 100 198.18.0.1
ip nat translation counters
ip nat kernel buffer size 16
ip nat pool P1 prefix-length 24
   range 198.18.0.101 198.18.0.120 2000 20000
   range 198.18.0.1 198.18.0.20 2000 20000
ip nat synchronization
   peer-address 198.18.1.1
   local-interface Ethernet11
````

### Describe the solution you would like

Representation in structured configuration:
````yaml
nat:
  kernel_buffer_size: 16
  pool:
    - name: P1
      prefix_length: 24
      ranges:
        - first_ip: 198.18.0.1
          last_ip: 198.18.20
          start_port: 2000
          end_port: 20000
        - first_ip: 198.18.0.101
          last_ip: 198.18.120
          start_port: 2000
          end_port: 20000
  synchronization:
    peer_address: 198.18.1.1
    local_interface: Ethernet11
  translation:
    address_selection_hash_field_source_ip: true
    counters: true
    max_entries:
      limit: 5000
      host_limit: 1000
      ip_limits:
        - ip: 198.18.0.1
          limit: 100
        - ip: 198.18.0.2
          limit: 200
````

### Additional context

Full structured config suggestion:
````yaml
nat:
  kernel_buffer_size: < 1-64 > (int)

  pool:
    - name: < pool_name > (str)
      prefix_length: < 16-32 > (int)
      ranges:
        - first_ip: < IP_address > (str)
          last_ip: < IP_address > (str)		
          start_port: < 1-65535> (int)
          end_port: < 1-65535> (int) # >= start_port
      utilization_log_threshold: < 1-100 > (int)

  synchronization:
    description: < description > (str)
    shutdown: < true | false | default -> false > (bool)
    expiry_interval: < 60-3600 > (int) # seconds
    local_interface: < local_interface_name > (str)
    peer_address: < IPv4_address > (str)
    port_range:
      start_port: < 1024-65535 > (int)
      end_port: < 1024-65535 > (int) # >= start_port
    port_range_split: < true | false | default -> true > (bool)
 
  translation:
    address_selection_hash_field_source_ip: < true | false | default -> false > (bool)
    
    counters: < true | false | default -> false > (bool)
    low_mark:
      percentage: < 1-99 | default -> 90 > (int)
      host_percentage: < 1-99 | default -> 90 > (int)
    max_entries:
      limit: < 0 - 4294967295 > (int)
      host_limit:  < 0 - 4294967295 > (int)
      ip_limits:
        - ip: < IPv4_address > (str)
          limit: < 0 - 4294967295 > (int)
    tcp_timeout: < 0 - 4294967295 | default -> 86400 > (int) # seconds
    udp_timeout: < 0 - 4294967295 | default -> 300 > (int) # seconds
````

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by kornoa** [comment]
Full implementation including testing & documentation can be done by me.

**Comment by carlbuchmann** [comment]
@kornoa thank you for submitting this feature request. We will review the proposed data model early next week and provide feedback before you start working on this PR. Have a great weekend!

**Comment by gmuloc** [comment]
Thanks @kornoa for another great research and submission as a model

## `show cli commands` output

Here is a full output of the CLI on a device running EOS 4.29.0F

```
device(config)#show cli commands | grep "ip nat" 
[no|default] ip nat TARGET static LOCALIP GLOBALIP ( INSIDE_VRF_VRF_KW ( INSIDE_VRF_VRF_DYNAMIC ) )
ip nat flow
[no|default] ip nat kernel buffer size BUFSIZE
[no|default] ip nat logging
[no|default] ip nat pool POOLNAME ( ( prefix-length PREFIXLEN ) | ( netmask MASK ) )
ip nat pool POOLNAME STARTIP ENDIP ( ( prefix-length PREFIXLEN ) | ( netmask MASK ) ) [ STARTPORT ENDPORT ]
[no|default] ip nat profile PROFILENAME [ ( VRF_VRF_KW ( VRF_VRF_DYNAMIC ) ) ]
[no|default] ip nat service-list NAME
[no|default] ip nat source ( INSIDE_VRF_VRF_KW ( INSIDE_VRF_VRF_DYNAMIC ) ) rate RATE burst BURST
[no|default] ip nat synchronization
[no|default] ip nat tcp flow creation trigger TRIGGER
[no|default] ip nat translation PROTO TIMEOUT
[no|default] ip nat translation address selection any
[no|default] ip nat translation address selection hash field source-ip
[no|default] ip nat translation counters
[no|default] ip nat translation low-mark PERCENT [ host ]
[no|default] ip nat translation max-entries MAXENTRIES [ host | IPADDR ]
```

and for the synchronization submode:

```
device(config-nat-synchronization)#show cli commands
[no|default] description DESCRIPTION
[no|default] expiry-interval INTERVAL
[no|default] local-interface INTF
[no|default] peer-address PEERIP
[no|default] port-range LOWER [ UPPER ]
[no|default] port-range split [disabled]
show active
show active all [ detail ]
show comment
[no|default] shutdown
```

## Comments on the proposed model

* Given that the key being implemented is for `ip nat` let's call the key `ip_nat` instead of `nat`
* for booleans where the default value is `false` you don't need to indicate this as a default
* given that we can have multiple pools - let's rename `pool` -> `pools`
* as a general rule we don't include the default values of percentage / timeouts in eos_cli_config_gen (you may find places in the schema where it is the case actually but do try to stay away from this) as they can change across platform and if there is nothing to render, the default value will be used by the switch.
* In order to unify the cli for the ranges for ip address and ports we suggest to use `first` and `last` everywhere
    ```yaml
    ip_nat:
      pools:
          ranges:
            - first_ip: < IP_address > (str)
              last_ip: < IP_address > (str)		
              first_port: < 1-65535> (int)
              last_port: < 1-65535> (int) # >= first_port
      synchronization:
        port_range:
          first_port: < 1024-65535 > (int)
          last_port: < 1024-65535 > (int) # >= first_port
    ```
* for the `synchronization.port_range` `split` - given that the default is enabled and there is only a key for disabled we suggest to use the following model
    ```yaml
    ip_nat:
      synchronization:
        port_range:
          first_port: < 1024-65535 > (int)
          last: < 1024-65535 > (int) # >= first_port
          split_disabled: < true | false >
    ```
* for the `ip nat translation tcp/udp-timeout <>` lines given that the model is `[no|default] ip nat translation PROTO TIMEOUT` we suggest modeling it like this:
    ```yaml
    ip_nat:
      translation:
         timeouts: # in seconds
          - protocol: <str> [valid_values tcp / udp>
             timeout: < 0 - 4294967295 > (int) 
    ```
* while the 
* Looking at cli for ip nat translation address selection and the fact that `any` and `hash field source-ip` can be configured at the same time we would like to change the model to
    ```yaml
    ip_nat:
      translation:
        address_selection:
          any: < true | false> (bool)
          hash_field_source_ip: < true | false> (bool)
    ```


## Final suggested model:

```yaml
ip_nat:
  kernel_buffer_size: < 1-64 > (int)
  pools:
    - name: < pool_name > (str)
      prefix_length: < 16-32 > (int)
      ranges:
        - first_ip: < IP_address > (str)
          last_ip: < IP_address > (str)		
          first_port: < 1-65535> (int)
          last_port: < 1-65535> (int) # >= first_port
      utilization_log_threshold: < 1-100 > (int)
  synchronization:
    description: < description > (str)
    shutdown: < true | false > (bool)
    expiry_interval: < 60-3600 > (int) # seconds
    local_interface: < local_interface_name > (str)
    peer_address: < IPv4_address > (str)
    port_range:
      start_port: < 1024-65535 > (int)
      end_port: < 1024-65535 > (int) # >= first_port
      split_disabled: < true | false > (bool)
  translation:
    address_selection:
      any: < true | false >
      hash_field_source_ip: < true | false > (bool)
    counters: < true | false > (bool)
    low_mark:
      percentage: < 1-99 > (int)
      host: < 1-99 > (int)
    max_entries:
      limit: < 0 - 4294967295 > (int)
      host_limit:  < 0 - 4294967295 > (int)
      ip_limits:
        - ip: < IPv4_address > (str)
          limit: < 0 - 4294967295 > (int)
    timeouts: # in seconds
      - protocol: <str> [valid_values tcp / udp]
        timeout: < 0 - 4294967295 > (int) 
```



Let us know if you have any questions / comments / feedbacks
