### ISSUE TITLE
Feat(eos_cli_config_gen): Interface NAT configuration options

### ISSUE THREAD

**Issue by kornoa** [aristanetworks/ansible-avd#2725]
### Enhancement summary

Provide interface level NAT rule configuration options:
- ip nat source static
- ip nat source dynamic
- ip nat destination static
- ip nat destination dynamic

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

EOS configuration example:
````code
interface Ethernet10
   ip nat source static 198.18.177.1 198.18.178.1 protocol tcp group 1 comment Test123
   ip nat destination static 198.18.77.1 22 198.18.78.1 2022 protocol tcp group 1 comment Test123
   ip nat source dynamic access-list ACL1 pool P1 comment Test-P1
````

### Describe the solution you would like

Representation in structured configuration:
````yaml
ethernet_interfaces:
  Ethernet10:
    ip_nat:
      destination:
        static:
          - comment: Test123
            group: 1
            original_ip: 198.18.77.1
            original_port: 22
            translated_ip: 198.18.78.1
            translated_port: 2022
      source:
        dynamic:
          - access_list: ACL1
            comment: Test-P1
            pool: P1
        static:
          - comment: Test123
            group: 1
            original_ip: 198.18.177.1
            translated_ip: 198.18.178.1
````

### Additional context

Full structured config suggestion:

**Routed Ethernet Interfaces**
````yaml
ethernet_interfaces:
  < Ethernet_interface_1 >:
    ip_nat:
      destination:
        dynamic:
          - access_list: < access_list_name > (str) # required
            comment: < NAT_rule_description > (str)
            pool: < ip_nat_pool_name > (str) # required
            priority: < 0 - 4294967295 | default -> 0 > (int)
        static:
          - access_list: < access_list_name > (str)
            comment: < NAT_rule_description > (str)
            direction: < ingress | egress | default -> ingress >
            group: < 1-65535 > (int) # excludes 'access_list'
            original_ip: < IP_address > (str) # required
            original_port: < 1-65535 > (int)
            protocol: < tcp | udp >
            translated_ip: < IP_address > (str) # required
            translated_port: < 1-65535 > (int)
      source:
        dynamic:
          - access_list: < access_list_name > (str) # required
            comment: < NAT_rule_description > (str)
            overload: < true | false | default -> false > (bool) # If true, excludes 'pool' option
            pool: < ip_nat_pool_name > (str)
            pool_usage: < address-only | full-cone >
            priority: < 0 - 4294967295 | default -> 0 > (int)
        static:
          - access_list: < access_list_name > (str)
            comment: < NAT_rule_description > (str)
            direction: < ingress | egress | default -> egress >
            group: < 1-65535 > (int) # excludes 'access_list'
            original_ip: < IP_address > (str) # required
            original_port: < 1-65535 > (int)
            protocol: < tcp | udp >
            translated_ip: < IP_address > (str) # required
            translated_port: < 1-65535 > (int)
````

**Port-Channel Interfaces**
````yaml
port_channel_interfaces:
  < Port-Channel_interface_4 >:
    ip_nat:
      *same options as on Routed Ethernet Interfaces*
````

**Tunnel Interfaces**
````yaml
tunnel_interfaces:
  - name: < interface_name >
    ip_nat:
      *same options as on Routed Ethernet Interfaces*
````

**VLAN Interfaces**
````yaml
vlan_interfaces:
  < Vlan_id_1 >:
    ip_nat:
      *same options as on Routed Ethernet Interfaces*
````

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by kornoa** [comment]
Full implementation including testing & documentation can be done by me.

**Comment by gmuloc** [comment]
Hi @kornoa - thanks a lot for all this work!

## Notes on proposed schema


* Given that ingress / egress and nothing renders different CLI:

    ```
     interface Ethernet1/1
        description test
    +   ip nat source egress static 5.5.5.4 9.9.9.4
    +   ip nat source ingress static 5.5.5.5 9.9.9.9
    +   ip nat source static 5.5.5.8 9.9.9.8
   ```

we suggest introducing `both` and making it render nothing and being the default (so if direction is not set for static NAT this is the value chosen)

* for source dynamic NAT - we propose grouping under a `nat_type` with 4 options so that it is clear that these are mutually exclusive and adding a pool name.

```
            nat_type: < overload | pool | pool-address-only | pool-full-cone >
            pool_name: < ip_nat_pool_name > (str) # required if nat_type is in pool-* but cannot be express in schema today
```

* Change `pool` to `pool_name` in destination dynamic NAT

## Proposed schema
```
ethernet_interfaces:
  < Ethernet_interface_1 >:
    ip_nat:
      destination:
        dynamic:
          - access_list: < access_list_name > (str) # required
            comment: < NAT_rule_description > (str)
            pool_name: < ip_nat_pool_name > (str) # required
            priority: < 0 - 4294967295 | default -> 0 > (int)
        static:
          - access_list: < access_list_name > (str)
            comment: < NAT_rule_description > (str)
            direction: < ingress | egress | both | default -> both > # both is not rendered on CLI
            group: < 1-65535 > (int) # excludes 'access_list'
            original_ip: < IP_address > (str) # required
            original_port: < 1-65535 > (int)
            protocol: < tcp | udp >
            translated_ip: < IP_address > (str) # required
            translated_port: < 1-65535 > (int)
      source:
        dynamic:
          - access_list: < access_list_name > (str) # required
            comment: < NAT_rule_description > (str)
            nat_type: < overload | pool | pool-address-only | pool-full-cone >
            pool_name: < ip_nat_pool_name > (str) # required if nat_type is in pool-* but cannot be express in schema today
            priority: < 0 - 4294967295 | default -> 0 > (int)
        static:
          - access_list: < access_list_name > (str)
            comment: < NAT_rule_description > (str)
            direction: < ingress | egress | both | default -> both > # both is not rendered on CLI
            group: < 1-65535 > (int) # excludes 'access_list'
            original_ip: < IP_address > (str) # required
            original_port: < 1-65535 > (int)
            protocol: < tcp | udp >
            translated_ip: < IP_address > (str) # required
            translated_port: < 1-65535 > (int)
```

## Some advice on schema writing
we recommend you write the model only once under a `$defs` key and then use the `$defs` in each of the interfaces schema to avoid repeating 4 time the schema,
This is quite new in 4.0 but you can have a look at these two files as an example:
* https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_designs/schemas/schema_fragments/defs_node_type.schema.yml 
* https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_designs/schemas/schema_fragments/node_type.schema.yml

don't hesitate to reach out if you need any help.


Thanks again for the great preparatory work!

**Comment by kornoa** [comment]
@gmuloc thank you for your detailled feedback.

- I fully agree on your dynamic NAT suggestion. I would like to have CLI config as clear as your data model. ;-)
- A special thanks for the help regarding schema writing and avoiding repeating code.
- Regarding the direction in IF nat rules. For me, it seems there is no `both`. In source rules direction defaults to egress and in destination rules it defaults to ingress on a 720XP-24ZY4 running 4.28.6.1M.
````code
TLRS-720-01(config)#int eth11
TLRS-720-01(config-if-Et11)#ip nat source egress static 5.5.5.4 9.9.9.4
TLRS-720-01(config-if-Et11)#sh run int eth11
interface Ethernet11
   no switchport
   ipv6 enable
   ipv6 address auto-config
   ipv6 nd ra rx accept default-route
   ip nat source static 5.5.5.4 9.9.9.4
TLRS-720-01(config-if-Et11)#ip nat destination ingress static 4.4.4.5 8.8.8.5
TLRS-720-01(config-if-Et11)#sh run int eth11
interface Ethernet11
   no switchport
   ipv6 enable
   ipv6 address auto-config
   ipv6 nd ra rx accept default-route
   ip nat destination static 4.4.4.5 8.8.8.5
   ip nat source static 5.5.5.4 9.9.9.4
````
  So, it would like to stay on my suggested data model for key `direction`.

# Proposed schema
````yaml
ethernet_interfaces:
  < Ethernet_interface_1 >:
    ip_nat:
      destination:
        dynamic:
          - access_list: < access_list_name > (str) # required
            comment: < NAT_rule_description > (str)
            pool_name: < ip_nat_pool_name > (str) # required
            priority: < 0 - 4294967295 | default -> 0 > (int)
        static:
          - access_list: < access_list_name > (str)
            comment: < NAT_rule_description > (str)
            direction: < egress | ingress | default -> ingress>
            group: < 1-65535 > (int) # excludes 'access_list'
            original_ip: < IP_address > (str) # required
            original_port: < 1-65535 > (int)
            protocol: < tcp | udp >
            translated_ip: < IP_address > (str) # required
            translated_port: < 1-65535 > (int)
      source:
        dynamic:
          - access_list: < access_list_name > (str) # required
            comment: < NAT_rule_description > (str)
            nat_type: < overload | pool | pool-address-only | pool-full-cone >
            pool_name: < ip_nat_pool_name > (str) # required if nat_type is in pool-* but cannot be express in schema today
            priority: < 0 - 4294967295 | default -> 0 > (int)
        static:
          - access_list: < access_list_name > (str)
            comment: < NAT_rule_description > (str)
            direction: < egress | ingress | default -> egress >
            group: < 1-65535 > (int) # excludes 'access_list'
            original_ip: < IP_address > (str) # required
            original_port: < 1-65535 > (int)
            protocol: < tcp | udp >
            translated_ip: < IP_address > (str) # required
            translated_port: < 1-65535 > (int)
````
