### ISSUE TITLE
eos_design/Network_services ospf vlan interface authentication message-digest missing command

### ISSUE THREAD

**Issue by philippebureau** [aristanetworks/ansible-avd#2726]
### Issue Summary

In eos_design - Network services tenant interfaces configuration of ospf authentication with message-digest, the output configuration for vlan (svi) interfaces is missing "ip ospf authentication message-digest"

YML example : 
```
TENANT_A:
  vrfs:
    BLUE:
      ospf:
        enabled: true
        process_id: 400
        bfd: true
        redistribute_bgp:
          enabled: true
        nodes:
          - s1-leaf1
          - s1-leaf2
      svis:
        104:
          name: ospf_test
          tags: [ DC1_LEAF1 ]
          nodes:
            s1-leaf1:
              ip_address: 20.20.20.1/29
            s1-leaf2:
              ip_address: 20.20.20.2/29
          ospf:
            enabled: true
            point_to_point: false
            area: 0.0.0.99
            authentication: message-digest
            message_digest_keys:
              - id: 1
                hash_algorithm: md5
                key: SDGASHERASEGRWH
```

Resulting configuration  on s1-leaf1:
```
interface Vlan104
   description ospf_test
   shutdown
   vrf BLUE
   ip address 20.20.20.1/29
   ip ospf area 0.0.0.99
   ip ospf message-digest-key 1 md5 7 SDGASHERASEGRWH
```

The expected output configuration would be :
<pre>
interface Vlan104
   description ospf_test
   shutdown
   vrf BLUE
   ip address 20.20.20.1/29
   ip ospf area 0.0.0.99
   <b>ip ospf authentication message-digest</b>
   ip ospf message-digest-key 1 md5 7 SDGASHERASEGRWH
<pre>

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
