### ISSUE TITLE
Feat(eos_designs): add redistribute connected to router ospf under network services

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#2763]
### Enhancement summary

Add option for redistribution of connected networks into ospf under network services of eos_desings:

In reference to PR #2762

```
tenants:
  # Tenant Specific Information - VRFs / VLANs
  Tenant_A:
    mac_vrf_vni_base: 10000
    vrfs:
      VRF_A:
        ospf:
          enabled: true
          process_id: <id>
          redistribute_connected:
            enabled: < true | false >
            route_map: < route-map name >
```

 

### Which component of AVD is impacted

eos_designs

### Use case example

The following YAMl should render the cli config bellow:

```
tenants:
  Tenant_A:
    mac_vrf_vni_base: 10000
    vrfs:
      VRF_A:
        ospf:
          enabled: true
          process_id: 5
          redistribute_connected:
            enabled: true
            route_map: RM-DEHE_PROD-CORE-PREFIX-DROP-OUT'''

```

```
router ospf 5 vrf VRF_A
   router-id 10.102.2.1
   passive-interface default
   no passive-interface Ethernet56.4050
   no passive-interface Vlan873
   redistribute connected route-map RM-DEHE_PROD-CORE-PREFIX-DROP-OUT
   redistribute bgp route-map RM-DEHE_PROD-CORE-PREFIX-DROP-OUT
```

### Describe the solution you would like

```
  Tenant_A:
    mac_vrf_vni_base: 10000
    vrfs:
      VRF_A:
        ospf:
          enabled: < true | false >
          process_id: < int, Default -> vrf_id >
          router_id: < router-id, Default -> switch router_id >
          max_lsa: < int >
          bfd: < true | false, Default -> false >
          redistribute_bgp:
            enabled: < true | false, Default -> true >
            route_map: < route-map name >
          redistribute_connected:
            enabled: < true | false >
            route_map: < route-map name >
          nodes:
            - < hostname1 >
            - < hostname2 >
```
  

### Describe alternatives you have considered

Could add the following via custom_structured_configuration per host_vars files. 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
