### ISSUE TITLE
Add parenthesis syntax for interface ranges

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#2768]
### Enhancement summary

Some platforms have these kind of breakout layout

```
network_ports:
  - switches:
      - MY-AWESOME-SWITCHES
    switch_ports:
      # Special ports
      # Ethernet 26, 28, 30 and 32 have only 1 and 3
      # Ethernet 33 and 35 have from 1-8
      - Ethernet9-25/1-4
      - Ethernet26/1
      - Ethernet26/3
      - Ethernet27/1-4
      - Ethernet28/1
      - Ethernet28/3
      - Ethernet29/1-4
      - Ethernet30/1
      - Ethernet30/3
      - Ethernet31/1-4
      - Ethernet32/1
      - Ethernet32/3
      - Ethernet33/1-8
      - Ethernet34/1-4
      - Ethernet35/1-8
      - Ethernet36/1-4
 ```

Adding parenthesis would help reduce the snippet above to something like

```
network_ports:
  - switches:
      - MY-AWESOME-SWITCHES
    switch_ports:
      # Special ports
      # Ethernet 26, 28, 30 and 32 have only 1 and 3
      # Ethernet 33 and 35 have from 1-8
      Ethernet(9-25,27,29,31,34)/1-4
      Ethernet(26,28,30,32)/(1,3)
      Ethernet(33,35)/1-8
```

### Which component of AVD is impacted

plugins

### Use case example

cf description

### Describe the solution you would like

parenthesis for ranges - cf description

### Describe alternatives you have considered

current functionality is working fine

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
