### ISSUE TITLE
Feat(eos_cli_config_gen): add missing options to ethernet logging event configuration

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#2781]
### Enhancement summary

the EOS cli is offering four options for logging event under ethernet interface, from which two are missing in AVD:

```
access(config-if-Et20)#no logging event ?
  congestion-drops  Drops due to congestion
  link-status       UPDOWN messages
  spanning-tree     Spanning tree messages
  storm-control     Configure storm-control
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
ethernet_interfaces:
  - name: Ethernet6
    logging:
      event:
        link_status: false
        congestion_drops: false
	spanning_tree: false
	storm_control: false
```

should render:

```
interface Ethernet6
 no logging event link-status
 no logging event congestion-drops
 no logging event spanning-tree
 no logging event storm-control
```

### Describe the solution you would like

YAML model:
```
ethernet_interfaces:
  - name: <str>
    logging:
      event:
        link_status: <bool>
        congestion_drops: <bool>
	spanning_tree: <bool>
	storm_control: <bool>
```

roles/eos_cli_config_gen
https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/ethernet-interfaces.j2

```
{%     if ethernet_interface.logging.event is arista.avd.defined %}
{%         if ethernet_interface.logging.event.link_status is arista.avd.defined(true) %}
   logging event link-status
{%         elif ethernet_interface.logging.event.link_status is arista.avd.defined(false) %}
   no logging event link-status
{%         endif %}
{%         if ethernet_interface.logging.event.congestion_drops is arista.avd.defined(true) %}
   logging event congestion-drops
{%         elif ethernet_interface.logging.event.congestion_drops is arista.avd.defined(false) %}
   no logging event congestion-drops

{%         if ethernet_interface.logging.event.spanning_tree is arista.avd.defined(true) %}
   logging event spanning-tree
{%         elif ethernet_interface.logging.event.spanning_tree is arista.avd.defined(false) %}
   no logging event spanning-tree

{%         if ethernet_interface.logging.event.storm_control is arista.avd.defined(true) %}
   logging event storm-control
{%         elif ethernet_interface.logging.event.storm_control is arista.avd.defined(false) %}
   no logging event storm-control

{%         endif %}
{%     endif %}
```

Schema:
https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/eos_cli_config_gen.schema.yml

```
        logging:
          type: dict
          keys:
            event:
              type: dict
              keys:
                link_status:
                  type: bool
                congestion_drops:
                  type: bool
		spanning_tree:
                  type: bool
        	storm_control:
                  type: bool
```

Json Schema
https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/eos_cli_config_gen.jsonschema.json

```
          "logging": {
            "type": "object",
            "properties": {
              "event": {
                "type": "object",
                "properties": {
                  "link_status": {
                    "type": "boolean",
                    "title": "Link Status"
                  },
                  "congestion_drops": {
                    "type": "boolean",
                    "title": "Congestion Drops"
                  }
                  "spanning_tree": {
                    "type": "boolean",
                    "title": "Spanning Tree"
                  }
                  "storm_control": {
                    "type": "boolean",
                    "title": "Storm Control"
                  }
                },
                "additionalProperties": false,
                "patternProperties": {
                  "^_.+$": {}
                },
                "title": "Event"
              }
            },
            "additionalProperties": false,
            "patternProperties": {
              "^_.+$": {}
            },
            "title": "Logging"
          },

```

Molecule 
https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/ethernet-interfaces.yml

```
  - name: Ethernet6
    logging:
      event:
        link_status: true
        congestion_drops: true
	spanning_tree: true
	storm_control: true
```
		

### Describe alternatives you have considered

usage of eos_cli

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
