### ISSUE TITLE
Feat(eos_cli_config_gen): Add support no bgp default ipv4-unicast

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#2786]
Add support for router bgp
 - `no bgp default ipv4-unicast` 
 - `no bgp default ipv4-unicast transport ipv6`

Suggested data model

```yaml
router_bgp:
  bgp:
    default:
      ipv4_unicast: < bool >
      ipv4_unicast_transport_ipv6: < bool >
```  

EOS cli output examples:

```eos
router bgp 65535
   no bgp default ipv4-unicast
   bgp default ipv4-unicast transport ipv6

router bgp 65535
   no bgp default ipv4-unicast
   no bgp default ipv4-unicast transport ipv6

router bgp 65535
   bgp default ipv4-unicast
   bgp default ipv4-unicast transport ipv6
```
