### ISSUE TITLE
Feat(eos_designs): Fabric variable to adjust graceful restart

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#2802]
Fabric variable to adjust graceful restart 

Example data model:

```yaml
bgp_graceful_restart:
  enabled: < bool >
  restart_time: < int >
```
