### ISSUE TITLE
Feat(eos_designs): Platform and Fabric variables to adjust update wait-for-convergence and update wait-install

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#2839]
Suggested data model:

```yaml
bgp_wait_for_convergence: <bool> -> default unset
bgp_update_wait_install: <bool> -> default unset

platform_settings:
      - platforms: "for all hardware based platforms"
        feature_support:
            bgp_wait_for_convergence: <bool> -> default true
            bgp_update_wait_install: <bool> -> default true
      - platforms: "veos & ceos"
        feature_support:
            bgp_wait_for_convergence: false
            bgp_update_wait_install: false

```
