### ISSUE TITLE
Feature: `structured_config` on `p2p_links`

### ISSUE THREAD

**Issue by chetryan** [aristanetworks/ansible-avd#2840]
### Enhancement summary

For `l3_edge` p2p links, there is currently limited support for interface level.

Until all/most of the interface level knobs are available, it would be great if we could specify `structured_config` as currently supported on *connected endpoints*.

### Which component of AVD is impacted

eos_designs

### Use case example

Example, to configure the qos input service-policy, a p2p_link_profile could be :

```
l3_edge:
  p2p_links_profiles:
    corporate_p2p_peering:
      structured_config:
          service_poicy:
              qos:
                 input: <name of policy>
```

### Describe the solution you would like

A knob `structured_config` that accepts a dictionary which is then merge with all the structured_config that was generated for the p2p links.

The behaviour should be similar to that of `structured_config` for the connected endpoints.

### Describe alternatives you have considered

Currently using `raw_eos_cli` under `p2p_links` which is even less ideal than using `structured_config` as it requires the raw eos cli commands.

```
l3_edge:
  p2p_links_profiles:
    corporate_p2p_peering:
      raw_eos_cli: |
        service-policy type qos input <name here>
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
