### ISSUE TITLE
Fix(eos_designs): bgp_mesh_pes doesn't generate any BGP configutation

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#2843]
### Issue Summary

`bgp_mesh_pes` flag for MPLS designs doesn't generate any configuration

### How do you run AVD ?

None

#### Ansible Inventory

AVD:
  vars:
    # SNIPPED AVD Global Vars
  children:
    MPLS:
      children:
        pe:
          vars:
            type: pe
          hosts:
            AR-PMBR1:
              ansible_host: 172.31.255.1
            AR-PMBR2:
              ansible_host: 172.31.255.2

#### Ansible Group Vars

```yaml
design:
  type: mpls
fabric_name: MPLS
underlay_routing_protocol: isis-sr
overlay_routing_protocol: ibgp

bgp_as: 65000
bgp_mesh_pes: true

pe:
  defaults:
    virtual_router_mac_address: 00:c1:00:00:00:11
    platform: vEOS-LAB
    node_sid_base: 100
    is_type: level-2
    isis_system_id_prefix: '0000.0001'
    loopback_ipv4_pool: 172.16.0.0/24
  nodes:
    AR-PMBR1:
      id: 1
      mgmt_ip: 172.31.255.1/24
    AR-PMBR2:
      id: 2
      mgmt_ip: 172.31.255.2/24
```

#### EOS router bgp output:

```eos
router bgp 65000
   router-id 172.16.0.1
   maximum-paths 4 ecmp 4
   neighbor MPLS-OVERLAY-PEERS peer group
   neighbor MPLS-OVERLAY-PEERS remote-as 65000
   neighbor MPLS-OVERLAY-PEERS update-source Loopback0
   neighbor MPLS-OVERLAY-PEERS bfd
   neighbor MPLS-OVERLAY-PEERS send-community
   neighbor MPLS-OVERLAY-PEERS maximum-routes 0
   !
   address-family evpn
   !
   address-family ipv4
      no neighbor MPLS-OVERLAY-PEERS activate
   !
   address-family vpn-ipv4
      neighbor MPLS-OVERLAY-PEERS activate
      neighbor default encapsulation mpls next-hop-self source-interface Loopback0
!
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
