### ISSUE TITLE
Feature: Add support for comments 

### ISSUE THREAD

**Issue by chetryan** [aristanetworks/ansible-avd#2863]
### Enhancement summary

Add a knob to `eos_cli_config_gen` to be able to use the EOS comment feature.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

In `qos_profiles` we might want to make use of comments on queues, as per below example: 

```
qos_profiles:
  - name: uc_mc_queues_test
    uc_tx_queues:
      - id: 1
        bandwidth_percent: 50
        priority: 'no priority'
        comment: "Test no priority"
      - id: 2
        bandwidth_percent: 10
        priority: 'priority strict'
      - id: 4
        bandwidth_guaranteed_percent: 10
        comment: "Test guaranteed percent"
```

### Describe the solution you would like

The basic implementation would add a knob to qos_profiles to support comments.

A possible better approach is to support comments wherever they are supported in the EOS configuration.

### Describe alternatives you have considered

The existing alternative is to use `raw_eos_cli` or `eos_cli`. 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
