### ISSUE TITLE
Feat(eos_cli_config_gen): add ip verify unicast source to ethernet-, sub- and vlan-interfaces

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#2880]
### Enhancement summary

add unicast reverse path forwarding (uRPF) to ethernet- and sub-interfaces and Vlan interfaces:

```
leaf-test(config-if)#ip verify ?
  unicast  Enable RPF on unicast traffic

leaf-test(config-if)#ip verify unicast ?
  source  RPF mode

leaf-test(config-if)#ip verify unicast source ?
  reachable-via  RPF mode

leaf-test(config-if)#ip verify unicast source reachable-via ?
  any  Set RPF check to loose-mode
  rx   Set RPF check to strict-mode
  ```
  

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
vlan_interfaces:
  - name: Vlan1021
    ip_verify_unicast_source_reachable_via: "rx"
```

```
interface Vlan1021
  ip verify unicast source reachable-via rx
```

### Describe the solution you would like

```
ethernet_interfaces:
  - name: <str>
    ip_verify_unicast_source_reachable_via: < any|rx >
```

```
vlan_interfaces:
  - name: <str>
    ip_verify_unicast_source_reachable_via: < any|rx >
```

### Describe alternatives you have considered

usage of eos_cli

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by kmueller68** [comment]
@ClausHolbechArista @carlbuchmann 
Could please anyone have a look at this?
Thank you very much.

**Comment by ClausHolbechArista** [comment]
Apologies for the delay. I would cut it up a bit to make room for future additions.
```
ip_verify:
  # leaving space for "source". You don't have to implement that now.
  unicast_source:
    reachable_via: <any | rx>
    # leaving space for "allow_default" and "exception_list". You don't have to implement those now.
```
I know allow_default and exception_list could technically be put after any/rx in some nested dict, but I think this is still reasonable and easier to read/write.

Please also implement for port-channel interfaces. Thanks.
