### ISSUE TITLE
Feature(eos_cli_config_gen): Implement managing RCF

### ISSUE THREAD

**Issue by spolack** [aristanetworks/ansible-avd#2891]
### Enhancement summary

Route Control Functions getting traction to replace Route-Maps. They should be managable using eos_cli_config_gen.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

We are leveraging Arista 7280 for internet scale routing. RCF is a very powerful too to filter at the network edge.

### Describe the solution you would like

Please extend the data model and generate actual eos cli config from the data model

### Additional context

We are using a custom_template to implement that feature. Feel free to take inspiration or incorporate this into avd.

Currently we are using a custom template for eos_cli_config_gen. Feel free to take inspiration or incorporate them into avd.

```
{# interdotlink-eos - rcf #}
{% if interdotlink_rcf is arista.avd.defined %}
!
router general
   control-functions
{%     if interdotlink_rcf.code_units is arista.avd.defined %}
{%         for code_unit in interdotlink_rcf.code_units | arista.avd.natural_sort('name') %}
{%             set content = code_unit.content %}
{%             if code_unit.name is arista.avd.defined %}
{#                 strip code unit statements .. #}
{%                 set content = content | ansible.builtin.regex_replace('.*code\ unit.*', '') %}
      code unit {{ code_unit.name }}
{%             endif %}
         {{ content | indent(width=9, first=False) }}
{%             if not 'EOF' in content %}
         EOF
{%             endif %}
{%         endfor %}
{%     endif %}
   !
{% endif %}
```

Inside the structured config we use it in the following way:
```
interdotlink_rcf:
  code_units:
    - name: COMMON_BGP_POLICIES
      content: {{ lookup('template', 'templates/bgp_policies/bgp.common.rcf.j2') | to_yaml }}
    - name: INBOUND_BGP_POLICIES
      content: {{ lookup('template', 'templates/bgp_policies/bgp.inbound.rcf.j2') | to_yaml }}
    - name: OUTBOUND_BGP_POLICIES
      content: {{ lookup('template', 'templates/bgp_policies/bgp.outbound.rcf.j2') | to_yaml }}
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
