### ISSUE TITLE
Feat(eos_cli_config_gen): Add options to OSPF default_information_originate

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-avd#2895]
### Enhancement summary

Add missing options as per CLI: https://www.arista.com/en/um-eos/eos-open-shortest-path-first-version-2

Currently, only the `always` parameter is supported. Parameters to add:

- metric
- metric-type

These 2 options are supported under areas, but not under the router ospf process directly

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Need to use the unsupported parameters under `default_information_originate` key

### Describe the solution you would like

Following knob under `router_ospf`:

```yaml
default_information_originate:
  always: true
  metric: < Integer 1-65535 > # Value of the route metric
  metric_type: < 1 | 2 > # OSPF metric type
```

### Describe alternatives you have considered

-

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
