### ISSUE TITLE
Add support for PFC on interfaces for RoCE 

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#292]
**Issue Type**
- Template enhancement

**Is your feature request related to a problem? Please describe.**
Extend eos_cli_config_gen to support PFC on interfaces for RoCE 
https://www.arista.com/en/um-eos/eos-section-17-4-configuring-priority-flow-control-pfc

**Describe the solution you'd like**
suggested data model:

```yaml
ethernet_interfaces:
  priority_flow_control: < on >
  priority_flow_control_priorities:
    - priority: < 0-7 >
      enable_pfc: <true/false >
```

Update the following template: https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/eos/ethernet-interfaces.j2
