### ISSUE TITLE
Test: create eos_designs deprecated vars molecule unit test

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#2947]
Create a new molecule scenario containing all deprecated variables.

Include all variables that support convert_dicts.

Test corner case in convert_dicts with keys that have no value:
```yaml
l3leaf:
  node_groups:
    - group: DC1_LEAF1
       structured_config:
          sflow:
            vrfs:
              OOB:
                destinations:
                  192.168.200.10:
                  10.0.200.90:
```
