### ISSUE TITLE
eos_designs: storm-control rendered into ethernet instead of port-channel 

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#2963]
### Issue Summary

when using ```network_ports``` for connected_endpoints including ```port-channel```then ```storm-control``` from the port-profile is rendered into the ethernet ports but not into the port-channel:

```
interface Port-Channel91
   description MUC35-10-012_Port-Channel
   no shutdown
   switchport
   switchport trunk allowed vlan 502,507,512,517,522,527,532,537,542,557,562,567,572,577,582,597,1810, 2210,2510,2810,3400-3404,4011
   switchport mode trunk
   
 interface Ethernet91
   description MUC35-10-012
   no shutdown
   channel-group 91 mode active
   storm-control broadcast level 0.5
   storm-control multicast level 0.5
   storm-control unknown-unicast level 0.5
!
```

I am using ```structured_config```in the port-profile, because if I use it "native" the ```eos_designs``` schema is warning that the value for level is not of type int.
Therefore I have to pass it through to the ```eos_cli_config_gen``` role.
 
```
port_profiles:
  PP-TRUNK:
    mode: trunk
    structured_config:
      storm_control:
        broadcast:
          level: 0.5
          unit: percent
        multicast:
          level: 0.5
          unit: percent
        unknown_unicast:
          level: 0.5
          unit: percent
```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce
use the following :

```shell
port_profiles:
  PP-TRUNK:
    mode: trunk
    structured_config:
      storm_control:
        broadcast:
          level: 0.5
          unit: percent
        multicast:
          level: 0.5
          unit: percent
        unknown_unicast:
          level: 0.5
          unit: percent

network_ports:
  - switches:
      - access-10-011-01
    description: l2-switch
    endpoint_ports:
      - Gig1/0/14
    switch_ports:
      - Ethernet91
    profile: PP-TRUNK
    vlans: "502,507,512,517,522,527,532,537,542,557,562,567,572,577,582,597,1810,
          2210,2510,2810,3400-3404,4011"
    port_channel:
      description: Port-Channel
      mode: 'active'
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
