### ISSUE TITLE
Feat(eos_designs): MLAG same_subnet algorithm allowing for /31 reuse

### ISSUE THREAD

**Issue by haylinmoore** [aristanetworks/ansible-avd#2964]
### Enhancement summary

The ability to specify a /31 to be used for all MLAG links allowing for reduced address space utilization across a large network

### Which component of AVD is impacted

eos_designs

### Use case example

Due to the local only nature of the VLAN ip addresses used for MLAG they can be freely reused across a network to not take-up limited the RFC1918 (or other local IP blocks). 

### Describe the solution you would like

```
fabric_ip_addressing:
  mlag:
    algorithm: "same_subnet"
 l3leaf:
  defaults:
    mlag_peer_ipv4_pool: 10.255.1.0/31 
    mlag_peer_l3_ipv4_pool: 10.255.1.2/31
```

### Describe alternatives you have considered

Using ip_addressing to change the J2 template for mlag IP addressing to a set /31 pair
```
ip_addressing:
    mlag_ip_primary: <path to J2 template - default inherited from templates.ip_addressing.mlag_ip_primary >
    mlag_ip_secondary: <path to J2 template - default inherited from templates.ip_addressing.mlag_ip_secondary >
    mlag_l3_ip_primary: <path to J2 template - default inherited from templates.ip_addressing.mlag_l3_ip_primary >
    mlag_l3_ip_secondary: <path to J2 template - default inherited from templates.ip_addressing.mlag_l3_ip_secondary >
```

### Additional context

With the addition of #2946 it will make implementation of extra MLAG addressing schemes quite simple

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
