### ISSUE TITLE
Feat(eos_designs): add BGP prefix-list support for peer_groups

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#2968]
### Enhancement summary

One can specify a BGP prefix-list for a discrete BGP neighbor IPv4/IPv6 address

From:
https://avd.sh/en/stable/roles/eos_designs/doc/network-services.html

```yaml
bgp_peers:
  < IPv4_address or IPv6_address >:
    prefix_list_in: < prefix_list_name >
    prefix_list_out: < prefix_list_name >
```

But there is no such setting for a BGP peer-group, only route-maps are supported:

```yaml
bgp_peer_groups:
  - name: < BGP peer group name >
    route_map_out: < route-map name >
    route_map_in: < route-map name >
```

As the prefix-list must be set under each address-family for the peer group this should be honored in the YAML data model.

From `eos_cli_config_gen`

```yaml
router_bgp:
  address_family_ipv4:
    peer_groups:
      < peer_group_name >:
        prefix_list_in: < prefix_list_name >
        prefix_list_out: < prefix_list_name >
```

### Which component of AVD is impacted

eos_designs

### Use case example

Allow only certain inbound route updates towards the fabric from a remote edge network.

Allow only certain outbound route updates to a neighbor network

### Describe the solution you would like

```yaml
bgp_peer_groups:
  - name: < BGP peer group name >
    address_family_ipv4:
      prefix_list_in: < prefix_list_name >
      prefix_list_out: < prefix_list_name >  
      route_map_out: < route-map name >
      route_map_in: < route-map name >
    address_family_ipv6:
      prefix_list_in: < prefix_list_name >
      prefix_list_out: < prefix_list_name >  
      route_map_out: < route-map name >
      route_map_in: < route-map name >
```

**NOTE** - EOS supports also setting a route-map and prefix-list on the global level for the BGP peer-group - so this should also still be vaild. This is also the case for the current implementation of the per peer-group route-map support in eos_designs.

```bash
router bgp 65103
   router-id 10.0.254.7
   no bgp default ipv4-unicast
   distance bgp 20 200 200
   graceful-restart restart-time 300
   graceful-restart
   maximum-paths 4 ecmp 4
   neighbor IPv4-OUTSIDE-PEER peer group
   neighbor IPv4-OUTSIDE-PEER local-as 65000 no-prepend replace-as
   neighbor IPv4-OUTSIDE-PEER route-map RM-Tenant_MU_DC_OUTSIDE-LAN-CORE-RESPECT-GSHUT-IN in
   neighbor IPv4-OUTSIDE-PEER send-community
   neighbor IPv4-OUTSIDE-PEER maximum-routes 12000
```

### Describe alternatives you have considered

use eos_cli_config_gen syntax to append my settings to eos_designs

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
