### ISSUE TITLE
Feat(eos_designs): add PoE interface configuration knobs to adapter_config data model

### ISSUE THREAD

**Issue by jrecchia1029** [aristanetworks/ansible-avd#2974]
### Enhancement summary

Add the eos_cli_config_gen [`ethernet_interface.poe`](https://avd.sh/en/devel/roles/eos_cli_config_gen/docs/Input%20Variables.html#ethernet-interfaces) key to the adapter_config data model so users do not need to input this info under the `structured_config` key in the adapter_config data model.

### Which component of AVD is impacted

eos_designs

### Use case example

If I'm configuring poe settings for interfaces on my access switches in my campus, there are certain times where I'll want to configure PoE settings for the interface.

### Describe the solution you would like

Add eos_cli_config_gen's `ethernet_interface.poe` dictionary to the keys defined under eos_design's adapter_config data model

```
<connected_endpoints_keys.key>:
  - name: <name>
     adapter:
       - poe:
            disabled: <bool>
            priority: "critical", "high", "medium", "low" 
            reboot: 
              action: "maintain", "power-off"
            link_down:
              action: "maintain", "power-off"
              power_off_delay: 1-86400
            shutdown:
              action: "maintain", "power-off"
            limit:
              class: 0-8
              watts: <int>
              fixed: <bool>
            negotiation_lldp: <bool>
            legacy_detect: <bool>
``` 

### Describe alternatives you have considered

You can just use the `structured_config` under the adapter_config data model.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
