### ISSUE TITLE
Feat(eos_cli_config_gen): add global logging event storm-control

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#2993]
### Enhancement summary

global logging event for storm-control is the only one being disabled by default in eos.
Add this global configuration option to eos_cli_config_gen to be able to enable it.

```
access#show run all | i logging event
no logging event storm-control discards global
no logging event storm-control discards interval
default logging event congestion-drops
logging event port-channel member-status global
no logging event login root
logging event link-status global
logging event spanning-tree global
logging event flowcontrol received syslog interval 10 seconds
```

```
access(config)#logging event ?
  congestion-drops  Drops due to congestion
  flowcontrol       Configure syslogging for flowcontrol
  link-status       UPDOWN messages
  login             Login activities
  port-channel      Configure port-channel messages
  spanning-tree     Spanning tree messages
  storm-control     Configure storm-control

access(config)#logging event storm-control ?
  discards  Discards due to storm control

access(config)#logging event storm-control discards ?
  global    Configure global storm control discard logging
  interval  Logging interval
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
logging:
  event:
    - storm_control_discards:
      enable: true
      interval: 10
```
```
logging event storm-control discards global
logging event storm-control discards interval 10
```

### Describe the solution you would like

```
logging:
  event:
    - storm_control_discards:
      enable: <bool>
      interval: <int>
```

should render the following cli:
```
logging event storm-control discards global
logging event storm-control discards interval <int>
```

### Describe alternatives you have considered

use of eos_cli

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I think you have a typo in your data model
```yaml
logging:
  event:
    storm_control_discards:
      enable: <bool>
      interval: <int>
```

Thanks
