### ISSUE TITLE
Using vault variable generates "is undefined" error

### ISSUE THREAD

**Issue by robobeaver6** [aristanetworks/ansible-avd#2995]
### Issue Summary

Using a variable `vault_tacacs_key`  in a vault.yml file, the task `TASK [arista.avd.eos_cli_config_gen : Generate eos intended configuration]` throws a key is undefined error:

```
fatal: [loynspine4 -> localhost]: FAILED! => 
  msg: '{''hosts'': [{''host'': ''192.168.1.100'', ''vrf'': ''MGMT'', ''key'': ''{{ vault_tacacs_key }}'', ''key_type'': ''7''}]}: ''vault_tacacs_key'' is undefined'
```
but a debug task shows the variable is defined.

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

set the vault secret with `ansible-vault edit ./inventory/prod/secrets/vault.yml`
inventory/prod/secrets/vault.yml
```yaml
---
vault_tacacs_key: "DUMMY_TACACS_KEY"
```
inventory/prod/inventory.yml
```yaml
all:
  children:
    FABRIC:
      ...
```
inventory/prod/group_vars/FABRIC.yml
```yml
tacacs_servers:
  hosts:
    - host: "192.168.1.100"
      vrf: MGMT
      key: "{{ vault_tacacs_key }}"
      key_type: "7"
```
playbook/build.yml
```yml
---
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: FABRIC
  connection: local
  gather_facts: false
  debugger: on_failed
  collections:
    - arista.avd
    - arista.cvp
  vars_files:
    - "{{inventory_dir}}/secrets/vault.yml"

  tasks:
    - name: 'reset local folders for output'
      import_role:
        name: arista.avd.build_output_folders

    - name: generate intended variables
      import_role:
        name: arista.avd.eos_designs

    - name: debug tacacs key
      debug:
        msg: "DEBUG CHECK vault_tacacs_key: {{ vault_tacacs_key }}"

    - name: generate device intended config and documentation
      import_role:
        name: eos_cli_config_gen
```
running the playbook I can see the vault is being unlocked and the variable prints the key in the debug
I get the output:
```
TASK [debug tacacs key] *************************************************************************************************************************************
ok: [loynspine4] => 
  msg: 'DEBUG CHECK vault_tacacs_key: DUMMY_TACACS_KEY'

...
...
...

TASK [arista.avd.eos_cli_config_gen : Generate eos intended configuration] **********************************************************************************
fatal: [hostname-> localhost]: FAILED! => 
  msg: '{''hosts'': [{''host'': ''192.168.1.100'', ''vrf'': ''MGMT'', ''key'': ''{{ vault_tacacs_key }}'', ''key_type'': ''7''}]}: ''vault_tacacs_key'' is undefined'
```
It stops on the debugger, and I can print the `vault_tacacs_key` variable.
```
[hostname] TASK: arista.avd.eos_cli_config_gen : Generate eos intended configuration (debug)> vars()["task_vars"]["vault_tacacs_key"]
'DUMMY_TACACS_KEY'
```
so the key is defined, but something is not looking in the right place.  This worked prior to upgrading to 4.1.0.

setting the variable in the FABRIC.yml works, but is not secure.
```


### Relevant log output

_No response_

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Thank you for your thorough report.
I believe this issue is related to #2711, so the problem is likely how you input the variables as play-vars. If you could run an `include_vars` task instead, including your vaulted file, I believe it should work.

**Comment by robobeaver6** [comment]
Thanks Claus, that worked 

```  
  # vars_files:
  #   - "{{inventory_dir}}/secrets/vault.yml"

  tasks:
    - name: Include Vault Vars to workaround bug
      ansible.builtin.include_vars:
        file: "{{inventory_dir}}/secrets/vault.yml"
```
now sees the vars.
