### ISSUE TITLE
Synchronize schema for ospf area type in between eos_designs and eos_cli_config_gen

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#2996]
### Issue Summary

Schema type for ```ospf area``` should be the same in role ```eos_designs```and ```eos_cli_congi_gen```.
It is currently ```<int>```versus ```<str>```.

eos_designs:
```
<network_services_keys.name>:
  - name: <str>
    vrfs:
      - name: <str>
        l3_interfaces:
          - interfaces:
            <snip>
            ospf:
              area: <int>
```

eos_cli_config_gen:
```
ethernet_interfaces:
  - name: <str>
  <snip>
    ospf_area: <str>
```

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Relevant log output

```shell
[WARNING]: [KHM-LEAF-202]: 'Validation Error: tenants[0].vrfs[0].l3_interfaces[0].ospf.area': '0.0.0.5' is not of type 'int'
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
