### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for OSPF Process `eos_cli` Escape Hatch

### ISSUE THREAD

**Issue by jrecchia1029** [aristanetworks/ansible-avd#3009]
### Enhancement summary

Similar to BGP defaults, add a key for `ospf_defaults` whose value will be a list of eos cli statements to be configured under an OSPF process ID. 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

This is relevant when a user wants to add some OSPF configuration under a process ID used for underlay routing which isn't covered by the existing **eos_cli_config_gen** `router_ospf` data model.

### Describe the solution you would like

A data model similar to BGP defaults

```
router_ospf:
  process_ids:
    - id: <int>
      ospf_defaults:
        - <eos-cli-command-1>
        - <eos-cli-command-2>
        ...
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
