### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for IPv6 Helper Addresses on VLAN interfaces

### ISSUE THREAD

**Issue by jrecchia1029** [aristanetworks/ansible-avd#3010]
### Enhancement summary

Add support for configuring ipv6_helper addresses on VLAN interfaces.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

It may be necessary to add IPv6 helper addresses in campus networks that use IPv6.

### Describe the solution you would like

Add the `ipv6_helpers` key and values to the supported keys under **eos_cli_config_gen's** `vlan_interfaces` data model.

```
vlan_interfaces:
  - name: <str>
    ipv6_helpers:
      -  ip_helper: <str>
         link_address: <str>
         local_interface: <str>
         source_address: <str>
         vrf: <str>
```

### Describe alternatives you have considered

The `eos_cli` key in the `vlan_interfaces` dictionary is a current way to configure this.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
