### ISSUE TITLE
dualstack support for underlay

### ISSUE THREAD

**Issue by afischer1-godaddy** [aristanetworks/ansible-avd#3014]
### Enhancement summary

Currently there is only the option to use an RFC5549 based IPv6 only underlay OR an IPv4 only underlay. Both address families together as dualstack (IPv4+IPv6) underlay is not natively supported as of now.

### Which component of AVD is impacted

eos_designs

### Use case example

Many DCs started with an access-distribution-core setup and a single routing table which is fine for a small environment but hit scale limits when growing. For uplifting such networks to modern design but sticking with the single routing table (with IPv4+IPv6) without any VRFs the option for a dual stack underlay would come in handy.

### Describe the solution you would like

With the following set I would expect both IPv4 and IPv6 underlay to be present in the config:
```yaml
underlay_ipv6: true

# for the individual roles of devices
uplink_ipv4_pool: <IPv4-subnet>
uplink_ipv6_pool: <IPv6-subnet> # or a link-local alternative
```
This would result in interface config with IPv4 and IPv6 addresses + BGP sessions for IPv4 and IPv6 carrying only their address families prefixes. This does not involve any overlays.

### Describe alternatives you have considered

Before trying to mess with `uplink_structured_config` and `custom_structured_configuration` using a single overlay comes to mind but would make it a more than necessary complex setup.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
