### ISSUE TITLE
[eos_cli_config_gen] add support for ftp/tftp/telnet client source interface

### ISSUE THREAD

**Issue by mkurjanski** [aristanetworks/ansible-avd#3031]
### Enhancement summary

Need an input var data model added for the commands below:

```
ip ftp client source-interface <int_name> vrf <vfr_name>
ip tftp client source-interface <int_name> vrf <vfr_name>
ip telnet client source-interface <int_name> vrf <vfr_name>
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

The mentioned commands should be supported so we can have config lines generated in a proper order.

### Describe the solution you would like

```
ip_ftp_client_source_interfaces:
  - name: < str >
    vrf: < str >

ip_tftp_client_source_interfaces:
  - name: < str >
    vrf: < str >

ip_telnet_client_source_interfaces:
  - name: < str >
    vrf: < str >
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
