### ISSUE TITLE
[eos_cli_config_gen] aaa_accounting.exec.[console, default] missing boolean logging

### ISSUE THREAD

**Issue by nnbruce** [aristanetworks/ansible-avd#3045]
### Enhancement summary

I would like to see support in eos_cli_config_gen for below commands

```
aaa accounting exec console start-stop logging
aaa accounting exec default start-stop logging
```

Ansible validation error

`
TASK [arista.avd.eos_cli_config_gen : Generate eos intended configuration] **********************************************************************************************************
ERROR! [dc3-leaf1]: 'Validation Error: aaa_accounting.exec.console': Unexpected key(s) 'logging' found in dict.
ERROR! [dc3-leaf1]: 'Validation Error: aaa_accounting.exec.default': Unexpected key(s) 'logging' found in dict.
`

```
aaa_accounting:
  exec:
    console:
      type: start-stop
      logging: true # Missing in data model but possible to configure in EOS
    default:
      type: start-stop
      logging: true # Missing in data model but possible to configure in EOS
  commands:
    console:
      - commands: all
        type: start-stop
        logging: true # Implemented in data model and schema
    default:
      - commands: all
        type: start-stop
        logging: true # Implemented in data model and schema
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Being able to use eos_cli_config_gen to generate aaa accounting exec command and using syslog as the logging destination instead of tacacs+ or radius

### Describe the solution you would like

Same behavior as aaa_accounting.commands[console, default] currently have, with support for boolean `logging`

### Additional context

Test ran on AVD 4.1.0

Docs used https://avd.sh/en/stable/roles/eos_cli_config_gen/docs/input-variables.html#aaa-accounting

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
