### ISSUE TITLE
Duplicate BGP neighbor interfaces with rfc5549 and multiple uplinks

### ISSUE THREAD

**Issue by bjmeuer** [aristanetworks/ansible-avd#3053]
### Issue Summary

When using rfc5549 and having multiple uplinks from one leaf to one spine there is an issue that in the structured config in the section `router_bgp.neighbor_interfaces` there will be duplicates.

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Input:

---
type: l3leaf

l3leaf:
  defaults: 
    # UPLINK MANAGEMENT 
    uplink_switches: ['cong-pnet-spn101', 'cong-pnet-spn102', 'cong-pnet-spn101', 'cong-pnet-spn102']
    uplink_interfaces: ['Ethernet49/1', 'Ethernet50/1','Ethernet51/1', 'Ethernet52/1']
    ...
  node_groups:
    - group: BiLeaf1
      bgp_as: 65101 
      nodes:
        - name: cong-pnet-lea101
          id: 3
          ...
          uplink_switch_interfaces: ['Ethernet10/1', 'Ethernet10/1', 'Ethernet16/1', 'Ethernet16/1']

```
```


### Relevant log output

```shell
Output in structured config of cong-pnet-spn101:


router_bgp:
  as: '65001'
  ...
  neighbor_interfaces:
  - name: Ethernet10/1
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    description: cong-pnet-lea101_Ethernet49/1
  - name: Ethernet10/1
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    description: cong-pnet-lea101_Ethernet49/1
  - name: Ethernet16/1
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    description: cong-pnet-lea101_Ethernet51/1
  - name: Ethernet16/1
    peer_group: IPv4-UNDERLAY-PEERS
    remote_as: '65101'
    description: cong-pnet-lea101_Ethernet51/1
```
```


### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
