### ISSUE TITLE
eos_designs: EVPN vlan-aware-bundle option for l2vlan

### ISSUE THREAD

**Issue by bjmeuer** [aristanetworks/ansible-avd#3065]
### Enhancement summary

To be able to use vlan-aware-bundles and having different names for l2vlans a new option for l2vlans should be introduced. With this every l2vlan could have a speaking name for the purpose of the VLAN and can be bundled into a EVPN vlan-aware-bundle to simplify the configuration.

### Which component of AVD is impacted

eos_designs

### Use case example

I want to define l2vlans with a speaking name which is different for ever VLAN, but want to combine some of those l2vlans into one EVPN vlan-aware-bundle. The combination into vlan-aware-bundles keeps the configration simple and smaller. 

### Describe the solution you would like

Introduce a new option for l2vlans, for example "evpn_vlan_bundle". All l2vlans where the same "evpn_vlan_bundle" is defined should be combined into a vlan-aware-bundle in case the global option for vlan-aware-bundles is enabled.

```
    l2vlans:
      - id: 10
        name: vmotion
        evpn_vlan_bundle: VmBundle
      - id: 20
        name: VmBackup   
        evpn_vlan_bundle: VmBundle
      - id: 30
        name: storageDate
        evpn_vlan_bundle: StorageBundle
      - id: 40
        name: storageBackup   
        evpn_vlan_bundle: StorageBundle
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
