### ISSUE TITLE
Feat(eos_cli_config_gen): add headend-replication key to vxlan_interface.Vxlan1 dict

### ISSUE THREAD

**Issue by natedoot** [aristanetworks/ansible-avd#3095]
### Enhancement summary

New key under vxlan_interface.Vxlan1 dict to support EVPN Multicast with HER implementation

TOI: [EVPN Multicast with HER](https://www.arista.com/en/support/toi/eos-4-30-0f/16897-evpn-multicast-with-her)
 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Example EOS Config:
```
!
interface Vxlan1
   description A-LEAF1_VTEP
   vxlan source-interface Loopback0
   vxlan virtual-router encapsulation mac-address mlag-system-id
   vxlan udp-port 4789
   vxlan vlan 10 vni 10010
   vxlan vrf A vni 50001
   vxlan multicast headend-replication <--- new 
!
```

### Describe the solution you would like

Update data model with `multicast_headend_replication` boolean key
```
keys:
  vxlan_interface:
    type: dict
    keys:
      Vxlan1:
        type: dict
        keys:
          description:
            type: str
          vxlan:
            type: dict
            keys:
              multicast_headend_replication:
                type: bool
```
Update vxlan-interface j2 template
```
{%     if vxlan_interface.Vxlan1.vxlan.multicast_headend_replication is arista.avd.defined(true) %}
   vxlan multicast headend-replication
{%     endif %}
```
input var example
```
vxlan_interface:
  Vxlan1:
    vxlan: 
      multicast_headend_replication: <bool>
```

### Describe alternatives you have considered

eos_cli under `vxlan_interface.Vxlan1` works but is not ideal.

### Additional context

Once this key is added to `eos_cli_config_gen`, `eos_designs` enhancement should be opened to support the remaining multicast/evpn configuration listed in the TOI. Similar to `evpn_multicast` key.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
