### ISSUE TITLE
Knob to enable/disable overlay iBGP peering per VRF

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#311]
**Issue Type**
- Template enhancement

**Is your feature request related to a problem? Please describe.**
By default we have to reserve a VLAN range for any number of VRFs defined in overlay, and this will trigger configuration of a dedicated VLAN with P2P and iBGP for each VRF. However this requirement is not the common use case. Most of the services that use VRF multi-tenancy do not have routing requirements (static route/BGP to external Firewall or Router).

With this we do not waste a VLAN for each VRF that is present and there is no such requirement for routing in the VRF. Imagine having 400 VRFs, where we have to reserve 400 VLANs from a pool just for this.

**Describe the solution you'd like**
To have a knob to enable this per VRF, example you have 400 VRFs, and only 10 VRFs have routing in them with single-homed hosts etc. You would like 390 VRFs not to have iBGP config so we do not waste 390 VLANs for this.

**Describe alternatives you've considered**
Disable this in tenants, and static configuration.

**Additional context**

```yaml
# On mlag leafs, an SVI interface is defined per vrf, to establish iBGP peering. | Required (when mlag leafs in topology)
# The SVI id will be derived from the base vlan defined: mlag_ibgp_peering_vrfs.base_vlan + vrf_vni
mlag_ibgp_peering_vrfs:
  base_vlan: < 1-4000 | default -> 3000 >

# Dictionary of tenants, to define network services: L3 VRFs and L2 VLNAS.

tenants:

  # Specify a tenant name. | Required
  # Tenant provide a construct to group L3 VRFs and L2 VLANs.
  # Networks services can be filtered by tenant name.
  < tenant_a >:
  **(knob to enable VLAN reservation to be used as p2p over peer-link for iBGP)**
```
