### ISSUE TITLE
Fix(eos_designs): incorrectely adds mtu 9214 for Mlag interface Vlan4094 on CCS-722/750

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#3123]
> [!NOTE]
> 09/07/2025 - @gmuloc 
> Now tracks:
>
> Making sure the default platforms in AVD properly tracks the 722/750 platforms for per-interface MTU support by setting properly the feature knob
> https://github.com/aristanetworks/avd/issues/3123#issuecomment-1727407040

### Issue Summary

switch models 722 and 750 do not support MTU settings per interface, but only global.

for example:
eos_designs adds `mtu 9214` to MLAG peer-interface VLAN4094, which is not supported on these platforms.

It throws an error message and MLAG will stay inactive.

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
just render mlag setting and push ist against two CCS-750/722 switches.
```

### Relevant log output

```shell
interface Vlan4094
   description MLAG_PEER
   mtu 9214
   no autostate
   ip address 172.29.31.82/31
```

```
access-04-111-01.LAN.MU__14:23:34(config-if-Vl4094)#mtu 9214% Unavailable command (not supported on this hardware platform)
```

```
domain-id                          :   ACCESS-04-111_01_02
local-interface                    :              Vlan4094
peer-address                       :          172.29.31.83
peer-link                          :        Port-Channel51
peer-config                        :

MLAG Status:
state                              :              Inactive
negotiation status                 :            Connecting
peer-link status                   :                    Up
local-int status                   :                    Up
system-id                          :     00:00:00:00:00:00
dual-primary detection             :              Disabled
dual-primary interface errdisabled :                 False
```
```


### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I guess we should set the global mtu setting instead, to whatever value we have in `p2p_uplinks_mtu`.

**Comment by ClausHolbechArista** [comment]
@kmueller68 thinking more about this, if the devices only support a single MTU value, it would lead to user SVIs also using the global value, which may not be the intention.
I can implement a knob under the platform settings for this, but I am not sure how we should decide on which MTU to set as global.

**Comment by kmueller68** [comment]
@ClausHolbechArista I know about a similar topic, because I ran into the same on platforms of another vendor.
It has been a challenge to first set the mtu globally to 9xxx and then reduce each single svi interface back to mtu=1500.

But even this would not work on 750/722 since we would never be able to set mtu back to 1500 on single interfaces.

But in this case, we are talking about MLAG control plane traffic between MLAG peers only.
There will never be sent any user data traffic between Vlan4094 interfaces, right?

Ethernet mtu by default is 9214 on 750/722.
So, switched traffic accross MLAG peerlink supports jumboframes anyways.

Why are you currently setting the mtu for MLAG control plane svi Vlan4094 to `p2p_uplinks_mtu`?
Is there a technical case, which I didnt get so far?
I have not found anything in the manual that MLAG peer svi mandatory needs to have jumboframes enabled.

This would mean, that we could leave Vlan4094 mtu at 1500.

I see only one usecase to increase the global mtu on 750/722 to jumboframes:
If 750/722 are part of an EVPN fabric as MLAG l3leafs and have overlay iBGP peering in the vrfs.

What is your opnion on this?

**Comment by ClausHolbechArista** [comment]
> Why are you currently setting the mtu for MLAG control plane svi Vlan4094 to p2p_uplinks_mtu?

I don't know the history of why, but I agree it should not be required as long as you don't have transit traffic on that SVI (it is possible to reuse the same SVI for iBGP).

I am working on a fix that implements these schema changes for eos_designs:

```yaml
keys:
  platform_settings:

<snip>

        feature_support:
          type: dict
          keys:
            per_interface_mtu:
              type: bool
              default: true
              description: |
                Disables configuration of per interface MTU for p2p links, MLAG SVIs and Network Services.
                Effectively this means that all settings regarding inteface MTU will be ignored.
                Platforms without support for per interface MTU can use a single default interface MTU setting. Set this via "default_interface_mtu"

<snip>

  default_interface_mtu:
    documentation_options:
      table: system-settings
    type: int
    convert_types:
      - str
    description: Default interface MTU configured on EOS under "interface defaults"
    min: 68
    max: 65535
```

In the above I have only allowed `default_interface_mtu` as a root key, and not under the `platform_settings`, but maybe I should add it there too.

**Comment by kmueller68** [comment]
I think that it would be good to have it under `plattform_settings` too.

Is it intened that the default platform settings are not shown in the avd.sh documentation or did I miss it anywhere else?
https://avd.sh/en/stable/roles/eos_designs/docs/tables/platform-settings.html?h=platform_settings

**Comment by ClausHolbechArista** [comment]
Ok, I can add it under platform settings too.
It was too big to fit into the docs, so we opted for an alternative approach with the tooling at hand.
![image](https://github.com/aristanetworks/ansible-avd/assets/48674677/4a439c0d-0bc0-4293-826a-4c94229a162e)
![image](https://github.com/aristanetworks/ansible-avd/assets/48674677/f7e89d86-1d19-4e93-8984-f721ef3c853f)

**Comment by ClausHolbechArista** [comment]
We need to figure out if we can change the default values now, or just provide the knobs, so you can change them yourself. It depends a bit if these mtu restrictions cover all devices under 722XP and 750X. @carlbuchmann @mpergament

**Comment by mpergament** [comment]
![image](https://github.com/aristanetworks/ansible-avd/assets/13856387/c02fcc10-1c29-4947-95ff-9ecc601a7a01)

**Comment by ClausHolbechArista** [comment]
@kmueller68 I have submitted #3128 to allow setting the things needed here, but I am reluctant to change the default platform settings, so I hope you can build it out yourself based on my PR. Please let me know if everything works in there, or if you find issues. Thanks.

**Comment by kmueller68** [comment]
@ClausHolbechArista thank you so much! 🙏 I will test it with the production repo tomorrow and give you feedback.

**Comment by kmueller68** [comment]
@ClausHolbechArista 
I have tested your PR with the following config.

question:
When I am setting this mtu things for 722XP it is appended to the default platform_settings, right?
It is not deleting any of the default settings?

LAN_ACCESS.yml
```
# special mtu settings for 722xpm switches supporting global mtu only
platform_settings:
  - platforms:
    - 722XP
    default_interface_mtu: 8000
    feature_support:
      per_interface_mtu: false
```
LAN_POD_08.yml
```
    ACCESS-04-111_01_02:
      platform: 722XP
      mlag_interfaces: "{{ mlag_interfaces_access_48 }}"
      uplink_interfaces: "{{ uplink_interfaces_access_48_mlag }}"
      uplink_switch_interfaces: ['Ethernet25']
      nodes:
        access-04-111-01.LAN.MU:
          id: 42
          # disabled to avoid generation of oob config
          # mgmt_ip: x.x.x.x/24
          uplink_switches: ['distri-08-01.LAN.MU']

        access-04-111-02.LAN.MU:
          id: 43
          # disabled to avoid generation of oob config
          # mgmt_ip: x.x.x.x/24
          uplink_switches: ['distri-08-02.LAN.MU']
```

gives me the following cli config for the two switches:
```
!
interface defaults
   mtu 8000
!
```

**Comment by ClausHolbechArista** [comment]
> question:
When I am setting this mtu things for 722XP it is appended to the default platform_settings, right?
It is not deleting any of the default settings?

Unfortunately it replaces the default platform_settings, so you have to copy the defaults (the big dictionary you can find in the docs using the (+) on the YAML page) and then add your extra setting.

Hopefully your changes should also show removal of the MTU under the interfaces, so the MLAG issue goes away.

**Comment by kmueller68** [comment]
@ClausHolbechArista 
I am sorry... I am currently to stupid to add it to the default platform_settings.

Where would you add the following?
```
- platforms:
  - 722XP
  default_interface_mtu: 8000
  feature_support:
    per_interface_mtu: false
 ```

**Comment by ClausHolbechArista** [comment]
:)

Please try to add this to the fabric group vars file:
```yaml
platform_settings:
# Custom platform settings
- platforms:
  - 722XP
  default_interface_mtu: 8000
  feature_support:
    per_interface_mtu: false
    queue_monitor_length_notify: false
  reload_delay:
    mlag: 300
    non_mlag: 330
  trident_forwarding_table_partition: flexible exact-match 16384 l2-shared 98304 l3-shared
    131072
# DEFAULT ENTRIES copied from docs
- feature_support:
    queue_monitor_length_notify: false
  platforms:
  - default
  reload_delay:
    mlag: 300
    non_mlag: 330
- feature_support:
    queue_monitor_length_notify: false
  platforms:
  - 7050X3
  - 720XP
  - 722XP
  reload_delay:
    mlag: 300
    non_mlag: 330
  trident_forwarding_table_partition: flexible exact-match 16384 l2-shared 98304 l3-shared
    131072
- lag_hardware_only: true
  platforms:
  - 7280R
  - 7280R2
  - 7020R
  reload_delay:
    mlag: 900
    non_mlag: 1020
  tcam_profile: vxlan-routing
- platforms:
  - 7280R3
  reload_delay:
    mlag: 900
    non_mlag: 1020
- lag_hardware_only: true
  management_interface: Management0
  platforms:
  - 7500R
  - 7500R2
  reload_delay:
    mlag: 900
    non_mlag: 1020
  tcam_profile: vxlan-routing
- management_interface: Management0
  platforms:
  - 7500R3
  - 7800R3
  reload_delay:
    mlag: 900
    non_mlag: 1020
- management_interface: Management0
  platforms:
  - 7368X4
  reload_delay:
    mlag: 300
    non_mlag: 330
- management_interface: Management0
  platforms:
  - 7300X3
  reload_delay:
    mlag: 1200
    non_mlag: 1320
  trident_forwarding_table_partition: flexible exact-match 16384 l2-shared 98304 l3-shared
    131072
- feature_support:
    bgp_update_wait_for_convergence: false
    bgp_update_wait_install: false
    interface_storm_control: false
    queue_monitor_length_notify: false
  platforms:
  - VEOS
  - VEOS-LAB
  - vEOS
  - vEOS-lab
  reload_delay:
    mlag: 300
    non_mlag: 330
- feature_support:
    bgp_update_wait_for_convergence: false
    bgp_update_wait_install: false
    interface_storm_control: false
    queue_monitor_length_notify: false
  management_interface: Management0
  platforms:
  - CEOS
  - cEOS
  - ceos
  - cEOSLab
  reload_delay:
    mlag: 300
    non_mlag: 330

```
