### ISSUE TITLE
Remove vrf_id integer limit

### ISSUE THREAD

**Issue by karnag3** [aristanetworks/ansible-avd#3132]
### Enhancement summary

The vrf_id key as defined in defs_network_services.schema.yml has a max value of 1024.  Since vrf_id can be used to populate the rd/rt this can be used to help generate config if not limited to 1024.

### Which component of AVD is impacted

eos_designs

### Use case example

```
tenants:
  # Tenant A Specific Information - VRFs / VLANs
  TENANT-A:
    mac_vrf_vni_base: 1000000
    vrfs:
      PROD:
        vrf_id: 41000
```

### Describe the solution you would like

In eos_designs in the defs_network_services.schema.yml remove the `max: 1024` value for `vrf_id`

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
