### ISSUE TITLE
Fix(eos_designs): Raise error when interface range is incorrect

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#3161]
### Issue Summary

For example when leveraging the default interface and inputting incorrect range `Ethernet51-3/1` vs. `Ethernet51-53/1`
range, it fails silently 

Example incorrect input:

```yaml
default_interfaces:
  - types: [ spine ]
    platforms: [ vEOS-LAB ]
    downlink_interfaces: [ Ethernet1-6/1 ]
  - types: [ l3leaf ]
    platforms: [ vEOS-LAB ]
    uplink_interfaces: [ Ethernet51-3/1 ]
```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
