### ISSUE TITLE
eos_designs: Support IP allocations using a file-backed pool manager.

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#3172]
Idea for data model
```yaml
ipv4_pools:
- ipv4_pool: "10.10.10.0/24"
  vrf: GREEN
  ip_assignments:
  - hostname: DC1-POD1-L2LEAF1A
    interface: Ethernet1/1
    ipv4: 10.10.10.10/31
- ipv4_pool: "10.10.10.0/24"
  vrf: default
  ip_assignments:
  - hostname: DC1-POD1-L2LEAF1A
    interface: Ethernet1/1
    ipv4: 10.10.10.10/31
```
