### ISSUE TITLE
eos_designs: Port-channel ID option for uplinks with type "port-channel"

### ISSUE THREAD

**Issue by bjmeuer** [aristanetworks/ansible-avd#3175]
### Enhancement summary

In some switches the autogenerated Port-channel ID in the networks services could potentially overlap with the uplink Port-channel ID. For example an Ethernet3/3 breakout port will get the same autogenerated Port-channel ID as Ethernet33 . Therefore it would be good to have two additional knobs to statically define the Port-channel IDs used for uplinks locally and on the uplink switch. 

### Which component of AVD is impacted

eos_designs

### Use case example

In some switches the autogenerated Port-channel ID in the networks services could potentially overlap with the uplink Port-channel ID. For example an Ethernet3/3 breakout port will get the same autogenerated Port-channel ID as Ethernet33 .

### Describe the solution you would like

Adding two additional knobs to statically define the Port-channel IDs used for uplinks locally and on the uplink switch. 

```
<node type>:
  defaults:
    ...
    uplink_port_channel_id: 111
    uplink_switch_port_channel_id: 222
  node_groups:
    - group: L2Leafs1
      ...
      nodes:
        - name: uplink-po-id-l2leaf-1a
          ...
          uplink_port_channel_id: 123
          uplink_switch_port_channel_id: 456
  nodes:
    - name: uplink-po-id-l2leaf-3
      ...
      uplink_port_channel_id: 333
      uplink_switch_port_channel_id: 444
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
