### ISSUE TITLE
Feat(eos_designs): add raw_eos_cli and/or structured_config to Network services point to point services settings

### ISSUE THREAD

**Issue by philippebureau** [aristanetworks/ansible-avd#3177]
### Enhancement summary

Allow to add CLI and/or structured config to VPWS services

### Which component of AVD is impacted

eos_designs

### Use case example

I am trying to add "mpls control-word" to vpws services which is not in the data model.  But this could be used for other configs

Reference documentation:
(https://avd.arista.com/4.3/roles/eos_designs/docs/tables/network-services-point-to-point-services-settings.html?h=network+services+point)

### Describe the solution you would like

```
<network_services_keys.name>:
  - name: <str>
    pseudowire_rt_base: <int>
    point_to_point_services:
      - name: <str>
        type: <str>
        subinterfaces:
          - number: <int>
        endpoints:
          - id: <int>
            nodes:
              - <str>
            interfaces:
              - <str>
            port_channel:
              mode: <str>
              short_esi: <str>
            structured_config: <dict>     <------
            raw_eos_cli: <str>            <------
```

### Describe alternatives you have considered

creating a custom_structured_configuration_eos_cli: entry per vpws service in hostvars but its very messy and will show at the end of the rendered .cfg file

hostvar_file.yml:
```
custom_structured_configuration_eos_cli: |
  router bgp 6.6971
    vpws BRANCH
      mpls control-word
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
