### ISSUE TITLE
Feat(eos_designs): Automatic VLAN to port_group assignment based on tags

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#3208]
### Enhancement summary

In larger EVPN fabrics there is a multitude of VLANs and Hypervisors. VLANs get assigned to Switches based on the `tags: ['foo']` option in the YAML definition:

```yaml
  Tenant_A:
    mac_vrf_vni_base: 10000
    vlan_aware_bundle_number_base: 5000
    l2vlans:
      600:
        name: PROJECT_A_600
        tags: ['ESX']
      601:
        name: PROJECT_B_601
        tags: ['ESX2']
```

l3ls Switches defined under the `node_groups:` support definition of `tags`  so ansible-avd knows the VLAN/VNIs a switch is interested in when rendering the configuration.

On the other hand, when downstream ports/connected endpoints are defined, `port_profiles` are referenced, e.g. `port_profile_ESX_HOSTS` and those `port_profiles`carry hand crafted VLAN IDs in the `vlans:` key. This is error prone.

A better solution would be to provide an automated way as alternative to the manually specifying the `vlans:` required.

This is an extension to the feature request specified in https://github.com/aristanetworks/ansible-avd/issues/2552

### Which component of AVD is impacted

eos_designs

### Use case example

Remove human error when deploying large range of VLAN on port groups

### Describe the solution you would like

```yaml
port_profiles:
  - profile: <str>
    parent_profile: <str>
    speed: <str>
    description: <str>
    enabled: <bool>
    vlans: <str>
    vlan_tags:  <- new
      - <str>
```

If both `vlans` and `vlan_tags` is defined, a superset is to be build when the resulting `switchport trunk allowed vlan` CLI command is built

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
