### ISSUE TITLE
Arista AVD Version - v4.3.0- Inventory is generated in different hierarchy

### ISSUE THREAD

**Issue by duddis1** [aristanetworks/ansible-avd#3210]
### Issue Summary

Arista AVD Version - v4.3.0- Inventory is generated in different hierarchy

As per the release notes the inventory config has to generated with below hierarchy:
https://avd.sh/en/stable/docs/porting-guides/4.x.x.html#supported-group-structure

The inventory config is currently generated in below hierarchy:
```
inventory.yml
all:
  children:
    RoS_FABRIC:
      children:
        LON:
          children:
            LON_FABRIC:
              children:
                LON_SERVERS:
                  children:
                    LON_IXLEAF: null
                LON_IXLEAF:
                  vars:
                    type: ixleaf
                  hosts:
                    LON-IX-SW:
                      ansible_host: 10.1.10.81/[2](https://gitlab.ros.gov.uk/srt-networks/arista-config-log/-/blob/6ea22a84e012d127069ad16948571cb45254cad4/inventory.yml#L2)4
            LON_TENANTS_NETWORKS:
              children:
                LON_IXLEAF: null
```

Below level of hierarchy is missing from the release notes, but this is needed for the config to be generated.
Can you please validate the above hierarchy whether it meets the criteria?

RoS_FABRIC:
      children:

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI with AVD Runner

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
