### ISSUE TITLE
router isis - Missing Features

### ISSUE THREAD

**Issue by Kennochas** [aristanetworks/ansible-avd#3247]
### Enhancement summary

We need to be able to set the following for Router ISIS:

set-overload-bit on-startup 300
authentication mode 
authentication key 7 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

For interop reasons, we use authentication on the ISIS stanza itself, as well as the overload bit.

### Describe the solution you would like

Something akin to this maybe?

```
router_isis:
  set_overload_bit:
    mode: on-startup
    delay: 300
  authentication:
    mode: md5
    type: 7
    key: {{ super secret key }}
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
