### ISSUE TITLE
Management SSH - Missing Features

### ISSUE THREAD

**Issue by Kennochas** [aristanetworks/ansible-avd#3248]
### Enhancement summary

We would like to be able to set:

fips restrictions
hostkey client strict-checking

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

We use these settings per compliance.

### Describe the solution you would like

Something akin to the following?
```
management_ssh:
  fips: true
  hostkey:
    client:
      strict-checking: true
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
