### ISSUE TITLE
Router BGP - Missing Features / Possibly not sure where to put them.

### ISSUE THREAD

**Issue by Kennochas** [aristanetworks/ansible-avd#3249]
### Enhancement summary

We need the following stanzas for router_bgp:

Some of these you may intend to set via BGP_defaults, but i'm not entirely sure, but it is how I am having to do it for some of these.

```
router bgp 13649
  bgp asn notation asdot
  timers bgp 5 15
  neighbor {{ neighbor }} additional-paths receive
  neighbor {{ neighbor }} additional-paths send limit 2
  neighbor {{ neighbor }} missing-policy address-family all include community-list prefix-list sub-route-map direction in action deny-in-out
  neighbor {{ neighbor }} missing-policy address-family all include community-list prefix-list sub-route-map direction in action deny-in-out
  neighbor {{ neighbor }} password 7 {{ password }}

  address-family ipv4
    redistribute connected route-map {{ routemap }}
    redistribute static route-map {{ routemap }}
  !
!
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

We presently set all of those settings, some of which are handled via bgp_defaults, some via eos_cli. We arent sure what is best.

### Describe the solution you would like

Something akin to the following, but I don't know most of this stuff. Im sure you have better ideas.

```
router_bgp:
  notation: asdot
  timers:
    min: 5
    max: 15
  additional_paths: install
  neighbors:
    - password: {{ password }}
      additional_paths:
        receive: true
        send_limit: 2
     missing_policy:
       address_family_all:
         include: community-list
         prefix-list: sub-route-map
         direction_in_action: deny-in-out
         direction_out_action: deny-in-out
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
