### ISSUE TITLE
Port Channel - Set BFD Neighbor

### ISSUE THREAD

**Issue by Kennochas** [aristanetworks/ansible-avd#3250]
### Enhancement summary

We would like to be able to set the BFD neighbor on a port-channel

```
interface Port-Channel10
   bfd neighbor {{ neighbor }}
   bfd per-link rfc-7130
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

We use this in a product offering, to setup BFD facing customers.

### Describe the solution you would like

Something akin to:

```
port_channel_interfaces:
  - bfd:
      neighbor: {{ neighbor }}
      per-link: true
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
