### ISSUE TITLE
Policy Map - QOS Policer

### ISSUE THREAD

**Issue by Kennochas** [aristanetworks/ansible-avd#3251]
### Enhancement summary

We would like to be able to create QOS policy maps:

```
policy-map type quality-of-service {{ policyname }}
  class class-default
      police rate 12000 mbps burst-size 4 mbytes
!
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

We use these for a customer product offering, where they are QOS's at a specific rate they purchase.

### Describe the solution you would like

Something akin to:

```
policy_maps:
  qos:
    class:
      - name: default
         police:
           rate: 10000 mbps
           burst: 4 mbytes
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
