### ISSUE TITLE
Feat(eos_cli_config_gen): add support for dhcp snooping

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#3257]
### Enhancement summary

Add global config commands for dhcp snooping 
https://arista.my.site.com/AristaCommunity/s/article/dhcp-snooping

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
ip dhcp snooping bridging
ip dhcp snooping information circuit-id type 2 
ip dhcp snooping vlan 1-3900
```
available cli options with eos 4.30.0F
```
access(config)#ip dhcp snooping bridging ?
  <cr>

access(config)#ip dhcp snooping information ?
  option  Configure Information Option

access(config)#ip dhcp snooping information option ?
  circuit-id  Circuit ID subopton in Option-82
  <cr>

access(config)#ip dhcp snooping information option circuit-id ?
  type  Type encoded in the Circuit ID sub-option

access(config)#ip dhcp snooping information option circuit-id type ?
  none     Do not include type in the Circuit ID sub-option
  <0-255>  Specify the type in the Circuit ID sub-option

access(config)#ip dhcp snooping vlan ?
  $         list end
  <1-4094>  VLAN ID or range(s) of VLAN IDs
```

### Describe the solution you would like

```
ip_dhcp_snooping:
  bridging: <bool> (true|false)
  information_option: <bool> (true|false)
    circuit_id_type: <integer> (0-255)
  vlan: <string> (like 10,20,500,1000-2000)
```

### Describe alternatives you have considered

use eos_cli

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Adjusting your suggested data model a bit, since you have combined a bool and a dict:
```yaml
ip_dhcp_snooping:
  enabled: <bool>
  bridging: <bool>
  information_option:
    enabled: <bool>
    circuit_id_type: <str> ("none" or 0-255) # use convert_types in schema from int.
  vlan: <string> (like 10,20,500,1000-2000) # use convert_types in schema from int.
```

**Comment by c-po** [comment]
Might it be a good idea to extend this for IPv6, too?

**Comment by kornoa** [comment]
> Might it be a good idea to extend this for IPv6, too?

Sounds reasonable. But perhaps as a separate issue/PR?

**Comment by kmueller68** [comment]
@ClausHolbechArista 
We will need to extend it with one more option `format`:
```
ip_dhcp_snooping:
  enabled: <bool>
  bridging: <bool>
  information_option:
    enabled: <bool>
    circuit_id_type: <str> ("none" or 0-255) # use convert_types in schema from int.
    circuit_id_type_format: <str> (%h:%p or %p:%v)
  vlan: <string> (like 10,20,500,1000-2000) # use convert_types in schema from int.
```

```
access#conf t
access6(config)#ip dhcp snooping information option circuit-id type 5 format %h:%p
access(config)#show run | i ip dhcp snooping
ip dhcp snooping bridging
ip dhcp snooping information option circuit-id type 5 format %h:%p
ip dhcp snooping vlan 1-4090
access(config)#ip dhcp snooping information option circuit-id type 99 format %h:%p
access0(config)#show run | i ip dhcp snooping
ip dhcp snooping bridging
ip dhcp snooping information option circuit-id type 99 format %h:%p
ip dhcp snooping vlan 1-4090
access4(config)#ip dhcp snooping information option circuit-id type 200 format %p:%v
access(config)#show run | i ip dhcp snooping
ip dhcp snooping bridging
ip dhcp snooping information option circuit-id type 200 format %p:%v
ip dhcp snooping vlan 1-4090
```
even `type none` needs a `format`:
```
access(config)#ip dhcp snooping information option circuit-id type none format %h:%p
access(config)#show run | i ip dhcp snooping
ip dhcp snooping bridging
ip dhcp snooping information option circuit-id type none format %h:%p
```
