### ISSUE TITLE
Management Interface is always required in eos_cli_config_gen

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#326]
## Issue Type

- Bug Report

## Summary

In `eos_cli_config_gen`, configuration rendering fails when `management1` is not set. But in some situation, this interface is not configured.

## Role or Module Name

- Role: `eos_cli_config_gen`

## Steps to reproduce

Use the following `intended_config` file:

```yaml
vlan_internal_order:
  allocation: ascending
  range:
    beginning: 1006
    ending: 1199
### VLANs ###
vlans:
  110:
    tenant: Tenant_A
    name: PR01-DMZ
  3010:
    tenant: Tenant_A
    name: MLAG_iBGP_TENANT_A_PROJECT01
    trunk_groups:
      - LEAF_PEER_L3
```

### Expected results

Correct EOS configuration for vlan

### Actual results

```
fatal: [vlan -> localhost]: FAILED! => {"changed": false, \
"msg": "AnsibleUndefinedVariable: 'management_interfaces' is undefined"}
```
