### ISSUE TITLE
IP Phone Support for connected_endpoints and network_ports (& associated profiles)

### ISSUE THREAD

**Issue by jonxstill** [aristanetworks/ansible-avd#3289]
### Enhancement summary

Improved support for IP phones as per:
* [https://www.arista.com/en/support/toi/eos-4-28-2f/16061-phone-vlan](https://www.arista.com/en/support/toi/eos-4-28-2f/16061-phone-vlan)
* [https://www.arista.com/en/support/toi/eos-4-22-1f/14339-phone-vlan-feature-toi](https://www.arista.com/en/support/toi/eos-4-22-1f/14339-phone-vlan-feature-toi)

### Which component of AVD is impacted

eos_designs

### Use case example

Support use cases:
* Port with phone attached, VLAN-aware or -unaware.
* Port with phone and PC attached, VLAN-aware or -unaware.
* Allow configuration of phone VLAN and PC VLAN.

### Describe the solution you would like

Simple extension to existing data model to allow addition of a phone VLAN and whether it is tagged or untagged.  `switchport mode trunk phone` is already supported.

Data model:
```
    adapters:
      - mode: "trunk phone"
        native_vlan: <int>
        # new keys below
        phone_vlan: <int>
        phone_trunk_mode: < tagged | untagged | tagged phone | untagged phone > # If omitted, EOS default is tagged
```

Desired configs:
```
! VLAN unaware phone, with or without VLAN unaware PC
! This uses MBVA
interface EthernetX
   switchport mode trunk phone
   switchport phone trunk tagged
   ! Data VLAN
   switchport trunk native vlan 100
   ! Phone VLAN
   switchport phone vlan 200

! VLAN aware phone, with or without VLAN unaware PC
interface EthernetX
   switchport mode trunk phone
   switchport phone trunk untagged
   ! Data VLAN
   switchport trunk native vlan 100
   ! Phone VLAN
   switchport phone vlan 200
```

Other configurations are possible (e.g. VLAN unaware phone, tagged data traffic, or VLAN-aware phone with standard trunk port) but less common and are combinations of the options specified above.

There are EOS-level defaults that can be set, but it feels easier and more flexible to use profiles in AVD to apply these.

### Describe alternatives you have considered

* Use `structured_config` under connected_endpoints or network_ports models.

### Additional context

AVD campus improvements.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
