### ISSUE TITLE
Make servers section optional

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#333]
## Issue Type

- Bug Report

## Summary

When `servers:` section is not defined, `eos_l3ls_evpn` fails. 

## Role or Module Name

`eos_l3ls_evpn`

## Steps to reproduce

```yaml
port_profiles:
  TENANT_B:
    mode: trunk
    vlans: "210-211"

servers:
  # server01_MLAG:
  #   rack: RackB
  #   adapters:
  #     - server_ports: [ Eth2, Eth3 ]
  #       switch_ports: [ Ethernet10, Ethernet10 ]
  #       switches: [ DC1-LEAF2A, DC1-LEAF2B ]
  #       profile: TENANT_B
  #       port_channel:
  #         state: present
  #         description: PortChanne1
  #         mode: active

```
