### ISSUE TITLE
Enable IPv6 for l3_interfaces

### ISSUE THREAD

**Issue by p-rintz** [aristanetworks/ansible-avd#3331]
### Enhancement summary

I would like to be able to add IPv6 Addresses to Interfaces.

### Which component of AVD is impacted

eos_designs

### Use case example

I need to be able to set an IPv6 Address on an uplink interface for BGP connectivity.

### Describe the solution you would like

Addition of ipv6_addresses to l3_interfaces.

### Describe alternatives you have considered

Currently, setting the IPv6 via custom structured configs or raw_eos_cli is the only alternative.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by theotherguy2175** [comment]
I would also love to have this feature. We can't use l3_interfaces because of it.

**Comment by theotherguy2175** [comment]
Not sure why they have not responded but was able to do a work around:

```
 - interfaces: [ Ethernet1/1 ]
             nodes: [ borderA ]
             description: L3PEER-I
             mtu: 9174
             enabled: false
             ip_addresses: [ 1.1.1.1/30 ]
             # ospf:
             #   enabled: true
             #   point_to_point: True
             structured_config:
               ipv6_address: 2001::1/64
               speed: forced 40gfull
               access_group_in: SANITY-IN
```
          
  The structured config here is very handy for any 'ethernet' eos cli
