### ISSUE TITLE
(eos_cli_config_gen) Extend sbfd functionality

### ISSUE THREAD

**Issue by chetryan** [aristanetworks/ansible-avd#3343]
### Enhancement summary

Extend the existing sbfd schema/data model in eos_cli_config_gen to also support `initiator measurement delay round-trip`. 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

To enable the `sbfd` configuration for `initiator measurement delay round-trip` one would use something like :

```yaml
router_bfd:
  sbfd:
    initiator_measurement_round_trip: <boolean>
```

### Describe the solution you would like

```yaml
router_bfd:
  sbfd:
    initiator_measurement_round_trip: <boolean>
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
