### ISSUE TITLE
VLAN Based Services are always VLAN Aware Bundles, if evpn_vlan_aware_bundles is true

### ISSUE THREAD

**Issue by Serazio** [aristanetworks/ansible-avd#3355]
### Issue Summary

If i set evpn_vlan_aware_bundles to true, all vlan based services will be deployed as vlan aware bundles, too.  

I would expect, that evpn_vlan_aware_bundles: true allows the configuration of vlan aware bundles only, but keeps vlan based services as is.  This behavior can be seen on avd 4.4.0

Something like this:
```
evpn_vlan_bundles:
  - name: 'BUNDLE1'
    id: 10000
    rt_override: 1234:1000
    rd_override: 10

tenants:
  - name: "TENANT1"
    evpn_l2_multi_domain: false
    l2vlans:

      - id: 301
        name: 'VLAN301'
        vni_override: 2000001
        evpn_vlan_bundle: 'BUNDLE1'
        
      - id: 302
        name: 'VLAN302'
        vni_override: 2000002
        evpn_vlan_bundle: 'BUNDLE1'

      - id: 303 # not in bundle
        name: 'VLAN303'
        vni_override: 2000003
        rt_override: 1234:1001
        rd_override: 23 
```

would result in the following bgp configuration currently:
```

   vlan-aware-bundle BUNDLE1
      rd 10.255.0.7:10
      route-target both 1234:1000
      redistribute learned
      vlan 301-302
   !
   vlan-aware-bundle VLAN303
      rd 10.255.0.7:23
      route-target both 1234:1001
      redistribute learned
      vlan 303
```

The expected one is:
```
   vlan-aware-bundle BUNDLE1
      rd 10.255.0.7:10
      route-target both 1234:1000
      redistribute learned
      vlan 301-302
   !
   vlan 303
      rd 10.255.0.7:23
      route-target both 1234:1001
      redistribute learned
```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
