### ISSUE TITLE
Interface "LACP Fallback Individual" Support

### ISSUE THREAD

**Issue by js-arista** [aristanetworks/ansible-avd#3367]
### Enhancement summary

It is not possible right now to configure "LACP Fallback Individual" via the AVD data model, we only support the "static" option currently.  This is a common requirement for automated server deployments in order to bootstrap bare-metal servers via a different VLAN or interface type (for example) than is configured against the port-channel interface.

EOS feature functionality is described here
https://arista.my.site.com/AristaCommunity/s/article/configuring-lacp-fallback-individual-ports-on-arista-switches

### Which component of AVD is impacted

eos_designs

### Use case example

This is a common requirement for automated server deployments in order to bootstrap bare-metal servers via a different VLAN then is configured against the port-channel interface.

### Describe the solution you would like

The ability to specify different interface configuration parameters at the member interface level than are specified at the port-channel level 

### Describe alternatives you have considered

There is no alternative in EOS, we are currently using the structured_configuration parameter as a workaround to allow for deployment to continue

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by bjmeuer** [comment]
Hey @js-arista ,

after a discussion in the AVD group we are planning to add the fallback "individual" option and provide the possibility to specify a port_profile which will be used for the member links. In case you want the member interfaces with the same config as the port-channel you reference the same port_profile as the port-channel has, if you want different config on the member interfaces you reference another port_profile. Examle:

```
  # port-channel with lacp fallback individual and profile for member interfaces
  - name: INDIVIDUAL_1
    adapters:
      - switches: [connected_endpoints, connected_endpoints]
        switch_ports: [Ethernet12, Ethernet13]
        port_channel:
          mode: "active"
          description: "INDIVIDUAL_1"
          lacp_fallback:
            mode: individual
            individual:
              profile: INDIVIDUAL_TRUNK

port_profiles:
  - profile: INDIVIDUAL_TRUNK
    mode: trunk
    vlans: "1,2,3,4,5,6,7,123,234"
    native_vlan_tag: False
    native_vlan: 123
    spanning_tree_portfast: "edge"
    spanning_tree_bpdufilter: True
```

Hope that will work for you ?
