### ISSUE TITLE
Feat(eos_cli_config_gen): add aaa unresponsive action under global dot1x

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#3376]
### Enhancement summary

We need the following two `aaa unresponsive` options under global dot1x settings for a full NAC implementation.
There are some more options, but I would like to start with this.

```
access(config)#dot1x
access5(config-dot1x)#aaa ?
  accounting    Configure accounting
  unresponsive  Configure AAA timeout options

access-5(config-dot1x)#aaa unresponsive ?
  action    Set action for supplicant when AAA times out
  eap       EAP options
  phone     Configure AAA timeout options for phone
  recovery  Configure unresponsive recovery

access(config-dot1x)#aaa unresponsive action ?
  apply    Apply an action when AAA times out
  traffic  Set action for supplicant traffic when AAA times out

access(config-dot1x)#aaa unresponsive action apply ?
  cached-results  Use results from a previous AAA response

access(config-dot1x)#aaa unresponsive action apply cached-results ?
  else  Apply alternate action if primary action fails
  <cr>

access(config-dot1x)#aaa unresponsive action apply cached-results else ?
  traffic  Set action for supplicant traffic when AAA times out

access5(config-dot1x)#aaa unresponsive action apply cached-results else traffic ?
  allow  Allow traffic when AAA times out

access(config-dot1x)#aaa unresponsive action apply cached-results else traffic allow ?
  vlan  Allow traffic in VLAN when AAA times out
  <cr>

access(config-dot1x)#aaa unresponsive action apply cached-results else traffic allow vlan ?
  <1-4094>  Identifier for a Virtual LAN

access(config-dot1x)#aaa unresponsive action apply cached-results else traffic allow vlan 5?
<1-4094>

access(config-dot1x)#aaa unresponsive action apply cached-results else traffic allow vlan 5 ?
  <cr>
```

```
access(config)#dot1x
access1(config-dot1x)#aaa unresponsive ?
  action    Set action for supplicant when AAA times out
  eap       EAP options
  phone     Configure AAA timeout options for phone
  recovery  Configure unresponsive recovery

access(config-dot1x)#aaa unresponsive action ?
  apply    Apply an action when AAA times out
  traffic  Set action for supplicant traffic when AAA times out

access(config-dot1x)#aaa unresponsive action traffic ?
  allow  Allow traffic when AAA times out

access(config-dot1x)#aaa unresponsive action traffic allow ?
  vlan  Allow traffic in VLAN when AAA times out
  <cr>

access(config-dot1x)#aaa unresponsive action traffic allow vlan 5 ?
  <cr>
  ```
  

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

The two options `aaa unresponsive action apply` and `aaa unresponsive action traffic` are either or.
```
dot1x
   aaa unresponsive action apply cached-results else traffic allow vlan 5
```
OR
```
dot1x
   aaa unresponsive action traffic allow vlan 10
```

### Describe the solution you would like

I struggle with a meaningful data model.
 
```
dot1x:
  aaa:
    unresponsive:
      action: <str; apply-cashed-results | traffic >
      allow_vlan: <int; 1-4094 >
 ```
 

### Describe alternatives you have considered

could use `eos_cli:` to add it to the cli config

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by kmueller68** [comment]
@ClausHolbechArista just a question:
If anyone would have any free time the next two weeks to have a look at this to agree on a valid data model, I could work on this during Christmas vacation.

**Comment by ClausHolbechArista** [comment]
I will take a look and update here.

**Comment by ClausHolbechArista** [comment]
This is my suggestion. Please verify if it makes sense.
This covers everything supported on the dut I tested on, but you can choose to implement the subset you need.

```yaml
---
dot1x:
  aaa:
    unresponsive:
      eap_response: <str; "success" | "disabled">
      action:
        apply_cached_results: <bool>
        cached_results_timeout:
          time_duration: <int; >=1; required>
          time_duration_unit: <str; "days" | "hours" | "minutes" | "seconds"; required>
        traffic_allow: <bool>
        traffic_allow_vlan: <int>

      phone_action:
        apply_cached_results: <bool>
        cached_results_timeout:
          time_duration: <int; >=1; required>
          time_duration_unit: <str; "days" | "hours" | "minutes" | "seconds"; required>
        traffic_allow: <bool>
        traffic_allow_vlan: <int>

      recovery_action_reauthenticate: <bool>
```
