### ISSUE TITLE
Feat(eos_cli_config_gen): Add encapsulation to flow tracking

### ISSUE THREAD

**Issue by chetryan** [aristanetworks/ansible-avd#3395]
### Enhancement summary

Add  encapsulation to flow tracking 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
flow_tracking:
 sampled: 
    encapsulation:
       ipv4: <bool>
       ipv6: <bool>
```

### Describe the solution you would like

Ideally extend the data model to support more flow tracking options.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
