### ISSUE TITLE
Allow evpn_vlan_bundle to be set up at tenant level

### ISSUE THREAD

**Issue by xaviramon** [aristanetworks/ansible-avd#3408]
### Enhancement summary

Allow `evpn_vlan_bundle` variable to be set up at tenant level, so all VLANs defined can be assigned to the same VLAN bundle.

### Which component of AVD is impacted

eos_designs

### Use case example

```
tenants:
  - name: TENANT_A
     vrfs:
       PRODUCTION:
       (...)
     l2vlans:
     - id: 1
       name: "TEST1"
       evpn_vlan_bundle: "VLAN_BUNLE_1"
     - id: 2
       name: "TEST2"
       evpn_vlan_bundle: "VLAN_BUNLE_1"
```

### Describe the solution you would like

```
tenants:
  - name: TENANT_A
    evpn_vlan_bundle: "VLAN_BUNLE_1"
     vrfs:
       PRODUCTION:
       (...)
     l2vlans:
     - id: 1
       name: "TEST1"
     - id: 2
       name: "TEST2"
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
