### ISSUE TITLE
Feat(eos_designs): support defining the port channel ip for P2P port-channels

### ISSUE THREAD

**Issue by chetryan** [aristanetworks/ansible-avd#3416]
### Enhancement summary

When defining `p2p_links` for `core_interfaces`, it is possible to define `port_channel` dictionary to build port-channels between devices. however it is not possible to define the ID to be used for that channel. 

### Which component of AVD is impacted

eos_designs

### Use case example

When defining a p2p core interface, explicitly define the port_channel that should be used: 

```
core_interfaces:
   p2p_links:
      -  node: [node_a, node_b]
          id: 1
          port_channel:
              mode: active
              channel_id: 2222
              node_child_interfaces: 
                 ...........
     
```

### Describe the solution you would like

Refer to Use Case Example.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
