### ISSUE TITLE
Feat(eos_cli_congi_gen): Support tcp mss options for `router path-selection`

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3423]
### Enhancement summary

    ```
    host1(config-dynamic-path-selection)#tcp mss ceiling ipv4 ?
      ingress     Enforce on packets ingressing from DPS tunnel
      <64-65515>  Segment size
    host1(config-dynamic-path-selection)#tcp mss ceiling ipv4 666 ingress
    host1(config-dynamic-path-selection)#show active
    router path-selection
       tcp mss ceiling ipv4 666 ingress
    host1(config-dynamic-path-selection)#tcp mss ceiling ipv4 ingress
    host1(config-dynamic-path-selection)#show active
    router path-selection
       tcp mss ceiling ipv4 ingress
    ```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

WAN design

### Describe the solution you would like

Tentative schema - taken from tunnel interfaces, except removing `egress` as a valid value for direction and `ipv6` as not supported
```
        tcp_mss_ceiling:
          type: dict
          keys:
            ipv4:
              type: int
              description: Segment Size for IPv4
              min: 64
              max: 65495
              convert_types:
                - str
            direction:
              type: str
              valid_values: ["ingress"]
              description: |
                Optional direction only `ingress` is supported today
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
