### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for `neighbor <neighbor_ID> ttl maximum-hops <hop_number> ` for neighbors and peer-groups

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3424]
### Enhancement summary

cf title

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Security measure for BGP

### Describe the solution you would like

```
router_bgp:
  neighbors:
    - ip_address: 42.42.42.42
       ttl_maximum_hops: <int>;  0-254 
  peer_groups:
    - name: MyAwesomePG-42
       ttl_maximum_hops: <int>;  0-254 
```

host1(config-router-bgp)#neighbor 2.2.2.2 ttl maximum-hops ?
  <0-254>  Maximum number of hops

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
