### ISSUE TITLE
eos_cli_config_gen: dot1q-tunnel on port channel not generating the indended config

### ISSUE THREAD

**Issue by rradim** [aristanetworks/ansible-avd#3428]
### Issue Summary

Hello,

we are using 4.4 version.

it seems that eos_cli_config_gen is not correctly generating intended config for dot1q-tunnel configuration. It works for physical ports though.

structured config:
```
- name: Port-Channel118
  description: xxxx
  type: switched
  shutdown: false
  link_tracking_groups:
  - name: LT_GROUP1
    direction: downstream
  mode: dot1q-tunnel
  vlans: '3110'
  spanning_tree_portfast: edge
  evpn_ethernet_segment:
    identifier: 0000:0000:0dc1:0000:0076
    route_target: 0d:c1:00:00:00:76
  lacp_id: 0dc1.0000.0076
```

resulting intended config => here its missing the `mode dot1q-tunnel`
```
interface Port-Channel118
   description OP-22-00018-00008s01;CZUB-ELINE
   no shutdown
   switchport
   evpn ethernet-segment
      identifier 0000:0000:0dc1:0000:0076
      route-target import 0d:c1:00:00:00:76
   lacp system-id 0dc1.0000.0076
   spanning-tree portfast
   link tracking group LT_GROUP1 downstream
```

Please can you check? 

Thanks a lot
Radim

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
