### ISSUE TITLE
Render access vlan on port-channel interfaces if `mode` is `dot1q-tunnel`

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#3442]
Hi ARISTA team,

thanks a lot for this quick fix :), I tested it in our project and works fine... but its not covering a scenario, where `dot1q-tunnel` is used in combination with switch `access vlan`. Not sure whether to write it into original issue or here...decided for this issue :). 

src:
```
  - name: dca-p3dc-dc-l13_Eth37_&_dca-p6dc-dc-l14_Eth34
    adapters:
      - switch_ports: [Eth37, Eth34]
        switches: [dca-p3dc-dc-l13, dca-p6dc-dc-l14]
        port_channel:
          channel_id: 118
          mode: active
        ethernet_segment: { short_esi: "0dc1:0000:0076" }
        vlans: "3110"
        mode: dot1q-tunnel
```

result should be:
```
interface Port-Channel118
   description OP-22-00018-00008s01;CZUB-ELINE
   no shutdown
   switchport
   switchport access vlan 3110
   switchport mode dot1q-tunnel
 ....
```

my quick fix was to duplicate the original "access" line and just change it a bit...

```
{%     if port_channel_interface.vlans is arista.avd.defined and port_channel_interface.mode is arista.avd.defined("access") %}
   switchport access vlan {{ port_channel_interface.vlans }}
{%     endif %}
{# 
HOTFIX - temp fix for dot1q-tunnel
#}
{%     if port_channel_interface.vlans is arista.avd.defined and port_channel_interface.mode is arista.avd.defined("dot1q-tunnel") %}
   switchport access vlan {{ port_channel_interface.vlans }}
{%     endif %}
```

Thanks
Radim

_Originally posted by @rradim in https://github.com/aristanetworks/ansible-avd/issues/3429#issuecomment-1860035211_
