### ISSUE TITLE
Empty "description" under each ports in intended configs

### ISSUE THREAD

**Issue by forcecity** [aristanetworks/ansible-avd#3443]
Hi there,
I just met an issue that if we only want to simply shutdown interfaces in Network ports settings for unused switchports.
```
network_ports:
  - switches:
      - leaf-sw01
    switch_ports:
      - Ethernet1-47,51-54
    enabled: false
```
After rendering, the CLI will be
```
interface Ethernet xx
   description
   shutdown
   switchport
interface Ethernet yy
   description
   shutdown
   switchport
...
```
These commands couldn't be delivered to devices since description is "empty". The switch will complain "**_Incomplete command (at token 0: 'description')_**". I'm not sure if it is a bug or i missed something else. Thank you!!
