### ISSUE TITLE
Consider the test result is passed when the ports didn't plug any transceivers while they are shutdown

### ISSUE THREAD

**Issue by forcecity** [aristanetworks/ansible-avd#3444]
### Enhancement summary

After I ran validation tasks (with AVD + ANTA) and check the result, I found there are several interfaces status tests are failed. Those ports are not connected, so I shut them down. But even though, the result always tells me it is not expected:
`The following interface(s) are not in the expected state: ['Ethernet1/1 is notPresent/adminDown expected down/adminDown']`
But to be honest, I think it is normal that transceivers are not plugged in for the unused ports.

### Which component of AVD is impacted

eos_validate_state

### Use case example

To the device configuration like below and they didn't plug in transceivers:
```
interface Ethernet51/1
   description unused
   shutdown
interface Ethernet52/1
   description unused
   shutdown
```
Running `eos_validate_state` role with ANTA enable.
```
---
- name: Run AVD validation
  hosts: all
  gather_facts: false
  tasks:
    - name: Validate Configured Devices
      ansible.builtin.import_role:
        name: arista.avd.eos_validate_state
      vars:
        use_anta: true
        save_catalog: true
```

### Describe the solution you would like

To the ports above, the test result could be passed

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
