### ISSUE TITLE
Feat(eos_designs): support access_group_in/out under network services SVI configuration and SVI profiles natively

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#3448]
### Enhancement summary

Add support for applying ip access-lists to SVIs and SVI profiles in eos_designs network services natively.

It is support today by using `structured_config`, but using this, the automatisms of eos_designs role like differentiation of VEOS vs hardware platform do not work.

### Which component of AVD is impacted

eos_designs

### Use case example

 ```
  Tenant_LAN:
    mac_vrf_vni_base: 50000
    vrfs:
      LAN_001:
        vrf_vni: 1001
        vtep_diagnostic:
          loopback: 101
          loopback_ip_range: 10.xx.xx.64/27
        svis:
          ### building XX
          2210:
            name: "DATA"
            tags: [data]
            enabled: true
            igmp_snooping_enabled: true
            ip_address_virtual: 10.xx.0.1/22
            access_group_out: ACL-OUT
```
```
  svi_profile_PDU:
    ip_helpers:
      10.xx.xx.153:
        source_interface: loopback101
        source_vrf: MU_LAN_001
        access_group_out: PDU-OUT
```

### Describe the solution you would like

 ```
  Tenant_LAN:
    mac_vrf_vni_base: 50000
    vrfs:
      LAN_001:
        vrf_vni: 1001
        vtep_diagnostic:
          loopback: 101
          loopback_ip_range: 10.xx.xx.64/27
        svis:
          ### building XX
          2210:
            name: "DATA"
            tags: [data]
            enabled: true
            igmp_snooping_enabled: true
            ip_address_virtual: 10.xx.0.1/22
            access_group_out: ACL-OUT
            access_group_in: ACL-IN
```
```
  svi_profile_PDU:
    ip_helpers:
      10.xx.xx.153:
        source_interface: loopback101
        source_vrf: MU_LAN_001
    access_group_out: ACL-OUT
    access_group_in: ACL-IN
```

### Describe alternatives you have considered

Use `structured_config` to apply acls but miss the eos_designs automatisms. 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
