### ISSUE TITLE
AnsibleMapping object has no attribute 'name' when enabling PIM with no RP

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#3454]
### Issue Summary

When configuring `l3_interfaces` under VRF with PIM enabled and no RP (`pim_rp_addresses`) configured in this VRF, ansible returns an error message which is a bit cryptic

```
fatal: [dc1-blm1a-mrv356 -> localhost]: FAILED! => \
{"changed": false, "msg": "'AnsibleMapping' object has no attribute 'name'"}
```

Already discussed with @jonxstill 

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```yaml
tenants:
  # Definition of tenants. Additional level of abstraction to VRFs
  - name: Tenant-A
    evpn_l3_multicast:
      evpn_underlay_l3_multicast_group_ipv4_pool: 232.232.0.0/20
      evpn_underlay_l3_multicast_group_ipv4_pool_offset: 1
    mac_vrf_vni_base: 10000
    vrfs:
      - name: MCAST
        vrf_id: 21
        vrf_vni: 21
        vtep_diagnostic:
          loopback: 21
          loopback_description: vtep_diagnostic
          loopback_ip_range: 10.254.0.0/24
        evpn_l3_multicast: 
          enabled: true
        svis:
          # List of svis truncated for comprehension
          - id: 219
            name: Flow_Multicast
            profile: GENERIC
            tags: [DC1]
            evpn_l2_multicast:
              enabled: false
            ip_address_virtual: 100.20.219.1/24
            ipv6_address_virtuals: ["fc00:100:20:219::1/64"]
        l3_interfaces:
          - nodes: [ dc1-blm1a-mrv356, dc1-blmba-mrv357 ]
            interfaces: [ Ethernet49/1.900, Ethernet49/1.900 ]
            encapsulation_dot1q_vlan: [ 900, 900 ]
            ip_addresses: [ 100.254.248.0/31, 100.254.248.4/31 ]
            descriptions: [ P2P_LINK_TO_rp-mrv380_Ethernet49/1, P2P_LINK_TO_rp-mrv380_Ethernet50/1 ]
            enabled: true
            pim:
              enabled: true 
          - nodes: [ dc1-blm1a-mrv356, dc1-blmba-mrv357 ]
            interfaces: [ Ethernet1.901, Ethernet1.901 ]
            encapsulation_dot1q_vlan: [ 901, 901 ]
            ip_addresses: [ 100.254.248.2/31, 100.254.248.6/31 ]
            descriptions: [ P2P_LINK_TO_row-hs307_Ethernet2, P2P_LINK_TO_row-hs307_Ethernet3 ]
            enabled: true
            pim:
              enabled: true
```

### Relevant log output

```shell
# Log from eos_design in task "Generate device configuration in structured format"

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'AnsibleMapping' object has no attribute 'name'
fatal: [dc1-blm1a-mrv356 -> localhost]: FAILED! => {"changed": false, "msg": "'AnsibleMapping' object has no attribute 'name'"}
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
