### ISSUE TITLE
EOS cli config schema for bgp/address-family-evpn missing neighbor list

### ISSUE THREAD

**Issue by aceplean** [aristanetworks/ansible-avd#3471]
### Issue Summary

In the variables input documentation and in this schema file:
`ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/eos_cli_config_gen.schema.yml`
under bgp: address-family-evpn we are missing the neighbor key which would be a list of the neighbors for that particular AF.
Compare to other address families like IPv4 this is what I would expect to have:
```
          neighbors:
            type: list
            primary_key: ip_address
            convert_types:
            - dict
            items:
              type: dict
              keys:
                ip_address:
                  type: str
                activate:
                  type: bool
```
With the schema missing the neighbors I cannot generate a config with neighbors active in the evpn address family.

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Execute sensible playbook...
Without the neighbors in the input variables the resulting CLI will be missing the necessary configuration to activate the neighbors for EVPN.
```

### Relevant log output

```
[WARNING]: [...]: 'Validation Error: router_bgp.address_family_evpn': Unexpected key(s) 'neighbors' found in dict.
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
