### ISSUE TITLE
Add support of profile at SVI level

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#349]
**Issue Type**

- Role enhancement: `eos_l3ls_evpn`

**Is your feature request related to a problem? Please describe.**

When a large number has to be configured it takes a lot of time to create/update information as we have to go SVI per SVI.

**Describe the solution you'd like**

It can be easier to use a set of PROFILE to configure common parameters only one time and apply a profile on SVI.

This profile would be optional and the user can choose to configure all parameters on SVI or a profile.

Below is a logical representation:

```yaml
profile_svi:
  MYPROFILE:
    tags: [DC1]
    enabled: true
    igmp_snooping_enabled: false

tenants:
  # Tenant A Specific Information - VRFs / VLANs
  Tenant_A:
    mac_vrf_vni_base: 10000
    vrfs:
      TENANT_A_PROJECT01:
        vrf_vni: 11
        svis:
          110:
            name: 'PR01-DMZ'
            ip_address_virtual: 10.1.10.254/24
    		profile: MYPROFILE
          111:
            name: 'PR01-TRUST'
            tags: [DC1]
            enabled: true
            ip_address_virtual: 10.1.11.254/24
```

Idea from @ClausHolbechArista
