### ISSUE TITLE
Feat(eos_designs): Support BGP ipv4 unicast peering on l3_edge.p2p_links within a RFC5549 enabled fabric

### ISSUE THREAD

**Issue by kornoa** [aristanetworks/ansible-avd#3493]
### Enhancement summary

Implement an additional key in `l3_edge.p2p_profiles` and `l3_edge.p2p_links` to explicitly ignore `underlay_rfc5549: true`.

### Which component of AVD is impacted

eos_designs

### Use case example

If a fabric is set to use RFC5549 for underlay BGP peering, the data model for l3_edge.p2p_links supports only RFC5549 BGP peering to devices outside of the fabric. But we cannot ensure that all 3rd party devices support RFC5549 or outside device's administrators commit on RFC5549. Therefor it would be very helpful to have a knob to instruct the role to render a classic IPv4 BGP peering based on the IP information provided within the p2p link.

### Describe the solution you would like

````yaml
underlay_routing_protocol: ebgp
underlay_rfc5549: true
l3_edge:
  p2p_links:
    - nodes:
        - borderleaf1
        - campus-core1
      subnet: 10.99.0.0/30
      include_in_underlay_protocol: true  # this is default, but helpful for the context
      ignore_rfc5549: true  # default false
      interfaces:
        - Ethernet1
        - Any
 ````

should render this BGP configuration on `borderleaf1`:

````code
router bgp 65101
   ...
   neighbor IPv4-UNDERLAY-NON-RFC5549-PEERS peer group
   neighbor IPv4-UNDERLAY-NON-RFC5549-PEERS password 7 <removed>
   neighbor IPv4-UNDERLAY-NON-RFC5549-PEERS send-community
   neighbor IPv4-UNDERLAY-NON-RFC5549-PEERS maximum-routes 12000
   ...
   neighbor 10.99.0.2 peer group IPv4-UNDERLAY-NON-RFC5549-PEERS
   neighbor 10.99.0.2 remote-as 65499
   ...
   address-family ipv4
      ...
      neighbor IPv4-UNDERLAY-NON-RFC5549-PEERS activate
````

### Describe alternatives you have considered

Using `custom_structured_config_router_bgp` and add peer group and peers manually.
But this leads to duplicate data within the inventory for IP addresses used in l3_edge.p2p_links and in custom_structured_config.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
