### ISSUE TITLE
Fix(eos_designs): Do not KeyError when no path-group is in common with pathfinder

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3511]
### Enhancement summary

```yaml
wan_route_servers:
- hostname: pathfinder1
    router_id: "1"
    path_groups:
    - name: internet
        interfaces:
        - name: Ethernet1
            ip_address: 192.168.99.1
- hostname: pathfinder2
    router_id: "2"
    path_groups:
    - name: internet
        interfaces:
        - name: Ethernet1
            ip_address: 192.168.99.2
```

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'wan_path_groups'
fatal: [Site100-LAX-R1 -> localhost]: FAILED! => changed=false
msg: '''wan_path_groups'''
```

### Which component of AVD is impacted

eos_designs

### Use case example

suggestion: improve error handling.

### Describe the solution you would like

suggestion: improve error handling.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
