### ISSUE TITLE
SVI State not applied to configuration

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#352]
## Issue Type

- Bug Report

## Summary

SVI state management is not applied correctly. SVI are always UP even with 

```
tenants:
  # Tenant A Specific Information - VRFs / VLANs
  Tenant_A:
    mac_vrf_vni_base: 10000
    vrfs:
      TENANT_A_PROJECT01:
        vrf_vni: 11
        svis:
          110:
            name: 'PR01-DMZ'
            tags: [DC1]
            enabled: false
            ip_address_virtual: 10.1.10.254/24
```

## Role or Module Name

`eos_l3ls_evpn`
