### ISSUE TITLE
Feat(eos_designs): Add ACL for Internet facing WAN interfaces

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3528]
### Enhancement summary

For WAN interfaces (identified when `wan_circuit` is set) use a default ACL inbound and outbound  (ACL defined in internal document - ping @gmuloc if needing assistance )
     * Pathfinder/Edge: Have ingress ACLs on the WAN ports of the Pathfinder that would disallow all incoming connections by default, except perhaps IPsec and a few other protocols.
    * egress ACLs to prevent any packets destined to RFC1918 addresses

Future work may imply adapting the ACL depending on the IPsec status

### Which component of AVD is impacted

eos_designs

### Use case example

automatic inbound ACL for WAN interfaces

### Describe the solution you would like

```
node_type_keys.key>:

  # Define variables for all nodes of this type.
  defaults:

    # PREVIEW: This key is currently not supported

    # L3 Interfaces currently only use for WAN interfaces.
    l3_interfaces:

        # L3 interface profile name. Profile defined under `l3_interface_profiles`.
      - profile: <str>

        # Ethernet interface name like 'Ethernet2'.
        name: <str; required; unique>
       
        [...]
        wan_acls: <bool | default true>
```

In the description indicates that this can be overwritten using the structured_configuration of the l3_interfaces

automatically generate the ACLs inbound and outbound as defined in the document.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
