### ISSUE TITLE
Feat(eos_designs): Allow to control DPS timers at the `wan_path_group` level

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3530]
### Enhancement summary

Allow some values for DPS interfaces

### Which component of AVD is impacted

eos_designs

### Use case example

Slow down DPS timers on metered links

### Describe the solution you would like

```
# List of path-groups used for the WAN configuration.
wan_path_groups:

    # Path-group name.
  - name: <str; required; unique>
     [...]
     dps:
       auto: <bool>
       interval: <int>
       failure_threshold: <int>
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
