### ISSUE TITLE
Feat(eos_designs): Configure BFD timers higher than DPS timeouts for WAN BGP neighbors

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3531]
### Enhancement summary

Configure BFD timers higher than DPS timeouts for WAN BGP neighbors

### Which component of AVD is impacted

eos_designs

### Use case example

Used for WAN topology for more stability

### Describe the solution you would like

For WAN_OVERLAY_PEERS and RR-OVERLAY-PEERS **when configuring a WAN device** ( that is `wan_role` is set) allow to set BFD timers and use default values as recommended by engineering (need to reach out to them).

```
bgp_peer_groups:
  wan_overlay_peers:
    # Import this from eos_cli_config_gen and overwrite the required keys to be false and use default value as given by engineering.
    bfd_timers:
                  # Interval in milliseconds.
                  interval: <int; 50-60000; default: TBC>
                  # Rate in milliseconds.
                  min_rx: <int; 50-60000; default: TBC>
                  multiplier: <int; 3-50; default: TBC>
  rr_overlay_peers:
    # Import this from eos_cli_config_gen
    bfd_timers:
                  # Interval in milliseconds.
                  interval: <int; 50-60000; default: TBC>
                  # Rate in milliseconds.
                  min_rx: <int; 50-60000; default: TBC>
                  multiplier: <int; 3-50; default: TBC>
```

Remember that you need to pick up `bfd_timers` in `plugins/eos_designs_facts/bgp_peer_groups.py`
Then in `roles/eos_designs/overlay/router_bgp.py` configure appropriately.

In molecule tests, try to overwrite some default timers
 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
