### ISSUE TITLE
Router multicast & PIM enhancements to include vrfs in eos_config_cli_gen

### ISSUE THREAD

**Issue by sundayN** [aristanetworks/ansible-avd#354]
**Issue Type**

- Role enhancement

**Is your feature request related to a problem? Please describe.**
While using eos_config_cli_gen in our media network with two vrfs, it was not possible to include vrf ipv4 routing or set RP addresses and groups for PIM-sparse mode.

**Describe the solution you'd like**
Include vrfs with 
- router-multicast.j2 and 
- router-pim-sparse-mode.j2  

This would allow for eos_config_cli_gen to be used in a media network. The following template changes can achieve this objective.

 ```yaml
router_multicast:
  ipv4:
    routing: < true | false >
  vrfs:
    < vrf_name >:
      ipv4:
        routing: < true | false >
```

```yaml
router_pim_sparse_mode:
  ipv4:
    rp_addresses:
      < rp_address_1 >:
        groups:
          < group_prefix_1/mask > :
          < group_prefix_2/mask > :
      < rp_address_2 >:
    anycast_rps:
      < anycast_rp_address_1 > :
        other_anycast_rp_addresses:
          < ip_address_other_anycast_rp_1 >:
            register_count: < register_count_nb >
  vrfs:
    < vrf_name >:
      ipv4:
        rp_addresses:
          < rp_address_1 >:
            groups:
              < group_prefix_1/mask > :
              < group_prefix_2/mask > :
```

**Describe alternatives you've considered**
I considered implementing this in the vrf-instances.j2, however it seemed more straightforward to implement it in the router-multicast section.

**Additional context**
The following resulting eos configuration has been tested successfully in our network

```eos
router multicast
   ipv4
      routing
   !
   vrf BLUE
     ipv4
        routing
   !
   vrf RED
     ipv4
        routing
!
```

```eos
router pim sparse-mode
   ipv4
      rp address 10.238.1.161 230.168.0.0/18
      rp address 10.238.1.161 231.168.0.0/18
      rp address 10.238.1.161 239.168.0.0/18
   !
   vrf BLUE
      ipv4
         rp address 10.238.2.161 230.168.64.0/18
         rp address 10.238.2.161 231.168.64.0/18
         rp address 10.238.2.161 239.168.64.0/18
   !
   vrf RED
      ipv4
         rp address 10.238.3.161 230.168.128.0/18
         rp address 10.238.3.161 231.168.128.0/18
         rp address 10.238.3.161 239.168.128.0/18
!
```
