### ISSUE TITLE
underlay_routing_protocol is case sensitive for ISIS configuration

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#359]
## Issue Type

- Bug Report

## Summary

Underlay value to enable ISIS is case sensitive leading to a misconfiguration if user configure variable like below:

```yaml
underlay_routing_protocol: isis
```

## Role or Module Name

`eos_l3ls_evpn`

## Steps to reproduce

In group_vars, configure:

```yaml
underlay_routing_protocol: isis
```

### Expected results

```yaml
### Routing - ISIS ###
router_isis:
  instance: EVPN_UNDERLAY
  net: 49.0001.0001.0000.0001.00
  router_id: 192.168.255.1
  no_passive_interfaces:
    - Ethernet5
    - Ethernet6
    - Ethernet1
    - Ethernet2
    - Ethernet3
    - Ethernet4
    - Ethernet7
    - Ethernet8
  is_type: level-2
  address_family: ['ipv4 unicast']
  isis_af_defaults:
    - maximum-paths 2
```

### Actual results

```yaml
### Routing - ISIS ###
router_isis:
```
