### ISSUE TITLE
core_interfaces can generate invalid config if BGP AS is not defined

### ISSUE THREAD

**Issue by xaviramon** [aristanetworks/ansible-avd#3596]
### Issue Summary

When using core_interfaces, if an ASN is required but not set, eos_designs will generate an invalid config:
Configuration:
```
p2p_links:
    - nodes: [ BA_SPLINE01, WAN_ROUTER ]
      profile: WAN_link
      id: 1
```
Variable `as` is not defined under the profile.
No error is thrown and generated configuration is:
```
   neighbor 172.16.0.9 remote-as None
   neighbor 172.16.0.9 local-as None no-prepend replace-as
 ```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
