### ISSUE TITLE
Feat(eos_cli_config_gen): Add more 'pim ipv4' interface commands

### ISSUE THREAD

**Issue by kornoa** [aristanetworks/ansible-avd#3631]
### Enhancement summary

Add more pim ipv4 commands to Ethernet, port-channel and vlan interfaces:
- pim ipv4 bfd
- pim ipv4 bidirectional
- pim ipv4 hello interval <1-65535>
- pim ipv4 hello count <1.5-65535>

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

````yaml
ethernet_interfaces:
  - name: Ethernet1
    pim:
      ipv4:
        bfd: true
        bidirectional: true
        hello:
           count: 2.5
           interval: 1
````

should render:

````code
interface Ethernet1
   pim ipv4 bidirectional
   pim ipv4 hello interval 1
   pim ipv4 hello count 2.5
   pim ipv4 bfd
````

### Describe the solution you would like

data_model on ethernet, port-channel and vlan interfaces:

````yaml
pim:
  ipv4:
    bfd: Boolean
    bidirectional: Boolean
    hello:
       count: Float # allowed values <1.5-65535>; default: 3.5
       interval: Integer  # allowed values <1-65535>; default: 30
````

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
