### ISSUE TITLE
Feat(eos_cli_config_gen): Add 'ip igmp host-proxy' interface support

### ISSUE THREAD

**Issue by kornoa** [aristanetworks/ansible-avd#3633]
### Enhancement summary

Add support to configure IP IGMP Host-Proxy feature:

````code
vEOS-4-30-5M(config-if-Et2)#ip igmp host-proxy ?
  A.B.C.D          Group Address
  access-list      Non-standard Access List name
  report-interval  Time interval between unsolicited reports
  version          IGMP version on IGMP host-proxy interface
  <cr>
````

### Which component of AVD is impacted

eos_cli_config_gen

### Enable

````yaml
ethernet_interfaces:
  - name: Ethernet1
    ip_igmp_host_proxy:
      enabled: true
````
should render:

````code
interface Ethernet1
   ip igmp host-proxy
````

### Group Filter

````yaml
ethernet_interfaces:
  - name: Ethernet1
    ip_igmp_host_proxy:
      groups:
         - group: 239.0.0.1
         - group: 239.0.0.2
           exclude:
             - source: 10.0.2.1
         - group: 239.0.0.3
           include:
             - source: 10.0.3.1
         - group: 239.0.0.4
           exclude:
             - source: 10.0.4.1
             - source: 10.0.4.2
           include:
             - source: 10.0.4.3
             - source: 10.0.4.4
````
should render:

````code
interface Ethernet1
   ip igmp host-proxy 239.0.0.2 exclude 10.0.2.1
   ip igmp host-proxy 239.0.0.3 include 10.0.3.1
   ip igmp host-proxy 239.0.0.1
   ip igmp host-proxy 239.0.0.4 include 10.0.4.3
   ip igmp host-proxy 239.0.0.4 include 10.0.4.4
   ip igmp host-proxy 239.0.0.4 exclude 10.0.4.1
   ip igmp host-proxy 239.0.0.4 exclude 10.0.4.2
````
````

### Report Interval

````yaml
ethernet_interfaces:
  - name: Ethernet1
    ip_igmp_host_proxy:
      report_interval: 2
````
should render:

````code
interface Ethernet1
   ip igmp host-proxy report-interval 2
````

### Access Lists

````yaml
ethernet_interfaces:
  - name: Ethernet1
    ip_igmp_host_proxy:
      access_lists:
        - name: ACL1
        - name: ACL2
````
should render:

````code
interface Ethernet1
   ip igmp host-proxy access-list ACL1
   ip igmp host-proxy access-list ACL2
````

### Version

````yaml
ethernet_interfaces:
  - name: Ethernet1
    ip_igmp_host_proxy:
      version: 2
````
should render:

````code
interface Ethernet1
   ip igmp host-proxy version 2
````

### Describe the solution you would like

data_model on ethernet, port-channel and vlan interfaces:

````yaml
ip_igmp_host_proxy:
  enabled: Boolean
  access_lists:
    - name: String  # ACL name
  groups:
    - group: String  # IPv4 Multicast Group; required
      exclude:
        - source: String  # IPv4 source address
      include:
        - source: String  # IPv4 source address
  report_interval: Integer  # allowed values: <1-31744>; default: 1
  version: Integer  # allowed_values: <1-3>; default: 3
````

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
