### ISSUE TITLE
Feat(eos_designs): Add a key `public_ip` under `node.l3_interfaces` to specify a public IP

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3637]
### Enhancement summary

```
wan_edge:
  nodes:
    - name: DEVICE
       l3_interfaces:
         - name: Ethernet1
            ip_address: dhcp
            public_ip: <X.X.X.X>. <============== Add this
         - name: Ethernet2
            ip_address: 10.10.42.1/24
            public_ip: <X.X.X.X>. <============== Add this
```

### Which component of AVD is impacted

eos_designs

### Use case example

Needed for devices behind NAT and/or using `dhcp` if the public IP is known

### Describe the solution you would like

cf summary

### Describe alternatives you have considered

Supported today for WAN route servers under `wan_route_servers.path_groups.interfaces.ip_address` but not possible for edges and transit routers

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
