### ISSUE TITLE
Feat(eos_designs): Allow to disable IPsec on dynamic peers for a path-group

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3671]
### Enhancement summary

cf title

### Which component of AVD is impacted

eos_designs

### Use case example

Disabling IPsec on some MPLS private path-group

### Describe the solution you would like

A new knob in the schema for path_groups to allow to disable ipsec for dynamic_peers
```
# Existing model
wan_path_groups:
  - name: <str>
    # Flag to configure IPsec at the path-group level.
    #
    # When set to `true`, IPsec is enabled for both the static and dynamic peers.
    ipsec: <bool; default=True>
```

Update to

```
# Existing model
wan_path_groups:
  - name: <str>
    # Path-group IPSec configuration
    ipsec:
        # When set to `true`, IPsec is enabled for dynamic peers.
        dynamic_peers: <bool; default=True>
        # When set to `true`, IPsec is enabled for static peers.
        static_peers: <bool; default=True>
```

to render

```
router path-selection
   path-group MPLS-1 id 666
      ipsec profile CP-PROFILE
      !
      local interface Ethernet1
      !
      peer dynamic
         ipsec disabled               <<<<<<<<<<<<<<<<<<<<<<<< this line
   !
```

Note that the IPsec profile can still be there for static peers (ipsec profile under path-group)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
