### ISSUE TITLE
For feature Uplink: p2p vrfs, instead of utilizing "uplink_ipv4_pool," we should be capable of assigning a subnet per VRF under "tenant.vrfs" for point-to-point subinterface links.

### ISSUE THREAD

**Issue by Spandanaarista** [aristanetworks/ansible-avd#3735]
### Enhancement summary

Instead of reusing IPs for different VRFs under sub-interfaces from the uplink_ipv4_pool, utilizing different subnets for different VRFs would eliminate the confusion associated with IP reuse.

### Which component of AVD is impacted

eos_designs

### Use case example

We aim to implement "Uplink: p2p vrfs" for a customer's Core connections to various L3LS fabric border leaf switches. This involves utilizing sub-interface point-to-point links for different VRFs, thereby streamlining the configuration of numerous L3 interfaces under network services.

### Describe the solution you would like

Having the capability to allocate separate IP pools for different VRFs would facilitate the usage of distinct IP subnets, enhancing operational clarity.

### Describe alternatives you have considered

Organizing multiple sub-interfaces with the "l3_interfaces" keys under network services for all VRFs in tenant files, for each VRF, connection, and sub-interface.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
We would not be able to use a pool defined under tenants for uplinks. Since nodes can have overlapping IDs, we need to handle such pools within the node type settings.
so ex:
```yaml
l3leaf:
  defaults:
    uplink_type: p2p-vrfs
    uplink_pools:
      - ipv4_pool: <ipv4_network/mask>
        vrf: VRF1
      - ipv4_pool: <ipv4_network/mask>
        vrf: VRF2
      - ipv4_pool: <ipv4_network/mask>
        vrf: VRF3
```
The behavior should be to fall back to the regular uplink_pool if the pool is not set for a given VRF.
