### ISSUE TITLE
FEAT(eos_cli_config_gen): Add support for isis spf-interval hold timer

### ISSUE THREAD

**Issue by chetryan** [aristanetworks/ansible-avd#3756]
### Enhancement summary

At the moment, the spf-interval data model does not support the hold interval configuartion

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

At the moment, we can only create a command like : ` spf-interval 5 100 300` using eos_cli. Ideally we would be able to do this using the router_isis data model.

### Describe the solution you would like

```
router_isis:
    .....
    spf_interval:
       interval: 5
       wait_interval: 100
       hold_interval: 300
```

should add the command : `spf-interval 5 100 300` to the generated code.

At the moment, the `hold_interval` cannot be specified

### Describe alternatives you have considered

At the moment we are having to use the eos_cli  option to define the router isis configuration.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
