### ISSUE TITLE
Extend match-lists to support IP Prefixes

### ISSUE THREAD

**Issue by colinmacgiolla** [aristanetworks/ansible-avd#3768]
### Enhancement summary

Currently match-lists only support string types. This enhancement is to add support for `prefix-ipv4` and `prefix-ipv6`.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

MSS-G makes use of IPv4 and IPv6 prefix match-lists to define segments e.g.

```shell
match-list input prefix-ipv4 BACKUP-CLIENTS
   match prefix-ipv4 100.1.0.0/25
!
```
By extending the existing match-lists, we can start to build MSS-G support

### Describe the solution you would like

Extend match-lists to support IPv4 and IPv6 prefix types

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
@colinmacgiolla please share the planned data model before you start implementing this.

**Comment by colinmacgiolla** [comment]
What do you think of the following:
```yaml
match_list_input:
  prefix_ipv4:
    - name: <str; required; unique>
      prefixes: 
         - <list of IPv4 prefixes>
  prefix_ipv6:
    - name: <str; required; unique>
      prefixes: 
        - <list of IPv6 prefixes>
```
The prefix match-lists don't use sequence numbers
