### ISSUE TITLE
Add support for MSS-G

### ISSUE THREAD

**Issue by colinmacgiolla** [aristanetworks/ansible-avd#3769]
### Enhancement summary

The  Group-Based Segment security feature provides the convenience of applying policies on segments rather than interfaces or subnets. 
* Hosts/networks are classified into segments based on prefixes. 
* Grouping prefixes into segments allows for definition of policies that govern flow of traffic between segments. 
* Policies define inter-segment or intra-segment communication rules, e.g. segment A can communicate with segment B but hosts in segment B cannot communicate with each other.

Using [MSS-G](https://www.arista.com/en/support/toi/eos-4-25-2f/14702-group-based-multi-domain-segmentation-services-mss-group) requires the following;
1. Defining the segments - see #3768 
2. Defining the policies, per-VRF
3. Enabling `segment-security`
4. (optionally) - enabling the hardware counters on 7280R3 series devices #3755 
5. (optionally) - defining custom policies 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

A typical use case would be allowing only backup traffic between hosts, and the backup servers within the same VLAN/subnet e.g. the hosts can communicate with the servers, and the server to the hosts, but no other traffic is allowed. Additionally only specific ports are allowed to communicate, providing tighter segmentation than alternative solutions can provide e.g. PVLANs

The configuration looks like this:
```shell
match-list input prefix-ipv4 BACKUP-CLIENTS
   match prefix-ipv4 100.1.0.0/25
!
match-list input prefix-ipv4 BACKUP-SERVER
   match prefix-ipv4 100.1.0.2/32
   match prefix-ipv4 100.1.0.3/32
   match prefix-ipv4 100.1.0.4/32
   match prefix-ipv4 100.1.0.5/32
!
hostname XXX
...
interface Management1
   no shutdown
   vrf MGMT
   ip address A.B.C.D/24
!
application traffic recognition
   application l4 dst-app-backup
      protocol tcp udp destination port field-set fs-backup
   !
   application l4 src-app-backup
      protocol tcp udp source port field-set fs-backup
   !
   field-set l4-port fs-backup
      8111, 9400-9401, 9403
!
router segment-security
   no shutdown
   !
   policy policy-src-CLIENT
      10 application dst-app-backup action forward stateless
   !
   policy policy-src-SERVER
      10 application src-app-backup action forward stateless
   !
   vrf default
      segment BACKUPS
         definition
            match prefix-ipv4 BACKUP-CLIENTS
         !
         policies
            from SERVER policy policy-src-SERVER
      !
      segment SERVER
         definition
            match prefix-ipv4 BACKUP-SERVER
         !
         policies
            from BACKUPS policy policy-src-CLIENT
!
ip routing
```

### Describe the solution you would like

We need the following to solve this:
1. Extend match-lists to cover IPv4 and IPv6 prefixes
2. Allow generation of `application traffic recognition` configuration
3. Allow generation of `router segment-security` configuration

The existing match-lists can just be extended as per #3768 

We need to define a datamodel for the traffic recognition and segment-security

I would propose the following schema for traffic recognition:
```yaml
application_traffic_recognition:
  application:
    l4:
      - name: <STRING>
        protocol: 
          - <tcp | udp >
        source: <name of field set>
        destination: <name of field set>
  field_set:
     ipv4:
     - name: <string>
        - <list of prefixes>
       
    l4_port: 
     - name: <string>
        - <list of port numbers or ranges>
```
This represents a subset of the available options, but is sufficient for an initial build.

For `segment_security` I'm thinking something like this:
```yaml
router_segment_security:
  enabled: <bool>
  segments:
    - name: <string> 
      vrf: <string>
      segment_definition:
        - <names of match-lists>
      policies:
        - from: <name of source segment>
          policy: <name of policy to be applied>        
   ```

### Additional context

Depends partially on #3768 and #3755 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
We already cover `application_traffic_recognition` in `eos_cli_config_gen`.

**Comment by colinmacgiolla** [comment]
must be going blind - it'll need to be extended to cover the `l4` use-case though - I think the `ipv4` option is just on the WAN devices... which is hardcoded into the template at the moment :(

**Comment by ClausHolbechArista** [comment]
> must be going blind - it'll need to be extended to cover the `l4` use-case though - I think the `ipv4` option is just on the WAN devices... which is hardcoded into the template at the moment :(

Maybe add `l4_applications` if the schema is very different. Then we can rename the existing `applications` to `ipv4_applications` or whatever? @gmuloc

**Comment by gmuloc** [comment]
just add `l4_applications` at the same level as `ipv4_applications` inside `applications`:
https://github.com/aristanetworks/avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/application_traffic_recognition.schema.yml#L78

So

```
application_traffic_recognition:
 applications:
     ipv4_applications: <list> # exist
     l4_applications: <list> # TODO for you
```

if the structure is very similar to the `ipv4_applications` we may look into having a defs to target.

We can discuss on some call if you want @colinmacgiolla

**Comment by colinmacgiolla** [comment]
Happy with the `router_segment_security` schema @ClausHolbechArista ?

**Comment by colinmacgiolla** [comment]
> just add `l4_applications` at the same level as `ipv4_applications` inside `applications`: https://github.com/aristanetworks/avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/schemas/schema_fragments/application_traffic_recognition.schema.yml#L78
> 
> So
> 
> ```
> application_traffic_recognition:
>  applications:
>      ipv4_applications: <list> # exist
>      l4_applications: <list> # TODO for you
> ```
> 
> if the structure is very similar to the `ipv4_applications` we may look into having a defs to target.
> 
> We can discuss on some call if you want @colinmacgiolla

Its basically a subset - we don't have the source/destination prefixes, but the rest looks to be the same

**Comment by colinmacgiolla** [comment]
> Happy with the `router_segment_security` schema @ClausHolbechArista ?

As discussed, some small changes:
```yaml
router_segment_security:
  enabled: <bool>
  vrfs:
    - name: <str>
      segments:
        - name: <string> 
           segment_definition:
            - <names of match-lists>
           policies:
            - from: <name of source segment>
              policy: <name of policy to be applied> 
```
