### ISSUE TITLE
eos_cli_config_gen: Add support to configure PEG DR election algorithm

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#3787]
### Enhancement summary

Add support to configure DR election algoriths as described in the TOI:
https://www.arista.com/en/support/toi/eos-4-27-1f/14899-pim-external-gateways-pegs
```
vrf X      
  evpn multicast
         gateway dr election algorithm modulus / hrw / preference
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Configuring other PEG DR elections under evpn multicast address family.

### Describe the solution you would like

Extend current support under bgp -> vrfs -> evpn_multicast to support these configurations.
https://avd.arista.com/4.6/roles/eos_cli_config_gen/docs/input-variables.html#router-bgp
```
  vrfs:

      # VRF name
    - name: <str; required; unique>

      # Route distinguisher
      rd: <str>
      evpn_multicast: <bool>

      # Enable per-AF EVPN multicast settings
      evpn_multicast_address_family:
        ipv4:

          # Enable EVPN multicast transit mode
          transit: <bool>
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
