### ISSUE TITLE
logging.j2 stops rendering at buffered

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#380]
## Issue Type

- Bug Report

## Summary

rendering logging config stops at buffered, ignoring everything including buffered and bellow

## Role or Module Name

 logging.j2 in role "eos_l3ls_evpn"

`arista.avd` collection and Python libraries version

```shell
$ pip freeze
ansible==2.9.2
apache-libcloud==2.8.0
argcomplete==1.8.1
attrs==19.3.0
Automat==0.8.0
blinker==1.4
certifi==2019.11.28
chardet==3.0.4
Click==7.0
cloud-init==20.2
colorama==0.4.3
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.8
dbus-python==1.2.16
distro==1.4.0
distro-info===0.23ubuntu1
dnspython==1.16.0
entrypoints==0.3
httplib2==0.14.0
hyperlink==19.0.0
idna==2.8
importlib-metadata==1.5.0
incremental==16.10.1
isc==2.0
Jinja2==2.10.3
jmespath==0.9.4
jsonpatch==1.22
jsonpointer==2.0
jsonschema==3.2.0
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lockfile==0.12.2
MarkupSafe==1.1.0
more-itertools==4.2.0
netaddr==0.7.19
netifaces==0.10.4
ntlm-auth==1.1.0
oauthlib==3.1.0
packaging==20.4
pluggy==0.13.1
ply==3.11
py==1.9.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycrypto==2.6.1
PyGObject==3.36.0
PyHamcrest==1.9.0
PyJWT==1.7.1
pykerberos==1.1.14
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==2.4.7
pyrsistent==0.15.5
pyserial==3.4
pytest==5.3.4
pytest-html==2.0.1
pytest-metadata==1.10.0
python-apt==2.0.0+ubuntu0.20.4.1
python-debian===0.1.36ubuntu1
pywinrm==0.3.0
PyYAML==5.3.1
requests==2.22.0
requests-kerberos==0.12.0
requests-ntlm==1.1.0
requests-unixsocket==0.2.0
SecretStorage==2.3.1
selinux==3.0
service-identity==18.1.0
simplejson==3.16.0
six==1.14.0
ssh-import-id==5.10
systemd-python==234
treelib==1.5.5
Twisted==18.9.0
ubuntu-advantage-tools==20.3
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
wadllib==1.3.3
wcwidth==0.2.5
xmltodict==0.12.0
zipp==1.0.0
zope.interface==4.7.1

ansible --version
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/kmueller/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
```

## OS / Environment

__EOS Version__

 vEOS-LAB-4.24.3M

__Cloudvision version__

2020.2.3

__OS running Ansible__

Ubuntu 20.04.1 LTS

## Steps to reproduce

Add the following lines to the DC1.yml and execute playbook "ansible-playbook playbooks/dc1-fabric-deploy-cvp.yml --tags build"

It seems that looging.j2 in role "eos_l3ls_evpn" misses some logging parameters in comparison to logging.j2 in role "eos_cli_config_gen"

```
logging:
  console: informational
  monitor: debugging
  buffered:
    size: 1000
    level: informational
  trap: informational
  format:
    timestamp: high-resolution
    hostname: fqdn
    sequence_numbers: true
  source_interface: Management1
  vrfs:
    MGMT:
      source_interface: Management1
      hosts:
        - 192.168.1.99
        - 192.168.2.99
```

### Expected results

```shell
$
logging console informational
logging monitor debugging
logging buffered 1000 informational
logging format hostname fqdn
logging format sequence-numbers
logging vrf mgmt host 192.168.1.99
logging vrf mgmt host 192.168.2.99
logging format timestamp high-resolution
logging source-interface Management1
```

### Actual results

```shell
logging console informational
logging monitor debugging
```
