### ISSUE TITLE
Feat(eos_cli_config_gen): Add IPsec and NAT options to `tunnel_interfaces`

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3824]
### Enhancement summary

Some new functionality is needed for tunnel interfaces

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Want to configure this:

```
interface Tunnel99
   mtu 1394
   ip address 20.99.1.1/24
   ip nat service-profile vrf-aware-nat  <<<<<<<<<<<<<<<<<<< missing
   tunnel mode ipsec                               <<<<<<<<<<<<<<<<<<< missing
   tunnel source interface Ethernet2
   tunnel destination 199.168.148.132
   tunnel ipsec profile ipsec00                  <<<<<<<<<<<<<<<<<<< missing
!
```

### Describe the solution you would like

Add new keys to the model and relevant template / documentation

```
tunnel_interfaces:

    # Tunnel Interface Name
  - name: <str; required; unique>
    description: <str>
    # NEW KEYS BELOW
    tunnel_mode: < [ipsec, gre] ; no default>
    ipsec_profile:  <str> # Add a description stating it is used only when tunnel_mode is set to ipsec and that it must target a defined IPsec profile
    nat_profile: <str> # Same it must target an existing NAT profile
    # END OF NEW KEYS
    # Keep eos_cli at the end
```

### Describe alternatives you have considered

`eos_cli` but need better

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
