### ISSUE TITLE
Feat(eos_cli_config_gen): Support port-only option in IP NAT pools

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#3825]
### Enhancement summary

Add support for `port-only` NAT pools

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
ip nat pool PORT_ONLY_POOL port-only <<<<<<<<<< port-only option
   port range 1500 65535
!
```

https://avd.sh/en/stable/roles/eos_cli_config_gen/docs/input-variables.html#ip-nat

### Describe the solution you would like

This requires two things:

1. remove required for prefix_length
2. Add a new boolean flag for port-only

Expected behavior, if `port_only` is set to True the rest is ignored

Updated model
```
ip_nat:
  pools:
    - name: <str; required; unique>
      type: <str; "ip-port" | "port-only"; default="ip-port">
      prefix_length: <int; 16-32; required>  <<<<<<<<<<<<<<  remove required, add in description it is only used when 
      ranges:

          # IPv4 address
        - first_ip: <str; required> <<<<<<<<<<<<<<  remove required, add in the description "required when type is 'ip-port' and ignored otherwise."
          # IPv4 address
          last_ip: <str; required> <<<<<<<<<<<<<<  remove required, add in the description "required when type is 'ip-port' and ignored otherwise."
          first_port: <int; 1-65535>
          last_port: <int; 1-65535>. <<<<<<<<<<<<<< Make sure the description idnicates it is required when first_port is set
      utilization_log_threshold: <int; 1-100>
```

## Implementation remarks

1/ in the EOS CLI the order is first to render the entries of type `ip-port` and then the entries of type `port-only` so make sure to capture this in the template. You can leverage `group by "type"` from Jinja for this.

2/ When the type is `ip-port`, the range command is `range <ip start> <ip end> [<port start> <port end>]` whereas when the type is `port-only`, the range command is `port range <port-start> <port-end>`

### Describe alternatives you have considered

`eos_cli` but not ideal

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
