### ISSUE TITLE
Feat(eos_cli_config_gen): Support activity polling-interval for multicast

### ISSUE THREAD

**Issue by kornoa** [aristanetworks/ansible-avd#3879]
### Enhancement summary

Support "activity polling-interval" under "router multicast" for IPv4 and IPv6

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Change EOS default polling interval for multicast hardware bits.

### Describe the solution you would like

Embed into existing structured config:

````yaml
router_multicast:
  ipv4:
    activity_polling_interval: 20
  ipv6:
    activity_polling_interval: 20
````

Intended CLI config:

````code
router multicast
   ipv4
      activity polling-interval 20
   ipv6
      activity polling-interval 20
````

### Describe alternatives you have considered

none

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
