### ISSUE TITLE
eos_designs: missing monitor_sessions definition for l3_interfaces

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#3888]
### Enhancement summary

There is no possibility to define / use the provided `monitor_sessions` also for `l3_interfaces`.

### Which component of AVD is impacted

eos_designs

### Use case example

We have a DANZ monitoring fabric connected to our L3LS fabric. The monitoring sessions are configured genericly under port_profiles for all out connected endpoints.

At the time of this writing it's not possible to also re-use the existing YML nodes to enable a monitoring port for a l3_interface.

`monitoring_session` key is only supported for:

```
<connected_endpoints_keys.key>:
network_ports:
port_profiles
```

### Describe the solution you would like

```yaml
network_services_keys.name>:
  - name: foo
    vrfs:
      - name: red
        l3_interfaces:
          - interfaces: Eth1
            monitor_sessions:
              - name: DMF
                role: source
                source_settings:
                  direction: both
```

### Describe alternatives you have considered

Workaround is to use the `structured_config` field

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
