### ISSUE TITLE
eos_designs not honoring all vlan_translations keys for PortChannel interfaces

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#3907]
### Issue Summary

Creating a vlan_translations mapping using structured_config is applied properly to individual Switchports but not on the PortChannel port.

EOS CLI reference https://www.arista.com/en/um-eos/eos-virtual-lans-vlans#xx1264429

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

Using version v4.7.0-29-gc505a7eab

#### Port Profile

```yaml
port_profiles:
  ##### parent port-profiles to be inherited by device related port-profiles #####
  - profile: port_profile_DOT1Q_EDGE
    mode: trunk
    spanning_tree_bpdufilter: false
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge
    storm_control:
      broadcast:
        level: 1
        unit: percent
      multicast:
        level: 1
        unit: percent
      unknown_unicast:
        level: 1
        unit: percent
    monitor_sessions:
      - name: DMF
        role: source
        source_settings:
          direction: both

  - profile: port_profile_L2_TRANSLATION_CUSTOMER
    parent_profile: port_profile_DOT1Q_EDGE
    spanning_tree_bpdufilter: false
    spanning_tree_bpduguard: false
    spanning_tree_portfast: null
    vlans: "400,401"
    port_channel:
      description: PortChannel
      mode: active
    structured_config:
      vlan_translations:
        - from: 400
          to: 1400
          direction: both
        - from: 401
          to: 1401
          direction: both
```

#### Connected Endpoint
```yaml
---
l2_switches:
  - name: CUSTOMER_400
    adapters:
      - profile: port_profile_L2_TRANSLATION_CUSTOMER
        endpoint_ports:
          - GiX/Y/Z
          - GiX/Y/Z
        switch_ports:
          - Ethernet29
          - Ethernet29
        switches:
          - spline-rz1-01.DC.TS
          - spline-rz2-02.DC.TS
```

### Relevant log output

The generated CLI configuration looks like:

```console

interface Port-Channel29
   description CUSTOMER_400_PortChannel
   no shutdown
   switchport
   switchport trunk allowed vlan 400,401
   switchport mode trunk
   mlag 29
   storm-control broadcast level 1
   storm-control multicast level 1
   storm-control unknown-unicast level 1
!
interface Ethernet29
   description CUSTOMER_400_GiX/Y/Z
   no shutdown
   switchport vlan translation 400 1400
   switchport vlan translation 401 1401
   channel-group 29 mode active
!
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by c-po** [comment]
Indenting the vlan_translation config one more level to be below `port_channel`:

```yaml
port_profiles:
  - profile: port_profile_L2_TRANSLATION_CUSTOMER
    parent_profile: port_profile_DOT1Q_EDGE
    spanning_tree_bpdufilter: false
    spanning_tree_bpduguard: false
    spanning_tree_portfast: null
    vlans: "400,401"
    port_channel:
      description: PortChannel
      mode: active
      structured_config:
        vlan_translations:
          - from: 400
            to: 1400
            direction: both
          - from: 401
            to: 1401
            direction: both
```

Renders a proper CLI configuration:

```console
interface Port-Channel29
   description CUSTOMER_400_PortChannel
   no shutdown
   switchport
   switchport trunk allowed vlan 400,401
   switchport mode trunk
   switchport vlan translation 400 1400
   switchport vlan translation 401 1401
   mlag 29
   storm-control broadcast level 1
   storm-control multicast level 1
   storm-control unknown-unicast level 1
 !
interface Ethernet29
   description CUSTOMER_400_GiX/Y/Z
   no shutdown
   channel-group 29 mode active
!
```

So this is more of a small "cosmetic" issue then a real bug @ClausHolbechArista
