### ISSUE TITLE
Feat(eos_cli_config_gen): BGP add redistribute option under address_family_ipv4

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#3928]
### Enhancement summary

The keys are available in other address families, but are missing for ipv4.  The expectation was probably that users could set `ipv4_unicast: true`

```
router_bgp:
        bgp:
          default:
            ipv4_unicast: false
         address_family_ipv4:
           redistribute_routes:
             - source_protocol: connected
               route_map: RM-CONN_TO_BGP
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Connected networks in the default vrf should be advertised into bgp.

### Describe the solution you would like

reuse the same keys from other address families.

```
router_bgp:
        bgp:
          default:
            ipv4_unicast: false
         address_family_ipv4:
           redistribute_routes:
             - source_protocol: connected
               route_map: RM-CONN_TO_BGP
```

In the alternative, implement either `eos_cli:` or `structured_config:` under `address_family_ipv4:`

### Describe alternatives you have considered

This can be implemented today with the following keys 
```
      eos_cli: |-
        router bgp 12345
          address-family ipv4
            redistribute connected route-map RM-CONN_TO_BGP
```       

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
