### ISSUE TITLE
Feat(eos_designs): Support of IPv6 range for vtep_diagnostic

### ISSUE THREAD

**Issue by bjmeuer** [aristanetworks/ansible-avd#3936]
### Enhancement summary

Today the diagnostic VTEP can only have an IPv4 address, but it is useful also to have IPv6 address capabilities. 

### Which component of AVD is impacted

eos_designs

### Use case example

IPv6 loopback diagnostics would be useful in case we only have IPv6 addressing in a VRF, it also can be used in case of DHCP Relay for IPv6 in anycast GW use-case.

### Describe the solution you would like

Introduce a new key like this:

```
<network_services_keys.name>:
  - name: <str; required; unique>
    vrfs:
      - name: <str; required; unique>
        vtep_diagnostic:
          ...
          loopback_ipv6_range: <str>
```

Else the logic should follow the IPv4 approach.

### Describe alternatives you have considered

Using structured_config for every single leaf works, but depending on the amount of leaves it is quite some extra lines. If it can be done with just one line in the network service this would be preferred.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
