### ISSUE TITLE
Add platform support for AWE5510/5310

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#3939]
### Enhancement summary

When trying to deploy configurations with AVD in these platforms:

1) BGP update wait install command is not supported on this platform.
2) Management interface is named "Management1/1"

We should add natively support for these platforms and adjust their defaults. Likely this will be the same on 7200R new series, but im unable to test.

### Which component of AVD is impacted

eos_designs

### Use case example

Using AVD to deploy SDWAN on these switches.

### Describe the solution you would like

Update platform settings to support these devices:
https://github.com/aristanetworks/avd/blob/devel/ansible_collections/arista/avd/roles/eos_designs/schemas/schema_fragments/platform_settings.schema.yml

### Describe alternatives you have considered

I am currently using the following workaround:

```
platform_settings:
# Custom platform settings
- platforms:
  - AWE
  default_interface_mtu: 1500
  management_interface: Management1/1 <--
  feature_support:
    bgp_update_wait_install: false <--
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
