### ISSUE TITLE
Banner template has rstrip function configured and remove some lines

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#394]
## Issue Type

- Bug Report

## Summary

When setting a login banned using multilines, delimiter is not set correctly in the output

Initially reported by @mpergament

## Role or Module Name

`arista.avd` collection and Python libraries version

## Steps to reproduce

```yaml
banners:
  login: |-
    My first banner line
    Connected to Device $(hostname) EOF
```

### Expected results

```eos
!
banner login
My first banner line
    Connected to Device $(hostname) EOF
!
```

### Actual results

```eos
banner login
My first banner line
    Connected to Device $(hostname) EOF!
```
