### ISSUE TITLE
Feat(eos_designs): add option for ip igmp snooping fast-leave

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#3942]
### Enhancement summary

Add key to enable ip igmp snooping vlan <x> fast-leave when 
```
evpn_l2_multicast: 
  enabled:  true
  ```
  is configured

### Which component of AVD is impacted

eos_designs

### Use case example

When deploying l2 multicast, configuration stanzas are issued for:
```
ip igmp snooping vlan 1234 querier
ip igmp snooping vlan 1234 querier address 1.2.3.4
```
There is a need to add `ip igmp snooping vlan 1234 querier` 

### Describe the solution you would like

Add the key `fast-leave` to the existing tenant configuration:

```
            igmp_snooping_querier:
              # Will be enabled automatically if "evpn_l2_multicast" is enabled.
              enabled: < true | false | default false >
              source_address: < ipv4_address -> default ip address of Loopback0 >
              version: < 1, 2, 3 -> default 2 (EOS) >
```

### Describe alternatives you have considered

We can generate the configuration with:

```
            eos_cli: |
              ip igmp snooping vlan 123 fast-leave
              ip igmp snooping vlan 1234 querier version 3
              ip igmp snooping vlan 1234 fast-leave
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
