### ISSUE TITLE
Feature(eos_designs) add feature to specify loopback for OSPF RID

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#3963]
### Enhancement summary

ospf config stanza has a router_id key. This requires an IP address of an interface on the host for the entry. 

```
# IPv4 Address
      router_id: <str>
```

Customers routinely use a specific interface for defining the RID.  An `ospf_router_id_source_interface:` option that substitutes the address of the source interface.  This would simplify configs and follow user practices.

### Which component of AVD is impacted

eos_designs

### Use case example

Configure OSPF RID without manually copying address info.

### Describe the solution you would like

Customer that defines a specific RID for a given process ID.

This PR asks for a change to eos_designs, but it sits between `eos_designs` and `eos_cli_config_gen`. An `eos_cli_config_gen` key of `ospf_rid_source_interface` make sense from a usability perspective, but it is not a direct rendering to a config.  

### Describe alternatives you have considered

This can be done today by copying thr address of the interface to the `router_id` key

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Implemented support for pointing to vtep diagnostic or general router id in #4775.

Abbreviated snip from docs:
```yaml
tenants:
  - <...>
    vrfs:
      - <...>
        ospf:
          # Router ID to use for OSPF in this VRF.
          # This can be an IPv4 address, "main_router_id", "none" or "diagnostic_loopback".
          # - "main_router_id" will use the IP address of Loopback0 or the common `router general` Router ID if `use_router_general_for_router_id` is set."
          # - "none" will not configure a OSPF Router ID for this VRF. EOS will use the main OSPF Router ID.
          # - "diagnostic_loopback" will use the IP address of the VRF Diagnostic Loopback interface.
          router_id: <str; default="main_router_id">
```
