### ISSUE TITLE
Enable option to activate BGP neighbors based on peer group instead of ipv4 address

### ISSUE THREAD

**Issue by bdugg21** [aristanetworks/ansible-avd#3972]
### Enhancement summary

please detail your feature enhancement

### Which component of AVD is impacted

eos_designs

### Use case example

Need the ability to modify how a neighbor is activated. Currently IPv4 is the only option.

### Describe the solution you would like

neighbor activation key with value options of ipv4 address or peer-group

### Describe alternatives you have considered

eos cli gen overrides

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
We have added this recently in #3887 (v4.8.0 should have it).

Please test it out and let me know if it works out for you. 

Note that EOS does not show the address familiy configs under the VRFs for peer-groups. The config will show up in the global context, but if a VRF neighbor is associated with the peer-group, the peer-group activation will be applied in the VRF AF as well.

```yaml
tenants:
  - name: mytenant
    bgp_peer_groups:
      - name: mybgppeergroup
        <...>
        address_family_ipv4:
          activate: true
    vrfs:
      - name: myvrf
        bgp_peer_groups:
          - name: myotherbgppeergroup
            <...>
            address_family_ipv6:
              activate: true
```
