### ISSUE TITLE
Feat(eos_designs) add option to configure ospf for p2p_links and p2p_links_profiles

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#3981]
### Enhancement summary

Neither `core_interfaces:` nor `l3_edge:` support configuring `ospf`.   There exists the option to configure the interface portion via `structured_config:`

```
      structured_config:
        ospf_network_point_to_point: true
        ospf_area: 0.0.0.1
```

This, however, still requires configuring the routing process separately, which can be done under `network_services:`

```
default:
  - name: "default"
    vrfs:
       - name: "default"       
          ospf:
            enabled: true

            process_id: 123
            nodes:
              - SW1
              - SW2
              - SW3
              - SW4
```

It would be valuable to have the option to configure the ospf options on the link and have `eos_designs` add the link to the appropriate `router_ospf` instance.

### Which component of AVD is impacted

eos_designs

### Use case example

There are numerous cases where the underlay routing is not uniform.  Customers using non-fully meshed iBGP frequently use OSPF to provide routing to peering loopbacks.  OSPF is also frequently used for multi-path reachability to specialized networks, such as OOB management networks.

### Describe the solution you would like

Provide the existing ospf interface keys to `p2p_links`, (with the addition of the router_ospf process id) and in addition to configuring the interface, add the `router_ospf` process and add the interface to the non-passive interface list if necessary. 

### Describe alternatives you have considered

This can be achieved by configuration in multiple places.  Configuration of structured config on the p2p_links, along with configuring the router_ospf instance under network_services works, but is prone to errors.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
