### ISSUE TITLE
Feat(eos_designs): add option uplink_mtu under the node config

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#3985]
### Enhancement summary

It is currently not possible to set the uplink mtu to dedicated leaf node or node group.

Add `uplink_mtu`for node_group and node settings.

### Which component of AVD is impacted

eos_designs

### Use case example

```
    - group: DISTRI_12
      bgp_as: 65412
      uplink_mtu: 9000
      filter:
        tenants: [all]
      nodes:
        - name: distri-12-01
          id: 11
          mgmt_ip: x.x.x.x
          uplink_switch_interfaces: ['Ethernet9', 'Ethernet9']
        - name: distri-12-02.LAN.MU
          id: 12
          mgmt_ip: x.x.x.x
          uplink_switch_interfaces: ['Ethernet10', 'Ethernet10']
```

### Describe the solution you would like

 ```
  # Define variables related to all nodes part of this group.
  node_groups:
      # Override the default `uplink_mtu` set at the `node_type_key` level.
      uplink_mtu: <str>

      # Define variables per node.
      nodes:
          # The Node Name is used as "hostname".
        - name: <str; required; unique>

          # Override the default `uplink_mtu` set at the `node_type_key` level.
          uplink_mtu: <str>
  ```
  

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
