### ISSUE TITLE
eos_cli_config_gen: dot1x captive portal and supplicant logging

### ISSUE THREAD

**Issue by lateefwalana** [aristanetworks/ansible-avd#4006]
### Enhancement summary

We are implementing dot1x and some missing variables. We need to generate the following config

```eos
dot1x
   captive-portal url http://portal-nacm08/captiveredirect/
   supplicant logging
```

to work around it it we are using:

```yaml
eos_cli: |
  dot1x: 
    supplicant logging 
    captive-portal url http://portal-nacm08/captiveredirect/
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

to work around it it we are using:

```yaml
eos_cli: |
  dot1x: 
    supplicant logging 
    captive-portal url http://portal-nacm08/captiveredirect/
```

### Describe the solution you would like

If model can be extended to support above that will be very useful 
https://avd.arista.com/4.7/roles/eos_cli_config_gen/docs/input-variables.html?h=dot1x#__tabbed_22_2

### Describe alternatives you have considered

```yaml
eos_cli: |
  dot1x: 
    supplicant logging 
    captive-portal url http://portal-nacm08/captiveredirect/
```

### Additional context

dot1x global configuration 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
