### ISSUE TITLE
Feat(eos_cli_config_gen):  Add knob for ospf_type when redistributing ospf into bgp.

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#4014]
### Enhancement summary

There is a need to render the following BGP config:

```
router bgp xxxx
   redistribute ospf match internal route-map RM_OSPF_INT_TO_BGP
   redistribute ospf match external route-map RM_OSPF_EXT_TO_BGP
```

For isis, we have the needed functionality through a key `ospf_route_type`

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Render an existing configuration.

### Describe the solution you would like

I would like to see the same pattern as we have for isis, but with bgp. 
```
        redistribute_routes:
          - source_protocol: "ospf"
            route_map: RM_OSPF_TO_BGP
            ospf_route_type: "external"
          - source_protocol: "ospf"
            route_map: RM_OSPF_TO_BGP
            ospf_route_type: "internal"
```            

### Describe alternatives you have considered

This can be done today with `eos_cli:`

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
