### ISSUE TITLE
Feat(eos_cli_config_gen): Support of static IPv6 neighbor entries

### ISSUE THREAD

**Issue by bjmeuer** [aristanetworks/ansible-avd#4041]
### Enhancement summary

Today there is no support for static IPv6 neighbor entries (static ARP for IPv4 is possible today):

            `ipv6 neighbor vrf <vrf_name> <IPv6 address> <out interface> <mac address>`

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

DC with Dual-Stack Hosts and design requires a view static entries. 

### Describe the solution you would like

Introduce a similar model as it exists for static ARP entries already:

```
ipv6_neighbor:
  static_entries:
      # Neighbor IPv6 address
    - ipv6_address: <str; required>
      # Neighbor entry VRF.
      vrf: <str>
      # Outgoing Interface.
      interface: <str; required>
      # Neighbor MAC address.
      mac_address: <str; required>
```
      

### Describe alternatives you have considered

```
raw_eos_cli: |
  ipv6 neighbor vrf <vrf_name> <IPv6 address> <outgoing interface> <mac address>
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
