### ISSUE TITLE
managment_ssh generation not including vrf in cli syntax.

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#409]
## Issue Type

- Bug Report

## Summary

eos_cli_config_gen `managment_ssh:` cli generation not including proper vrf syntax.

## Role or Module Name

- eos_cli_config_gen

### `arista.avd` collection and Python libraries version

ansible-avd v1.1.1

## Steps to reproduce

```yaml
management_ssh:
  access_groups:
    - name: ACL-SSH
    - name: ACL-SSH-VRF
      vrf: mgt
  idle_timeout: 15
  enable: true
  vrfs:
    mgt:
      enable: true
```

### Expected results

```eos
management ssh
   ip access-group ACL-SSH in
   ip access-group ACL-SSH-VRF vrf mgt in
   idle-timeout 15
   no shutdown
   !
   vrf mgt
      no shutdown
```

### Actual results

```eos
management ssh
   ip access-group ACL-SSH in
   ip access-group ACL-SSH-VRF in
   idle-timeout 15
   no shutdown
   !
   vrf mgt
      no shutdown
```

reported by @aphillipps
