### ISSUE TITLE
Add option to disable  default 'redistribute connected ' in VRF.

### ISSUE THREAD

**Issue by psmirnov-arista** [aristanetworks/ansible-avd#4091]
### Enhancement summary

Add option to disable  default 'redistribute connected ' in VRF.

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

MPLS topology . Customer does not want to see connected routes in RT.

### Describe the solution you would like

We need an option per VRF to disable 'redistribute connected'.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
We have limited resourced and decided to push this out to a later 5.x release.

From AVD 5.0 this can be worked around easily with:

```
tenants:
  - name: mytenant
    vrfs:
      - name: myvrf
        bgp:
          structured_config:
            redistribute:
              connected:
                enabled: false
```

Note that this workaround will *not* work on older releases.
