### ISSUE TITLE
Support for IPv6 addresses in Network service VRF L3 interfaces

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#4186]
### Enhancement summary

We currently do not support defining IPv6 addresses under tenant L3 interfaces:

https://avd.arista.com/4.9/roles/eos_designs/docs/input-variables.html#network-services-vrf-l3-interfaces-configuration
```
        l3_interfaces:
          - interfaces:

                # Interface name.
              - <str>

            # For sub-interfaces the dot1q vlan is derived from the interface name by default, but can also be specified.
            encapsulation_dot1q_vlan:
              - <int; 1-4094>
            ip_addresses:

                # IPv4_address/Mask.
              - <str>
 ```

It is possible to use structured_configuration but ideally it should not be required.

### Which component of AVD is impacted

eos_designs

### Use case example

We need to create PE-CE IPV6 interfaces for MPLS ISIS-LDP deployment with VPNv6.

### Describe the solution you would like

Similar to current IPv4 support, it would be nice to be able to define a list of IPv6 addresses.
```
            ip_addresses: [10.10.100.2/31]
```

### Describe alternatives you have considered

Currently using the following but i can only define one interface at a time:
```
        l3_interfaces:
          # L3 interfaces
          - interfaces: [Ethernet1]
            nodes: [ISP-A-PE1]
            description: "CE-A-1 L3 service"
            enabled: true
            ip_addresses: [10.10.100.0/31]
            structured_config:
              ipv6_enable: true
              ipv6_address:
                fc00:100::0/127
          - interfaces: [Ethernet1]
            nodes: [ISP-A-PE2]
            description: "CE-A-1 L3 service"
            enabled: true
            ip_addresses: [10.10.100.2/31]
            structured_config:
              ipv6_enable: true
              ipv6_address:
                fc00:100::2/127
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
