### ISSUE TITLE
Support for IPVPNv6 via eos_designs

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#4187]
### Enhancement summary

We currently can configure MPLS VPNv6 using eos_cli_configuration but not via standard eos_design automation.

We can configure in tenants AF VPNv6 but it will not enable the configuration as we do with VPNv4:
```
TenantA:
  - name: "TenantA"
    vrfs:
      - name: "RED"
        vrf_id: 10
        address_families:
          - vpn-ipv4
          - vpn-ipv6
```

1) enable address vpnv6 family in RR and PEs
2) enable unicast routing on the VRFs
3) add RT configuration for vpnv6

Currently we need the following:

1) Enable AF:

1.1) RR
```
custom_structured_configuration_router_bgp:
  address_family_vpn_ipv6:
    peer_groups:
      - name: MPLS-OVERLAY-PEERS
        activate: true
      - name: RR-OVERLAY-PEERS
        activate: true
```
1.2) PE:
```
custom_structured_configuration_router_bgp:
  address_family_vpn_ipv6:
    peer_groups:
      - name: MPLS-OVERLAY-PEERS
        activate: true
```
2)  Enable unicast IPv6 routing on PEs:
```
additional_vrfs:
  - name: RED
    ipv6_routing: true
  - name: BLUE
    ipv6_routing: true
```
3) Manually set RT:
```
        additional_route_targets:
          - type: import
            address_family: vpn-ipv6
            route_target: "65000.0:12"
          - type: export
            address_family: vpn-ipv6
            route_target: "65000.0:12"
```

### Which component of AVD is impacted

eos_designs

### Use case example

MPLS IPVPNv4 and IPVPNv6 deployment. We can use eos_cli_configuration to generate the required configuration, but ideally eos_designs could be used to facilitate the configuration.

### Describe the solution you would like

As described above, enable AFs, IPv6 routing and set RTs automatically via eos_designs.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
