### ISSUE TITLE
Feat(eos_designs): L2VLAN profile support

### ISSUE THREAD

**Issue by kornoa** [aristanetworks/ansible-avd#4192]
### Enhancement summary

Add a profile option for L2 VLANs within the network services

### Which component of AVD is impacted

eos_designs

### Use case example

I have to specify the same bgp.structured_config under many, many L2 VLANs on the fabric. Currently this is only possible by having a lot of duplicate code within the inventory. A profile option can rule out this amount of duplicate code and make changes easier.

### Describe the solution you would like

A profile option like it is implemented for VRF SVIs.

Example:
within NETWORK SERVICES.yml:

```yaml
<network_services_keys.name>:
  - name: <name>
    l2vlans:
      - name: TEST1
        id: 101
        profile: FABRIC_L2_VLAN_DEFAULTS

l2vlan_profiles:
  - profile: FABRIC_L2_VLAN_DEFAULTS
    tags:
       - ...
    bgp:
      structured_config:
         ...
    ...
```

### Describe alternatives you have considered

Jinja variable substitution. But this is limited to one key.
Jinja filter combine would be functional but complex. This would tough to maintain by not so experienced Ansible users.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
