### ISSUE TITLE
Clarification is needed on "input variables" to the various roles

### ISSUE THREAD

**Issue by fatpelt** [aristanetworks/ansible-avd#4197]
### Enhancement summary

maybe we can add verbiage to the "input variables" page of "eos_cli_config_gen" to indicate that the schema displayed there is the *output* from eos_designs and should be less preferred for users to use, though they can.

something like "this schema is the processed output from eos_designs.  please use the schema defined there unless it does not provide the desired functionality"

it wasn't immediately clear which of two ways to define ntp settings was preferred, when the one in eos_cli_config_gen clearly worked.  what i should have been using was the ntp_settings option described in eos_designs instead as that's the more "end-user facing" schema.

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

```
ntp:
  servers:
  - name: uk.pool1.ntp.org
    preferred: true
    vrf: "{{ mgmt_interface_vrf }}"

ntp_settings:
  servers:
    - name: uk.pool.ntp.org
```

### Describe the solution you would like

see summary

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
