### ISSUE TITLE
Add storm-control to role eos_l3ls_evpn template leaf-server-interfaces.j2

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#420]
**Issue Type**

- Template enhancement

**Describe the solution you'd like**
Ethernet interface storm-control broadcast|multicast|unknown-unicast configuration is already available with role eos_cli_config_gen/ethernet-interfaces.j2, but it would be helpful if it would be available with role eos_l3ls_evpn template leaf-server-interfaces.j2 für L3LS fabric setup too. 

**Describe alternatives you've considered**
Maybe I could use a CVP configlet assigned to the Leaf containers adding the storm-control lines to all ethernet ports per se.

**Additional context**
A server port profile within DC_SERVER.yml might look like this:

```yaml
port_profiles:
  Tenant_PROD_ESX:
    mode: trunk
    native_vlan: '100'
    vlans: 100,101,102, 103, 201, 205
    spanning_tree_bpdufilter: false
    spanning_tree_portfast: edge
    storm_control:
      broadcast:
        level: 1
        unit: percent
      multicast:
        level: 1
        unit: percent
      'unknown-unicast':
        level: 1
        unit: percent
```

Thank you
