### ISSUE TITLE
Support for BGP default timers and send-community commands

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#4218]
### Enhancement summary

We are looking to remove this commands from the fabric file:
```
bgp_defaults:
      - timers bgp 5 15
      - neighbor default send-community
```
And support them as native ansible vars. However this is not supported today via "eos_cli_config_gen" for all neighbours, only for peer-grups:

https://avd.arista.com/4.9/roles/eos_cli_config_gen/docs/input-variables.htmlhttps://avd.arista.com/4.9/roles/eos_cli_config_gen/docs/input-variables.html

```
peer_groups:

      # Peer-group name.
    - name: <str; required; unique>

      # Key only used for documentation or validation purposes.
      type: <str>
     [...]
       # 'all' or a combination of 'standard', 'extended', 'large' and 'link-bandwidth (w/options)'.
      send_community: <str>

      # BGP Keepalive and Hold Timer values in seconds as string "<0-3600> <0-3600>".
      timers: <str>
```

We would like support this also under global BGP settings, so it applies to any new peer-groups that are defined.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Remove bgp_defaults cli commands and use eos_cli_config_gen.

### Describe the solution you would like

Support the commands above under bgp general settings also.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
