### ISSUE TITLE
Feat(eos_designs): Enable static multicast on fabric links

### ISSUE THREAD

**Issue by GerardPhillips** [aristanetworks/ansible-avd#4228]
### Enhancement summary

Static multicast is useful in many M&E installations. It may be needed on uplinks. The CLI would look like this
client(config)#interface Ethernet 1
client(config-if-Et1)#multicast ipv4 static

There is already a way to enable dynamic multicast on uplinks:
underlay_multicast: true

It would be cool if we could have something that operated very similarly to "underlay_multicast: true", but for static multicast.

The AVD could look like:
underlay_multicast_ipv4_static: true
Current Issue is only for fabric links/core interfaces that involves l3 interfaces

### Which component of AVD is impacted

eos_designs

### Use case example

See enhancement summary

### Describe the solution you would like

See enhancement summary

### Describe alternatives you have considered

now we need structured config:

```yaml
ethernet_interfaces:
- name: Ethernet2
  description: P2P_LINK_TO_CORE-2-OSPF-LDP_Ethernet2
  shutdown: false
  speed: 100full
  mtu: 1601
  ip_address: [100.123.123.2/31](http://100.123.123.2/31)
  multicast:
    ipv4:
      static: true
```
### Additional context

This would be used with Arista's MCS or a 3rd party multicast SDN

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by sarunac** [comment]
This issue only addresses routed core interfaces. Will create a separate issue for,
-  L3 interfaces that connect to endpoints/hosts 
- L2 interfaces that connect to endpoints/hosts

**Comment by carlbuchmann** [comment]
After input and discussion from @GerardPhillips and @sarunac, we require more granular control on link multicast configuration.
In M&E it is common to have a mix of dynamic multicast (pim ipv4 sparse-mode) and static multicast (multicast ipv4 static) configured on different uplinks.

Also note that the original underlay_multicast was explicitly developed for EVPN OISM scenarios and didn't consider traditional L3LS Multicast networks.

Here's my proposal for various new keys to control multicast configuration. I have included the current `underlay_multicast` keys for completeness and to help with the discussion:

```yaml


### Current Global for underlay multicast was intented for EVPN OISM overlay scenarios ###

# Enable dynamic Multicast in the underlay on all p2p uplink interfaces and mlag l3 peer interface.
# Specifically PIM Sparse-Mode will be configured on all routed underlay interfaces.
# This also enables "router multicast | ipv4 routing"
# The configuration is intended to be used as multicast underlay for EVPN OISM overlay.
underlay_multicast: <bool; default=False>


### Proposed new keys ###

# Global variable can be overriden by node_type and core_interfaces specific knobs to enable/disable behavior as required.

# Enable Protocol Independent Multicast sparse mode in the underlay on all p2p uplink interfaces, mlag l3 peer interface and core interfaces.
# Specifically PIM Sparse-Mode will be configured on all routed underlay interfaces.
# This also enables "router multicast | ipv4 routing"
underlay_pim_sm_multicast: <bool; default=False> | Perhaps in the future this replaces "underlay_multicast"

# Enable Protocol Independent Multicast bidirectional in the underlay on all p2p uplink interfaces, mlag l3 peer interface and core interfaces.
# Specifically PIM bidirectional will be configured on all routed underlay interfaces.
# This also enables "router multicast | ipv4 routing"
underlay_pim_bidir_multicast: <bool; default=False> | Perhaps in the future this replaces "underlay_multicast"

# Enable static Multicast in the underlay on all p2p uplink interfaces, mlag l3 peer interface and core interfaces.
# Specifically "multicast ipv4 static" will be configured on all routed underlay interfaces.
# This also enables "router multicast | ipv4 routing"
underlay_static_multicast: <bool; default=False>

# Proposed node type variable for uplink and mlag link configuration, allows customers for granular control on interfaces.

node_type_keys.key:

  # Define variables for all nodes of this type.
  defaults:
    # Enable/Disable Protocol Independent Multicast sparse mode in the underlay on p2p uplink interfaces.
    # This also enables "router multicast | ipv4 routing"
    uplink_pim_sm_multicast: <bool; default=False>
    # Enable/Disable Protocol Independent Multicast bidirectional mode in the underlay on p2p uplink interfaces.
    # This also enables "router multicast | ipv4 routing"
    uplink_pim_bidir_multicast: <bool; default=False>
    # Enable/Disable static Multicast in the underlay on p2p uplink interfaces.
    # This also enables "router multicast | ipv4 routing"
    uplink_static_multicast: <bool; default=False>
    # Enable/Disable Protocol Independent Multicast sparse mode in the underlay on mlag interfaces.
    # This also enables "router multicast | ipv4 routing"
    mlag_pim_sm_multicast: <bool; default=False>
    # Enable/Disable static Multicast in the underlay on mlag interfaces.
    # This also enables "router multicast | ipv4 routing"
    mlag_static_multicast: <bool; default=False>


core_interfaces:
  p2p_links:
    - name:
      ### Current key ###

      # It seems odd that this would require the global `underlay_multicast to be `true`.
      # Likely because it requires "router multicast | ipv4 routing" to be configured.

      # Enable PIM sparse mode. Requires `include_in_underlay_protocol` and the global `underlay_multicast` to be `true`.
      underlay_multicast: <bool; default=False>

      ### Proposed new Keys ###

      # Enable/Disable Protocol Independent Multicast sparse mode. Requires `include_in_underlay_protocol`.
      # This also enables "router multicast | ipv4 routing", when set to true.
      underlay_pim_sm_multicast: <bool; default=False>

      # Enable/Disable Protocol Independent Multicast bidirectional mode. Requires `include_in_underlay_protocol`.
      # This also enables "router multicast | ipv4 routing"
      underlay_pim_bidir_multicast: <bool; default=False>

      # Enable/Disable static Multicast "multicast ipv4 static". Requires `include_in_underlay_protocol`.
      # This also enables "router multicast | ipv4 routing", when set to true.
      underlay_static_multicast: <bool; default=False>
```

**Comment by ClausHolbechArista** [comment]
1. The global keys should be inverted like we usually do, to make them easier to group.
So `underlay_multicast_pim_sm`

2. Nobody is asking for bidir, so I think we can skip that one for now.

3. Since we deepmerge vars under the node settings, I think we should create a nested model there:

```yaml
l3leaf:
  defaults:
    underlay_multicast:
      pim_sm:

        # Inherits from global setting `underlay_multicast_pim_sm`
        enabled: <bool>
        uplinks: <bool; default=True>
        mlag: <bool; default=True>
        # Room to grow for other settings.

      static:

        # Inherits from global setting `underlay_multicast_static`
        enabled: <bool>
        uplinks: <bool; default=True>
        mlag: <bool; default=False>
```

4. On core interfaces we should have the same `underlay_multicast` key where it will participate and follow the same logic. We can decide if we want it to inherit from global _if_ the `include_in_underlay_protocol` is `True` but it would be breaking, so I suggest we instead let people enable it manually.

**Comment by MaheshGSLAB** [comment]
The first input model
```yaml
### Current Global for underlay multicast was intented for EVPN OISM overlay scenarios ###

# Enable dynamic Multicast in the underlay on all p2p uplink interfaces and mlag l3 peer interface.
# Specifically PIM Sparse-Mode will be configured on all routed underlay interfaces.
# This also enables "router multicast | ipv4 routing"
# The configuration is intended to be used as multicast underlay for EVPN OISM overlay.
underlay_multicast: <bool; default=False>


### Proposed new keys ###

# Global variable can be overriden by node_type and core_interfaces/edge_interfaces specific knobs to enable/disable behavior as required.

# Enable Protocol Independent Multicast sparse mode in the underlay on all p2p uplink interfaces, mlag l3 peer interface and core interfaces.
# Specifically PIM Sparse-Mode will be configured on all routed underlay interfaces.
# This also enables "router multicast | ipv4 routing"
underlay_multicast_pim_sm: <bool> | Perhaps in the future this replaces "underlay_multicast"

# Enable static Multicast in the underlay on all p2p uplink interfaces, mlag l3 peer interface and core interfaces.
# Specifically "multicast ipv4 static" will be configured on all routed underlay interfaces.
# This also enables "router multicast | ipv4 routing"
underlay_multicast_static: <bool>

# Proposed node type variable for uplink and mlag link configuration, allows customers for granular control on interfaces.

node_type_keys.key:

  # Define variables for all nodes of this type.
  defaults:
    underlay_multicast:
      pim_sm:

        # Inherits from global setting `underlay_multicast_pim_sm`. Enable/Disable Protocol Independent Multicast sparse mode in the underlay on all p2p uplink interfaces, mlag l3 peer interface and core interfaces for the specific node.
        enabled: <bool>
        # Enable/Disable Protocol Independent Multicast sparse mode in the underlay on specific p2p uplink interfaces. 
        # If not set, all uplinks will be enabled. Set as an empty list to remove all uplinks.
        uplinks: <bool>
            # Interface name
          - <str>
        # Enable/Disable Protocol Independent Multicast sparse mode in the underlay on all mlag l3 peer interface and core interfaces for the specific node.
        mlag: <bool; default=True>

      static:

        # Inherits from global setting `underlay_multicast_static`. Enable/Disable static Multicast in the underlay on all p2p uplink interfaces, mlag l3 peer interface and core interfaces for the specific node.
        enabled: <bool>
        # Enable/Disable static Protocol Independent Multicast in the underlay on specific p2p uplink interfaces. 
        # If not set, all uplinks will be enabled. Set as an empty list to remove all uplinks.
        uplinks:
            # Uplink Interface name to enable for static multicast
          - <str>
        # Enable/Disable static Multicast in the underlay on all mlag l3 peer interface and core interfaces for the specific node.
        mlag: <bool; default=False>  # <-- Confirm default here.


core_interfaces/l3_edge:
  p2p_links:
    - name:
      ### Current key ###

      # It seems odd that this would require the global `underlay_multicast to be `true`.
      # Likely because it requires "router multicast | ipv4 routing" to be configured.

      # Enable PIM sparse mode. Requires `include_in_underlay_protocol` and the global `underlay_multicast` to be `true`.
      underlay_multicast: <bool; default=False>

      ### Proposed new Keys ###
      # Enable/Disable Protocol Independent Multicast sparse mode. Requires the global `underlay_multicast_pim_sm` to be `true`.
      underlay_multicast_pim_sm: <bool>

      # Enable/Disable static Protocol Independent Multicast. Requires the global `underlay_multicast_static` to be `true`.
      underlay_multicast_static: <bool>

**Comment by gmuloc** [comment]
@carlbuchmann green light for @MaheshGSLAB to start implementing this?

**Comment by carlbuchmann** [comment]
Approved, additionally, let's deprecated:

`underlay_multicast:` to be replaced with `underlay_multicast_pim_sm:`

And deprecate this key in the core_interdaces/l3edge data model

```yaml
core_interfaces/l3_edge:
  p2p_links:
    - name:
      underlay_multicast:
```

And replace with:

```yaml
core_interfaces/l3_edge:
  p2p_links:
    - name:
      underlay_multicast_pim_sm: <bool>
```
