### ISSUE TITLE
p2p_links does not generate appropriate configuration for subinterfaces

### ISSUE THREAD

**Issue by ddecker-arista** [aristanetworks/ansible-avd#4229]
### Issue Summary

When attempting to use core_interfaces/l3_edge to generate subinterface p2p links, the output configuration produces "no switchport" and mtu statements that are not supported on subinterfaces. 

```
core_interfaces:
  p2p_links_ip_pools:
    - name: egress_to_fg
      ipv4_pool: 100.99.98.0/23
  p2p_links_profiles:
    - name: overlay
      ip_pool: egress_to_fg
      include_in_underlay_protocol: true

  p2p_links:
    - nodes: [FG01a, E0101a]
      interfaces: [Ethernet49/1.101, Ethernet1/1.101]
      as: [101, 65111]
      id: 5
      profile: overlay
```
The input above produces the output below:
```
interface Ethernet1/1.101
   description P2P_LINK_TO_FG01a_Ethernet49/1.101
   no shutdown
   mtu 9214
   no switchport
   ip address 100.99.98.9/31
```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
