### ISSUE TITLE
Add primary_key in schema for monitor connectivity host

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#4263]
### Enhancement summary

Today there is no primary_key in the list
https://github.com/aristanetworks/avd/blob/dec32ba2dae18af3287f1eb54af8c43b87b4ae65/python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/monitor_connectivity.schema.yml#L46

but on EOS the host can only be unique (there is another list in each VRF)

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

use case is that it is better when overwriting EOS design with custom structured configuration

### Describe the solution you would like

```yaml
      hosts:
        type: list
        primary_key: name <<<<<<<<<<<<
        items:
          type: dict
          keys:
            name:
              description: Host Name.
              type: str
```

and same under VRF

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
