### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for "monitor server radius"

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#4273]
### Discussed in https://github.com/aristanetworks/avd/discussions/4270

<div type='discussions-op-text'>

<sup>Originally posted by **chrisgerdener** July 26, 2024</sup>
I am back with another RADIUS related question/idea.

For our fabric we are using the "monitor server radius" to probe our RADIUS servers, as described in this Arista TOI https://www.arista.com/en/support/toi/eos-4-29-2f/17031-monitoring-radius-servers-via-arista-switches

As fas as I can see this is not yet supported in AVD, therefore we are implementing it with direct configuration through eos_cli variables.

I would like to propose that this be added as a new feature to eos_cli_config_gen

The data model could look like this:

```
monitor_server:
  radius:
    service:
      dot1x:
        probe:
          interval: <int, 1-1000>
          threshold_failure: <int, 1-255>
          method:
            status_server: <bool> # set to true by default, set to false for access_request probe
            access_request:
              username: <str>
              password: <str> # Password as type 7
                            
```

What does everyone think?                  
</div>

**Comment by ClausHolbechArista** [comment]
Let's flatten the model a bit and also make sure we align more with the CLI:

```yaml
monitor_server_radius:
  service_dot1x: <bool>
  probe:
    interval: <int, 1-1000>
    threshold_failure: <int, 1-255>
    method: <str; "status-server" | "access-request">
    access_request: # Only relevant when method is 'access-request'
      username: <str>
      password: <str> # Password as type 7
```
