### ISSUE TITLE
Add capability to create non routable VLANs

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#43]
example of data model entry:

```yaml
Tenants:
  Tenant_A:
    l2vlans:
      260:
        name: VMotion
        tags: [ vmotion ]
        enabled: true
```
