### ISSUE TITLE
Support endpoint interfaces description to carry information which defined on other parts of the interfaces for Network ports in eos_designs role

### ISSUE THREAD

**Issue by forcecity** [aristanetworks/ansible-avd#4303]
### Enhancement summary

In our network, we are using the network ports format to configure the endpoints interfaces. Most of the ports are defined in port-channel pairly for 2x MLAG peers. Our endpoints will get the connected information from lldp (normally, descriptions/devices/interfaces) to decide which port-channel they will be in and according this information, they will get different configs on endpoints side. So we would like to include <channel_group_id> into the description.

By the way, for the automatically generated port-channel, we hope the port-channel id could be automatically included in description (By default each port will be configured in a port-channel with one member when leveraging automatic channel-id generation.) if we didn't define it. 

### Which component of AVD is impacted

eos_designs

### Use case example

```
  - switches:
      - switch-[ab].*
    switch_ports:
      - Ethernet1/1-2
    profile: xxx
    description: xxx_PoCH_<channel_group_id>
    port_channel:
      channel_id: 11
  ... ...
```
If we have the single port on each leaf pair member and didn't give the description key, the `channel_group_id` could be automatically added to the description:
```
  - switches:
      - switch-[ab].*
    switch_ports:
      - Ethernet1/1
    profile: xxx
```
Will be rendered as:
```
switch-a:
interface Ethernet1/1
  description Endpoints_Channel_Group_<channel_group_id>
  channel-group 11 mode active
  ... ...

switch-b:
interface Ethernet1/1
  description Endpoints_Channel_Group_<channel_group_id>
  channel-group 11 mode active
  ... ...
```

### Describe the solution you would like

Maybe define a var which can be used in description

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
