### ISSUE TITLE
Feat: (eos_designs) Create SVI with Passive OSPF Interface for L2LS design

### ISSUE THREAD

**Issue by mthiel117** [aristanetworks/ansible-avd#4325]
### Enhancement summary

In an L2LS Design, allow a simple way to enable OSPF as a passive-interface on an SVI.  By default when enabling `underlay_routing_protocol: OSPF`, we set `passive-interface default` under router ospf.  This part is good.  The issue is when enabling OSPF on an SVI, then we automatically add a no passive-interface <SVI> statement under router ospf <process id> section.  Many customers use OSPF with their L2LS designs (vrf default and non-default VRFs) and set `passive-interface default` under router ospf <process id>.  Any SVI they actually want to run OSPF, they will set as `no passive-interface <svi>`.

This allows the SVIs to be seen as OSPF routes and not have to use redistributed connected.  This should also be turned off as default behavior.  Current data model allows you to set this as false, but it is overwritten with eos_designs because there is no overlay routing protocol set with L2LS design.

### Which component of AVD is impacted

eos_designs, eos_cli_config_gen

### Use case example

Typical customer configuration.

Vlan 154 - OSPF enabled
Vlan 155 - OSPF Passive
Vlan 200 - OSPF Passive

```
interface Vlan154
   ip address 172.16.13.100/29
   ip ospf area 0.0.0.0
   ip virtual-router address 172.16.13.102
!
interface Vlan155
   ip address 172.16.13.108/29
   ip ospf area 0.0.0.0
   ip virtual-router address 172.16.13.110
!
interface Vlan200
   description 200_wireless_172.16.207.254/21
   ip ospf area 0.0.0.0
   ip virtual-router address 172.16.207.254
!
router ospf 1 vrf default
   router-id 10.1.252.1
   passive-interface default
   no passive-interface Vlan4093
   no passive-interface Vlan154
!
```

### Describe the solution you would like

I would like the following:

1. Passive Interface is set by default when using OSPF - already completed today.
2. New Key/value pair to enable an SVI to run OSPF.  Explicitly set as passive or not. Default to passive if not set.
3. Remove `redistribute connected` as default behavior in L2LS design

Proposed Data model:

```
---
tenants:
  - name: MY_FABRIC
    vrfs:
      - name: default
        ospf:
          enabled: true
          process_id: 1
          redistribute_bgp:
            enabled: False
          redistribute_connected:
            enabled: False
        svis:
          - id: 154
            name: 'vlan154'
            enabled: True
            ospf:
              enabled: True
              area: 0.0.0.0
              passive_interface: bool <default=True, False>
          - id: 155
            name: 'vlan155'
            enabled: True
            ospf:
              enabled: True
              area: 0.0.0.0
              passive_interface: bool <default=True, False>
          - id: 200
            name: 'vlan200'
            enabled: True
            ospf:
              enabled: True
              area: 0.0.0.0
              passive_interface: bool <default=True, False>
```

### Describe alternatives you have considered

Writing `custom_structured_configuration_router_ospf:`  and set the list a list of `no passive interfaces`.  This requires using a list replace function and causes other issues when you need a merge operation.

### Additional context

Current data model has a key to enabled OSPF.

```
ospf:
    enabled: True
    area: 0.0.0.0
```
Would if be possible when the key `ospf.enabled: False` is set then do not add a `no passive-interface <svi>` statement?  Just a thought versus adding a new key.  The idea is that if ospf.area is set, then enable OSPF as a passive interface.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
