### ISSUE TITLE
Add support for "vxlan vrf XX multicast group encap range x.x.x.x/x delayed"

### ISSUE THREAD

**Issue by ksantos-arista** [aristanetworks/ansible-avd#4375]
### Enhancement summary

Just looking to support the following command:

`interface vxlan1`
`       vxlan vrf XX multicast group encap range x.x.x.x/x delayed`

TOI:
https://www.arista.com/en/support/toi/eos-4-29-1f/16546-multicast-evpn-irb-multiple-underlay-groups

This command is required when configuring Multicast EVPN IRB: Multiple Underlay Groups.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

please detail your use case

### Describe the solution you would like

This command is required when configuring Multicast EVPN IRB: Multiple Underlay Groups.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by kornoa** [comment]
It would make sense to implement in the same change the support for single multicast group mappings from the same tech note:
```
interface Vxlan1
   vxlan vrf red multicast group overlay 239.2.2.2 encap 226.1.1.1 immediate
```

**Comment by gmuloc** [comment]
Let's go with this:

```
type: dict
keys:
  vxlan_interface:
    type: dict
    keys:
      vxlan1:
        type: dict
        keys:
          description:
            type: str
          vxlan:
            type: dict
            keys:
              [...]
              vrfs:
                type: list
                primary_key: name
                items:
                  type: dict
                  keys:
                    name:
                      type: str
                      description: VRF Name.
                      convert_types:
                        - int
                    vni:
                      type: int
                      convert_types:
                        - str
                    multicast_group:
                      type: str
                      description: IP Multicast Group Address. 
                      description: Default IP Multicast Group Address for the VRF. 
                    multicast_group_encap_range:
                      type: str
                      description: |-
                        N:M mapping, the overlay groups in the VRF are mapped to one of
                        the underlay groups defined within the encap range.
                        The format is X.X.X.X/YY.
                    multicast_groups: 
                      type: list
                      primary_key: overlay_group
                      unique_keys: [encap]
                      description: |-
                        List of 1:1 mappings where each configured overlay is mapped 
                        directly to the specified underlay group 'encap'. 
                      items:
                        type: dict
                          keys:
                            overlay:
                              type: str
                              description: Overlay multicast group.
                            encap:
                              type: str
                              required: true
                              description: Underlay multicast group.
```
