### ISSUE TITLE
Update eos_designs code to generate new switchport model in structured_configs

### ISSUE THREAD

**Issue by Shivani-gslab** [aristanetworks/ansible-avd#4455]
### Enhancement summary

The model for `switchport` has been changed under `ethernet_interfaces` and `port_channel_interfaces` in eos_cli_config_gen.
We need to update the eos_designs code to generate the same new model in structured_configs.

### Which component of AVD is impacted

eos_designs

### Use case example

Generate below structured config - 
```
ethernet_interfaces:
    -  name: Ethernet1
       switchport:
            enabled: true
            mode: access
            access_vlan: 10
```
instead of -
```
ethernet_interfaces:
    -  name: Ethernet1
       type: switched
       mode: access
       vlans: 10
```

### Describe the solution you would like

Update eos_designs code to generate new switchport model in structured_configs

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
