### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for OSPF graceful restart

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#4468]
### Enhancement summary

add dedicated keys under `router_ospf` for manipulating graceful restart

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Configuring the graceful restart feature for OSPF.

### Describe the solution you would like

I would like to suggest dedicated keys under router_ospf like:

router_ospf:
  graceful_restart : <bool>
  graceful_restart_grace_period: <int:1-1800> # seconds
  graceful_restart_helper: <bool> # Default: True
  
  This should render
  
```
router ospf 100
   graceful-restart
   
```

or 
```
router ospf 100
   graceful-restart grace-period 15
   no graceful-restart-helper
```

### Describe alternatives you have considered

This can be implemented today using eos_cli:

```
custom_structured_configuration_router_ospf:
        process_ids:
          100:
            eos_cli: graceful-restart
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
