### ISSUE TITLE
Feat(eos_designs): Add support for structured_config for an ospf underlay

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#4470]
### Enhancement summary

add the capability to add supported options to the underlay ospf process. 

### Which component of AVD is impacted

eos_designs

### Use case example

customers wish to implement additional ospf features beyond the required options that `eos_designs` provides.

### Describe the solution you would like

add a fabric-level key such as `underlay_ospf_structured_config` that add the corresponding configuration

```
underlay_ospf_structured_config:
   maximum_paths: 4
   eos_cli: graceful-restart
```

### Describe alternatives you have considered

This can be implemented today with:

```
      custom_structured_configuration_router_ospf:
        process_ids:
          100:
            maximum_paths: 4
            eos_cli: graceful-restart
```            

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
