### ISSUE TITLE
Support for AAA settings via eos_designs

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#4480]
### Enhancement summary

As discussed with @carlbuchmann, it would be a nice addition to be able to set AAA configuration via eos_designs, so it facilitates the configuration of the MGMT/inband VRF etc (as we do today with ntp_settings or snmp_settings).

Similar to this but for AAA:
- `use_mgmt_interface_vrf` will configure the NTP server(s) under the VRF set with `mgmt_interface_vrf` and set the `mgmt_interface` as NTP local-interface.
   An error will be raised if `mgmt_ip` or `ipv6_mgmt_ip` are not configured for the device.
- `use_inband_mgmt_vrf` will configure the NTP server(s) under the VRF set with `inband_mgmt_vrf` and set the `inband_mgmt_interface` as NTP local-interface.
  An error will be raised if inband management is not configured for the device.

Some EOS configuration commands that are affected:
```
tacacs-server host <tacacs-srv-1> vrf <vrf_name> key 7 <key-1>
tacacs-server host <tacacs-srv-2> vrf <vrf_name> key 7 <key-2>

radius-server host <radius-srv-1> vrf <vrf_name> key 7 <key-1>
radius-server host <radius-srv-2> vrf <vrf_name> key 7 <key-2>

aaa group server tacacs+ tac-servers 
 server <srv-1> vrf <vrf_name> 
 server <srv-2> vrf <vrf_name>

aaa group server radius radius-servers
 server <srv-1> vrf <vrf_name> 
 server <srv-2> vrf <vrf_name>

ip tacacs vrf <vrf_name> source-interface <interface>
ip radius vrf <vrf_name> source-interface <interface>
```

### Which component of AVD is impacted

eos_designs

### Use case example

Using AAA for Campus and inband connectivity only (no OOB network).

Example of inband config required via eos_cli_config_gen:
```
custom_structured_configuration_aaa_authentication:
  login:
    default: group tacacs_login local
    console: local
  dot1x:
    default: group ISE
  policies:
    on_failure_log: true
    on_success_log: true

custom_structured_configuration_aaa_authorization:
  exec:
    default: group tacacs_login local
  config_commands: true
  serial_console: true
  commands:
    all_default: local

custom_structured_configuration_aaa_accounting:
   exec:
     default:
       type: start-stop
       group: tacacs_login
   commands:
     default:
       - commands: 0-15
         type: start-stop
         group: tacacs_login
   dot1x:
     default:
       type: start-stop
       group: ISE

custom_structured_configuration_radius_server:
  hosts:
    - host: 1.2.3.4
      key: "{{ vault.radius.key1 }}"
    - host: 1.2.3.5
      key: "{{ vault.radius.key2 }}"

custom_structured_configuration_tacacs_servers:
  hosts:
    - host: 1.2.3.6
      key: "{{ vault.tacacs.key1 }}"
    - host: 1.2.3.7
      key: "{{ vault.tacacs.key2 }}"

custom_structured_configuration_aaa_server_groups:
  - name: tacacs_login
    type: "tacacs+"
    servers:
      - server: 1.2.3.6
      - server: 1.2.3.7
  - name: ISE
    type: "radius"
    servers:
      - server: 1.2.3.4
      - server: 1.2.3.5
```

### Describe the solution you would like

Try to simplify the configuration via eos_designs managing the VRF configuration and maybe reducing the number of inputs required.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by dgonzalez-arista** [comment]
Reusing this existing RFE. As discussed, we would like to simplify the user inputs that today require the user to set the VRF for AAA configuration, using eos_designs. Tacacs/radius source_interface settings already take care of the source-interface configurations.

This would be the template that we currently use for Tacacs+:
```
 custom_structured_configuration_tacacs_servers:
   hosts:
     - host: [tacacs_servers.hosts.host]
       vrf: [mgmt.vrf]
       key: "{{ vault.tacacs.server1.key }}"
       key_type: 7
   policy_unknown_mandatory_attribute_ignore: true
```
And Radius:
```
custom_structured_configuration_radius_server:
   hosts:
     - host: [radius_server.hosts.host]
       vrf: [mgmt.vrf]
       key: "{{ vault.radius.server1.key }}"
```
And the aaa_server_groups:
```
 custom_structured_configuration_aaa_server_groups:
   - name: "TACACS_SERVER"
     type: "tacacs+"
     servers:
       - server: [tacacs_servers.hosts.host]
         vrf: [mgmt.vrf]
   - name: "RADIUS_SERVER"
     type: "radius"
     servers:
       - server: [radius_server.hosts.host]
         vrf: [mgmt.vrf]
```

Based on the default_mgmt_method (oob or inband) we would like to automatically derive the VRF used for tacacs+/radius hosts and AAA server groups from other AVD vars:
```
[mgmt.vrf]: Default OOB: “mgmt_interface_vrf” / Default Inband VRF: “inband_mgmt_vrf”
```
The new data model would be something like:
```
tacacs_settings:
   hosts:
     - host:  <str>
       key: <str>
       key_type: <str; "0" | "7" | "8a"; default="7">

radius_settings:
   hosts:
     - host:  <str>
       key: <str>

aaa_server_groups_settings:
   - name: <str; required; unique>
     type: <str; "tacacs+" | "radius" | "ldap">
     servers:
       - server: <str>
```
Note: We are assuming here that we set the VRF for all the AAA hosts in the "default_mgmt_method" VRF, although that might not be always the case (tacacs/radius support multiple vrfs simultaneously).

**Comment by ClausHolbechArista** [comment]
Could we combine it all under `aaa_settings` and maybe simplify the inputs a bit by not strictly following the CLI layout? Also it would be great if we could reduce further by implementing our best practices.

```yaml
aaa_settings:
  local_users:
    - name: <str; required; unique>
      <...>
  login:
    authentication_sources:
      - group: <str>
      - local: <bool>
    console_authentication_sources:
      - group: <str>
      - local: <bool>
  <...>
  tacacs:
    servers:
      - name: <str; required; unique>
        group: <str; required>
        key: <str; required>
        key_type: <str; "0" | "7"; default="7">  # 8a TBD
    policy:
      ignore_unknown_mandatory_attribute: <bool; default=false>
      <...>
  radius:
    servers:
      - name: <str; required; unique>
        group: <str; required>
        key: <str; required>
    policy:
      <...> 
```

**Comment by gmuloc** [comment]
Updated model - please use this for implementation

```yaml
aaa_settings:
  # Need to implement a logic to check that groups from tacacs servers are not conflicting with groups from radius servers, the groups need to be generated by eos_designs
  tacacs:
    servers:
      - name: <str> # IP or hostname
        groups: <list[str]; required, min item 1>
        key: <str; required> # will be subject to `encrypt_passwords` global knob. For now only type7
        vrf: <str, default to `use_default_mgmt_method_vrf`, also need to support other mgmt method keys.>
        port: <int>
    vrfs: # implement like logging_settings
      - name: <str>
        source_interface: <str>
    policy:
      ignore_unknown_mandatory_attribute: <bool; default=false>
  radius:
    servers:
      - name: <str> # IP or hostname
        groups: <list[str]; required, min item 1>
        key: <str; required> # will be subject to `encrypt_passwords` global knob. For now only type7
    vrfs: # implement like logging_settings
      - name: <str>
        source_interface: <str>
  authentication: ref from cli_gen
  authorization: ref from cli_gen
  accounting: ref from cli_gen
  root_login:
    enabled: <bool; default: false>
    sha512_password: <str> # later on will be subject to `encrypt_passwords` 
```

Also need to deprecate `source_interfaces.radius` & `source_interfaces.tacacs` and use the new behavior

Remember to update description for `default_mgmt_method`: https://avd.arista.com/5.4/ansible_collections/arista/avd/roles/eos_designs/docs/input-variables.html#management-interface-settings
