### ISSUE TITLE
New Node Type Keys specific to Media

### ISSUE THREAD

**Issue by sugetha24** [aristanetworks/ansible-avd#4484]
### Enhancement summary

Need new node type keys for Media devices.

### Which component of AVD is impacted

eos_designs

### Use case example

Need new node types for m&e devices with custom ptp priorities

### Describe the solution you would like

```yaml
node_type_keys:
  - key: ptp_leaf
    type: ptp_leaf
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 10
  - key: media_spine
    type: media_spine
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 20
  - key: media_leaf
    type: media_leaf
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 30
```

### Describe alternatives you have considered

Creating custom device types

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
