### ISSUE TITLE
Update eos_designs code to generate new interface encapsulation model in structured_configs

### ISSUE THREAD

**Issue by Shivani-gslab** [aristanetworks/ansible-avd#4498]
### Enhancement summary

The model for `encapsulation` has been changed under ethernet_interfaces and port_channel_interfaces in eos_cli_config_gen.
We need to update the eos_designs code to generate the same new model in structured_configs.

### Which component of AVD is impacted

eos_designs

### Use case example

Generate below structured config -

```
ethernet_interfaces:
    -  name: Ethernet1
        encapsulation_dot1q:
             vlan: 4
             inner_vlan: 34
```
```
ethernet_interfaces:
    -  name: Ethernet1
        encapsulation_vlan:
              client:
                  outer_vlan: 23
                  inner_vlan: 45
                  protocol: dot1q
                  inner_protocol: dot1q
              network:
                 protocol: dot1ad
                 outer_vlan: 32
                 inner_vlan: 54
                 inner_protocol: dot1ad
```

Instead of - 
```
ethernet_interfaces:
    -  name: Ethernet1
        encapsulation_dot1q_vlan: 4
```
```
ethernet_interfaces:
    -  name: Ethernet1
        encapsulation_vlan:
              client:
                  dot1q:
                       outer: 23
                       inner: 45
              network:
                 dot1q:
                      outer: 32
                      inner: 54
```
       

### Describe the solution you would like

Update eos_designs code to generate new switchport model in structured_configs

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
