### ISSUE TITLE
Add support for per vrf pool for dynamic ip allocation in network_services for l3 interfaces

### ISSUE THREAD

**Issue by vyelpale** [aristanetworks/ansible-avd#4512]
### Enhancement summary

  Using network services for defining tenants where  there is a requirement for high scale of l3 interfaces, static allocation of ip addressing mean a lot of manual inputs. It would be nice to be able to provide a pool (per vrf) which will be leveraged for dynamic allocation.

### Which component of AVD is impacted

eos_designs

### Use case example

L3 routers acting as cloud/vendor attachment routers which will be doing dynamic bgp peerings within different vrfs . l3 sub-interfaces are used over which bgp peering will be established, and within each vrf there would be multiple l3 interfaces. <Nx interface> x <Nx VRFs> increases the overall scale of manual data entries within the yml file. 

### Describe the solution you would like

```yaml
tenants:
 tenant_A:
       vrfs:
           VRFA:
               VRFA_ip_pool: 10.1.1.0/24
                l3_interfaces:
                 - interfaces: [Ethernet1]
                   ip_address:  [VRFA_ip_pool.IP_1/31" > dynamic rendering from pool here; 
                   nodes: [node1]
            VRFB:
               VRFB_ip_pool: 10.1.1.0/24
                l3_interfaces:
                 - interfaces: [Ethernet2]
                   ip_address:  [VRFB_ip_pool.IP_1/31" > dynamic rendering from pool here; 
                   nodes: [node1]
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
