### ISSUE TITLE
Add BFD timers to bgp peer

### ISSUE THREAD

**Issue by ruddan** [aristanetworks/ansible-avd#4533]
### Enhancement summary

Add bfd timers to `bgp_peers`. Currently only possible to add BFD timers under `bgp_peer_groups`.
https://avd.arista.com/4.10/roles/eos_designs/docs/input-variables.html#bgp-settings

### Which component of AVD is impacted

eos_designs

### Use case example

`bgp_peers` inside a VRF that needs custom `bfd_timers`

### Describe the solution you would like

```
vrfs:
      - name: vrf1
      ...
      bgp_peers:
         - ip_address:
           bfd: true
           bfd_timers:
              interval: <int>
              min_rx: <int>
              multiplier: <int>
```
      

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
