### ISSUE TITLE
Fix(eos_designs): bgp peer on l3 interface not working when uplink_type: lan

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#4542]
bgp peer on l3 interface not working when uplink_type: lan

Steps to reproduce:

```yaml

ipv4_prefix_list_catalog:
  - name: ALLOW-DEFAULT
    sequence_numbers:
      - sequence: 10
        action: permit 0.0.0.0/0

wan_router:
  defaults:
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.42.0/24
    uplink_ipv4_pool: 10.0.3.0/24
    uplink_interfaces: [Ethernet1]
    uplink_switch_interfaces: [Ethernet1]
    uplink_type: lan
    bgp_as: 65000
  nodes:
    - name: site3-wan1
      cv_pathfinder_region: REGION2
      cv_pathfinder_site: SITE3
      id: 11
      mgmt_ip: "{{ ansible_host }}/24"
      uplink_switches: [site3-leaf1]
      l3_interfaces:
        - name: Ethernet4
          peer_interface: Ethernet8
          peer_ip: 100.64.30.1
          ip_address: 100.64.30.2/24
          profile: INTERNET-WAN-INTERFACE
          wan_carrier: REGION2-INTERNET-CORP
          wan_circuit_id: inet-site3-wan1
          bgp:
            peer_as: 65042
            ipv4_prefix_list_in: ALLOW-DEFAULT
```
