### ISSUE TITLE
Feat(eos_designs): support for bgp aggregate within a vrf

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#4561]
### Enhancement summary

While it is possible to configure a bgp aggregate within a vrf using eos_cli_config_gen, 

```yaml
router_bgp:
  vrfs:
    MY_VRF:
      aggregate_addresses:
        172.16.0.0/16:
          summary_only: true
```

it should be possible to do so using eos_designs within the network services structure.

### Which component of AVD is impacted

eos_designs

### Use case example

please detail your use case

### Describe the solution you would like

Within the Network services VRF BGP configuration section,
add a key for the aggregate that would render the following:
```
router bgp xxx
   vrf MY_VRF
      ...
      aggregate-address 172.16.0.0/16 summary-only
      ...
 ```

### Describe alternatives you have considered

Tnis is possible today using eos_cli_config_gen under the node group,. 

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
