### ISSUE TITLE
port_profiles: add verify range option

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#4564]
### Enhancement summary

Add option to limit the range of VLANs assigned to an edge port.

### Which component of AVD is impacted

eos_designs

### Use case example

We utilize multiple tenants and also `port_profiles` in AVD. A tenant usually has a dedicated VLAN range that he can consume (e.g. 200-1200). The individual port profiles are all derived from a parent port_profile.

It would be very good to limit the VLAN range a tenant can consume via `port_profiles` and throw a render error if this is violated

### Describe the solution you would like

```yaml
port_profiles:
  - profile: port_profile_Tenant_A_DOT1Q_EDGE
    mode: trunk
    spanning_tree_bpdufilter: false
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge
    storm_control:
      broadcast:
        level: 1
        unit: percent
      multicast:
        level: 1
        unit: percent
      unknown_unicast:
        level: 1
        unit: percent
    vlan_allow_range: "200-1200"

  - profile: port_profile_Tenant_A_Hypervisor
    parent_profile: port_profile_Tenant_A_DOT1Q_EDGE
    vlans: "237-238,1003"
```

If now someone adds Vlan 2000 to the list of `port_profile_Tenant_A_Hypervisor` it will violate `vlan_allow_range` of the parent profile and Ansible will abort rendering the design.

```yaml
  - profile: port_profile_Tenant_A_Hypervisor
    parent_profile: port_profile_Tenant_A_DOT1Q_EDGE
    vlans: "237-238,1003,2000"
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
