### ISSUE TITLE
New l3_interfaces settings are not working

### ISSUE THREAD

**Issue by theotherguy2175** [aristanetworks/ansible-avd#4581]
### Issue Summary

When following the 4.10.2 documentation:
[https://avd.sh/en/stable/roles/eos_designs/docs/input-variables.html?h=l3_interfaces#node-type-l3-interfaces-configuration](url)

It says things like speed, peer_ip, and bgp are settings that can be applied. But even doing speed the output acts like that is not a valid keys:

`[WARNING]: [borderA2.bldc]: 'Validation Error: tenants[0].vrfs[2].l3_interfaces[7]': Unexpected key(s) 'speed' found in dict.`

This is a snippet of the AVD Yaml I am trying to use:
```
    - name: RESEARCH
        l3_interfaces:
          - interfaces: [ Ethernet3/1 ] #322
            nodes: [ borderA2.bldc ]
            description: "#HIDDEN#"
            encapsulation_dot1q_vlan: [ 322 ]
            mtu: 9000
            speed: forced 40gfull
            enabled: true
            ip_addresses: [ #HIDDEN# ]
            structured_config:
              ipv6_address: #HIDDEN#
            # peer_ip: #HIDDEN#
            # bgp:
            #   peer_as: #HIDDEN#
            #   description: '#HIDDEN#'
            #   next_hop_self: false
            #   shutdown: true
            #   send_community: extended
            #   maximum_routes: 0
```

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
