### ISSUE TITLE
Router bgp - missing maximum-paths within vrf section

### ISSUE THREAD

**Issue by juanjtomasg** [aristanetworks/ansible-avd#4583]
### Enhancement summary

The router_bgp.j2 template doesn't contemplate the case in which the maximum-path option is defined at vrf level.

router(config)#router bgp 123
router(config-router-bgp)#   vrf 151
router(config-router-bgp-vrf-151)#maximum-paths ?
  <1-600>  Value for maximum number of equal cost paths

router(config-router-bgp-vrf-151)#maximum-paths 32 ?
  ecmp  Maximum number of installed ECMP routes
  <cr>  

router(config-router-bgp-vrf-151)#maximum-paths 32 ecmp ?
  <1-600>  Value for maximum number of installed ECMP routes
 router(config-router-bgp-vrf-151)#maximum-paths 32 ecmp 32 ?
  <cr>  

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

router bgp 123
   vrf 1
      rd 1:1
      **maximum-paths 32 ecmp 32**
      neighbor 1.2.3.4 remote-as 321
      neighbor 1.2.3.4 description peer
      neighbor 1.2.3.4 password 7 password

### Describe the solution you would like

Introduce maximum-paths attribute within vrf secion in router_bgp.

If dictionary is:
```
router_bgp:
  ...
  vrfs:
    - name: <str; required; unique>
      ...
      maximum_paths:
        paths: <int; 1-600; required>
        ecmp: <int; 1-600>
```
    
When providing this values:

```
router_bgp:
  ...
  vrfs:
    - name: "Test"
      ...
      as: 123
      maximum_paths:
        paths: 60
        ecmp: 60
```

Rendered configuration should be:

```
router bgp 123
   vrf test
     maximum-paths 60 ecmp 60
```

### Describe alternatives you have considered

N/A

### Additional context

N/A

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
