### ISSUE TITLE
Feat (eos_cli_config_gen): Add support for the config needed for the Multihomed Multidomain EVPN VXLAN-MPLS Gateway 

### ISSUE THREAD

**Issue by colinmacgiolla** [aristanetworks/ansible-avd#4604]
### Enhancement summary

Feature TOI is [here](https://www.arista.com/en/support/toi/eos-4-32-0f/19245-multihoming-on-multi-domain-evpn-vxlan-mpls-gateway).
Some points are already covered e.g.
* L2 FEC inplace update #3811 
* Encapsulation MPLS next-hop self source-interface #4243 

Currently we are missing the option to set the *remote* domain identifier e.g.
```
router bgp <ASN>
   address-family evpn
      domain identifier 1:1
      domain identifier 2:2 remote
```
currently only the local domain identifier can be set.

We also need to be able to set the local and remote segment identifiers e.g.
```
router bgp <ASN>
   address-family evpn
      evpn ethernet-segment domain local
         identifier 0011:1111:1111:1111:1111
         route-target import 11:11:11:11:11:11
      !
      evpn ethernet-segment domain remote
         identifier 0022:2222:2222:2222:2222
         route-target import 22:22:22:22:22:22
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

please detail your use case

### Describe the solution you would like

For the evpn segments, I'd propose the following datamodel:
```yaml
router_bgp:
   address_family_evpn:
      evpn_ethernet_segment:
         - domain: <local | remote>
           identifier: <segment id>
           route_target: <EVPN Route Target for ESI with format xx:xx:xx:xx:xx:xx.>
```
But open to ideas about the domain change - currently the model is
```yaml
router_bgp:
   address_family_evpn:
      domain_identifier: <string>
```
but now we need two - a local and a remote. This suggestion is non-breaking
```yaml
router_bgp:
   address_family_evpn:
      domain_identifier: <string>
      domain_identifier_remote: <string>
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
