### ISSUE TITLE
Add BGP UCMP support for l3_edge and l3_leaf

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#4617]
### Enhancement summary

Add support for asymetric link bandwidth

### Which component of AVD is impacted

eos_designs

### Use case example

Leveraging `eos_designs` role to build large (as in geographically) stretched networks we found that there is no "nice" support for asymetric link bandwidth - as ECMP is the preferred way.

We would also like to make use of UCMP as per https://www.arista.com/en/support/toi/eos-4-24-1f/14534-bgp-ucmp

### Describe the solution you would like

Add a new nerd know for `ucmp` in combination with `l3_edge` - e.g. building a DCI

```yaml
l3_edge:
  p2p_links:
    - id: 1
      profile: dci_profile_red
      nodes: [spine-1a7-01.DC.MU, spine-2a7-01.DC.MU]
      interfaces: [Ethernet1, Ethernet1]
      ucmp:
        enabled: <bool; default=False>
        interface_speed: [10000, 25000]
        next_hop_set: (Optional) A maximum set size for the UCMP next-hop set (M)
        deviation: (Optional) A % deviation constraint from the optimal traffic load sharing ratio for every next-hop in the UCMP set (deviation%)
```

or `l3_leaf` in a leaf/spine fabric

```yaml
l3_leaf:
  node_groups:
    - group: BLUE_01
      ucmp:
        enabled: <bool; default=False>
        next_hop_set: (Optional) A maximum set size for the UCMP next-hop set (M)
        deviation: (Optional) A % deviation constraint from the optimal traffic load sharing ratio for every next-hop in the UCMP set (deviation%)
      nodes:
        - name: blue-access-01
          id: 3
          mgmt_ip: 172.29.0.3
          speed: 10000
        - name: blue-access-02
          id: 4
          mgmt_ip: 172.29.0.4
          speed: 25000


```

### Additional context

Enabling UCMP for a given `l3_leaf` or `l3_edge` should instantiate the appropriate commands under `router bgp` in addtion to creating the necessary extended BGP communities.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
