### ISSUE TITLE
Inconsistent TCP MSS Ceiling Schema

### ISSUE THREAD

**Issue by perimore** [aristanetworks/ansible-avd#4620]
### Issue Summary

Inconsistency between ethernet_interfaces and tunnel_interfaces when configuring TCP MSS ceiling segment size.

`ethernet_interfaces` uses the below:

```
            ethernet_interfaces:
              - name: Ethernet10
                tcp_mss_ceiling:
                  ipv4_segment_size: 1500
```

Whereas `tunnel_interfaces` uses:

```
            tunnel_interfaces:
              - name: Tunnel1
                tcp_mss_ceiling:
                  ipv4: 1500
```

Rendering the same config:

```
interface Ethernet10
   switchport
   tcp mss ceiling ipv4 1500
!
interface Tunnel1
   tcp mss ceiling ipv4 1500
```

We would expect them both to use the same key. Considering support in ethernet_interfaces was implemented first, I would suggest using `ipv4_segment_size`

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

PyAVD

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
