### ISSUE TITLE
IP locking enforcement disabled

### ISSUE THREAD

**Issue by xaviramon** [aristanetworks/ansible-avd#4624]
### Enhancement summary

As detailed under https://www.arista.com/en/support/toi/eos-4-25-1f/14628-ip-locking-release-updates IP locking has a "enforcement disabled" mode which is not covered today in AVD

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Allow enforcement disabled functionality in the physical/vlan interface

### Describe the solution you would like

Expand the model:
```
ethernet_interfaces:
  - name: <str; required; unique>
  address_locking:
      ipv4: <bool>
          enforcement_disabled: <bool>
```
Which will generate the following CLI configuration:
```
locked-address ipv4 enforcement disabled
```
Ideally, also add support for vlan config-mode, which also supports the functionality

### Additional context

Configuration to be generated:
```
vlan 10
   address locking
      address-family ipv4
      locked-address ipv4 enforcement disabled
```
```
interface Ethernet1
   shutdown
   !
   address locking
      address-family ipv4
      locked-address ipv4 enforcement disabled
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
