### ISSUE TITLE
Support for IPv4/v6 in SVIs and the SVIs are running at underlay and talk to the other service nodes, e.g. Firewalls

### ISSUE THREAD

**Issue by forcecity** [aristanetworks/ansible-avd#4628]
### Enhancement summary

It would be great that we could configure the IPv4/v6 services in SVIs, but at underlay network (vrf default, but not through evpn vxlan tunnel).
VLANs/SVIs at underlay network (vrf default but without rd/rt, evpn related stuffs)
BGP neighbors at underlay. Could establish the peers with other network nodes.

### Which component of AVD is impacted

eos_designs

### Use case example

Some of our switches are managed or accessed from underlay networks (via loopback 0) and the mgmt system could be in different VRFs, the FW will control the access acrossing the different VRFs, so an underlay SVIs for the FWs are needed to dump the traffic of the switches' management at the underlay.
For now, I use the "structured_config" in nodes settings:
```
l3leaf:
  defaults:
    uplink_switches: <omit>
    uplink_interfaces: <omit>
    ... ...
  node_groups:
    - group: leaf-pair
      filter:
        tags:
          - < omit.. >
      bgp_as: xxxxxx
      structured_config:
        router_bgp:
          neighbors:
            - ip_address: xx.xxx.xxx.10
              peer_group: FWs-PEER-GP   # it is defined in Network_services
              description: fw_bgp_underlay
      nodes:
        - name: leaf-a
          id: 1
          uplink_switch_interfaces:
            - Ethernet1
            - Ethernet2
            - Ethernet3
            - Ethernet4
          structured_config:
            vlans:
              - id: 10
                name: fw_bgp_underlay
            vlan_interfaces:
              - name: Vlan10
                shutdown: false
                description: fw_bgp_underlay
                ip_address: xx.xxx.xxx.11/28
                arp_gratuitous_accept: true
                mtu: 9100
        - name: leaf-b
          id: 2
          uplink_switch_interfaces:
            - Ethernet1
            - Ethernet2
            - Ethernet3
            - Ethernet4
          structured_config:
            vlans:
              - id: 10
                name: fw_bgp_underlay
            vlan_interfaces:
              - name: Vlan10
                shutdown: false
                description: fw_bgp_underlay
                ip_address: xx.xxx.xxx.12/28
                arp_gratuitous_accept: true
                mtu: 9100
```

### Describe the solution you would like

At the network service section, would it be possible to create a "Network services SVIs configuration without VRF", similar to other SVIs in VRFs but located the global instance.

### Describe alternatives you have considered

Or probably a new section dedicated to the underlay services configs (like, the services for l3_edge) which could include the services of SVIs or l3_interfaces or subinterfaces, etc... These services are all related to the network which will go through the vxlan fabric, and will provide the network services at underlay (or so to say pure l3 networks).

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
We have improved a lot in AVD 5.0 (pending release hopefully this Friday) for services in VRF default. This means you can define your SVIs, BGP peers etc under network services for the default VRF. If you don't want it to be EVPN enabled, you can set `address_families: []` under the VRF (this trick should work already in 4.x).

Please give it a try and let me know what you are missing.

**Comment by forcecity** [comment]
Hello Claus,

Thank you for you reply.

Yes, i just tried your workaround to set `address_families: []`. The SVIs were created succesfully as what we want and no evpn stuff or ip-prefix stuffs now.

but I didn't find a way to configure the bgp peers (peer groups) for the neighbors in the underlay.. The `bgp_peers:` or `bgp.structured_config:` are not rendered when they are located in VRF default. Would you mind to also give me a hint how I can configure this part in `network_services` or it is not possible now?

Now I still put this part into `Node type settings`:
```
  node_groups:
    - group: leaf-pair
      filter:
        tags:
          - < omit.. >
      bgp_as: xxxxxx
      structured_config:
        router_bgp:
          neighbors:
            - ip_address: xx.xxx.xxx.10
              peer_group: FWs-PEER-GP   # it is defined in Network_services
              description: fw_bgp_underlay
```

**Comment by ClausHolbechArista** [comment]
This will work much better in AVD 5.0, but for 4.x we have a temporary "nerd-knob"  you an try: `new_network_services_bgp_vrf_config: true`.

**Comment by forcecity** [comment]
Hi Claus,
I think when i change this knob, the vrf default will be generated in bgp configs, but not as we expected, it treated default as a new vrf instead of putting neighbor configs directly globally (like IPv4-Underlay-peers). 
```
router bgp xxxxxxxxxx
   vrf default
      update wait-install
      neighbor xx.xxx.xxx.10 peer group FWs-PEER-GP
      neighbor xx.xxx.xxx.10 description fw_bgp_underlay
      !
      address-family ipv4
         neighbor xx.xxx.xxx.10 activate
```
So I think I will leave this point here and when 5.0 is released, i will test it again. Thank you for your answer.

**Comment by wahezu** [comment]
Hi @ClausHolbechArista ,

I would like to implement the same, i.e. underlay SVIs which are distributed with underklay BGP to the rest of switches. (vrf default but without rd/rt, evpn related stuffs)

Until very recently we didn't have any requirement for EVPN and we were using AVD for a pure L3 Spine&Leaf topology without VXLAN/EVPN. We were using`overlay_routing_protocol: none` and the SVIs were configured with `vxlan: false` and it was working fine(MLAG peering, SPINE peering, etc.)

Recently we had a requirement to extend some new VLANs across the fabric and I tested the `address_families: []` option and the intended configs generated seem to fit for the purpose, however the SVIs are not distributed on the underlay BGP.  I noticed redistributed connected command with Route map under the Router BGP section, I think this will prevent the SVIs to be announced via underlay:    `redistribute connected route-map RM-CONN-2-BGP` which will limit the connected to loopbacks.

To get the underlay SVIs distributed, I think we should add `redistribute connected ` to the `address-family ipv4` section of the BGP however I don't know how to  configure it with AVD. Or maybe there is another way to achieve the same?

Thanks in advance.
Wahe

**Comment by ClausHolbechArista** [comment]
> Hi @ClausHolbechArista ,
> 
> To get the underlay SVIs distributed, I think we should add `redistribute connected ` to the `address-family ipv4` section of the BGP however I don't know how to configure it with AVD. Or maybe there is another way to achieve the same?

I *think* we have solved this in 5.0, so could you check with the latest version (5.1)? Please let me know what you find. Thanks.

**Comment by wahezu** [comment]
Hi @ClausHolbechArista ,

I just upgraded AVD to 5.1.0 but unfortunately I don't see the command for `redistribute connected` under `address-family ipv4` and the command `redistribute connected route-map RM-CONN-2-BGP` still forces only loopbacks to be advertised.

Config on a leaf Switch:

```
router bgp 65101
   router-id 192.168.255.6
   distance bgp 20 200 200
   maximum-paths 4 ecmp 4
   neighbor EVPN-OVERLAY-PEERS peer group
   neighbor EVPN-OVERLAY-PEERS update-source Loopback0
   neighbor EVPN-OVERLAY-PEERS bfd
   neighbor EVPN-OVERLAY-PEERS ebgp-multihop 3
   neighbor EVPN-OVERLAY-PEERS password 7 ccccccccccccccc
   neighbor EVPN-OVERLAY-PEERS send-community
   neighbor EVPN-OVERLAY-PEERS maximum-routes 0
   neighbor IPv4-UNDERLAY-PEERS peer group
   neighbor IPv4-UNDERLAY-PEERS password 7 pppppppppppppp
   neighbor IPv4-UNDERLAY-PEERS send-community
   neighbor IPv4-UNDERLAY-PEERS maximum-routes 12000
   neighbor MLAG-IPv4-UNDERLAY-PEER peer group
   neighbor MLAG-IPv4-UNDERLAY-PEER remote-as 65101
   neighbor MLAG-IPv4-UNDERLAY-PEER next-hop-self
   neighbor MLAG-IPv4-UNDERLAY-PEER description DC1_LEAF1B
   neighbor MLAG-IPv4-UNDERLAY-PEER route-map RM-MLAG-PEER-IN in
   neighbor MLAG-IPv4-UNDERLAY-PEER password 7 ppppppppppppppppppp
   neighbor MLAG-IPv4-UNDERLAY-PEER send-community
   neighbor MLAG-IPv4-UNDERLAY-PEER maximum-routes 12000
   neighbor 10.255.251.7 peer group MLAG-IPv4-UNDERLAY-PEER
   neighbor 10.255.251.7 description DC1_LEAF1B_Vlan4093
   neighbor 172.31.255.12 peer group IPv4-UNDERLAY-PEERS
   neighbor 172.31.255.12 remote-as 65001
   neighbor 172.31.255.12 description DC1_SPINE1_Ethernet1
   neighbor 172.31.255.14 peer group IPv4-UNDERLAY-PEERS
   neighbor 172.31.255.14 remote-as 65001
   neighbor 172.31.255.14 description DC1_SPINE2_Ethernet1
   neighbor 192.168.255.4 peer group EVPN-OVERLAY-PEERS
   neighbor 192.168.255.4 remote-as 65001
   neighbor 192.168.255.4 description DC1_SPINE1_Loopback0
   neighbor 192.168.255.5 peer group EVPN-OVERLAY-PEERS
   neighbor 192.168.255.5 remote-as 65001
   neighbor 192.168.255.5 description DC1_SPINE2_Loopback0
   redistribute connected route-map RM-CONN-2-BGP
   !
   vlan-aware-bundle EVPN_Zone
      rd 192.168.255.6:10
      route-target both 10:10
      redistribute learned
      vlan 111-112
   !
   address-family evpn
      neighbor EVPN-OVERLAY-PEERS activate
   !
   address-family ipv4
      no neighbor EVPN-OVERLAY-PEERS activate
      neighbor IPv4-UNDERLAY-PEERS activate
      neighbor MLAG-IPv4-UNDERLAY-PEER activate
   !
   vrf EVPN_Zone
      rd 192.168.255.6:10
      route-target import evpn 10:10
      route-target export evpn 10:10
      router-id 192.168.255.6
      redistribute connected
!
end
```

AVD config on `group_vars/DC1_NETWORK_SERVICES.yaml`

```
---
tenants:
  # Tenant A VRFs / VLANs
  - name: Tenant_A
    mac_vrf_vni_base: 10000
    enable_mlag_ibgp_peering_vrfs: false
    vrfs:
      - name: EVPN_Zone
        vrf_vni: 10
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.255.1.0/24
        svis:
          - id: 111
            name: Tenant_A_OP_Zone_2
            tags:
              - opzone_evpn
            enabled: true
            vxlan: true
            ip_address_virtual: 10.1.11.1/24
          - id: 112
            name: Tenant_A_OP_Zone_3
            tags:
              - opzone_evpn
            enabled: true
            vxlan: true
            ip_address_virtual: 10.1.12.1/24
      - name: default
        vrf_id: 1
        address_families: []
        redistribute_connected: true
        svis:
          - id: 211
            name: Vlan211
            tags:
              - opzone_pod1
            enabled: true
            vxlan: false
            nodes:
              - node: DC1_LEAF1A
                ip_address: 10.2.11.252/24
              - node: DC1_LEAF1B
                ip_address: 10.2.11.253/24
            ip_virtual_router_addresses:
              - 10.2.11.1
          - id: 212
            name: Vlan212
            tags:
              - opzone_pod2
            enabled: true
            vxlan: false
            nodes:
              - node: DC1_LEAF2A
                ip_address: 10.2.12.252/24
              - node: DC1_LEAF2B
                ip_address: 10.2.12.253/24
            ip_virtual_router_addresses:
              - 10.2.12.1
```

AVD config on `group_vars/DC1_FABRIC.yaml`:

```
---
fabric_name: DC1_FABRIC

dc_name: LAB-DC

underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp



evpn_vlan_aware_bundles: true
```

**Comment by wahezu** [comment]
Update to my previous post:

I think I got it working on AVD5.1, with two options for implementation:

1.  redisctribute all connected interfaces in the underlay BGP protocol, adding structured config in the `group_vars/DC1_NETWORK_SERVICES.yaml` file:

```
      - name: default
        vrf_id: 1
        address_families: []
        structured_config:
          router_bgp:
            address_family_ipv4:
              redistribute:
                  connected:
                     enabled: true
```

2. redistribute only a limited set of connected interfaces, levereaging the route map `RM-CONN-2-BGP` which by default will only redistribute the VTEP loopbacks. This is implemented using `custom_structured_config` applied to nodes via group_vars `group_vars/DC1_LEAF1.yaml `(one group per MLAG pair of switches):

```
custom_structured_configuration_prefix_lists:
  - name: PL-SVIS-UNDERLAY
    sequence_numbers:
      - sequence: 10
        action: permit 10.2.11.0/24 eq 24

custom_structured_configuration_route_maps:
  - name: RM-CONN-2-BGP
    sequence_numbers:
      - sequence: 20
        type: permit
        match:
          - ip address prefix-list PL-SVIS-UNDERLAY
```


I hope the above will be useful for someone trying to implement a similar topology. Feel free to suggest improvements or different approaches.

Thanks!

**Comment by forcecity** [comment]
Hi @wahezu 
Your solution is valuable to people who need to propagate other routes at underlay. I just has some points maybe can be discussed. 
1. I normally put the prefix_lists and route_maps vars into the "node_groups -> group -> structured_config" regarding i have multiple leaf pairs in one yml file. "custom_structured_configuration_" prefix may be impact all the leafs in this group_vars file instead of a specific pair which needs the other routes. But if you only have one pair leaf switches in this file, then It will be the same.
2. Regarding the `redistribute connected route-map RM-CONN-2-BGP` already in "router bgp xxxxxxx", i think 
```
        structured_config:
          router_bgp:
            address_family_ipv4:
              redistribute:
                  connected:
                     enabled: true
```
is not needed.

**Comment by wahezu** [comment]
Hi @forcecity,

Thanks for your inputs. 

 I use group_vars files, so `DC1_LEAF1.yaml` will be applied to DC1_LEAF1A and DC1_LEAF1B switches. I would need one of those group_vars file per pair of swtiches forming a MLAG.  I'll test it out using your approach (node_groups -> group -> structured_config) to see if it is more convenient.

Regarding `redistribute connected route-map RM-CONN-2-BGP`. If you dont add that config snipet then only VTEP loopbacks are redistriburted as the route-map RM-CONN-2-BGP will only include the loopback prefix. At least this is what I saw on my lab.

But as I said initially you only need to implement one of the options (redistribute all connected interfaces or only the ones included in the route-map). 


This config:
```
        structured_config:
          router_bgp:
            address_family_ipv4:
              redistribute:
                  connected:
                     enabled: true
```
 Will add redistribute connected to the default vrf:

```
   address-family ipv4
      no neighbor EVPN-OVERLAY-PEERS activate
      neighbor IPv4-UNDERLAY-PEERS activate
      neighbor MLAG-IPv4-UNDERLAY-PEER activate
      redistribute connected
```

This config:
```
custom_structured_configuration_prefix_lists:
  - name: PL-SVIS-UNDERLAY
    sequence_numbers:
      - sequence: 10
        action: permit 10.2.11.0/24 eq 24

custom_structured_configuration_route_maps:
  - name: RM-CONN-2-BGP
    sequence_numbers:
      - sequence: 20
        type: permit
        match:
          - ip address prefix-list PL-SVIS-UNDERLAY
```
Will add sequence 20 to the route-map:
```
route-map RM-CONN-2-BGP permit 10
   match ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY
!
route-map RM-CONN-2-BGP permit 20
   match ip address prefix-list PL-SVIS-UNDERLAY
```

Only one of the above configs is needed.
