### ISSUE TITLE
Feat(eos_designs):  Add speed option for default_interfaces

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#4639]
### Enhancement summary

When using the `default_interfaces:` model, it makes sense to also be able to define corresponding interface speed.

### Which component of AVD is impacted

eos_designs

### Use case example

please detail your use case

### Describe the solution you would like

```
default_interfaces:
  - types: [ l3leaf ]
    platforms: [ 720XP-48 ]
    uplink_interfaces: [ Ethernet53/1, Ethernet54/1 ]
    uplink_speed: forced 100G
```

### Describe alternatives you have considered

Manually configure the interface speed under the node type.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
