### ISSUE TITLE
Add the support for NTP under source_interfaces settings

### ISSUE THREAD

**Issue by ksantos-arista** [aristanetworks/ansible-avd#4640]
### Enhancement summary

Similar to DNS, Radius, TACACS add the support for NTP under source_interfaces settings

### Which component of AVD is impacted

eos_designs

### Use case example

please detail your use case

### Describe the solution you would like

Set the NTP source interface via eos_design as it done for similar features 

```
source_interfaces:
  ntp:
    mgmt_interface: <bool>
    inband_mgmt_interface: <bool>
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
