### ISSUE TITLE
Support for logging settings via eos_designs

### ISSUE THREAD

**Issue by ksantos-arista** [aristanetworks/ansible-avd#4641]
### Enhancement summary

Similar to DNS, Radius, TACACS add the support for Logging under source_interfaces settings

### Which component of AVD is impacted

eos_designs

### Use case example

please detail your use case

### Describe the solution you would like

Set the Logging source interface via eos_design as it done for similar features

```
source_interfaces:
  logging:
    mgmt_interface:
    inband_mgmt_interface:
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by dgonzalez-arista** [comment]
We would like to simplify the user inputs that today require the user to set the VRF and source interface via eos_designs: This would be a common template:
```
logging_settings:
  console: informational
  monitor: informational
  buffered:
    size: 10000000
    level: notifications
  trap: warnings
  format:
    timestamp: high-resolution
    hostname: fqdn
  vrfs:
    - name: [mgmt.vrf]
      source_interface: [mgmt.source_interface]
      hosts:
        - name: [logging.vrfs.hosts.name]
          protocol: udp
```

Based on the default_mgmt_method (oob or inband) we would like to automatically derive the VRF and source interface from other AVD vars:
```
[mgmt.vrf]: Default OOB: “mgmt_interface_vrf” / Default Inband VRF: “inband_mgmt_vrf”
[mgmt.source_interface]: Default OOB: “mgmt_interface” / Default Inband: “inband_mgmt_interface”
```
For the source interface could also augment the current source_interfaces model to support logging:
https://avd.arista.com/5.2/ansible_collections/arista/avd/roles/eos_designs/docs/input-variables.html#source-interfaces-settings

We are assuming here that all hosts in the same VRF, although that might not be always the case (syslogs supports multiple vrfs simultaneously).

**Comment by dgonzalez-arista** [comment]
In essence this would be something that we would like to have (similar to ntp/dns):
```
logging_settings:
   hosts:
     - name: [logging.vrfs.hosts.name]

source_interfaces:
  logging:
    mgmt_interface: <bool; default=False>
    inband_mgmt_interface: <bool; default=False>
```

Ideally we would like to also get some defaults as seen in the previous snippet, if we think that is sensible for most customers:
```
  console: informational
  monitor: informational
  buffered:
    size: 10000000
    level: notifications
  trap: warnings
  format:
    timestamp: high-resolution
    hostname: fqdn
```
So that we need minimal configuration and inputs to set logging up.
