### ISSUE TITLE
avd 5.0.0 - redistribute_routes still throws deprecation warning

### ISSUE THREAD

**Issue by PieterL75** [aristanetworks/ansible-avd#4669]
### Issue Summary

AVD v5.0.0 no longer has the auto-conversion of old data model for router_bgp.redistribute_routes and router_bgp.vrfs[].redistribute_routes.

My configs already had the proper new syntax, by I still get the warning.

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Create a VRF with this BGP config :
tenants:
 - name: test
   vrfs:
     - vrf: myvrf1
        bgp:
          structured_config:
            redistribute_routes:
              - source_protocol: static
                route_map: INFRA-BE-EBGP4-OUT
              - source_protocol: connected
                route_map: INFRA-BE-EBGP4-OUT
```

### Relevant log output

```shell
False The input data model 'tenants[0].vrfs[0].bgp.structured_config.redistribute_routes' is deprecated. Use 'redistribute' instead. This feature will be removed from 
arista.avd.eos_designs in version 6.0.0. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Thank you for reporting!

There are two changes in 5.0 for this area:

1. Very old model was a list-of-strings, and in 3.x and 4.x we autoconverted that to a list of dicts. This autoconversion was removed.
2. The newer model was constantly leading to issues, especially when trying to override things with custom structured configuration. So we introduced a new model called `redistribute` which is a deeper dict structure.

We should update the porting-guide to point to the new model for both changes.

**Comment by PieterL75** [comment]
That was what I needed :-)
Looks like I was mixing the 'auto-conversion' and then the deprecation.. 

I changed the customconfig to this, and all works fine now !
```
tenants:
 - name: test
   vrfs:
     - vrf: myvrf1
          structured_config:
            redistribute:
              static:
                enabled: true
                route_map: INFRA-BE-EBGP4-OUT
              connected:
                enabled: true
                route_map: INFRA-BE-EBGP4-OUT
```

Thx again for the switch response
