### ISSUE TITLE
Add filter supported by default section in l2leaf and l3leaf devices.

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#469]
**Issue Type**

- Role enhancement

**Is your feature request related to a problem? Please describe.**

Currently all knobs available under `l3leaf.node_groups[]` are also supported by `l3leaf.defaults` except for `filter` configuration.

Would be more consistent to have that feature supported by defaults knob in both `l2leaf` and `l3leaf`

**Describe the solution you'd like**

Being able to configure filter in one place like:

```yaml
l3leaf:
  defaults:
    filter:
       tenants: []
       tags: []
```
