### ISSUE TITLE
Feat(eos_designs): Add support for Port-Channels for WAN interfaces

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#4695]
### Enhancement summary

Use the following schema in parallel of `l3_interfaces` under nodes

```yaml
l3_port_channels:
  - id: 123
    mode: active
    ip_address: 1.2.3.4/23
    member_interfaces:
      - name: Ethernet12
        peer: <peer>
        peer_interface: <peer_interface>
        description: <description>
      - name: Ethernet13
        peer: <peer>
        peer_interface: <peer_interface>
        description: <description>
```

Need to add code in `eos_designs` and the tests

### Which component of AVD is impacted

eos_designs

### Use case example

WAN interfaces connecting via port-channel to Service Provider

### Describe the solution you would like

cf summary

### Describe alternatives you have considered

Can make it work using structured config today

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
```yaml
l3_port_channels:
    # Port-Channel interface name like 'Port-Channel2' or subinterface name like 'Port-Channel2.42'.
    # For a Port-Channel subinterface, the parent Port-Channel interface must be defined as well.
  - name: <str; required; unique>
    
    # Port-Channel mode. Should not be set on Port-Channel subinterfaces.
    mode: <str; "active" | "passive" | "on"; default="active">

    # Port-Channel member interfaces. Should not be set on Port-Channel subinterfaces.
    member_interfaces:
        # Ethernet interface name like 'Ethernet2'.
      - name: <str; required; unique>
        # The peer device name. Used for description and documentation.
        # If not set, this inherits the peer setting on the port-channel interface.
        peer: <str>

        # The peer device interface. Used for description and documentation.
        peer_interface: <str>

        # Speed should be set in the format `<interface_speed>` or `forced <interface_speed>` or `auto <interface_speed>`.
        speed: <str>

        # Custom structured config for the Ethernet interface.
        structured_config: <dict>

    # Node IPv4 address/Mask or 'dhcp'.
    ip_address: <str>

    # When the `ip_address` is `dhcp`, this optional field allows to indicate the expected
    # IPv4 address (without mask) to be allocated on the interface if known.
    # This is not rendered in the configuration but can be used for substitution of 'interface_ip' in the Access-list
    # set under `ipv4_acl_in` and `ipv4_acl_out`.
    dhcp_ip: <str>

    # Node IPv4 address (no mask).
    #
    # This is used to get the public IP (if known) when the device is behind NAT.
    # This is only used for `wan_rr` routers (AutoVPN RRs and Pathfinders) to determine the Public IP
    # with the following preference:
    #   `wan_route_servers.path_groups.interfaces.ip_address`
    #       -> `l3_interfaces.public_ip`
    #           -> `l3_interfaces.ip_address`
    #
    # The determined Public IP is used by WAN routers when peering with this interface.
    public_ip: <str>

    # For subinterfaces the dot1q vlan is derived from the interface name by default, but can also be specified.
    encapsulation_dot1q_vlan: <int; 1-4094>

    # Accept a default route from DHCP if `ip_address` is set to `dhcp`.
    dhcp_accept_default_route: <bool; default=True>

    # Enable or Shutdown the interface.
    enabled: <bool; default=True>

    # The peer device name. Used for description and documentation.
    peer: <str>

    # The peer device port-channel interface. Used for description and documentation.
    peer_port_channel: <str>

    # The peer device IPv4 address (no mask). Used as default route gateway if `set_default_route` is true and `ip` is an IP address.
    peer_ip: <str>

    # Enforce IPv4 BGP peering for the peer
    bgp:

      # BGP AS <1-4294967295> or AS number in asdot notation "<1-65535>.<0-65535>".
      # For asdot notation in YAML inputs, the value must be put in quotes, to prevent it from being interpreted as a float number.
      peer_as: <str; required>

      # Prefix List Name. Accept routes for only these prefixes from the peer.
      # Required for wan interfaces.
      ipv4_prefix_list_in: <str>

      # Prefix List Name. Advertise routes for only these prefixes.
      # If not specified, nothing would be advertised.
      ipv4_prefix_list_out: <str>

    # Name of the IPv4 access-list to be assigned in the ingress direction.
    # The access-list must be defined under `ipv4_acls` and supports field substitution for "interface_ip" and "peer_ip".
    # Required for all WAN interfaces (`wan_carrier` is set) unless the carrier is marked as 'trusted' under `wan_carriers`.
    ipv4_acl_in: <str>

    # Name of the IPv4 Access-list to be assigned in the egress direction.
    # The access-list must be defined under `ipv4_acls` and supports field substitution for "interface_ip" and "peer_ip".
    ipv4_acl_out: <str>

    # Configure IPv4 static routes pointing to `peer_ip`.
    static_routes: # >=1 items

        # IPv4_network/Mask.
      - prefix: <str; required>

    # QOS service profile.
    qos_profile: <str>

    # The WAN carrier this interface is connected to.
    # This is used to infer the path-groups in which this interface should be configured.
    # Unless the carrier is marked as 'trusted' under `wan_carriers`, `ipv4_acl_in` is also required on all WAN interfaces.
    wan_carrier: <str>

    # The WAN circuit ID for this interface.
    # This is not rendered in the configuration but used for WAN designs and descriptions.
    wan_circuit_id: <str>

    # For a WAN interface (`wan_carrier` is set), allow to disable the static tunnel towards Pathfinders.
    connected_to_pathfinder: <bool; default=True>

    # PREVIEW: This key is in preview mode
    cv_pathfinder_internet_exit:

      # List of Internet-exit policies using this interface as exit.
      policies:

          # Internet-exit policy name.
        - name: <str; required; unique>

          # Number range to use for Tunnel interfaces to an internet-exit service provider using this local interface.
          # Examples: '1-3' or '100,200,300'
          tunnel_interface_numbers: <str>

    # Configures flow-tracking on the interface. Overrides `fabric_flow_tracking.l3_port_channels` setting.
    flow_tracking:
      enabled: <bool>

      # Flow tracker name as defined in flow_tracking_settings.
      name: <str>

    # EOS CLI rendered directly on the port-channel interface in the final EOS configuration.
    raw_eos_cli: <str>

    # Custom structured config for the Port-Channel interface.
    structured_config: <dict>
```
