### ISSUE TITLE
Bug(eos_cli_config_gen): NTP authentication keys don't render if the hash_algorithm isn't defined, but it is not mandatory in the schema

### ISSUE THREAD

**Issue by colinmacgiolla** [aristanetworks/ansible-avd#4732]
### Issue Summary

The [currect schema](https://github.com/aristanetworks/avd/blob/40626f71d5ce2b84b6b313adec49e27019773afd/python-avd/pyavd/_eos_cli_config_gen/schema/schema_fragments/ntp.schema.yml#L75) specifies the following:
```yaml
  authentication_keys:

      # Key identifier.
    - id: <int; 1-65534; required; unique>
      hash_algorithm: <str; "md5" | "sha1">

      # Obfuscated key.
      key: <str>
      key_type: <str; "0" | "7" | "8a">
```

However the [code](https://github.com/aristanetworks/avd/blob/40626f71d5ce2b84b6b313adec49e27019773afd/python-avd/pyavd/_eos_cli_config_gen/j2templates/eos/ntp.j2#L9C1-L20C17) for that section requires the `hash_algorithm`.
```jinja2
{%     for authentication_key in ntp.authentication_keys | arista.avd.natural_sort('id') %}
{%         if authentication_key.id is arista.avd.defined and
              authentication_key.key is arista.avd.defined and
              authentication_key.hash_algorithm is arista.avd.defined %}
{%             set ntp_auth_key_cli = "ntp authentication-key " ~ authentication_key.id ~ " " ~ authentication_key.hash_algorithm %}
{%             if authentication_key.key_type is arista.avd.defined %}
{%                 set ntp_auth_key_cli = ntp_auth_key_cli ~ " " ~ authentication_key.key_type %}
{%             endif %}
{%             set ntp_auth_key_cli = ntp_auth_key_cli ~ " " ~ authentication_key.key | arista.avd.hide_passwords(hide_passwords) %}
{{ ntp_auth_key_cli }}
{%         endif %}
{%     endfor %}
```

As I see it, we could go 3 ways as a bug fix;

1. Mark the `hash_algorithm` as `required` in the schema
2. Set the default `hash_algorithm` as `md5`
3. Redo the jinja2 template to render even if the `hash_algorithm` is unspecified

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
