### ISSUE TITLE
eos_cli_config_gen / pim anycast rp config is not generated if 'other_anycast_rp_addresses' is not defined

### ISSUE THREAD

**Issue by philippebureau** [aristanetworks/ansible-avd#4753]
### Issue Summary

example structured data:

```
      router_pim_sparse_mode:
        ipv4:
          anycast_rps:
            - address: 10.64.96.15
```

config output:
```
!
router pim sparse-mode
   ipv4
!
```

if you add ''other_anycast_rp_addresses' value it generate config

```
      router_pim_sparse_mode:
        ipv4:
          anycast_rps:
            - address: 10.64.96.15
              other_anycast_rp_addresses:
                - address: ""
```
output:
```
!
router pim sparse-mode
   ipv4
      anycast-rp 10.64.96.15 
!
```

the jinja template 'python-avd/pyavd/_eos_cli_config_gen/j2templates/eos/router-pim-sparse-mode.j2'

i think the template should check if 'other_anycast_rp_addresses' exist before going into the for loop at line 45 and add elif with a for loop through anycast_rps.address 

![Screenshot from 2024-11-21 10-08-07](https://github.com/user-attachments/assets/ebedd1a9-d0bb-4368-80e9-8b7af7608d61)

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI with AVD Runner

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
