### ISSUE TITLE
add support for fips_restrictions

### ISSUE THREAD

**Issue by KrasenKolev** [aristanetworks/ansible-avd#4760]
### Discussed in https://github.com/aristanetworks/avd/discussions/4588

Add support for fips restrictions under management security -> ssl profile.  In eos_cli_config_gen role -> management_ssh there is support for fips restrictions, but it’s missing in ssl profile.  

```
management_security:
## OMIT ##
  ssl_profiles:
    - name: <str>
      tls_versions: <str>
      fips_restrictions: <bool> 
      ## OMIT ##
```
