### ISSUE TITLE
add support for unix-socket protocol

### ISSUE THREAD

**Issue by KrasenKolev** [aristanetworks/ansible-avd#4761]
### Discussed in https://github.com/aristanetworks/avd/discussions/4588

add support for protocol unix-socket under management api https-commands In management_api_http there is boolean for http and https protocols, but it’s missing for unix-socket.

```
management_api_http:
  enable_http: <bool>
  enable_https: <bool>
  enable_unix_socket: <bool>
  ## OMIT ##
```
