### ISSUE TITLE
Feat(eos_designs): Add platform match criteria for network_ports

### ISSUE THREAD

**Issue by kpbush30** [aristanetworks/ansible-avd#4786]
### Enhancement summary

When applying network port profiles using the `network_ports` data structure, add the ability to target device hostnames with regex AND platform. This is helpful, especially in larger deployments, where hostname convention may not indicate platform differences that make it difficult to apply port profiles/configuration across large groups of devices.

### Which component of AVD is impacted

eos_designs

### Use case example

This is highly dependent on a customer's environment, hostname convention, and platform selection. In a use case where access switches are a combination of 24 and 48 port switches (or 750 chassis) and hostname convention does not take into account platform specifics, you must use complex regex to try and peel off specific switches. The use case is applying blanket access port profiles across all switches (especially in a large campus). The same benefit is recognized in datacenter as well.

The model below would overlap and requires breakout of match criteria or increasingly complex regex to target switches of specific platforms based on hostname alone.

```yaml
network_ports:

    # Regex matching the full hostname of one or more switches.
    # This expression catches all hostnames regardless of platform
  - switches:
      - "floor[1-3].*sw[0-9]+.*"
      
    switch_ports:
      - {{ 'Ethernet1-48' | range_expand }}
      
  - switches:
      - "floor[1-3].*sw[0-9]+.*"
      
     switch_ports:
      - {{ 'Ethernet1-24' | range_expand }}
```

### Describe the solution you would like

The ability to match on the filtered list AND the device platform assigned would make this more efficient in applying port configurations. Example below can easily target the same hostname regex with the ability to target 24 vs 48 port systems.

```yaml
network_ports:

    # Regex matching the full hostname of one or more switches.
    # This expression catches all hostnames regardless of platform
  - switches:
      - "floor[1-3].*sw[0-9]+.*"
     platforms:
       - 720XPM-48Y6
     switch_ports:
      - {{ 'Ethernet1-48' | range_expand }}
      
  - switches:
      - "floor[1-3].*sw[0-9]+.*"
     platforms:
       - 720XPM-24Y6
     switch_ports:
      - {{ 'Ethernet1-24' | range_expand }}
```

### Describe alternatives you have considered

Other than a long list of port profiles to match each switch.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
