### ISSUE TITLE
Feat(eos_designs):  Support underlay address pool per spine.

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#4801]
### Enhancement summary

Allow for the configuration of an ip underlay pool per uplink_switch. 

### Which component of AVD is impacted

eos_designs

### Use case example

The ability to specify different addressing per uplink switch allows for deterministic PIM DR election.   

### Describe the solution you would like

If uplink_ipv4_pool is specified as a list, such as:
```
uplink_ipv4_pool:
  - 10.10.2.0/24
  - 10.10.1.0/24
 ```

If uplink_switches are defined as `uplink_switches: [SPINE1,SPINE2]` then uplinks to SPINE1 use pool 10.10.2.0/24 and SPINE2 use 10.10.1.0/24

### Describe alternatives you have considered

This could be implemented with custom jinja templates.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I don't think we will implement this. We have added `downlink_pools` to be set on the spine. It contains an inteface range for each pool which is used to index into the pool. This was built for cases where they want pools per spine linecard. I think it could be used for your case as well by just having a single downlink pool and all the downlink interfaces of the spine associated. It would only be used if you remove the uplink pool 

Note that this can _only_ be set per node.

 ```yaml
<node_type_keys.key>:

  # Define variables per node.
  nodes:

      # The Node Name is used as "hostname".
    - name: <str; required; unique>

      # IPv4 pools used for links to downlink switches. Set this on the parent switch. Cannot be combined with `uplink_ipv4_pool` set on the downlink switch.
      downlink_pools:

          # IPv4 pool from which subnets will be allocated for links to downlink switches.
        - ipv4_pool: <str>

          # List of downlink interfaces or ranges of interfaces to use this pool. The index of the interface in this list will determine which subnet will be taken from the pool.
          downlink_interfaces:
            - <str>
```
