### ISSUE TITLE
AVD structured config not generating EOS CLI for snmp-server commands

### ISSUE THREAD

**Issue by rys-arista** [aristanetworks/ansible-avd#4802]
### Issue Summary

During testing of the SNMP feature, we noticed that while the `"snmp-server <server_ip>"` details are correctly captured in the AVD model, they are not reflected in the EOS CLI output.

Below provided  the snmp config  we used along with the corresponding AVD output. We're currently using AVD version 4.10.2.

**SNMP Configuration:**
```
snmp-server contact 123-456-789
snmp-server location LOCATION-LOC
snmp-server source-interface traps mgmt0
snmp-server user admin vdc-admin auth md5 0xafe1e3d7f36cfae8473c55a priv 0xafe1e3d7f36cfae8473c55 localizedkey
snmp-server host 192.168.1.10 traps version 2c public
snmp-server host 192.168.1.10 use-vrf management
snmp-server host 192.168.2.20 traps version 2c public
snmp-server host 192.168.2.20 use-vrf management
snmp-server enable traps bgp state-changes limited
snmp-server enable traps callhome event-notify
snmp-server enable traps callhome smtp-send-fail
snmp-server enable traps cfs state-change-notif
snmp-server enable traps lldp lldpRemTablesChange
snmp-server enable traps cfs merge-failure
snmp-server enable traps port-security access-secure-mac-violation
snmp-server enable traps port-security trunk-secure-mac-violation
snmp-server enable traps aaa server-state-change
snmp-server enable traps hsrp state-change
snmp-server enable traps feature-control FeatureOpStatusChange
snmp-server enable traps sysmgr cseFailSwCoreNotifyExtended
snmp-server enable traps config ccmCLIRunningConfigChanged
snmp-server enable traps snmp authentication
snmp-server enable traps mpls ldp session-up
snmp-server enable traps mpls ldp session-down
snmp-server enable traps link cisco-xcvr-mon-status-chg
snmp-server enable traps vtp notifs
snmp-server enable traps vtp vlancreate
snmp-server enable traps vtp vlandelete
snmp-server enable traps bridge newroot
snmp-server enable traps bridge topologychange
snmp-server enable traps stpx inconsistency
snmp-server enable traps stpx root-inconsistency
snmp-server enable traps stpx loop-inconsistency
snmp-server enable traps system Clock-change-notification
snmp-server community public group vdc-operator
snmp-server community public use-acl SNMP-RO
```

**AVD structured model:**
```
snmp_server:
  communities:
  - access_list_ipv4:
      name: SNMP-RO
    name: public
  contact: 123-456-789
  hosts:
  - host: 192.168.1.10
    version: 2c
    vrf: management
  - host: 192.168.2.20
    version: 2c
    vrf: management
  location: LOCATION-LOC
  traps:
    snmp_traps:
    - name: bgp state-changes limited
    - name: callhome event-notify
    - name: callhome smtp-send-fail
    - name: cfs state-change-notif
    - name: lldp lldpRemTablesChange
    - name: cfs merge-failure
    - name: port-security access-secure-mac-violation
    - name: port-security trunk-secure-mac-violation
    - name: aaa server-state-change
    - name: hsrp state-change
    - name: feature-control FeatureOpStatusChange
    - name: sysmgr cseFailSwCoreNotifyExtended
    - name: config ccmCLIRunningConfigChanged
    - name: snmp authentication
    - name: mpls ldp session-up
    - name: mpls ldp session-down
    - name: link cisco-xcvr-mon-status-chg
    - name: vtp notifs
    - name: vtp vlancreate
    - name: vtp vlandelete
    - name: bridge newroot
    - name: bridge topologychange
    - name: stpx inconsistency
    - name: stpx root-inconsistency
    - name: stpx loop-inconsistency
    - name: system Clock-change-notification
```

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

PyAVD

### Relevant log output

```shell
At present, the EOS CLI output for the above SNMP configuration is as follows. You can see the snmp-server commands are missing in the generated output.

snmp-server contact 123-456-789
snmp-server location LOCATION-LOC
snmp-server community public ro SNMP-RO
snmp-server enable traps aaa server-state-change
snmp-server enable traps bgp state-changes limited
snmp-server enable traps bridge newroot
snmp-server enable traps bridge topologychange
snmp-server enable traps callhome event-notify
snmp-server enable traps callhome smtp-send-fail
snmp-server enable traps cfs merge-failure
snmp-server enable traps cfs state-change-notif
snmp-server enable traps config ccmCLIRunningConfigChanged
snmp-server enable traps feature-control FeatureOpStatusChange
snmp-server enable traps hsrp state-change
snmp-server enable traps link cisco-xcvr-mon-status-chg
snmp-server enable traps lldp lldpRemTablesChange
snmp-server enable traps mpls ldp session-down
snmp-server enable traps mpls ldp session-up
snmp-server enable traps port-security access-secure-mac-violation
snmp-server enable traps port-security trunk-secure-mac-violation
snmp-server enable traps snmp authentication
snmp-server enable traps stpx inconsistency
snmp-server enable traps stpx loop-inconsistency
snmp-server enable traps stpx root-inconsistency
snmp-server enable traps sysmgr cseFailSwCoreNotifyExtended
snmp-server enable traps system Clock-change-notification
snmp-server enable traps vtp notifs
snmp-server enable traps vtp vlancreate
snmp-server enable traps vtp vlandelete
!
end
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
