### ISSUE TITLE
Feat(eos_designs): Expose rack, pod, dc, fabric information in the structured_config metadata

### ISSUE THREAD

**Issue by carl-baillargeon** [aristanetworks/ansible-avd#4805]
Having this information will be used in future integrations.

Proposal:
```yaml
metadata:
  # Physical location metadata
  rack: <str>
  pod_name: <str>
  dc_name: <str>
  fabric_name: <str>
```
