### ISSUE TITLE
Feat(eos_designs): Add polling interval knob for sflow_settings in  eos_designs

### ISSUE THREAD

**Issue by ernestoherrerab** [aristanetworks/ansible-avd#4813]
### Enhancement summary

The option to modify the polling interval for sflow_settings does not exist.

le01a(config)#sflow polling-interval ?
  <1-3600>  Seconds

### Which component of AVD is impacted

eos_designs

### Use case example

People would like to edit the sflow polling interval from the default 2 seconds.

### Describe the solution you would like

The goal would be to add the following to the sflow_settings data model as shown below:

```yaml
sflow_settings:
  polling_interval: 1
  sample: 
    rate: 16384
  destinations:
    - destination: 127.0.0.1
      vrf: use_mgmt_interface_vrf
```

### Describe alternatives you have considered

I am ready to submit the PR.

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
