### ISSUE TITLE
Feat (eos_cli_config_gen): Add ICMP echo size for Monitor Connectivity hosts

### ISSUE THREAD

**Issue by ctyrider** [aristanetworks/ansible-avd#4848]
### Enhancement summary

Add support for "icmp echo size ..." CLI syntax, under Monitor Connectivity hosts:

```
monitor connectivity
   host <HOST-NAME>
      icmp echo size <36-18024>
   vrf <VRF-NAME>
      host <HOST-NAME>
         icmp echo size <36-18024>

```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Specify custom size of ICMP echo probes for Monitor Connectivity Hosts

### Describe the solution you would like

New `icmp_echo_size` variable in `eos_cli_config_gen`:

```
monitor_connectivity:
  hosts:
     - name: <str; required; unique>
       icmp_echo_size: <int>
  vrfs:
     - name: <str; required; unique>
	   hosts:
             - name: <str; required; unique>
               icmp_echo_size: <int>

```

### Describe alternatives you have considered

n/a

### Additional context

n/a

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
