### ISSUE TITLE
Feat(eos_designs):  support mst pvst border as a node default

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#4872]
### Enhancement summary

Add a key such as `spanning_tree_mst_pvst_boundary: <bool>` so that it can be grouped with the other spanning tree options in the defaults section of a node_type.  

### Which component of AVD is impacted

eos_designs

### Use case example

Certain hardware platforms may not support the number of active spanning tree instances needed for PVST and a large number of configured VLANs.  In this case, the spanning tree msp pvst boundary configuration is used.

### Describe the solution you would like

Add a key such as `spanning_tree_mst_pvst_boundary: <bool>` so that it can be grouped with the other spanning tree options in the defaults section of a node_type.  

### Describe alternatives you have considered

This can be implemented today using:

```
    #spanning_tree_mode: mstp
    #spanning_tree_priority: 16384
    structured_config:
      spanning_tree:
        mst:
          pvst_border: true
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
