### ISSUE TITLE
Add support to eos_cli_config_gen for configuring "dhcp server ipv4" for a Port-Channel interface

### ISSUE THREAD

**Issue by ashenoy-arista** [aristanetworks/ansible-avd#4875]
### Enhancement summary

We are missing `dhcp_server_ipv4` attribute in eos_cli_config_gen schema for Port-Channel interface.
Allow eos_cli_config_gen schema to configure "dhcp server ipv4" eos cli under Port-Channel interface based on presence of `dhcp_server_ipv4` schema bool attribute set to true for a port_channel_interface when included within generated structured config.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

We intend to configure "dhcp_server_ipv4" under Port-Channel interface on EOS via "dhcp_server_ipv4" schema set for Port-Channel interface when supported by eos_cli_config_gen schema

### Describe the solution you would like

We would like to configure "dhcp_server_ipv4" (EOS cli) under Port-Channel interface based on presence of "dhcp_server_ipv4" bool schema attribute set for Port-Channel interface within eos_cli_config_gen

### Describe alternatives you have considered

Use raw eos cli option in host/group vars to realize the intended EOS cli configuration for Port-Channel interface
Here is a sample example/workaround for configuring "dhcp server ipv4" under L3 Port-Channel interface (feature in-progress)

```
   l3_port_channels:
        - name: Port-Channel8
          mode: active
          description: site3-wan1-Port-Channel4
          member_interfaces:
            - name: Ethernet8
          ip_address: 100.64.30.1/24
          raw_eos_cli: |
            dhcp server ipv4
```

### Contributing Guide

- [X] I agree to follow this project's Code of Conduct
