### ISSUE TITLE
Config difference after adopting arista avd v5.0.0

### ISSUE THREAD

**Issue by duddis1** [aristanetworks/ansible-avd#4899]
### Enhancement summary

We have resolved all the errors, and the configuration has been generated successfully with Arista AVD v5.0.0. However, we still need to address the following differences in the configuration:

Difference 1: The output is populating "no enable password" in each config file, but we want it to populate as "enable password key". I am providing the following fields as input in the fabric defaults, but the config is still generating with "no enable password":

```
enable_password:
  key: XXXXX
  disabled: false
  hash_algorithm: sha51
```

Difference 2: You previously requested moving EAPOL to the structured_config section. However, if we move it there, it will be applied to all switches, but we need it specifically for campus switches. Therefore, we have populated this in port_profiles before.

```
custom_structured_configuration:
  dot1x:
    dynamic_authorization: true
    eapol:
      disabled: true
```
Can you please suggest if there is any alternative solution for this?

Difference 3: The Interface Type column is not populated for IPv4 and L2 interfaces. This is not causing any issues with the config but is showing as a difference in the .md file.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Difference 1: I passed the following structure in the input, but the config is generated with "no enable password":

```
enable_password:
  key: XXXXX
  disabled: false
  hash_algorithm: sha512
```

Difference 2: I placed the EAPOL flag at the platform level to populate it only on campus switches, but it is not allowing it at this level. If we place it in the fabric defaults, it gets populated for all switches, but we need it only for campus switches.

```
custom_structured_configuration:
  dot1x:
    dynamic_authorization: true
    eapol:
      disabled: true
```
Difference 3: The "Interface Type" field is not being populated in the .md file, but there is no difference for this in the config file.

### Describe the solution you would like

Difference 1: The config should be generated with "enable password key" when we set disabled: false.

Difference 2: EAPOL should be available at the platform level or in the port profile; otherwise, it will be populated for all switches.

Difference 3: The "Interface Type" field should be populated as before in the .md files.

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
re 1:
```yaml
custom_structured_configuration_enable_password:
  key: XXXXX
  disabled: false
  hash_algorithm: sha512
```

re 2:
```yaml
# Guessing the node type here - adjust as needed
l2leaf:
  defaults:
    structured_config:
      dot1x:
        dynamic_authorization: true
        eapol:
          disabled: true
```

**Comment by duddis1** [comment]
The first issue with "no enable password" is fixed.

For the second one for eapol, it seems dot1x config need to be populated under ethernet_interfaces, please check whether this is correct, earlier we added this under port_profiles until 4.x.
```
    ethernet_interfaces:
      dot1x:
        dynamic_authorization: true
        eapol:
          disabled: true
```


Also, please advise do you have support for adding below attributes in the config?

3rd party transceivers:

=====================================
`service unsupported-transceiver Registers_of_Scotland`
 

MBH-CAMP01-DOT1X
==========================================
```
router bgp 65111
vlan-aware-bundle PROD-VRF
redistribute dot1x
!
```

**Comment by duddis1** [comment]
Hi @ClausHolbechArista ,  Can you please update on this ticket?

**Comment by ClausHolbechArista** [comment]
Hi @duddis1, please note this is an open source project with best-effort community support. Arista sells TAC support for AVD, where you can have the usual awesome TAC response times and expertise.

That said, I don't think your snip on dot1x worked exactly like that, but I think I get your point. Try doing this:

```yaml
port_profiles:
  - profile: dot1x_interface
    structured_config:
      dot1x:
        dynamic_authorization: true
        eapol:
          disabled: true
```
and point to that profile from your connected endpoints and/or network_ports.

3rd part transceivers, you can do

```yaml
unsupported_transceiver:
  license_name: <>
  license_key: <>
```

For the vlan aware bundle you need to use the `evpn_vlan_bundle` setting under each SVI and then define the bundle under `evpn_vlan_bundles`:
```yaml
evpn_vlan_bundles:
  - name: mybundle
    id: 123
    bgp:
      raw_eos_cli: |-
        redistribute dot1x
```
