### ISSUE TITLE
AVD 5.1.0 eos_cli_config_gen role ignoring variables in event-handler config

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#4902]
### Issue Summary

AVD 5.1.0 does not replace the variables in this event-handler configuration with the values, but it is rendering it as plain text.
AVD 4.10.2 is working correct on it.

```
  - name: ConfigureHardwareModel
    trigger: on-boot
    actions:
      # Define BASH command action. Command could be multiline also.
      bash_command: |
        python -m Acons Sysdb << EOF
        cd /ar/Sysdb/hardware/entmib
        _.fixedSystem.modelName = '{{ hw_model }}'
        _.systemMacAddr = '{{ mac_address }}'
        EOF
    delay: 60
```

### Which component(s) of AVD impacted

eos_cli_config_gen

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
inventory.yml

hosts:
  KHM-switch-01:
    ansible_host: 10.0.110.239
    mac_address: 50:de:01:73:58:2f
    hw_model: CCS-720DT-48S-2
    is_deployed: true


all.yml

event_handlers:
  - name: ConfigureHardwareModel
    trigger: on-boot
    actions:
      # Define BASH command action. Command could be multiline also.
      bash_command: |
        python -m Acons Sysdb << EOF
        cd /ar/Sysdb/hardware/entmib
        _.fixedSystem.modelName = '{{ hw_model }}'
        _.systemMacAddr = '{{ mac_address }}'
        EOF
    delay: 60
```

### Relevant log output

```shell
renderd config looks like this:


event-handler ConfigureHardwareModel
   trigger on-boot
   action bash
      python -m Acons Sysdb << EOF
      cd /ar/Sysdb/hardware/entmib
      _.fixedSystem.modelName = '{{ hw_model }}'
      _.systemMacAddr = '{{ mac_address }}'
      EOF
   delay 60
```

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
It works for me on `devel` branch as well as v5.1.0:

Adding to hostvars:
![Image](https://github.com/user-attachments/assets/ff801f64-0fee-4a22-ba30-f256c8e3068e)

Seeing correctly updated config:
![Image](https://github.com/user-attachments/assets/1af25945-dc8e-4126-8293-be590e601ce1)


All this happens outside of AVD. The Jinja rendering is handled by Ansible before loading the AVD code. Try moving the `hw_model` and `mac_address` around to see if it makes a difference. Also try different `ansible-core` versions. I used 2.16.13 in my testing (just the random version I had installed).

**Comment by kmueller68** [comment]
@ClausHolbechArista 
I am using your AVD Dev Container "Universal".

I am using two different event-handler using `hw_model` variable.
It is working well for `name: EosIntfMapping` but not for `name: ConfigureHardwareModel`.
Therefore I believe that `hw_model` is general availble to be replaced by its value.

Any tipps how to driil it down?

all.yml
```
hw_model: CCS-720DT-48S-2R

### Event Handler Settings ###
event_handlers:
  - name: ConfigureHardwareModel
    trigger: on-boot
    actions:
      # Define BASH command action. Command could be multiline also.
      bash_command: |
        python -m Acons Sysdb << EOF
        cd /ar/Sysdb/hardware/entmib
        _.fixedSystem.modelName = '{{ hw_model }}'
        _.systemMacAddr = '{{ system_mac_address }}'
        EOF
    delay: 60

  - name: EosIntfMapping
    trigger: on-boot
    actions:
      # Define BASH command action. Command could be multiline also.
      bash_command: "FastCli -p 15 -c copy http://10.0.110.35/{{ hw_model }}.json flash:EosIntfMapping.json; EOF"
    delay: 60
```

result:

```
!
event-handler ConfigureHardwareModel
   trigger on-boot
   action bash
      python -m Acons Sysdb << EOF
      cd /ar/Sysdb/hardware/entmib
      _.fixedSystem.modelName = '{{ hw_model }}'
      _.systemMacAddr = '{{ system_mac_address }}'
      EOF

   delay 60
!
event-handler EosIntfMapping
   trigger on-boot
   action bash FastCli -p 15 -c copy http://10.0.110.35/CCS-720DT-48S-2R.json flash:EosIntfMapping.json; EOF
   delay 60
!
```

**Comment by ClausHolbechArista** [comment]
In your latest snip you have `{{ system_mac_address }}` where you had `{{ mac_address }}` in the previous one. The way inline jinja works in Ansible is that it will skip the full string, if _any_ value is unavailable. So Try to also set `system_mac_address` above and rerun. It may help you troublehshoot further.

**Comment by kmueller68** [comment]
@ClausHolbechArista Thank you.
It is an issue that both values must be available.
If I both set in the yaml with the event_handler, then it works.

I now have to figure out, why `system_mac_address` under node_group is unavailable.


```
 node_groups:
    - group: SWITCHES_CS
      bgp_as: "65402.10001"
      nodes:
        - name: switch-cs-208-10
          id: 10
          serial_number: xxxxxxxxx
          system_mac_address: b4:92:fe:a3:f1:db
          mgmt_ip: "{{ mgmt_prefix | ansible.utils.ipaddr('net') | ansible.utils.ipaddr('10') }}"
```
