### ISSUE TITLE
Support for additional platform MMU profile options

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#4921]
### Enhancement summary

We are looking to replicate configurations for AI deployment. We need to modify some buffer allocation settings in some platforms.

In particular the headroom pool limit configuration as described in these TOIs:

https://www.arista.com/en/support/toi/eos-4-15-0f/19869-mmu-profiles-for-front-panel-ports
https://www.arista.com/en/support/toi/eos-4-21-3f/14110-mmu-profile-reservation-in-cells

```
switch(config)#platform trident mmu headroom-pool limit cells <cells>
switch(config)#platform trident mmu headroom-pool limit bytes <bytes>

(config)#platform trident mmu headroom-pool limit ?
  bytes         Specify the headroom pool limit (in bytes)
  cells         Specify the headroom pool limit (in cells)
  <1-33554432>  Max limit on headroom pool size

(config)#platform trident mmu headroom-pool limit cells ?
  <1-131072>  Max limit on headroom pool size
```
And also the ingress priority-group:
```
platform trident mmu queue profile CUSTOM
(queue-profile-<name>)# ingress priority-group <priority-group-num> reserved <bytes>

(config-queue-CUSTOM)#ingress priority-group ?
  <0-7>  The priority-group group number

(config-queue-CUSTOM)#ingress priority-group 0 ?
  reserved   Specify the amount of memory that should be reserved
  threshold  Specify the dynamic shared memory threshold

(config-queue-CUSTOM)#ingress priority-group 0 reserved ?
  bytes        Specify the amount of memory that should be reserved (in bytes)
  cells        Specify the amount of memory that should be reserved (in cells)
  <0-2097152>  Amount of memory that should be reserved (in bytes)

(config-queue-CUSTOM)#ingress priority-group 0 threshold ?
  1      alpha1
  1/128  alphaDiv128
  1/16   alphaDiv16
  1/2    alphaDiv2
  1/32   alphaDiv32
  1/4    alphaDiv4
  1/64   alphaDiv64
  1/8    alphaDiv8
  2      alpha2
  4      alpha4
  8      alpha8
```
This is currently not supported:
https://avd.arista.com/5.1/roles/eos_cli_config_gen/docs/input-variables.html#platform

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Adjust trident buffer allocation for AI deployment.

### Describe the solution you would like

Expand ip-platform section in eos_cli_config_gen to support this.

### Describe alternatives you have considered

```
custom_structured_configuration_eos_cli: |
  platform trident mmu headroom-pool limit cells 10000

platform:
  trident:
    mmu:
      active_profile: CUSTOM
      queue_profiles:
        - name: CUSTOM
          unicast_queues:
            - id: 1
              threshold: 2
            - id: 3
              threshold: 8
```
But missing the priority group option.

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct
