### ISSUE TITLE
Support structured_config in "network services -> VRF OSPF configuration" section

### ISSUE THREAD

**Issue by forcecity** [aristanetworks/ansible-avd#4924]
### Enhancement summary

Would also be a good idea to support structured_config in "network services -> VRF OSPF configuration" section. For BGP, it has the possibility to configure the structured configs under each VRFs. So I think, for OSPF, it is also a good idea to have this so that people can use the parameters defined in cli_config_gen at network services layer.

### Which component of AVD is impacted

eos_designs

### Use case example

BGP EVPN overlay over a partially-meshed routed OSPF core with a partial mesh between the cores. Define the extra parameters under network services based on VRFs directly.

### Describe the solution you would like

```
<network_services_keys.name>:
  - name: xxx
    vrfs:
      - name: yyy
        ospf:
          structured_config:
            auto_cost_reference_bandwidth: xxxxx
            ospf_maximum_paths: xxxxx
            ......
           raw_eos_cli:
```

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct
