### ISSUE TITLE
Feat(eos_designs): support type 8a bgp passwords

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#4930]
### Enhancement summary

When 

```
management security
   password encryption reversible aes-256-gcm
```

is configured, type 8a passwords are shown in the configuration.  AVD always specifies the type 7 password

```
bgp_peer_groups:
  ipv4_underlay_peers:

    # Name of peer group.
    name: <str; default="IPv4-UNDERLAY-PEERS">

    # Type 7 encrypted password.
    password: <str>
```

### Which component of AVD is impacted

eos_designs

### Use case example

please detail your use case

### Describe the solution you would like

The feature requested is to change the password type to 8a when ` password encryption reversible aes-256-gcm` is set.  In the alternative, set an additional key specifying the password_type under the peer_group.

### Describe alternatives you have considered

We used a python script to update the setting, basically doing a:

eos_cli = eos_cli.replace("password 7", "password 8a")

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct
