### ISSUE TITLE
Banner per device appended to standard banner

### ISSUE THREAD

**Issue by PieterL75** [aristanetworks/ansible-avd#4940]
### Enhancement summary

I would like to be able to add extra lines to the 'fabric defined banner' for some devices.

The default motd/login banners are defined in the fabric.yml
It would be great if there was a config variable that can be used to pre or append banner text per device/group

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

For each device I want to add extra information to the motd banner (racklocation, customer purpose, ...) without having to repeat the fabric wide general banner.

### Describe the solution you would like

new variables available as structured_config under node_type_default/node_groups/nodes.

```
banners_prepend:
  # Multiline string without ending EOF
  login: <str>
  # Multiline string without ending EOF
  motd: <str>

banners_append:
  # Multiline string without ending EOF
  login: <str>
  # Multiline string without ending EOF
  motd: <str>
```
the `banner_prepend` is added before the 'banner', the 'banner_append' is inserted just before the EOF line

### Describe alternatives you have considered

I tried to accomplish this with variable, but the Jinja is not parsed and put litterly in the config:

```
banners:
  login: !unsafe "{{ '\n'.join((_fabric_banner_login, _device_banner_login ,'EOF')) }}"
  motd: "{{ _fabric_banner_motd }}{{ _device_banner_motd }}\nEOF"
```
becomes
```
banner login
{{ '
'.join((_fabric_banner_login, _device_banner_login ,'EOF')) }}
EOF

!
banner motd
{{ _fabric_banner_motd }}{{ _device_banner_motd }}
EOF
!
```

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I think this is a good use case for inline jinja.

Something like:
```
banners:
  login: |-
    {{ ([device_banner | arista.avd.default(""), common_banner | arista.avd.default("")]) | join("\n") }}
```

**Comment by PieterL75** [comment]
I tried that, but the jinja is not being processed, it is taken over literally.
Or do you mean as a solution to the implementation in the config_gen ?

**Comment by ClausHolbechArista** [comment]
Your snip contains !unsafe, which will prevent ansible from templating that.

**Comment by PieterL75** [comment]
forgot to remove that from the FR, but even without, the jinja is just passed to the device config without being parsed (See the banner motd)

**Comment by ClausHolbechArista** [comment]
Something in your vars is missing. Inline jinja in Ansible returns the original template if _any_ variable is missing. You can use our default filter to handle that.

Example with and without the default filter proving the point:

```yaml
_common_banner: |
  Foo

_device_banner: |
  Bar

custom_structured_configuration_banners:
  login: "{{ _missing_banner | arista.avd.default('') }}{{ _device_banner | arista.avd.default('') }}{{ _common_banner | arista.avd.default('') }}"
  motd: "{{ _missing_banner }}{{ _device_banner }}{{ _common_banner }}"
```

Leads to this update in the generated config:
![Image](https://github.com/user-attachments/assets/b1f7dc2d-33e2-4e71-a136-a4056e02d0c5)

**Comment by PieterL75** [comment]
Now that I know that the empty value was causing the problems..

How do i set a global variable on a node_group ? 
```
l2spine:
  defaults:
    spanning_tree_mode: rapid-pvst
  node_groups:
    - group: beaz1
      _banners_motd_device: |
        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        !! Changes only allowed with a CHG and during an approved window !!
        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
does not pickup that _banners_motd_device

Looks like this is not the way to go I guess

**Comment by ClausHolbechArista** [comment]
You will have to use the ansible group hierarchy to set this. So find or create a group_vars file for the group of devices and set it there. Alternatively you can try to set

```yaml
l2spine:
  defaults:
    spanning_tree_mode: rapid-pvst
  node_groups:
    - group: beaz1
      structured_config:
        _banners_motd_device: |
          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
          !! Changes only allowed with a CHG and during an approved window !!
          !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
Which will produce the `_banners_motd_device` in the _output_ of eos_designs, and it can be picked up by Ansible's templating.
