### ISSUE TITLE
new role to help to collect cli output 

### ISSUE THREAD

**Issue by ksator** [aristanetworks/ansible-avd#495]
**Issue Type**
-new role

**Describe the solution you'd like**
A new role to collect lot of cli accross a lot of devices. Usefull for an offline human review/troubleshooting.

Example: 

group vars: 
```
cli_to_collect: 
  - show ip bgp summary
  - show lldp neighbors 
  - show ip interface brief
  - show interfaces description
  - show ip route
  - show version | json
  - show running-config
  - show running-config section bgp
```
turn this playbook into an avd role
```
---
- name: Run commands on remote EOS devices and save the output
  hosts: eos
  connection: httpapi
  gather_facts: false
  
  tasks:

    - name: Create output directory for each EOS device
      file:
        path: "{{save_dir}}/cli/{{inventory_hostname}}"
        state: directory

    - name: run show commands on remote EOS devices
      eos_command:
        commands: "{{item}}"
      with_items: "{{cli_to_collect}}"
      register: cli_output

    - name: copy commands output in the save directory
      copy:
        content: "{{ item.stdout.0 }}"
        dest: "{{save_dir}}/cli/{{inventory_hostname}}/{{item.item}}.txt"
      loop: "{{ cli_output.results }}"
```
once the role is executed all commands output for each devices is available for a human review: 
```
ls {{save_dir}}/cli/
```
