### ISSUE TITLE
Feat ( eos_designs) : New node type keys specific to M&E deployments

### ISSUE THREAD

**Issue by sarunac** [aristanetworks/ansible-avd#4950]
### Enhancement summary

New default Node type Keys for M&E deployments

## Component(s) name

`arista.avd.eos_designs`

```yaml

node_type_keys:
  - key: ptp_leaf
    type: ptp_leaf
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 10
  - key: media_spine
    type: media_spine
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 20
  - key: media_l2leaf
    type: media_l2leaf
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
    default_ptp_priority1: 30
  - key: media_l3leaf
    type: media_l3leaf
    default_overlay_routing_protocol: none
    connected_endpoints: true
    network_services:
      l2: true
      l3: true
    default_ptp_priority1: 30
```

### Which component of AVD is impacted

eos_designs

### Use case example

Need new node types for m&e devices with custom ptp priorities and network services

### Describe the solution you would like

Need new node types for m&e devices with custom ptp priorities and network services

### Describe alternatives you have considered

Creating custom device types

### Additional context

https://docs.google.com/document/d/19hfw4nTshr5N0qRbfsM-SPk_1NpNPUoQSeF3dh47Gd8/edit?tab=t.0

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct
