### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for radius proxy

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#4965]
### Enhancement summary

Add support for configuring radius proxy for campus wifi and nac environments.
Radius proxy is available in EOS since 4.31.2F.
https://www.arista.com/en/support/toi/eos-4-31-2f/19037-radius-proxy
https://arista.my.site.com/AristaCommunity/s/article/Deploying-RADIUS-Proxy-on-Arista-Tunnel-Aggregator-Switches

We will start using this function now in two current campus lan & wifi projects on the central tunnel-aggregator VTEP switches.

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
radius proxy
   dynamic-authorization
   client key 7 0870151C514A5243445E
   client session idle-timeout 60 seconds
   !
   client group cg1
      client ipv4 1.1.1.1 vrf red
      client ipv4 10.10.10.0/24 vrf red key 7 065F57761A1B5D4A5746
      client ipv6 A:B:C:D:E:F:G:H vrf red key 7 065F57761A1B5D4A5746
      client ipv6 A:B:C:D:E:F:G:H/I vrf red
      client host hostname vrf blue key 7 014254570F5E5058791517
      server group sg1 sg2 sg3
```

### Describe the solution you would like

```

radius_proxy:
  client_groups:
    - group: <str; unique>
      server_group: <str;	multiple group names separated by space>

      # Encrypted key - only type 7 supported.
      key: <str; optional>

      hosts:
        # Hostname
        - host:  <str; unique>
          vrf: <str; required>
          # Encrypted key - only type 7 supported.
          key: <str; optional>

      prefixes_ipv4:
        # IPv4 address "A.B.C.D" or prefix "A.B.C.D/E"
        - prefix: <str; unique>
          vrf: <str; required>
          # Encrypted key - only type 7 supported.
          key: <str; optional>

      prefixes_ipv6:
        # IPv6 address "A:B:C:D:E:F:G:H" prefix "A:B:C:D:E:F:G:H/I".
        - prefix: <str; unique>
          vrf: <str; required>
          # Encrypted key - only type 7 supported.
          key: <str; optional>

  # Encrypted key - only type 7 supported.
  client_key: <str>

  client_session_idle_timeout: <int; 1 - 86400 seconds>

  dynamic_authorization: <bool>
```

### Describe alternatives you have considered

eos_cli does the job but it's not pretty.

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct

**Comment by carlbuchmann** [comment]
Small suggestion change host to client to match EOS naming.

```yaml
radius_proxy:
  client_groups:
    - group: <str; unique>
      server_group: <str;	multiple group names separated by space>

      clients:
        # Hostname
        - client:  <str; unique>
          vrf: <str; required>
          # Encrypted key - only type 7 supported.
          key: <str; optional>

      prefixes_ipv4:
        # IPv4 address "A.B.C.D" or prefix "A.B.C.D/E"
        - prefix: <str; unique>
          vrf: <str; required>
          # Encrypted key - only type 7 supported.
          key: <str; optional>

      prefixes_ipv6:
        # IPv6 address "A:B:C:D:E:F:G:H" prefix "A:B:C:D:E:F:G:H/I".
        - prefix: <str; unique>
          vrf: <str; required>
          # Encrypted key - only type 7 supported.
          key: <str; optional>

  # Encrypted key - only type 7 supported.
  client_key: <str>

  client_session_idle_timeout: <int; 1 - 86400 seconds>

  dynamic_authorization: <bool>
```

**Comment by carlbuchmann** [comment]
For ipv4 and ipv6 EOS also supports address and prefix, so we need to adjust the data model:

```eos
eos-1(config-rp-cg-test3)#client ipv4 ?
  A.B.C.D    IPv4 address
  A.B.C.D/E  IPv4 prefix

eos-1(config-rp-cg-test3)#client ipv6 ?
  A:B:C:D:E:F:G:H    IPv6 address
  A:B:C:D:E:F:G:H/I  IPv6 prefix
```

**Comment by carlbuchmann** [comment]
To help ensure the uniqueness of data entries, I would suggest the following data model. Pending review from other AVD maintainers:

```yaml
radius_proxy:
  # Encrypted key - only type 7 supported.
  client_key: <str>
  client_session_idle_timeout: <int; 1 - 86400 seconds>
  dynamic_authorization: <bool>
  client_groups:
    - group: <str; unique>
      server_groups: 
        - <str>
      vrfs:
        - name: <str; unique>
          clients:
              # Hostname or 
              # IPv4 address "A.B.C.D" or prefix "A.B.C.D/E" or
              # IPv6 address "A:B:C:D:E:F:G:H" prefix "A:B:C:D:E:F:G:H/I".
            - client: <str; unique>
              type: <str; "host" | "ipv4" | "ipv6" >
              # Encrypted key - only type 7 supported.
              key: <str; optional>
```

**Comment by ClausHolbechArista** [comment]
- `group` -> `name` in the `client_groups` list and set as primary key
- `client` set as primary key
- `type` should be required

If we want to avoid ambuiguity and issues only caught by EOS, we should create separate lists of `host_clients`, `ipv4_clients` and `ipv6_clients` and then set the format in the schema. (ipv4 accepts an address or a cidr). Unfortunately EOS sorts on the type first, then the address and finally the VRF, so it will require some data mangling to make the template sort them the same.

```yaml
radius_proxy:
  # Encrypted key - only type 7 supported.
  client_key: <str>
  # Idle timeout in seconds
  client_session_idle_timeout: <int; 1-86400>
  dynamic_authorization: <bool>
  client_groups:
    - name: <str; unique>
      server_groups: 
        - <str>
      vrfs:       
          # VRF name
        - name: <str; required; unique>
          ipv4_clients:
              # IPv4 address "A.B.C.D" or prefix "A.B.C.D/E" or
            - address: <str; format: ipv4; required; unique>
              # Encrypted key - only type 7 supported.
              key: <str; optional>
          ipv6_clients:
              # IPv6 address "A:B:C:D:E:F:G:H" prefix "A:B:C:D:E:F:G:H/I".
            - address: <str; format: ipv6; required; unique>
              # Encrypted key - only type 7 supported.
              key: <str; optional>
          host_clients:
            # Hostname
            - name: <str; required; unique>
              # Encrypted key - only type 7 supported.
              key: <str; optional>
  ```
