### ISSUE TITLE
Is the following topology supported?

### ISSUE THREAD

**Issue by Olen** [aristanetworks/ansible-avd#4987]
I am unable to wrap my head around how to configure this:

We have two 4 x 10G interfaces
Ethernet3/1 - L3, directly connected to an endpoint
Ethernet3/2 - L3, directly connected to an endpoint
Ethernet3/3
Ethernet3/4 - Part of Po1 - Connected to a 3 party router (uplink)

Ethernet4/1 - L3, directly connected to an endpoint
Ethernet4/2 - L3, directly connected to an endpoint
Ethernet4/3
Ethernet4/4 - Part of Po1 - Connected to a 3 party router (uplink)

The endpoints are configured under
```
tenants:
  vrfs:
    l3_interfaces:
      interfaces: 
        - Ethernet4/1
        ...
```
However I have not found a way to specify "speed 10g" anywhere in this section.  I have tested a range of different versions of "structured_config" but apparently not in the right location. 

For the uplinks to the router, I have tried every single combination I can think of, but getting to a place where I can both configure the link as a port-channel, AND specify "speed 10g" for the underlying interfaces seems to be more than I can cope with.

My best shot was the following:
```
routers:
- adapters:
  - endpoint_ports:
    - Ethernet2/5
    - Ethernet2/5
    port_channel:
      channel_id: '1'
      endpoint_port_channel: lag-1
      mode: active
    speed: 10g
    structured_config:
      channel_group:
        id: 1
        mode: active
      speed: 10g
      type: port-channel-member
    switch_ports:
    - Ethernet3/4
    - Ethernet4/4
    switches:
    - rt-a-spine-11
    - rt-a-spine-11
  name: xxxxx
```

But it does not create config for the two Ethernet interfaces (Ethernet3/4 and Ethernet4/4)
The router in the other end is from another brand and is not managed by AVD obviously.

Po1 has multiple subinterfaces in different VLANs, and is also configured in the different `tenants -> vrfs ...` and those interfaces look fine.

**Comment by ClausHolbechArista** [comment]
Take a look at `l3_edge`. It may have what you need.

We also _very_ recently added `l3_port_channels` under the `l3leaf` area. In the same area we also have per-node `l3_interfaces`, which should handle all this very well. Note that these models do not support VRFs.

To use `l3_port_channels` you will have to install from `devel` (check the installation guide) or wait a few days (a week maybe) when we release AVD version 5.2. To check out the docs for devel, just go to avd.arista.com and select `devel` on the top left.

**Comment by Olen** [comment]
Thanks. I'll have a look at the devel-version.

In the mean time, I worked around it after I found out I could add `ethernet_interfaces` under e.g.
```
spine:
  nodes:
    - node: xxxx
      structured_config:
        ethernet_interfaces:
```
