### ISSUE TITLE
Inventory to Container module fails to parse YAML file

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#499]
## Issue Type

- Bug Report

## Summary

Under certain circumstances, `inventory_to_container` module can fail to iterate and generate CVP topology with the following error message.

```shell
File "/tmp/ansible_arista.avd.inventory_to_container_payload_\
nydmlupk/ansible_arista.avd.inventory_to_container_payload.zip/\
ansible_collections/arista/avd/plugins/modules/\
inventory_to_container.py", line 307, in get_devices

TypeError: argument of type 'NoneType' is not iterable
```

Reported by @ClausHolbechArista 

## Role or Module Name

Module: `arista.avd.inventory_to_container`

Python version:

```shell
python --version
Python 3.6.12
```

## Steps to reproduce

Inventory file example

```yaml
---
  all:
    children:
      FABRIC:
        children:
          DDC1:
            children:
              DC1_SUPER_SPINES:
                hosts:
                  SS-DC1POD01-a-t:
                    ansible_host: 1.1.1.1
                  SS-DC1POD01-b-t:
                    ansible_host: 1.1.1.1
              DC1_ROUTE_SERVERS:
                hosts:
                  S-DC1POD01-a-t:
                    ansible_host: 1.1.1.1
              CST01:
                children:
                  CST01_SPINES:
                    hosts:
                      nwsp-DC1POD01-CST01a-t:
                        ansible_host: 1.1.1.1
                      nwsp-DC1POD01-CST01b-t:
                        ansible_host: 1.1.1.1
                  CST01_LEAFS:
                    children:
                      CST01_LEAFS_POD01:
                        hosts:
                          CL-DC1POD01-CST01-01a-POD01-t:
                            ansible_host: 1.1.1.1
                          CL-DC1POD01-CST01-01b-POD01-t:
                            ansible_host: 1.1.1.1
                      CST01_L3BORDERS_POD01:
                        hosts:
                          BL-DC1POD01-CST01-02a-t:
                            ansible_host: 1.1.1.1
                          BL-DC1POD01-CST01-02b-t:
                            ansible_host: 1.1.1.1
                      CST01_L2BORDERS_POD01:
                        hosts:
                          nwb2-DC1POD01-CST01-03a-t:
                            ansible_host: 1.1.1.1
```

Minimal Playbook:

```yaml
  - name: Configuration deployment with CVP
    hosts: CVP
    connection: local
    gather_facts: false
    collections:
      - arista.avd
    tasks:
      - name: run CVP provisioning
        import_role:
          name: arista.avd.eos_config_deploy_cvp
        vars:
          inventory_file: "{{inventory_dir}}/inventory.yml"
          container_root: DDC1
          configlets_prefix: CONFIGLET-
          device_filter: t
          state: present
```

### Expected results

Correct YAML structure for CVP_TOPOLOGY in `cv_server_topology.yml`

### Actual results

Traceback

```shell
File "/tmp/ansible_arista.avd.inventory_to_container_payload_\
nydmlupk/ansible_arista.avd.inventory_to_container_payload.zip/\
ansible_collections/arista/avd/plugins/modules/\
inventory_to_container.py", line 307, in get_devices

TypeError: argument of type 'NoneType' is not iterable
```
