### ISSUE TITLE
Feat(eos_designs): Add pvlan support for eos_design

### ISSUE THREAD

**Issue by jcassan** [aristanetworks/ansible-avd#5001]
### Enhancement summary

We would like to be able to configure private vlan feature within eos_design Network Services L2.

### Which component of AVD is impacted

eos_designs

### Use case example

For segmentation purposes, we use pvlan so Virtual Machines can only access a backup master server without allowing VM to access each other.

### Describe the solution you would like

I imagine two possible solutions.

first is to add direct private vlan configuration under l2vlans
```yaml
<network_services_keys.name>:
  - name: <str; required; unique>
    l2vlans:
      - id: <int; 1-4094; required>
        private_vlan:
          type: <str; "community" | "isolated">
          primary_vlan: <int>
 ```

second is to add a structured_config field :

```yaml
<network_services_keys.name>:
  - name: <str; required; unique>
    l2vlans:
      - id: <int; 1-4094; required>
        structured_config:
          private_vlan:
            type: <str; "community" | "isolated">
            primary_vlan: <int>
          
 ```

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct
