### ISSUE TITLE
Latest TerminAttr settings to AVD

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#505]
**Issue Type**

- Template enhancement
- Role enhancement
- Documentatin enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Add support for newer TerminAttr knobs so we are aligned with future CVP releases.

**Describe the solution you'd like**

Support for newer knobs under TerminAttr

Old
```
daemon TerminAttr
   exec /usr/bin/TerminAttr -ingestgrpcurl=< IP> -cvcompression=gzip -ingestauth=token,/tmp/token -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -ingestvrf=default -taillogs
   no shutdown
```
New
```
daemon TerminAttr
   exec /usr/bin/TerminAttr -cvaddr=< IP > -cvauth=token,/tmp/token -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -cvvrf=default -taillogs
   no shutdown
```

**Describe alternatives you've considered**

**Additional context**

**Comment by lermilov** [comment]
+1 to support https://eos.arista.com/toi/cvp-2019-1-0/cvp-with-terminattr-certificates/

**Comment by noredistribution** [comment]
So I was thinking of having the following data model (also contains grpcaddr #999 and would add a few more flags to the final merge ):
## TerminAttr yaml example

```yaml
---

daemon_terminattr:
  clusters:
    - name: primary
      cvaddrs:
          - 10.83.12.71:9910
          - 10.83.12.72:9910
          - 10.83.12.73:9910
      # only one of these can be set
      cvauth_token_file: /tmp/token
      # cvauth_token_secure_file: /tmp/cv-onboarding-token
      # cvauth_key: arista1234
    # - name: dublin
    #   cvaddrs:
    #       - 10.83.12.79:9910
    #   cvauth_key: "arista1234"
    - name: cvaas
      cvaddrs:
        - www.arista.io:443
      cvauth_token_secure_file: /tmp/cv-onboarding-token
  smashexcludes: "ale,flexCounter,hardware,kni,pulse,strata"
  ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
  disable_aaa: true
  cvvrf: MGMT
  cvproxy: http://cvpadmin:arista@10.83.12.78:3121
  grpcaddr: MGMT/0.0.0.0:6042
  grpcreadonly: true
  cvsourceip: 10.1.1.1
  cvobscurekeyfile: true
  taillogs: /var/log/messages
```

Sample configs would look like below:

## TerminAttr multi cluster streaming output

```
daemon TerminAttr
   exec /usr/bin/TerminAttr -cvopt primary.cvaddr=10.83.12.71:9910,10.83.12.72:9910,10.83.12.73:9910 -cvopt primary.cvauth=token,/tmp/token -cvopt cvaas.cvaddr=www.arista.io:443 -cvopt cvaas.cvauth=token-secure,/tmp/cv-onboarding-token -cvvrf=MGMT -cvsourceip=10.1.1.1 -cvobscurekeyfile -disableaaa -cvproxy=http://cvpadmin:arista@10.83.12.78:3121 -grpcaddr=MGMT/0.0.0.0:6042 -grpcreadonly -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -taillogs=/var/log/messages
   no shutdown
```

## TerminAttr single cluster streaming output

```shell
daemon TerminAttr
   exec /usr/bin/TerminAttr -cvaddr=10.83.12.71:9910,10.83.12.72:9910,10.83.12.73:9910 -cvauth=token,/tmp/token -cvvrf=MGMT -cvsourceip=10.1.1.1 -cvobscurekeyfile -disableaaa -cvproxy=http://cvpadmin:arista@10.83.12.78:3121 -grpcaddr=MGMT/0.0.0.0:6042 -grpcreadonly -smashexcludes=ale,flexCounter,hardware,kni,pulse,strata -ingestexclude=/Sysdb/cell/1/agent,/Sysdb/cell/2/agent -taillogs=/var/log/messages
   no shutdown
```

We've been moving away from ingest flags since 2017/2018 and it makes sense to standardize on cvaddr flags, which is what CVaaS uses too.

code example for this would be something like this (would have to be tweaked a bit to have the ansible avd specific knobs):


## TerminAttr j2 template

```jinja
{# eos - TerminAttr #}
{% set cvp_config = namespace() %}
{# Create list of non CVaaS server #}
daemon TerminAttr
{% if daemon_terminattr.clusters | length > 1 %}
{%    set cvp_config.cli = "exec /usr/bin/TerminAttr" %}
{% for cluster in daemon_terminattr.clusters %}
{%    set cvp_config.cli = cvp_config.cli ~  " -cvopt " ~ cluster.name ~ ".cvaddr=" ~ cluster.cvaddrs | join(',') %}
{%    if cluster.cvauth_key is defined %}
{%       set cvp_config.cli = cvp_config.cli ~ " -cvopt " ~ cluster.name ~ ".cvauth=key," ~ cluster.cvauth_key %}
{%    elif cluster.cvauth_token_file is defined %}
{%       set cvp_config.cli = cvp_config.cli ~ " -cvopt " ~ cluster.name ~ ".cvauth=token," ~ cluster.cvauth_token_file %}
{%    elif cluster.cvauth_token_secure_file is defined %}
{%       set cvp_config.cli = cvp_config.cli ~ " -cvopt " ~ cluster.name ~ ".cvauth=token-secure," ~ cluster.cvauth_token_secure_file %}
{%    endif%}
{% endfor %}
{% elif daemon_terminattr.clusters | length == 1 %}
{%    set cvp_config.cli = "exec /usr/bin/TerminAttr -cvaddr=" ~ daemon_terminattr.clusters[0].cvaddrs | join(',') %}
{%    if daemon_terminattr.clusters[0].cvauth_key is defined %}
{%       set cvp_config.cli = cvp_config.cli ~ " -cvauth=key," ~ daemon_terminattr.clusters[0].cvauth_key %}
{%    elif daemon_terminattr.clusters[0].cvauth_token_file is defined %}
{%       set cvp_config.cli = cvp_config.cli ~ " -cvauth=token," ~ daemon_terminattr.clusters[0].cvauth_token_file %}
{%    elif daemon_terminattr.clusters[0].cvauth_token_secure_file is defined %}
{%       set cvp_config.cli = cvp_config.cli ~ " -cvauth=token-secure," ~ daemon_terminattr.clusters[0].cvauth_token_secure_file %}
{%    endif %}
{%    endif %}
{% if daemon_terminattr.cvvrf is defined %}
{%    set cvp_config.cli = cvp_config.cli ~ " -cvvrf=" ~ daemon_terminattr.cvvrf %}
{% endif%}
{% if daemon_terminattr.cvsourceip is defined %}
{%    set cvp_config.cli = cvp_config.cli ~ " -cvsourceip=" ~ daemon_terminattr.cvsourceip %}
{% endif%}
{% if daemon_terminattr.cvgnmi is defined %}
{%    set cvp_config.cli = cvp_config.cli ~ " -cvgnmi" %}
{% endif%}
{% if daemon_terminattr.cvobscurekeyfile is true %}
{%    set cvp_config.cli = cvp_config.cli ~ " -cvobscurekeyfile" %}
{% endif%}
{% if daemon_terminattr.disable_aaa is true %}
{%    set cvp_config.cli = cvp_config.cli ~ " -disableaaa" %}
{% endif%}
{% if daemon_terminattr.cvproxy is defined %}
{%    set cvp_config.cli = cvp_config.cli ~ " -cvproxy=" ~ daemon_terminattr.cvproxy %}
{% endif%}
{% if daemon_terminattr.grpcaddr is defined %}
{%    set cvp_config.cli = cvp_config.cli ~ " -grpcaddr=" ~ daemon_terminattr.grpcaddr %}
{% endif%}
{% if daemon_terminattr.grpcreadonly is true %}
{%    set cvp_config.cli = cvp_config.cli ~ " -grpcreadonly" %}
{% endif%}
{% if daemon_terminattr.smashexcludes  %}
{%    set cvp_config.cli = cvp_config.cli ~ " -smashexcludes=" ~ daemon_terminattr.smashexcludes %}
{% else %}
{%    set cvp_config.cli = cvp_config.cli ~ " -smashexcludes=" %}
{% endif %}
{% if daemon_terminattr.ingestexclude  %}
{%    set cvp_config.cli = cvp_config.cli ~ " -ingestexclude=" ~ daemon_terminattr.ingestexclude %}
{% else %}
{%    set cvp_config.cli = cvp_config.cli ~ " -ingestexclude=" %}
{% endif %}
{% if daemon_terminattr.taillogs is defined  %}
{%         set cvp_config.cli = cvp_config.cli ~ " -taillogs=" ~ daemon_terminattr.taillogs %}
{% else %}
{%         set cvp_config.cli = cvp_config.cli ~ " -taillogs" %}
{% endif%}
   {{ cvp_config.cli }}
   no shutdown
```

Let me know what you think @ClausHolbechArista @carlbuchmann
