### ISSUE TITLE
Data-model issue in eos_cli_config_gen for SNMP local interfaces

### ISSUE THREAD

**Issue by aphillipps** [aristanetworks/ansible-avd#507]
## Issue Type

- Data-model issue in eos_cli_config_gen for SNMP local interfaces

## Summary

The data-model for local interfaces for SNMP should be modified as one interface can only be associated to one VRF in EOS.

## Role or Module Name
Eos_cli_config_gen

## Steps to reproduce

In the current model, with the following data:
```yaml
snmp_server:
  local_interfaces:
  - vrf: mgt
    name: Management1
  - name: Loopback0
  - vrf: test1
    name: Loopback12
  - vrf: test2
    name: Loopback12
```
eos_cli_config_gen will render:

```shell
snmp-server vrf mgt local-interface Management1
snmp-server local-interface Loopback0
snmp-server vrf test1 local-interface Loopback12
snmp-server vrf test2 local-interface Loopback12
```

in EOS this will result in the following configuration as one interface can only be associated to one VRF: 

```shell
snmp-server vrf mgt local-interface Management1
snmp-server local-interface Loopback0
snmp-server vrf test2 local-interface Loopback12
```

### Suggested Change

The data-model can be modified to limit the association local-interface/VRF as per EOS. 
Note that:
-  the key "vrfs" already exists in snmp_server for a different purpose 
-  a local interface can also be associated to the default vrf. 

See below the suggested data-model:

```yaml
snmp_server:
  local_interfaces:
    Management1:
      vrf: mgt
    Loopback0:
    Loopback12:
      vrf: test2
```

 eos_cli_config_gen will then render the following which is also the configuration in EOS:

```shell
snmp-server vrf mgt local-interface Management1
snmp-server local-interface Loopback0
snmp-server vrf test2 local-interface Loopback12
```
