### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for configuring dhcp server ipv4 and dhcp server ipv6 for Vlan interfaces

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#5086]
### Enhancement summary

We are missing dhcp_server_ipv4 and dhcp_server_ipv6 attribute in eos_cli_config_gen schema for Vlan interface.
Allow eos_cli_config_gen schema to configure "dhcp server ipv4" and "dhcp server ipv6" eos cli under Vlan interface based on presence of dhcp_server_ipv4 or dhcp_server_ipv6 schema bool attribute set to true for a vlan_interface when included within generated structured config.

```
interface Vlan10
   description WiFi users
   ip address 10.10.10.1/24
   dhcp server ipv4
   dhcp server ipv6
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

please detail your use case

```
vlan_interfaces:
  - name: Vlan10
    # Enable IPv4 DHCP server.
    dhcp_server_ipv4: true

    # Enable IPv6 DHCP server.
    dhcp_server_ipv6: true
```

should render

```
interface Vlan10
   dhcp server ipv4
   dhcp server ipv6
```

### Describe the solution you would like

```
vlan_interfaces:
  - name: <str; required; unique>

    # Enable IPv4 DHCP server.
    dhcp_server_ipv4: <bool>

    # Enable IPv6 DHCP server.
    dhcp_server_ipv6: <bool>
```

### Describe alternatives you have considered

Use eos cli option:
 
```
vlan_interfaces:
  - name: "Vlan3198"
    description: VL_MGMT
    shutdown: false
    vrf: default
    eos_cli: |
      dhcp server ipv4
      dhcp server ipv6
```

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct
