### ISSUE TITLE
"no protocol http" disapeard in v5.2.2

### ISSUE THREAD

**Issue by PieterL75** [aristanetworks/ansible-avd#5107]
### Issue Summary

After upgrade to v5.2.2, the `no protocol http` is missing in the `management api http` intended and generated config

### Which component(s) of AVD impacted

eos_cli_config_gen, eos_designs

### How do you run AVD ?

None

### Steps to reproduce

I have this in my FABRIC:
```
management_eapi:
  enable_http: false
  enable_https: true
custom_structured_configuration_management_api_http:
  https_ssl_profile: eos_https_tls1.2
  enable_vrfs:
    - name: mgmt-vrf
      access_group: SEC-MGMT-V4-IN
```

In 5.1.0 it generated
```
management_api_http:
  enable_vrfs:
  - name: mgmt-vrf
    access_group: SEC-MGMT-V4-IN
  enable_http: false
  enable_https: true
  https_ssl_profile: eos_https_tls1.2
```

in v5.2.2 it generates
```
management_api_http:
  enable_https: true
  https_ssl_profile: eos_https_tls1.2
  enable_vrfs:
  - name: mgmt-vrf
    access_group: SEC-MGMT-V4-IN
```

### Relevant log output

```shell

```

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct

**Comment by gmuloc** [comment]
Hi @PieterL75 thanks for reporting - I can confirm and reproduce the issue - sadly it was not part of our test suite.

Will push a PR out. In the meantime you can get back the previous behavior by adding `enable_http: false` to your custom structured config block:

```
management_eapi:
  enable_https: true
custom_structured_configuration_management_api_http:
  https_ssl_profile: eos_https_tls1.2
  enable_http: false
  enable_vrfs:
    - name: mgmt-vrf
      access_group: SEC-MGMT-V4-IN
```
