### ISSUE TITLE
Feature(cv_deploy): support multiple studios static configlets per device.

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#5116]
### Enhancement summary

With the legacy provisioning, there was an option to configure an ordered list of configlets to a device and apply a configlet to a container.

We would like to see this functionality implemented for the cv_deploy role.

### Which component of AVD is impacted

others

### Use case example

This will facilitate alternative options for day-2 operations.

### Describe the solution you would like

We currently have the functionality in https://avd.arista.com/5.1/roles/eos_config_deploy_cvp/index.html

sample:
```
# group_vars/DC1_FABRIC.yml

# List of additional CVP configlets to bind to devices and containers
# Configlets MUST be configured on CVP before running AVD playbooks.
cv_configlets:
  containers:
    DC1_L3LEAFS:
      - GLOBAL-ALIASES
  devices:
    DC1-L2LEAF2A:
      - GLOBAL-ALIASES
    DC1-L2LEAF2B:
      - GLOBAL-ALIASES
```

### Describe alternatives you have considered

We do this manually via the CloudVision GUI.

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct
