### ISSUE TITLE
Bug(eos_designs): support redistribute dot1x in network services

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-avd#5132]
### Issue Summary

In upgrading a repo from 4.10.2 to 5.2.2, the following snippet:

```
tenants:
  vrfs:
    svis:
      -id: 123
            ...
            bgp:
              structured_config:
                redistribute_routes: [ dot1x ]
```

has no corresponding key to set under the new `redistribute` key.

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell

```

### Relevant log output

```shell

```

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
I don't think we have changed the schema for redistribution on BGP VLANs. Only on BGP VRFs / default.

Snip from docs:
```yaml
router_bgp:
  <...>
  vlans:
    - id: <int; required; unique>

      # Key only used for documentation or validation purposes.
      tenant: <str>

      # Route distinguisher.
      rd: <str>
      rd_evpn_domain:
        domain: <str; "remote" | "all">

        # Route distinguisher.
        rd: <str>
      route_targets:
        both:
          - <str>
        import:
          - <str>
        export:
          - <str>
        import_evpn_domains:
          - domain: <str; "remote" | "all">
            route_target: <str>
        export_evpn_domains:
          - domain: <str; "remote" | "all">
            route_target: <str>
        import_export_evpn_domains:
          - domain: <str; "remote" | "all">
            route_target: <str>
      redistribute_routes:
        - <str>
      no_redistribute_routes:
        - <str>

      # Multiline EOS CLI rendered directly on the Router BGP, VLAN definition in the final EOS configuration.
      eos_cli: <str>
```
