### ISSUE TITLE
EOS CLI Dot1x

### ISSUE THREAD

**Issue by xaviramon** [aristanetworks/ansible-avd#5146]
### Enhancement summary

Configuration of dot1x global settings:
```
aaa unresponsive
radius av-pair
captive-portal
statistics packets dropped
vlan assignment group
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

configure above commands under dot1x, as example:
```
dot1x
   vlan assignment group TEST members 111
```

### Describe the solution you would like

Add the described variables to the working structure:

```
dot1x:
  system_auth_control: true
  dynamic_authorization: true
  radius_av_pair:
    framed_mtu: 1514
```

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct
