### ISSUE TITLE
Feat(eos_designs): Add 7388X5 to default platform_settings

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#5162]
### Enhancement summary

Add best practise default platform settings for 7388X5 to eos_designs.

Please verify the correct values internal to Arista.

### Which component of AVD is impacted

eos_designs

### Use case example

```
platform_settings:
- management_interface: Management0
  platforms:
  - 7388X5
  reload_delay:
    mlag: 300
```

### Describe the solution you would like

```
platform_settings:
- management_interface: Management0
  platforms:
  - 7388X5
  reload_delay:
    mlag: 300
```

### Describe alternatives you have considered
Use `custom_platform_settings:` 

_No response_

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct
