### ISSUE TITLE
Feat (eos_cli_config_gen): Add 'replay protection' support in MacSec profiles

### ISSUE THREAD

**Issue by ctyrider** [aristanetworks/ansible-avd#5179]
### Enhancement summary

Add support for "replay protection" CLI syntax, in MacSec profiles:

```
mac security
   profile <PROFILE-NAME>
      replay protection disabled
      replay protection window <0-4294967295>

```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Ability to configure 'replay protection' options under MacSec profiles

### Describe the solution you would like

```yaml
mac_security:
  profiles:
      # Profile-Name.
    - name: <str; required; unique>
      replay_protection:
        disabled: <bool>
        window: <int; 0-4294967295>

```

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct
