### ISSUE TITLE
PO created twice

### ISSUE THREAD

**Issue by PieterL75** [aristanetworks/ansible-avd#5193]
### Issue Summary

I have a set of EndPoints that create a PortChannel, based on a profile
then in my VRf's I have l3interfaces that create a subinterface on that PO.
The genereated config show that Po interface 2 times.
One for the EndPoints:

```
interface Port-Channel62
   !! AVD_PROFILE: CUSTOM_ROUTED_WITH_SUBINTERFACES_PO_LACPFAST
   no shutdown
   switchport
!
```
and once for the l3subinterface
```
interface Port-Channel62
   no shutdown
   no switchport
!
```

I have not deployed that config yet in production. Currently converting my brownfield to AVD.

Is that a valid config  ? or should both Po references be merged to one by AVD

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```
  - name: wan001
    adapters:
      - endpoint_ports: [xe-0/0/19, xe-1/0/19]
        switch_ports: [Ethernet6, Ethernet5]
        switches: [leaf1, leaf2]
        port_channel:
          description: ae62
          mode: active
          channel_id: 62
          structured_config:
            comment: "AVD_PROFILE: CUSTOM_ROUTED_WITH_SUBINTERFACES_PO_LACPFAST"
        profile: CUSTOM_ROUTED_WITH_SUBINTERFACES_PO_LACPFAST
```
and
```
  - profile: ROUTED_WITH_SUBINTERFACES
    enabled: true
    structured_config:
      switchport:
        enabled: false
   
  - profile: CUSTOM_ROUTED_WITH_SUBINTERFACES_PO_LACPFAST
    parent_profile: ROUTED_WITH_SUBINTERFACES
    port_channel:
      lacp_timer:
        mode: fast
```

This profile generates this PO config on the leaf1
```
interface Port-Channel62
   !! AVD_PROFILE: CUSTOM_ROUTED_WITH_SUBINTERFACES_PO_LACPFAST
   no shutdown
   switchport
!
interface Ethernet5
   no shutdown
   no switchport
   channel-group 62 mode active
   lacp timer fast
!
interface Ethernet6
   no shutdown
   no switchport
   channel-group 62 mode active
   lacp timer fast
```
so far (almost) good. Expept for that 'switchport' should be 'no switchport'

now, we add the vrf config (only relevant config is shown)
```
      - name: myVrf # id 20
        l3_interfaces:
          - interfaces: [Port-Channel62.3202, Port-Channel63.3202]
            nodes: [leaf1, leaf2]
            encapsulation_dot1q_vlan: [3202, 3202]
            ip_addresses: [100.71.1.10/29, 100.71.1.11/29]
            enabled: true
```
This in turn generates
```
interface Port-Channel62
   no shutdown
   no switchport
interface Port-Channel62.3202
   no shutdown
   encapsulation dot1q vlan 3202
   vrf myVrf 
   ip address 100.71.1.10/29
```
Causing a seconf Po62 interface in the config

### Relevant log output

```shell

```

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct

**Comment by ClausHolbechArista** [comment]
Re
```
    structured_config:
      switchport:
        enabled: false
```
put this under the port_channel key in the profile.

**Comment by ClausHolbechArista** [comment]
The other issue is that you are using `l3_interfaces` which only supports Ethernet interfaces. So in the output structured config the second "Port-Channel62" is under the `ethernet_interfaces` key. We do not support `l3_port_channels` in any shipping code, but we are merging a PR with this feature within minutes of me writing this :) So if you feel brave, you can run from "devel" (see installation guide for instructions).

**Comment by PieterL75** [comment]
that switchport setting indeed was required under the port_channel key.

I'll spinup a devcontainer to see if I can run the devel on my config !
Great stuff !

**Comment by PieterL75** [comment]
I installed the devcontainer of the 'devel' branch, but no changes when doing a rebuild. 
If you want, you can ping me on slack (I joined the networktocode)

**Comment by gmuloc** [comment]
@PieterL75 you need to update your input to

```
      - name: myVrf # id 20
        l3_port_channels: <<<<<<<<<<<<<<<<<<<<<<<
          - interfaces: [Port-Channel62.3202, Port-Channel63.3202]
            nodes: [leaf1, leaf2]
            encapsulation_dot1q_vlan: [3202, 3202]
            ip_addresses: [100.71.1.10/29, 100.71.1.11/29]
            enabled: true

**Comment by PieterL75** [comment]
Simply replacing that does not work, it gives me 
```
ERROR! [p01]: 'Validation Error: tenants[1].vrfs[5].l3_port_channels[0]': Unexpected key(s) 'interfaces, ip_addresses, nodes' found in dict.
ERROR! [p01]: 'Validation Error: tenants[1].vrfs[5].l3_port_channels[0]': Required key 'name' is not set in dict.
ERROR! [p01]: 'Validation Error: tenants[1].vrfs[5].l3_port_channels[0]': Required key 'node' is not set in dict.
ERROR! [p01]: 'Validation Error: tenants[1].vrfs[5].l3_port_channels[0].encapsulation_dot1q_vlan': Invalid type 'list'. Expected a 'int'.
```

**Comment by PieterL75** [comment]
Found the 'doc' https://github.com/aristanetworks/avd/blob/5c324ca3ac2518d02a72b3b8b3b1873858d85d2c/ansible_collections/arista/avd/roles/eos_designs/docs/tables/network-services-vrfs-l3-port-channel-settings.md

updating to
```
        l3_port_channels:
          - name: Port-Channel62.3202
            node: leaf1
            ip_address: 100.71.1.10/29
            encapsulation_dot1q_vlan: 3202
            enabled: true
          - name: Port-Channel63.3202
            node: leaf2
            ip_address: 100.71.1.11/29
            encapsulation_dot1q_vlan: 3202
            enabled: true
```

But it would be nice to also have that 'list' possibility to keep the config tight

**Comment by gmuloc** [comment]
indeed - apologies I should have mentioned this in my comment (answered too fast!)

**Comment by PieterL75** [comment]
the build now says
```
One or more L3 Port-Channels 'Port-Channel62' need to be specified as they have sub-interfaces referencing them.
One or more L3 Port-Channels 'Port-Channel63' need to be specified as they have sub-interfaces referencing them.
```

My endpoints file still has the Po62 and Po63 defined, with the portprofile to make that Po routed and enabled

**Comment by PieterL75** [comment]
It looks like I have to define the Po62 and Po63 under my l3leafs/nodes/node ??
that is not very handy.. 
the endpoints come out of a DCIM, and the l3leaf/nodes/node is static.. 
Can this be updated that the checks also see of the endpoints create the port-channel interfaces ?

**Comment by gmuloc** [comment]
Yes, basically the feature is not able to pick up port channels across module like you have today (between connected endpoints and network services).

You should be able to move the definition for some part (options may be missing) but if you just add in your tenant file

```
    l3_port_channels:
          - name: Port-Channel62
            node: leaf1
```

It should create what you need.

Because this time you would bu using the right output model (`port_channel_interfaces`) in the structure config, the two definitions should be merged together (today)

No need to go under nodes

**Comment by PieterL75** [comment]
I actually already have them in my tenant:

```
tenants:
  - name: T1
    vrfs:
     - name: MyVRF
        l3_port_channels:
          - name: Port-Channel62.3202
            node: leaf1
            ip_address: 100.71.1.10/29
            encapsulation_dot1q_vlan: 3202
            enabled: true
          - name: Port-Channel63.3202
            node: leaf2
            ip_address: 100.71.1.11/29
            encapsulation_dot1q_vlan: 3202
            enabled: true
```

The endpoints only have
```
  - name: wan001
    adapters:
      - endpoint_ports: [xe-0/0/19, xe-1/0/19]
        switch_ports: [Ethernet6, Ethernet5]
        switches: [leaf1, leaf2]
        port_channel:
          description: ae62
          mode: active
          channel_id: 62
          structured_config:
            comment: "AVD_PROFILE: CUSTOM_ROUTED_WITH_SUBINTERFACES_PO_LACPFAST"
        profile: CUSTOM_ROUTED_WITH_SUBINTERFACES_PO_LACPFAST
     - endpoint_ports: [xe-0/0/20, xe-1/0/20]
        switch_ports: [Ethernet6, Ethernet5]
        switches: [leaf1, leaf2]
        port_channel:
          description: ae63
          mode: active
          channel_id: 63
          structured_config:
            comment: "AVD_PROFILE: CUSTOM_ROUTED_WITH_SUBINTERFACES_PO_LACPFAST"
        profile: CUSTOM_ROUTED_WITH_SUBINTERFACES_PO_LACPFAST

```

**Comment by gmuloc** [comment]
Hmmm ok this is how it is intended to be used but you want them in VRF default.. let me edit

```
tenants:
  - name: T1
    vrfs:
     - name: MyVRF
        l3_port_channels:
          - name: Port-Channel62.3202
            node: leaf1
            ip_address: 100.71.1.10/29
            encapsulation_dot1q_vlan: 3202
            enabled: true
          - name: Port-Channel63.3202
            node: leaf2
            ip_address: 100.71.1.11/29
            encapsulation_dot1q_vlan: 3202
            enabled: true
>>>>>
      - vrf: default
        l3_port_channels:
          - name: Port-Channel62
            node: leaf1
          - name: Port-Channel63
            node: leaf1
>>>>>
```

**Comment by gmuloc** [comment]
Maybe lets go on a short call to take a look - can you ping me on networktocode slack (gmuloc) I cannot find you it seems

**Comment by PieterL75** [comment]
We made this work by settings
```
    vrfs:
      - name: default
        address_families: []
        vrf_id: 666
        l3_port_channels:
          - name: Port-Channel62
            node: leaf1            
          - name: Port-Channel63
            node: leaf2
     - name: MyVRF
        l3_port_channels:
          - name: Port-Channel62.3202
            node: leaf1
            ip_address: 100.71.1.10/29
            encapsulation_dot1q_vlan: 3202
            enabled: true
          - name: Port-Channel63.3202
            node: leaf2
            ip_address: 100.71.1.11/29
            encapsulation_dot1q_vlan: 3202
            enabled: true
```
