### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for static mac-address configuration

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#5202]
### Enhancement summary

Add support to configure static mac address-table entries, which will be used with the port-security protect mode feature.
https://www.arista.com/en/support/toi/eos-4-24-0f/14467-port-security-protect-mode

Port-security protect mode only allows a certain number of static configured or learned mac addresses.

There are more options behind `mac`and `mac address-table`, but I would like to start with the `static`first.

```
switch(config)#mac ?
  access-list    Named access-lists
  address-table  MAC forwarding table
  security       Media Access Control Security (802.1AE) commands

switch(config)#mac address-table ?
  aging-time    Set MAC address table entry maximum age
  flushing      Flush MAC entries
  notification  Options for notification
  reserved      Reserved
  static        static keyword
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

```
mac_address_table:
  static_entries:
    - mac_address: 1111.2222.3333
      vlan: 1021
      # 'drop' and 'interface' are mutually exclusive.
      drop: false
      # Interface. Example - Ethernet4, Port-Channel1, Vxlan1 etc.
      interface: Ethernet5
```

should render

```
mac address-table static 1111.2222.3333 vlan 1021 interface Ethernet5
```

### Describe the solution you would like

```
mac_address_table:
  static_entries:
    - mac_address: <str; required>
      vlan: <str>
      # 'drop' and 'interface' are mutually exclusive.
      drop: <bool>
      # Interface. Example - Ethernet4, Port-Channel1, Vxlan1 etc.
      interface: <str>
```

### Describe alternatives you have considered

use `eos_cli: | `

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct
