### ISSUE TITLE
Bug(eos_designs): Regression - Short ESIs are not generated for MPLS network connected endpoints

### ISSUE THREAD

**Issue by ZoeyFahner-Arista** [aristanetworks/ansible-avd#5227]
### Issue Summary

In an MPLS fabric without VTEP overlays the `connected_endpoints` do not properly receive `short_esi` keys due to faulty logic within the `_get_short_esi()` utility function, which can be found here (devel branch):

https://github.com/aristanetworks/avd/blob/786f98bc024645bb8df4cca6add61716f33770d4/python-avd/pyavd/_eos_designs/structured_config/connected_endpoints/utils.py#L113

This is a regression from AVD 4.7.1 to AVD 4.8.0 and beyond, potentially from this commit:

https://github.com/aristanetworks/avd/commit/b4d5caf72fe381eed48ed85e36e59e6a6e2cb847#diff-ef96c464acb24f9b2cb71a2b9a3210b3ab4147120fee1085b218b691c2286112 

An ESI should meet the following requirements to be created:
- At least two switch ports are terminating the service
- An EVPN or VTEP overlay is configured

Since the logic in the function is checking for violations instead of success the appropriate logic would be similar to this:

```
if len(set(adapter["switches"])) < 2 or (not self.shared_utils.overlay_evpn and not self.shared_utils.overlay_vtep)
```

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

Create any MPLS fabric definition that does not have any `overlay_vteps` defined. Connected endpoints that define an ESI will not have structured_configuration for that ESI constructed.

**Example Connected Endpoint**
```yaml
endpoint_example:
  - name: "Example"
    adapters:
      - endpoint_ports: [ "Ethernet1", "Ethernet2" ]
        switch_ports: [ "Ethernet1", "Ethernet1" ]
        switches: [ "BETA-01", "BETA-02" ]
        port_channel:
          description: "Failed Subinterface ESI"
          mode: active
          subinterfaces:
            # INTERNET
            - number: 1001
              short_esi: 0000:0000:1001
```

This results in the following incorrect structured config which is missing the `evpn_ethernet_segment` key on the subinterface:

```yaml
port_channel_interfaces:
- name: Port-Channel1.1001
  vlan_id: 1001
  encapsulation_vlan:
    client:
      encapsulation: dot1q
      vlan: 1001
    network:
      encapsulation: client
```

The expected `structured_config` would read as follows:

```yaml
port_channel_interfaces:
- name: Port-Channel1.1001
  vlan_id: 1001
  encapsulation_vlan:
    client:
      encapsulation: dot1q
      vlan: 1001
    network:
      encapsulation: client
  evpn_ethernet_segment:
    identifier: 0000:0000:0000:0000:1016
    route_target: 00:00:00:00:10:16
```

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct
