### ISSUE TITLE
Bug(eos_designs) - ISIS-SR underlay protocol generates duplicate Node Indices

### ISSUE THREAD

**Issue by colinmacgiolla** [aristanetworks/ansible-avd#5232]
### Issue Summary

When setting the `underlay_routing_protocol` to `isis-sr` (default), the `node-segment ipv4 index` assigned to the Loopback0 seems to be just the `node_group` `id`. Since each node_group has its own id/index list, this means that we generate duplicate Node SIDs between the groups (this can easily be seen by changing the underlay_routing_protocol in the example). 

Tested with: AVD 5.2.3

### Which component(s) of AVD impacted

eos_designs

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Load the `isis-ldp-ipvpn` example.

Update the `FABRIC.yml` file as follows;

# Define underlay and overlay routing protocol to be used
underlay_routing_protocol: isis-sr
overlay_routing_protocol: ibgp


And run the build playbook.
```

### Relevant log output

```shell
p1.cfg:

interface Loopback0
   description ROUTER_ID
   no shutdown
   ip address 10.255.0.1/32
   node-segment ipv4 index 1
   isis enable CORE
   isis passive
!


pe1.cfg:
interface Loopback0
   description ROUTER_ID
   no shutdown
   ip address 10.255.1.1/32
   node-segment ipv4 index 1
   isis enable CORE
   isis passive
```

### Contributing Guide

- [x] I agree to follow this project's Code of Conduct

**Comment by colinmacgiolla** [comment]
I'm thinking a way to solve it would be to add something like a `node_sid_base: <int>` to the `switch_group` vars, and generate the Node SID with `node_sid_base + id`. 

Another thought is that we should also allow for the `node_sid` to be set on the node level though, in case someone needs to do something different.

**Comment by gmuloc** [comment]
@colinmacgiolla can you please indicate which AVD version you are using?

**Comment by ClausHolbechArista** [comment]
We already have `node_sid_base`.

```yaml
<node_type_keys.key>:

  # Define variables for all nodes of this type.
  defaults:

    # Node-SID base for isis-sr underlay variants. Combined with node id to generate ISIS-SR node-SID.
    node_sid_base: <int; default=0>
```

EDIT: It seems like the below stuff is not applicable to the node id for SR.

~IMO a better solution is the newer `isis_system_id_format: underlay_loopback` (default now) which will simplify this a lot by just using your loopback0 IP.~

**Comment by colinmacgiolla** [comment]
Tested this, works fine - is it worth doing an ISIS-SR example, and mix in TI-LFA, etc.?
```yaml
pe:
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: vEOS-lab
    # Pool of IPv4 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv4_pool: 10.255.1.0/27
    virtual_router_mac_address: 00:1c:73:00:dc:00
    mpls_route_reflectors: [ rr1, rr2 ]
    # ISIS NET system id prefix
    isis_system_id_prefix: '0000.0001'
    spanning_tree_mode: none
    node_sid_base: 100
```

```
interface Loopback0
   description ROUTER_ID
   no shutdown
   ip address 10.255.1.1/32
   node-segment ipv4 index 101
   isis enable CORE
   isis passive
```
