### ISSUE TITLE
Feat(eos_cli_config_gen): Support for 400G BIDI/400G-SR4.2 breakout into 4 x 100G BIDI/100G-SR1.2

### ISSUE THREAD

**Issue by hopaul** [aristanetworks/ansible-avd#5260]
### Enhancement summary

Arista 400G-BIDI has an additional application at speed 100g-2 to interoperate with the legacy QSFP-100G-SRBD modules. 

On EOS releases >= 4.31.0F:
```eos
switch(config)#interface ethernet 19/1,19/3,19/5,19/7 inactive expose
switch(config-if-Et19/1,19/3,19/5,19/7)#speed 100g-2
switch(config-if-Et19/1,19/3,19/5,19/7)#interface ethernet 19/1
switch(config-if-Et19/1)#**transceiver application override 100gbase-srbd**
```

On EOS releases <= 4.30.2F:
```eos
switch(config-if-Et19/1)#**transceiver application override 3**
```

Furthermore, the transceiver application override only support on the first lane of 400G port (et1/1, et2/1) 

In AVD we can leverage "uplink_switch_interface_speed" for breakout however, there is no way to support "transceiver application override" configuration. 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

In my Spine will breakout its 400G-BIDI into 4 x 100G bidi on the leaf groups. 

```yaml
spine:
  node_groups:
    - group: SPINES
      mlag: false
      nodes:
        - name: spine-1
          id: 1
          mgmt_ip: [10.192.71.51/24](http://10.192.71.51/24)
          structured_config:
            ethernet_interfaces:
              - name: Ethernet1/1
                description: "400G bidi breakout"
                speed: 400g-8
                eos_cli: transceiver application override 3
              - name: Ethernet2/1
                description: "400G bidi breakout"
                speed:400g-8
                eos_cli: transceiver application override 3
```

For Leaf groups
```yaml
l3leaf:
  node_groups:
    DC1_LEAF1:
      uplink_interface_speed: forced 100gfull
      uplink_switch_interface_speed: 100g-2
```

### Describe the solution you would like

There should be a new key, "application override",  under ethernet_interface structured_config 

### Describe alternatives you have considered

eos_cli

### Contributing Guide

- [x] I agree to follow this project Code of Conduct

**Comment by Spandanaarista** [comment]
We need to implement this for another customer as well.

**Comment by ClausHolbechArista** [comment]
So we need
1. `application_override: <str>` under `ethernet_interfaces[].transceiver` in `eos_cli_config_gen`
2. `uplink_interface_transceiver` and `uplink_switch_interface_transceiver` in `eos_designs` using `$ref` to the cli_gen schema. This way we can also set frequency etc.
   Today we use the `uplink_interface_speed` on the spine as well, unless `uplink_switch_interface_speed` is set. Should we do the same for this new `.._transceiver` key?

@Spandanaarista @hopaul

**Comment by Spandanaarista** [comment]
@ClausHolbechArista , I used the same approach, I had to set uplink_switch_interface_speed: "100g-2" and also uplink_interface_speed: 'forced 100gfull' for the leaf side!                                                                                                                                                      uplink_switch_interface_speed: "100g-2" - This one overrides and configured only on Spines (only needed on spines), like expected.

**Comment by ClausHolbechArista** [comment]
Could there be cases where you would want to set something transceiver related only on the leaf and not on the spine? If so we would need to implement it slightly different than the `uplink_interface_speed` behavior.

For reference, transceiver data model
```yaml
        transceiver:

          # Transceiver Laser Frequency in GHz (min 190000, max 200000).
          frequency: <str>

          # Unit of Transceiver Laser Frequency.
          frequency_unit: <str; "ghz">
          media:

            # Transceiver type.
            override: <str>

          application_override: <str>   # <---- not there Today
```
