### ISSUE TITLE
eos_cli_config_gen: `ip_name_server_groups` schema doesn't support multiple ip domain-list

### ISSUE THREAD

**Issue by carl-baillargeon** [aristanetworks/ansible-avd#5277]
Schema:
```yaml
  ip_name_server_groups:
    type: list
    primary_key: name
    items:
      type: dict
      keys:
        name:
          type: str
        name_servers:
          type: list
          primary_key: ip_address
          allow_duplicate_primary_key: true
          items:
            type: dict
            keys:
              ip_address:
                type: str
                description: IPv4 or IPv6 address for DNS server.
              vrf:
                description: VRF Name.
                type: str
                required: true
                convert_types:
                - int
              priority:
                description: Priority value (lower is first).
                type: int
                convert_types:
                - str
                min: 0
                max: 15
        dns_domain:
          type: str
        ip_domain_list:
          type: str  # <-- list?
          description: Set domain names to complete unqualified host names.
```
`ip_domain_list` is a str but should probably be a list?

On EOS supports multiple ip domain-list entries:
```bash
ip name-server group DNS_Servers
   name-server vrf MGMT 8.8.8.8
   name-server vrf MGMT 10.22.30.1
   dns domain labsphere.cc
   ip domain-list google.com
   ip domain-list nhl.com
```

Also, maybe I'm blind but it looks like the documentation is missing for this data model: https://avd.arista.com/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/input-variables.html
