### ISSUE TITLE
Include platform (hardware-lag) commands in eos_l3ls_evpn

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#530]
**Issue Type**

- Template enhancement
- Role enhancement
- Documentatin enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Let's add this, as this should be mandatory in any design with R series.

```
platform:
  sand:
    lag:
      hardware_only: true
```

Would make sense to have it under

```
platform_settings:
  - platforms: [ 7800R3, 7500R3, 7500R, 7280R3, 7280R2, 7280R ]
    tcam_profile: vxlan-routing
    **lag_hardware_only: true**
    reload_delay:
      mlag: 780
      non_mlag: 1020
```

**Describe the solution you'd like**

Else have to get this with custom stuff, which I think it's important to have there as a default in any design.

**Describe alternatives you've considered**

**Additional context**
