### ISSUE TITLE
enable_password.disabled being set to true by default and difficult to override

### ISSUE THREAD

**Issue by jcheung808** [aristanetworks/ansible-avd#5313]
### Environment
- AVD Version: 5.3.0
- Ansible Version: 2.17.10
- Python Version: 3.10.2
- Environment: Local config generation only (PyCharm)

### Description
The `enable_password.disabled` setting appears to be getting set to `true` by a system default, making it difficult to override. This occurs during the configuration generation phase using AVD, even before any deployment to actual devices.

### Current Behavior
Even when explicitly setting:
```yaml
enable_password:
  disabled: false
  hash: "$1$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"


### The final data model shows:

{"enable_password": {"disabled": false, "hash": "$1$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}, "enable_password": {"disabled": true}}

### indicating that somewhere in the system, the setting is being overridden.

### Expected Behavior
User-defined `enable_password.disabled` settings should take precedence over system defaults.
### Attempted Solutions
Have tried:
1. Setting at root level
2. Using structured_config override
3. Using node_type_keys override
4. Using custom_structured_configuration_enable


### Which components of AVD are impacted

eos_cli_config_gen

### AVD version

5.3.0

### Ansible version

2.17.10

### Python version

3.10.2

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell

```

### Relevant log output

```shell
{"enable_password": {"disabled": false, "hash": "$1$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"}, "enable_password": {"disabled": true}}
```

### Contributing Guide

- [x] I agree to follow this project Code of Conduct

**Comment by ClausHolbechArista** [comment]
The data model you are using is for `eos_cli_config_gen` which gets overwritten by the output of `eos_designs`. Please read this article to get a better picture of how it fits together: https://avd.arista.com/devel/ansible_collections/arista/avd/roles/eos_designs/docs/how-to/custom-structured-configuration.html

**Comment by ClausHolbechArista** [comment]
Example from another issues concerning the same:

```yaml
custom_structured_configuration_enable_password:
  key: XXXXX
  disabled: false
  hash_algorithm: sha512
```

**Comment by networkdevg** [comment]
Hello,

I had the same issue after upgrading to 5.4.0

*** avd 4.10.2 **
Input :
```
enable_password:
  hash_algorithm: sha512 
  key: xxx
```

eos_designs output
`(nothing)`

eos_cli_config_gen output : ok

*** avd 5.4.0 **
Input :
```
enable_password:
  disabled: false
  hash_algorithm: sha512 
  key: xxx
```

eos_designs output
```
enable_password:
  disabled: true
```

eos_cli_config_gen output : not ok

The porting guide says generate_default_config has been disabled but can be replaced with this :
```
enable_password:
  disabled: true
```

However as explained above, eos_designs does not use enable_password configuration. So it should not generate any enable_password config right ?

To avoid confusion, eos_designs should either read enable_password configuration or generate a default only if nothing is set, but not always force "disabled: true" which sounds like a bug.

In the meantime, the workaround with "custom_structured_configuration_enable_password:" works well.
