### ISSUE TITLE
allow route-map on redistribute static/connected

### ISSUE THREAD

**Issue by PieterL75** [aristanetworks/ansible-avd#5329]
### Enhancement summary

The current design/bgp only allowes us to enable/disable route redistribution in BGP.
```
        # Enable or disable the redistribution of all static routes to BGP in the VRF.
        redistribute_static: <bool>

        # Enable or disable the redistribution of all connected routes to BGP in the VRF. Note this is not applicable to VRF `default`.
        redistribute_connected: <bool; default=True>
```

I would like to be able to add route-maps to the bgp redistribute design knop

### Which component of AVD is impacted

eos_designs

### Use case example

I don't want all static routes to be redistributed
I want to add extra metrics, communities, .. to certain routes

### Describe the solution you would like

Similar is in the OSPF section :

```
          redistribute_static:
            enabled: <bool; default=True>

            # Route-map name.
            route_map: <str>
          redistribute_connected:
            enabled: <bool; default=False>

            # Route-map name.
            route_map: <str>
```

### Describe alternatives you have considered

I use the 'structured_config'option to enable this:
```
        bgp:
          structured_config:
            redistribute:
              static:
                enabled: true
                route_map: INFRA-BE-EBGP4-OUT-TRANSIT
              connected:
                enabled: true
                route_map: INFRA-BE-EBGP4-OUT-TRANSIT
```

### Additional context

An other option is a knob that creates 'network' statements for all connected networks in the VRF, in stead of redistributing them. This looks much nicer in BGP, as the route as a proper origin

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
