### ISSUE TITLE
Storm-control settings in l3ls_evpn

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#534]
## Issue Type

- Bug Report
- Documentation Issue Report
- EOS Configuration error

## Summary

This got solved for eos_cli_config_gen where the unit is optional, but in l3ls it's mandatory and some platforms don't support it.

```
    storm_control:
      all:
        level: < Configure maximum storm-control level >
        unit: < percent* | pps (optional and is hardware dependant - default is percent)>
```

We would need to factor this in for eos_l3ls_evpn and make it optional

```
{%                 if port_profiles[adapter.profile].storm_control is defined and port_profiles[adapter.profile].storm_control is not none %}
    storm_control:
{%                     for section in port_profiles[adapter.profile].storm_control %}
      {{ section }}:
        level: {{ port_profiles[adapter.profile].storm_control[section].level }}
        unit: {{ port_profiles[adapter.profile].storm_control[section].unit }}
{%                     endfor %}
{%                 endif %}
```

## Role or Module Name
eos_l3ls_evpn

### OS / Environment

__EOS Version__

__Cloudvision version__ (optional)

__OS running Ansible__

## Steps to reproduce

```yaml

```

### Expected results

```shell
$
```

### Actual results

```shell

```
