### ISSUE TITLE
Enhance `additional_route_targets` inputs `network_services` data model

### ISSUE THREAD

**Issue by rrajpuro** [aristanetworks/ansible-avd#5347]
### Enhancement summary

Enhance the `network_services_keys.vrfs.additional_route_targets` schema to support all attributes from the `structured_config.route_targets` (e.g., `route_map`, `rcf`, and `vrf_route_filter_rcf`). Also, allow `route_target` to accept a list of strings for parity with `structured_config`. This avoids the need to duplicate import/export route target definitions across both structured configs and network services, reducing config overhead and potential mismatches.

### Which component of AVD is impacted

eos_designs

### Use case example

See the example under **alternatives you have considered** below — the use case is apparent from the redundant configuration pattern.

### Describe the solution you would like

Proposed schema for the enhanced `additional_route_targets`:
```YAML
<network_services_keys.name>:
  - name: <str; required; unique>
    vrfs:
      - name: <str; required; unique>
        # Configuration of extra route-targets for this VRF. Useful for route-leaking or gateway between address families.
        additional_route_targets:
          - type: <str; "import" | "export">
            address_family: <str; required; one of "evpn", "vpn-ipv4", "vpn-ipv6", etc.>
            # One or more route-targets to apply. Accepts either a string or a list of strings.
            route_targets:
              - <str>
            # Optional route-map name. Only applicable for address_family "evpn", "vpn-ipv4", or "vpn-ipv6".
            route_map: <str>
            # Optional RCF function to generate route-targets. Format: FunctionName(args). Only for "evpn", "vpn-ipv4", or "vpn-ipv6".
            rcf: <str>
            # Optional RCF function to filter imported VPN routes. Only valid for "import" type with "vpn-ipv4" or "vpn-ipv6". Requires `rcf` to be set.
            vpn_route_filter_rcf: <str>
            # Optional RCF function to filter exported VRF routes. Only valid for "export" type with "vpn-ipv4" or "vpn-ipv6". Requires `rcf` to be set.
            vrf_route_filter_rcf: <str>
            # Nodes is required to restrict configuration to specific nodes in the network.
            nodes:
              - <str>
```

### Describe alternatives you have considered

```YAML
<network_services_keys.name>:
  - name: TENANT
    vrfs:
      - name: VRFA
        additional_route_targets:
          - type: export
            address_family: vpn-ipv4
            route_target: "64999:1112"

        bgp:
          structured_config:
            route_targets:
              export:
                - address_family: vpn-ipv4
                  route_map: "EXPORT-TO-VRFA_B-RT"
```

### Additional context

Additionally, having to manually specify a list of `nodes` for each `additional_route_target` is **not scalable**. A more flexible mechanism—such as referencing **Ansible groups (including constructed groups)** or filtering by **tags/labels**—would significantly reduce overhead in large deployments.

_Some sections of this issue may have been AI-assisted to ensure clarity and consistency._

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
