### ISSUE TITLE
eos_designs: Conditional configuration of Access List, Prefix List, Route Maps based on them being used on the device.

### ISSUE THREAD

**Issue by theotherguy2175** [aristanetworks/ansible-avd#5351]
Redefined scope:
- Create "catalogues" of access-lists, prefix-lists, route-maps, which can be referenced under bgp neighbors, route-maps, interfaces, redistribution etc.
- The catalog item will only be configured on devices where some other config is referring to it.

----
Original content:

### Enhancement summary

Instead of defining ACLs in several places/yaml files, it would be nice to be able to have a similar feature to SVIs Tagging. Where we can define all ACLs and Prefix Lists in a single file like Network Services, and then add tags that can then be applied just like SVIs

### Which component of AVD is impacted

eos_designs

### Use case example

Instead of defining ACLs in several places/yaml files, it would be nice to be able to have a similar feature to SVIs Tagging. Where we can define all ACLs and Prefix Lists in a single file like Network Services, and then add tags that can then be applied just like SVIs

### Describe the solution you would like

```
#Network Services.yml
prefix_lists:
- name: DEFAULT
  filter:
    tags: ["Borders"]
  sequence_numbers:
  - sequence: 5
    action: permit 0.0.0.0/0

#DC1.yml
- group: BLDC_BORDER_GROUP_1 
      filter:
        tags: ["Borders"]
```

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
