### ISSUE TITLE
Enhancement for PTP

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#538]
**Issue Type**

- Template enhancement
- Role enhancement
- Documentatin enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Add following knobs for ptp

```
ptp:
  announce:
    interval: < integer>
  sync-message:
    interval: <-integer>
  delay-req: <-integer>
  role: < master | slave >
```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by morinpa** [comment]
Could I ask for the addition of the following knob for PTP:  vlan 

like this: 
```
ptp:
  announce:
    interval: < integer>
  sync-message:
    interval: <-integer>
  delay-req: <-integer>
  role: < master | slave >
  vlan: <vlan_number>
```
