### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for vxlan qos dscp ecn rewrite bridged enabled

### ISSUE THREAD

**Issue by tosha25** [aristanetworks/ansible-avd#5393]
### Enhancement summary

Hello AVD team, please can you add YAML data structure option under eos_cli_config_gen role for the vxlan interface for the following command. This is called "Bridging + Encap (Uniform mode)" on the Jericho2 platforms to maintain the same QoS DSCP value for the bridged traffic. 

```
interface Vxlan1
   vxlan qos dscp ecn rewrite bridged enabled
```
This option should most likely be under this data structure:
```
vxlan_interface:
  vxlan1:
    description: <str>
    vxlan:
      qos:
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

This option should be enabled under the eos_cli_config_gen role, the following data structure:

```
vxlan_interface:
  vxlan1:
    description: <str>
    vxlan:
      qos:
```

### Describe the solution you would like

Please, enable DSCP rewrite bridged option under vxlan1 interface.

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
