### ISSUE TITLE
arista.cvp integration - Support provision and deletion in role

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#54]
Role `eos-config-deploy-cvp` is only supporting Fabric creation. In some use cases, it might be interesting to reset fabric from CVP and move EOS devices to ZTP mode.

Role should allow an option to choose whether we want to build or cleanup CVP.

```yaml
- name: Configuration deployment with CVP
  hosts: CVP
  connection: local
  gather_facts: no
  tasks:
    - name: run CVP provisioning
      import_role:
         name: eos-config-deploy-cvp
      vars:
        state: {{present|absent}}  # present is default value
```

**Comment by titom73** [comment]
All variables defined in this role have a default value:

```yaml
# Filter to apply on cv_device to target only devices involved in Fabric
device_filter: 'all'

# Define inventory group to consider root of container topology
container_root: '{{ fabric_name }}'

# Configure prefix to append to configlets on CloudVision
configlets_prefix: 'AVD-{{ fabric_name }}-'

# State management to know if module should create/update or delete fabric
state: 'present'
```
