### ISSUE TITLE
default_igmp_snooping in l3ls_evpn

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#540]
## Issue Type

- Bug Report
- Documentation Issue Report
- EOS Configuration error

## Summary

```
# Disable IGMP snooping at fabric level.
# If set, it overrides per vlan settings
default_igmp_snooping: < boolean | default -> true >
```

This one doesn't seem to be doing anything if set to false.

### OS / Environment

__EOS Version__

__Cloudvision version__ (optional)

__OS running Ansible__

## Steps to reproduce

```yaml

```

### Expected results

```shell
$
```

### Actual results

```shell

```

**Comment by ksator** [comment]
working on it.  
Looks like in l3ls role it is 
- `default_igmp_snooping_enabled` (at the root level) 
- `igmp_snooping_enabled` (under l3leaf/default or l3leaf/nodes/xxx) (templates/evpn-fabric-l3leaf-yml.j2)
- `igmp_snooping_enabled` (under l2leaf/default or l2leaf/nodes/xxx) (templates/evpn-fabric-l2leaf-yml.j2)
- `igmp_snooping_enabled` (under tenants/vrfs/svis) (templates/tenant_evpn_vxlan/leaf-tenant-igmp-snooping.j2)
- `igmp_snooping_enabled` (under tenants/l2vlans) (templates/tenant_evpn_vxlan/leaf-tenant-igmp-snooping.j2)

```
default_igmp_snooping_enabled: true
l3leaf:
  defaults:
    igmp_snooping_enabled: false
    # virtual router mac for VNIs assigned to Leaf switches
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: vEOS-LAB
    bgp_as:
    # Parent spine switches (list)
    spines: [DC1-SPINE1, DC1-SPINE2]
    # Uplink to spine interfaces (list)
    uplink_to_spine_interfaces: [Ethernet1, Ethernet2]
    # MLAG interfaces (list)
    mlag_interfaces: [Ethernet7, Ethernet8]
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  # The node groups are group of one or multiple nodes
  # All variables defined under `node_groups` dictionary can be defined under the `defaults` key. They will be inherited.
  # The variables defined under a specific `node_group` will take precedence over `defaults`.
  node_groups:
    DC1_LEAF1:
      # Enable/Disable MLAG when two nodes are defined in node group. Default is true.
      mlag: true
      igmp_snooping_enabled: true
      bgp_as: 65101
      filter:
        tenants: [ Tenant_A, Tenant_D ]
        tags: [ opzone, web, app, vm ]
      nodes:
        DC1-LEAF1A:
          # Unique identifier assigned to each device.
          id: 1
          # Node management IP address
          mgmt_ip: 10.73.1.105/24
          # Spine interfaces (list), interface located on Spine
          spine_interfaces: [Ethernet1, Ethernet1]
        DC1-LEAF1B:
          id: 2
          mgmt_ip: 10.73.1.106/24
          spine_interfaces: [Ethernet2, Ethernet2]
``` 

I will fix the doc and the code
