### ISSUE TITLE
RCF Support for VrfLeak Agent

### ISSUE THREAD

**Issue by davidgwatkins** [aristanetworks/ansible-avd#5407]
### Enhancement summary

Please extend the existing `router_general` model to permit the use of RCF subscriptions as alternatives to route-maps.  See the associated [EOS 4.33.2F TOI](https://www.arista.com/en/support/toi/eos-4-33-2f/21278-routing-control-functions-vrfleak-agent-support)

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Network that wishes to use AVD for automation and also avoid route-maps by exclusively utilizing RCFs.

### Describe the solution you would like

These options should be configured under the `router_general` key in `eos_cli_config_gen`.

**Current:**
```yaml
router_general:
  vrfs:
      # Destination-VRF.
    - name: <str; required; unique>
      leak_routes:
        - source_vrf: <str>

          # Route-Map Policy.
          subscribe_policy: <str>
````

**Proposed:**
```yaml
router_general:
  vrfs:
      # Destination-VRF.
    - name: <str; required; unique>
      leak_routes:
        - source_vrf: <str>

          # Route-Map Policy.
          subscribe_policy: <str>

          # RCF Policy.
          subscribe_rcf: <str>
````

### Describe alternatives you have considered

Alternative deployment requires a custom Jinja2 template and additional non-overlapping data models.

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
