### ISSUE TITLE
Fix(eos_designs): Enable OSPF authentication on MLAG peer links

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#5416]
### Issue Summary

When enabling OSPF authentication in the underlay, we do not set OSPF authentication in the vlan4093 (by default), used for redundancy between MLAG peers.

For example, the following snippet:
```
underlay_routing_protocol: "ospf"
underlay_ospf_graceful_restart: true
underlay_ospf_authentication:
  enabled: true
  message_digest_keys:
    - id: 1
      hash_algorithm: "sha512"
      key: "arista"
```
In L3LS, it will only set OSPF authentication in the leaf-spine links. While in L2LS, the spines also will not have OSPF authentication enabled between them. OSPF is enabled in vlan 4093 without authentication though.

OSPF authentication should be enabled in all OSPF peerings established in vlan4093.

### Which components of AVD are impacted

eos_designs

### AVD version

5.4.0

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Steps to reproduce

```shell
Configure the following and check OSPF configuration in vlan4093:

underlay_routing_protocol: "ospf"
underlay_ospf_graceful_restart: true
underlay_ospf_authentication:
  enabled: true
  message_digest_keys:
    - id: 1
      hash_algorithm: "sha512"
      key: "arista"
```

### Relevant log output

```shell

```

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
