### ISSUE TITLE
Feat(eos_designs): Support for route-maps using OSPF to BGP redistribution

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#5418]
### Enhancement summary

When we enable OSPF in tenant configuration via eos_designs:
```
    vrfs:
      - name: "RED"
        vrf_vni: 1001
        vtep_diagnostic:
          loopback: 100
          loopback_ip_range: 10.100.100.0/24
        ospf:
          enabled: true
          process_id: 1
          redistribute_bgp:
            enabled: true
            route_map: REDISTRIBUTE-BGP-TO-OSPF
	redistribute_ospf: true
```

We allow the user to set a route-map from BGP to OSPF that generates:
```
router ospf 2 vrf BLUE
   router-id 192.168.100.5
   passive-interface default
   no passive-interface Vlan60
   redistribute bgp route-map REDISTRIBUTE-BGP-TO-OSPF
   redistribute connected
   max-lsa 12000
   graceful-restart
```
However for OSPF to BGP (using the knob redistribute_ospf) we just generate the following configuration without a route-map applied:
```
 vrf RED
    rd 192.168.100.5:1001
    route-target import evpn 1001:1001
    route-target export evpn 1001:1001
    router-id 192.168.100.5
    neighbor 172.16.1.9 peer group MLAG-IPv4-VRFS-PEER
    neighbor 172.16.1.9 description DC1-SL2_Vlan4000
    redistribute connected route-map RM-CONN-2-BGP-VRFS
    redistribute ospf
```
We should be able to specify a route-map also from OSPF to BGP, and also to be able to match the types of routes to redistribute:
```
DC1-SL1(config-router-bgp-vrf-BLUE)#redistribute ospf match ?
  external       OSPF routes learned from external sources
  internal       OSPF routes learned from internal sources
  nssa-external  OSPF routes learned from external NSSA sources
```
For example, extend the current redistribute_ospf knob to something along these lines:
```
redistribute_ospf: 
  enabled: <boolean>
  route_map: <route-map-name>
  match: "external/internal/nssa-external"
```

### Which component of AVD is impacted

eos_designs

### Use case example

L3LS EVPN fabric, peering with OSPF routers on the Border Leaves.

### Describe the solution you would like

Use eos_designs to configure mutual OSPF to BGP redistribution.

### Describe alternatives you have considered

cli config gen configuration to overwrite the bgp configuration:
```
custom_structured_configuration_router_bgp:
  vrfs:
    - name: RED
      redistribute:
        ospf:
          enabled: true
          match_external:
            enabled: true
            route_map: RM-REDISTRIBUTE-OSPF-TO-BGP
```

### Contributing Guide

- [x] I agree to follow this project Code of Conduct

**Comment by gmuloc** [comment]
This model

```
redistribute_ospf: 
  enabled: <boolean>
  route_map: <route-map-name>
  match: "external/internal/nssa-external"
```

would not work as it would not allow to express `match internal / external` with different route-maps. We need to inspire ourselves to what is being done in https://github.com/aristanetworks/avd/pull/7144 given that the `match internal` presence is equivalent to no match (see below in cEOS 4.36):

```
veos-4-36-0-1F(config-s-s2-router-bgp-vrf-BLAH)#show session-config dif
--- system:/running-config
+++ session:/s2-session-config
+router bgp 666
+   vrf BLAH
+      redistribute ospf route-map TOTO
+      redistribute ospf match external route-map BLOG
+      redistribute ospf match nssa-external 2 include leaked route-map BLAH
veos-4-36-0-1F(config-s-s2-router-bgp-vrf-BLAH)#redistribute ospf match internal route-map TOTO
veos-4-36-0-1F(config-s-s2-router-bgp-vrf-BLAH)#show session-config dif
--- system:/running-config
+++ session:/s2-session-config
+router bgp 666
+   vrf BLAH
+      redistribute ospf match internal route-map TOTO
+      redistribute ospf match external route-map BLOG
+      redistribute ospf match nssa-external 2 include leaked route-map BLAH
veos-4-36-0-1F(config-s-s2-router-bgp-vrf-BLAH)#redistribute ospf  route-map OTHER-RM
veos-4-36-0-1F(config-s-s2-router-bgp-vrf-BLAH)#show session-config dif
--- system:/running-config
+++ session:/s2-session-config
+router bgp 666
+   vrf BLAH
+      redistribute ospf route-map OTHER-RM
+      redistribute ospf match external route-map BLOG
+      redistribute ospf match nssa-external 2 include leaked route-map BLAH
```
