### ISSUE TITLE
AVD Build eos_designs not detecting spine and l3leaf interfaces for building underlay/overlay

### ISSUE THREAD

**Issue by Jtown0011** [aristanetworks/ansible-avd#5429]
Hello Arista Team,

I've been working on a project that utilizes AVD with a single L3LS fabric configuration using cEOS version 4.33.3F containers built using [ContainerLabs](https://containerlab.dev/).

ContainerLab 0.68.0

Python 3.10.12

Ansible Galaxy Collections

- ansible.netcommon = 8.0.0
- ansible.utils = 6.0.0
- arista.avd = 5.4.0
- arista.cvp = 3.12.0
- arista.eos = 11.0.0

Python Packages

- ansible = 10.7.0
- ansible-core = 2.17.11
- ansible-lint = 25.4.0
- anta = 1.4.0
- cvprac = 1.4.1
- pyavd[ansible-collection] = 5.4.0

I'm running into an issue where when performing the build.yml none of the interfaces between the spines and l3leaves are configured/detected. It's as if these interfaces do not exist.

To rule out an issue with link virtualization/connectivity between the containers when defining a topology file with Containerlab, I manually configured layer 3 on the links between my spines and l3leaves and was able to successfully ping across them with no issue. I also saw LLDP neighbor adjacencies formed between the spines and the l3leaves.

So I started digging and looked at the build process. I noticed that during the build process under eos_designs when building the structured configuration I don't see 'uplink_switches' get defined so I'm not sure if that's the issue or not.

I have a similar folder structure as outlined in [https://github.com/aristanetworks/avd/discussions/4706](https://github.com/aristanetworks/avd/discussions/4706)

**Comment by ClausHolbechArista** [comment]
Can you share a snip of YAML for your leaf config? Starting from the `l3leaf:` and show at least two `nodes`. Remember to remove/replace any sensitive information first.

**Comment by Jtown0011** [comment]
Hi @ClausHolbechArista,

Below is the contents for l3_leaves.yml configuration file. I've noticed that all MLAG connections get configured correctly between the l3 leaves but none of the uplinks to the spines are configured. After the build I check the documentation for the spines and l3 leaves but none of those uplinks are being configured.


l3_leaves.yml
```yaml
---
type: l3leaf

l3leaf:
  defaults:
    platform: cEOS
    bgp_as: 66101-66199
    loopback_ipv4_pool: 192.168.2.0/64
    vtep_loopback_ipv4_pool: 192.168.3.0/24
    uplink_switches: ['dc1-spine1', 'dc1-spine2']
    uplink_ipv4_pool: 192.168.4.0/24
    mlag: true
    mlag_peer_ipv4_pool: 192.168.5.0/24
    mlag_peer_l3_ipv4_pool: 192.168.6.0/24
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp

  node_groups:
    - group: DC1_L3_LEAF1
      bgp_as: 66101
      mlag_interfaces: [Ethernet1/27, Ethernet1/28]
      nodes:
        - name: dc1-leaf1a
          id: 1
          mgmt_ip: 172.16.1.101/24
          uplink_switch_interfaces: [Ethernet1/1, Ethernet1/1]
        - name: dc1-leaf1b
          id: 2
          mgmt_ip: 172.16.1.102/24
          uplink_switch_interfaces: [Ethernet1/2, Ethernet1/2]
    - group: DC1_L3_LEAF2
      bgp_as: 66102
      mlag_interfaces: [Ethernet1/27, Ethernet1/28]
      nodes:
        - name: dc1-leaf2a
          id: 3
          mgmt_ip: 172.16.1.103/24
          uplink_switch_interfaces: [Ethernet1/3, Ethernet1/3]
        - name: dc1-leaf2b
          id: 4
          mgmt_ip: 172.16.1.104/24
          uplink_switch_interfaces: [Ethernet1/4, Ethernet1/4]

```
