### ISSUE TITLE
L2 leaf uplinks with LAG without MLAG

### ISSUE THREAD

**Issue by ksator** [aristanetworks/ansible-avd#543]
## Issue Type

- Bug Report

## Summary

Currently L2 leaves are always deployed by 2 with mlag. 
 
## Role or Module Name

role eos_l3ls_evpn 

root cause is https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/evpn-fabric-l2leaf-yml.j2#L261  

this template always uses mlag https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/l3leaf_l2leafs_uplinks/l2leaf-port-channel-uplinks.j2  

## Steps to reproduce
```
l2leaf:
  defaults:
    platform: vEOS-LAB
    # Parent L3 switches (list)
    parent_l3leafs: [ DC1-LEAF1A, DC1-LEAF1B ]
    # Uplink interfaces (list), interface located on L2 Leaf,
    uplink_interfaces: [ Ethernet1, Ethernet2 ]
    mlag: false
    # MLAG interfaces (list)
    # mlag_interfaces: [ Ethernet7, Ethernet8 ]
  node_groups:
    DC1_L2LEAF1:
      parent_l3leafs: [ DC1-LEAF1A, DC1-LEAF1B ]
      nodes:
        DC1-L2LEAF1A:
          id: 5
          mgmt_ip: 10.73.1.117/24
          l3leaf_interfaces: [ Ethernet3, Ethernet3 ]
    DC1_L2LEAF2:
      parent_l3leafs: [ DC1-LEAF1A, DC1-LEAF1B ]
      filter:
        tenants: [ Tenant_A ]
        tags: [ app, web ]
      nodes:
        DC1-L2LEAF2A:
          id: 7
          mgmt_ip: 10.73.1.118/24
          l3leaf_interfaces: [ Ethernet4, Ethernet4 ]
```

### Expected results

```
interface Port-Channel1
   description DC1-LEAF1A_Po3
   switchport trunk allowed vlan 110-112,120-121,140-141,150,310-311,350,400-402
   switchport mode trunk
```

### Actual results

```
interface Port-Channel1
   description DC1-LEAF1A_Po3
   switchport trunk allowed vlan 110-112,120-121,140-141,150,310-311,350,400-402
   switchport mode trunk
   mlag 1
!
```
