### ISSUE TITLE
Align OSPF underlay authentication and OSPF network services authentication

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#5441]
### Enhancement summary

When configuring OSPF underlay authentication, the key must be a plaintext password:

https://avd.arista.com/5.4/ansible_collections/arista/avd/roles/eos_designs/docs/input-variables.html#ospf-settings
```
  # Key password.
      # Only plaintext passwords are supported here as `eos_designs` will encrypt the password for each individual underlay interface.
      # To protect the password at rest it is strongly recommended to make use of Ansible Vault or similar.
```
While when configuring OSPF authentication in tenants, the key is a type 7 encrypted key:

https://avd.arista.com/5.4/ansible_collections/arista/avd/roles/eos_designs/docs/input-variables.html#network-services-vrf-ospf-configuration

```
                  message_digest_keys:
                    - id: <int>
                      hash_algorithm: <str; "md5" | "sha1" | "sha256" | "sha384" | "sha512"; default="sha512">

                      # Type 7 encrypted key.
                      key: <str>
```

This results in OSPF passwords in the vault file to be different key types, so we would like to have a consistent method for both underlay/overlay OSPF passwords. Using Type7 for also the OSPF underlay would keep things consistent (note also BGP settings use type 7 passwords).

### Which component of AVD is impacted

eos_designs

### Use case example

OSPF underlay configurations for L3LS or L2LS fabrics, with OSPF external peerings will have different OSPF password types.

### Describe the solution you would like

Use OSPF passwords type 7 in OSPF settings as well.

### Describe alternatives you have considered

Different password types at the moment.

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
