### ISSUE TITLE
Add MLAG speed option for default_interfaces

### ISSUE THREAD

**Issue by ksantos-arista** [aristanetworks/ansible-avd#5445]
### Enhancement summary

When using the default_interfaces: model, it makes sense to also be able to define the mlag interface speed.

### Which component of AVD is impacted

eos_designs

### Use case example

please detail your use case

### Describe the solution you would like

```
default_interfaces:
  - types: [ l3leaf ]
    platforms: [ 720XP-48 ]
    mlag_interfaces: [ Ethernet51/1, Ethernet52/1 ]
    mlag_interface_speed:: forced 100G
```

### Describe alternatives you have considered

Manually configure the interface speed under the node type.

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
