### ISSUE TITLE
Feat(eos_cli_config_gen): Add support for E-Tree leaf config under VLAN

### ISSUE THREAD

**Issue by colinmacgiolla** [aristanetworks/ansible-avd#5448]
### Enhancement summary

Add support for the E-Tree leaf configuration for both VXLAN and MPLS: [https://www.arista.com/en/support/toi/eos-4-24-0f/14481-evpn-e-tree-for-mpls](https://www.arista.com/en/support/toi/eos-4-24-0f/14481-evpn-e-tree-for-mpls)

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

The CLI config is as follows:
```
switch#config
 switch(config)#vlan 1000
switch(config-vlan-1000)#e-tree role leaf
switch(config-vlan-etree-1000)#remote leaf host drop
...
vlan 1000
   e-tree role leaf
      remote leaf host drop
```

### Describe the solution you would like

This would extend the existing `vlans` schema. I'd suggest the following additions:
```yaml
vlans:
  - id: <int; required; unique>
    etree:
       # All VLANs by default have the E-Tree root role
       leaf_role: <bool; default: False>
       # enables remote leaf hosts to instead be installed as explicit drop routes in the local FDB
       remote_leaf_host_drop: <bool; default: false>
```

### Describe alternatives you have considered

I don't see any real benefits to going for a deeper structure, closer to the CLI, but I'm open either way

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
