### ISSUE TITLE
Add support for interface encapsulation dot1q for L3 sub-interface

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#546]
**Issue Type**

- Template enhancement
- Role enhancement

**Is your feature request related to a problem? Please describe.**

When we need to configure a set of L3 sub-interfaces, it is required to configure vlan tag using following EOS cli to tag traffic with a specific vlan

```eos
localhost(config-if-Et1.101)#show active
interface Ethernet1.101
   encapsulation dot1q vlan 101
   ip address 10.1.1.2/24
```

**Describe the solution you'd like**

Implement a new entry in `eos_cli_config_gen` data model for both Ethernet interfaces and Port-Channel like this:

```yaml
ethernet_interfaces:
  ethernet1:
    type: routed
  ethernet1.101:
    type: l3dot1q
    encapsulation:
      dot1q:
        vlan: 101
```

**Describe alternatives you've considered**

Another solution might be to extend `mode` to add a new key like `dot1q-encap` and use the vlans field to capture vlan ID but seems to be less readable and deviate from CLI implementation reported in YAML structure.

**Additional context**

Required for a deployment
