### ISSUE TITLE
Support for eapi via eos_designs

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#5469]
### Enhancement summary

We would like to simplify the user inputs that today require the user to set the VRF, using eos_designs to set the eAPI configuration. This would be the template that we currently use:

```
custom_structured_configuration_management_api_http:
  enable_http: false
  enable_https: true
  enable_vrfs:
    - name: [mgmt.vrf]
      access_group: EAPI-ACL
```

Based on the default_mgmt_method (oob or inband) we would like to automatically derive the VRF from other AVD vars:
```
[mgmt.vrf]: Default OOB: “mgmt_interface_vrf” / Default Inband VRF: “inband_mgmt_vrf”
```

The data model would be something like:
```
management_api_settings:
  enable_http: <bool>
  enable_https: <bool>
  access_group: <str>
```

Note: We are assuming here that we just listen in the default_mgmt_method VRF, although that might not be always the case (eapi supports multiple vrfs simultaneously).

### Which component of AVD is impacted

eos_designs

### Use case example

please detail your use case

### Describe the solution you would like

Reduce inputs for user during configuring management settings.

### Contributing Guide

- [x] I agree to follow this project Code of Conduct

**Comment by gmuloc** [comment]
PR in 5.x: keep behavior as today unless you give the VRF keys which then takes precedence.
```
management_eapi:
  # Enable/Disable api http-commands.
  enabled: <bool; default=true>
  enable_http: <bool>
  enable_https: <bool; default=true>
  default_services: <bool>
  vrfs: # should be implemented like snmp_settings after #5531 has merged
    - name: <str> # supports `use_default_mgmt_method_vrf` ...
      enabled: <bool; required>
      ipv4_acl: <str>
      ipv6_acl: <str>
```

Remember to update description for `default_mgmt_method`: https://avd.arista.com/5.4/ansible_collections/arista/avd/roles/eos_designs/docs/input-variables.html#management-interface-settings

6.0 behavior (in another PR, could be implemented behind an AVD toggle):

* do not enable eapi by default (`enabled: <bool; default=false>`)
* default value of VRFs will be
```
vrfs:
  - name: use_default_mgmt_method_vrf
    enabled: true
```
