### ISSUE TITLE
Configure SSH settings via eos_designs

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#5470]
### Enhancement summary

We would like to simplify the user inputs that today require the user to set the VRF, using eos_designs to set the SSH configuration. This would be the template that we currently use:

```
custom_structured_configuration_management_ssh:
  access_groups:
    - name: SSH-ACL
      vrf: [mgmt.vrf]
  idle_timeout: 60
  enable: false
  vrfs:
    - name: [mgmt.vrf]
      enable: true
```
Based on the default_mgmt_method (oob or inband) we would like to automatically derive the VRF from other AVD vars:
```
[mgmt.vrf]: Default OOB: “mgmt_interface_vrf” / Default Inband VRF: “inband_mgmt_vrf”
```
The new data model would be something like:
```
ssh_settings:
  access_groups:
    - name: <str>
  idle_timeout: <int; 0-86400>
  enable: <bool>
```
Note: We are assuming here that we just listen in the default_mgmt_method VRF, although that might not be always the case (SSH supports multiple vrfs simultaneously).

 

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Avoid asking the user for the MGMT vrf.

### Describe the solution you would like

New ssh settings data model in eos_designs

### Contributing Guide

- [x] I agree to follow this project Code of Conduct

**Comment by gmuloc** [comment]
For ACLs in VRF "default" the vrf should be removed by eos_designs.
```
ssh_settings:
  vrfs: # should be implemented like snmp_settings after #5531 has merged
    - name: <str> # supports `use_default_mgmt_method_vrf` ...
      enabled: <bool; required>
      ipv4_acl: <str>
      ipv6_acl: <str>
  idle_timeout: <int; 0-86400> # ref from eos_cli_config_gen
```

Remember to update description for default_mgmt_method: https://avd.arista.com/5.4/ansible_collections/arista/avd/roles/eos_designs/docs/input-variables.html#management-interface-settings
