### ISSUE TITLE
Enhance SNMP settings via eos_designs

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#5472]
### Enhancement summary

We would like to simplify the user inputs that today require the user to set the VRF name, when using eos_designs to set the SNMP configuration. 

This would be the template that we currently use for SNMPv3 (similar for SNMPv2c):
```
snmp_settings:
  contact: [snmp_settings.contact]
  location: true
  enable_mgmt_interface_vrf: true // for oob
  enable_inband_mgmt_vrf: true // for inband
  compute_local_engineid: true
  compute_v3_user_localized_key: true
  views:
    - name: VIEW-ALL-ITEMS
      mib_family_name: ".1"
      included: true
  groups:
    - name: GROUP-READ-ALL
      version: v3
      authentication: priv
      read: VIEW-ALL-ITEMS
  users:
    - name: [snmp_settings.users.name]
      group: GROUP-READ-ALL
      version: v3
      auth: sha
      auth_passphrase: "{{ vault.snmpv3.user1.auth }}"
      priv: aes
      priv_passphrase: "{{ vault.snmpv3.user1.priv }}"
  hosts:
    - host: [snmp_settings.hosts.host]
      vrf: [mgmt.vrf]
      version: 3
      users:
        - username: [snmp_settings.hosts.users.username]
          authentication_level: priv
  ipv4_acls:
    - name: SNMP-ACL
      vrf: [mgmt.vrf]
  traps:
    enable: true

source_interfaces:
  snmp:
    mgmt_interface: true // for oob
   inband_mgmt_interface: true // for inband
```
Based on the default_mgmt_method (oob or inband) we would like to automatically derive the VRF used for hosts and ipv4_acls from other AVD vars:
```
[mgmt.vrf]: Default OOB: “mgmt_interface_vrf” / Default Inband VRF: “inband_mgmt_vrf”
```
The data model would be same as the existing one, but with a default VRF automatically set for hosts and ipv4_acls based on the inband/oob selection, so user does not need to provide it (otherwise user can overwrite it):
```
snmp_settings:
 [...]
  hosts:
    - host: [snmp_settings.hosts.host]
      vrf: [mgmt.vrf] // default mgmt VRF set if not provided
      version: 3
      users:
        - username: [snmp_settings.hosts.users.username]
          authentication_level: priv
  ipv4_acls:
    - name: SNMP-ACL
      vrf: [mgmt.vrf]  // default mgmt VRF set if not provided
```
Note: We are assuming here that we set the SNMP VRF for all the hosts and the IPv4 ACL in the "default_mgmt_method" VRF, although that might not be always the case (SNMP supports multiple vrfs simultaneously).

### Which component of AVD is impacted

eos_designs

### Use case example

Reduce inputs for user during configuring management settings.

### Describe the solution you would like

Explained above

### Contributing Guide

- [x] I agree to follow this project Code of Conduct

**Comment by ClausHolbechArista** [comment]
We already support dynamic VRF assignment for `snmp_settings`. A snip from the current model:

```yaml
snmp_settings:
<...>
      hosts:

          # Host IP address or name.
        - host: <str>

          # VRF Name.
          # Can be used in combination with "use_mgmt_interface_vrf" and "use_inband_mgmt_vrf" to configure the SNMP host under multiple VRFs.
          vrf: <str>

          # Configure the SNMP host under the VRF set with "mgmt_interface_vrf". Ignored if 'mgmt_ip' or 'ipv6_mgmt_ip' are not configured for the device, so if the host is only configured with this VRF, the host will not be configured at all. Can be used in combination with "vrf" and "use_inband_mgmt_vrf" to configure the SNMP host under multiple VRFs.
          use_mgmt_interface_vrf: <bool>

          # Configure the SNMP host under the VRF set with "inband_mgmt_vrf". Ignored if inband management is not configured for the device, so if the host is only configured with this VRF, the host will not be configured at all. Can be used in combination with "vrf" and "use_mgmt_interface_vrf" to configure the SNMP host under multiple VRFs.
          use_inband_mgmt_vrf: <bool>
          version: <str; "1" | "2c" | "3">

          # Community name. Required with version "1" or "2c".
          community: <str>
          users:
            - username: <str>
              authentication_level: <str; "auth" | "noauth" | "priv">
```

**But we would need to do the same for `ipv[46]_acls`**
