### ISSUE TITLE
Enhance sflow via eos_designs

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#5473]
### Enhancement summary

We would like to simplify the user inputs that today require the user to set the VRF name, when using eos_designs to set the Sflow configuration. Sflow settings already takes care of the source-interface configuration.

Currently, if we want to use an interface that is in a non-default VRF, we can to specify the VRF to the terminattr daemon using the sflowaddr flag as shown below:
```
sflow_settings:
  sample:
    rate: 100000
  destinations:
    - destination: 127.0.0.1
      vrf: [mgmt.vrf]
  vrfs:
    - name: [mgmt.vrf]
      source_interface: [mgmt.source_interface]

custom_structured_configuration_daemon_terminattr:
  sflowaddr: [mgmt.vrf]/127.0.0.1:6343
```
Based on the default_mgmt_method (oob or inband) we would like to automatically derive the VRF used from other AVD vars:
```
[mgmt.vrf]: Default OOB: “mgmt_interface_vrf” / Default Inband VRF: “inband_mgmt_vrf”
```
The data model would be same as the existing one, but with the VRF automatically set:
```
sflow_settings:
  sample:
    rate: <int; 1-4294967295>
  destinations:
    - destination: <str; required>
```

When using CVP as the sflow collector (127.0.0.1 address) the daemon terminattr should be also automatically configured to listen in the appropiate VRF.
```
sflow_settings:
  sample:
    rate: <int; 1-4294967295>
  destinations:
    - destination: 127.0.0.1

terminattr_sflowaddr: [mgmt.vrf]/127.0.0.1:6343 // automatically set
```
Note: We are assuming here that we set the sflow VRF for all the destinations in the "default_mgmt_method" VRF, although that might not be always the case (sflow supports multiple vrfs simultaneously).

### Which component of AVD is impacted

eos_designs

### Use case example

Reduce inputs for user during configuring management settings.

### Describe the solution you would like

Described above

### Contributing Guide

- [x] I agree to follow this project Code of Conduct

**Comment by gmuloc** [comment]
this will be a flag added to the model

Requires #6174

```
sflow_settings:
  sample:
    rate: 100000
  destinations:
    - destination: 127.0.0.1
      vrf: [mgmt.vrf]
  vrfs:
    - name: [mgmt.vrf]
      source_interface: [mgmt.source_interface]
>>>> new dict
  export_to_cloudvision:
    enabled: <bool>
    vrf: <use_inband_mgmt_vrf, use_mgmt_interface_vrf , use_default_mgmt_method_vrf, str,  default=use_default_mgmt_method_vrf>
>>> end new dict
```

When this is set, eos_designs will automatically add a destination to the Sflow settings:
```
sflow_settings:
  destinations:
    - destination: 127.0.0.1
      vrf: MGMT
```

as well as setting:

```
daemon_terminattr:
  # where MGMT is the VRF
  sflowaddr: "MGMT/127.0.0.1:6343"
```

NOTE: if `export_to_terminattr.enabled: true` and  `cv_settings` is not set, `eos_designs` should raise
