### ISSUE TITLE
Add BGP plain password authentication

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#5500]
### Enhancement summary

As discussed with @gmuloc, it would be great to enhance BGP to support clear password authentication, as we already do with OSPF underlay.

Today we can already use inline jinja and AVD encrypt plugin to do that. for example using the following references to plaintext passwords in the vault file:
```
bgp_peer_groups:
  ipv4_underlay_peers:
       password: "{{ vault.bgp_peerings.underlay.password | arista.avd.encrypt(passwd_type='bgp', key='IPv4-UNDERLAY-PEERS') }}"

  mlag_ipv4_underlay_peer:
       password: "{{ vault.bgp_peerings.mlag.password | arista.avd.encrypt(passwd_type='bgp', key='MLAG-IPv4-UNDERLAY-PEER') }}"

  evpn_overlay_peers:
         password: "{{ vault.bgp_peerings.overlay.password | arista.avd.encrypt(passwd_type='bgp', key='EVPN-OVERLAY-PEERS') }}"

  mlag_ipv4_vrfs_peer:
    name: "MLAG-IPv4-VRFS-PEER"
    password: "{{ vault.bgp_peerings.mlag.password | arista.avd.encrypt(passwd_type='bgp', key='MLAG-IPv4-VRFS-PEER') }}"
```
Today with OSPF in the underlay, we calculate the hashes using the AVD plugin internally:
```
underlay_ospf_authentication:
  enabled: <bool; default=False; required>
  message_digest_keys: # 1-2 items; required
    - id: <int; required; unique>
      hash_algorithm: <str; "md5" | "sha1" | "sha256" | "sha384" | "sha512"; default="sha512">
      # Key password.
      # Only plaintext passwords are supported here as `eos_designs` will encrypt the password for each individual underlay interface.
      # To protect the password at rest it is strongly recommended to make use of Ansible Vault or similar.
      key: <str; length 1-16; required>
underlay_ospf_bfd_enable: <bool; default=False>
```
https://avd.arista.com/5.4/ansible_collections/arista/avd/roles/eos_designs/docs/input-variables.html#ospf-settings

So we would like to enhance BGP settings to encrypt the password for each peer group individually based on its default or custom name:
https://avd.arista.com/5.4/ansible_collections/arista/avd/roles/eos_designs/docs/input-variables.html#bgp-settings

### Which component of AVD is impacted

eos_designs

### Use case example

Users entering clear texts passwords for BGP and without using explicitly the AVD plugin & inline jinja.

### Describe the solution you would like

Same as OSPF encryption.

### Describe alternatives you have considered

Using jinja as described above.

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
