### ISSUE TITLE
validate_state awareness with anta_runner role

### ISSUE THREAD

**Issue by arista-matt** [aristanetworks/ansible-avd#5503]
### Enhancement summary

We're requesting that anta executions via the anta_runner role to honor the validate_state bool.

### Which component of AVD is impacted

anta_runner

### Use case example

Using the L2LS example (slightly modified):
```
servers:
  - name: HostA
    rack: POD1
    adapters:
      - endpoint_ports: [Eth1, Eth2]
        switch_ports: [Ethernet3, Ethernet13]
        switches: [LEAF1, LEAF2]
        profile: PP-BLUE
        port_channel:
          mode: active
        validate_state: false
```

We're requesting that anta executions via the anta_runner role to honor the validate_state bool. So in this example, this port-channel would be ignored.

If we use anta to test a digital-twin, some of the port-channels that are stubbed out for server connections will likely be down, and as a result fail the VerifyPortChannels tests.

### Describe the solution you would like

We're requesting that anta executions via the anta_runner role to honor the validate_state bool.

### Describe alternatives you have considered

We could use https://avd.arista.com/5.4/ansible_collections/arista/avd/roles/anta_runner/index.html#test-based-filtering , but this would ignore all port-channels.

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
