### ISSUE TITLE
Feat (eos_cli_config_gen): SVI support for IGMP Querier Virtual Address

### ISSUE THREAD

**Issue by ctyrider** [aristanetworks/ansible-avd#5522]
### Enhancement summary

Add support for "ip igmp querier address virtual" CLI command under SVI interfaces:

```
interface <VLAN-NAME>
   ip igmp querier address virtual
```

### Which component of AVD is impacted

eos_cli_config_gen

### Use case example

Ability to configure "ip igmp querier address virtual" CLI command under SVI interfaces

### Describe the solution you would like

```yaml
vlan_interfaces:
  - name: <str; required; unique>
    ip_igmp_querier_address_virtual: <bool>
```

### Describe alternatives you have considered

n/a

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
