### ISSUE TITLE
Add VRF support under router OSPF in EOS CLI Config Gen

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#554]
**Issue Type**

- Template enhancement

**Is your feature request related to a problem? Please describe.**

Add VRF support for OSPF configuration

**Describe the solution you'd like**

Enhance data model with a VRF key

```yaml
router_ospf:
  process_ids:
    < process_id >:
      vrf: < VRF name >
```
