### ISSUE TITLE
Test: Move inline jinja away from host1 in `eos_designs_deprecated_vars`

### ISSUE THREAD

**Issue by gmuloc** [aristanetworks/ansible-avd#5544]
Today `host1` is excluded from PYTEST because there is inline jinja - this implies that it is excluded from coverage which is sad.

```
---
all:
  children:
    IGNORE_IN_PYTEST:
      hosts:
        host1: # TODO: Remove inline jinja
    EOS_DESIGNS_DEPRECATED_VARS:
      hosts:
        host1:
        host2:
    TENANTS:
      children:
        EOS_DESIGNS_DEPRECATED_VARS:
```

this PR is to improve coverage by moving keys using inline keys to a third host like we did in `eos_cli_config_gen` to be able to use `host1` back.

```
---
all:
  children:
    IGNORE_IN_PYTEST:
      hosts:
        host_inline_jinja:
    EOS_DESIGNS_DEPRECATED_VARS:
      hosts:
        host_inline_jinja:
        host1:
        host2:
    TENANTS:
      children:
        EOS_DESIGNS_DEPRECATED_VARS:
```
