### ISSUE TITLE
Enhance IPFlow via eos_designs

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#5547]
### Enhancement summary

We would like to simplify the user inputs that today require the user to set the "local_interface" and "vrf", when using eos_designs to set the IPFlow configuration. 

Currently, if we want to use an interface that is in a non-default VRF, we can to specify the VRF to the terminattr daemon using the ipfixaddr flag as shown below:
```
flow_tracking_settings:
  sampled:
    sample: 10000
  trackers:
    - name: ftr1
      record_export:
        on_inactive_timeout: 300000
        on_interval: 15000
      exporters:
        - name: exp1
          collector:
            host: 127.0.0.1
          local_interface: [mgmt.source_interface]

custom_structured_configuration_daemon_terminattr:
  ipfixaddr: [mgmt.vrf]/127.0.0.1:4739
```
Based on the default_mgmt_method (oob or inband) we would like to automatically derive the VRF used from other AVD vars:
```
[mgmt.vrf]: Default OOB: “mgmt_interface_vrf” / Default Inband VRF: “inband_mgmt_vrf”
```
The data model would be same as the existing one, but with the local_interface automatically set for the flow tracking settings:
```
flow_tracking_settings:
  sampled:
    sample: <int; 1-4294967295; default=10000>
  trackers:
    - name: <str; required; unique>
      record_export:
        on_inactive_timeout: <int; 3000-900000>
        on_interval: <int; 1000-36000000>
      exporters:
        - name: <str; required; unique>
          collector:
            host: <str>
```
When using CVP as the IPFix collector (127.0.0.1 address) the daemon terminattr should be also automatically configured to listen in the appropiate VRF.
```
flow_tracking_settings:
       ...
      exporters:
        - name: <str; required; unique>
          collector:
            host: 127.0.0.1

terminattr_ipfixaddr: [mgmt.vrf]/127.0.0.1:4739 // automatically set
```
Note: We are assuming here that we set the IPFlow VRF for all the destinations in the "default_mgmt_method" VRF, although that might not be always the case. 

IPFix supports multiple collectors. If they are in different VRFs then we can create multiple exporters and each exporter uses the VRF based on the configured local interface.

### Which component of AVD is impacted

eos_designs

### Use case example

Reduce inputs for user during configuring management settings.

### Describe the solution you would like

Described above

### Contributing Guide

- [x] I agree to follow this project Code of Conduct

**Comment by gmuloc** [comment]
to the implementer - we will split this issue in two PRs

1/ local_interface should be (for both sampled and hardware):

```
flow_tracking_settings:
  sampled:
    sample: 10000
  trackers:
    - name: ftr1
      record_export:
        on_inactive_timeout: 300000
        on_interval: 15000
      exporters:
        - name: exp1
          collector:
            host: 127.0.0.1

          # The value will be interpreted according to these rules:
          #   - `use_mgmt_interface` will configure the `mgmt_interface` as the local interface.
          #   - `use_inband_mgmt_interface` will configure the `inband_mgmt_interface` as the local interface.
          #   - `use_default_mgmt_method_interface` will configure `mgmt_interface` or `inband_mgmt_interface` as the local interface depending on the value of `default_mgmt_method`.
          #   - Any other string will be used directly as the local interface.
          local_interface: <str; default="use_default_mgmt_method_interface">
```


2/ this will be a flag added to the model

```
flow_tracking_settings:
  sampled:
    sample: <int; 1-4294967295; default=10000>
  trackers:
    - name: <str; required; unique>
      record_export:
        on_inactive_timeout: <int; 3000-900000>
        on_interval: <int; 1000-36000000>
>>>> new dict
      export_to_cloudvision:
        enabled: <bool>
        name: <str, default=CLOUDVISION>
        vrf: <use_inband_mgmt_vrf, use_mgmt_interface_vrf , use_default_mgmt_method_vrf, str,  default=use_default_mgmt_method_vrf>
        # Local interface used to connect to TerminAttr on EOS.
        # If not set, the local interface may be set automatically when VRF is set to `use_mgmt_interface_vrf`, `use_inband_mgmt_vrf` or `use_default_mgmt_method_vrf`.
        source_interface: <str>
>>> end new dict
      exporters:
        - name: <str; required; unique>
          collector:
            host: <str>
            port: <int>
```

When this is set, `eos_designs` will automatically add an exporter to the traffic as follow:

```
      exporters:
        - name: CLOUDVISION
          collector:
            host: 127.0.0.1
          local_interface: <based on local_interface or VRF if set>
```

as well as setting:

```
daemon_terminattr:
  # where MGMT is the VRF
  ipfixaddr: "MGMT/127.0.0.1:4739"
```

NOTE: if `export_to_cloudvision.enabled: true` and  `cv_settings` is not set, `eos_designs` should raise


This means:


```
flow_tracking_settings:
  trackers:
    - name: BLAH
      export_to_cloudvision:
        enabled: true
```

will generate the exporter for the tracker + the daemon_terminattr command
