### ISSUE TITLE
Digital twin: support for local CVP in ACT

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#5566]
### Enhancement summary

As dicussed @ClausHolbechArista, we currently deploy a local CVP in ACT, so it would be useful if we can have the ability to define the same via AVD:

The topology file contains the cvp definition (user, pass, version, ip, instance_type, etc):
```
cvp:
  # Define global cvp node parameters
  username: root
  password: cvproot
  version: 2025.1.1
  instance: singlenode
# List of ACT nodes
nodes:
  - cvp:
      ip_addr: 192.168.0.5
      node_type: cvp
      auto_configuration: true
      ntp_ip: 0.pool.ntp.org
      instance_type: large
```

We also define a connection to an OOB switch, so it can manage the devices via the OOB network (if available, described in this [RFE5567](https://github.com/aristanetworks/avd/issues/5567) ):
```
  - connection:
      - cvp:Management0
      - oob-sw:Ethernet1
```

### Which component of AVD is impacted

eos_designs

### Use case example

Having a local CVP instance for managing the ACT lab.

### Describe the solution you would like

Expand the vars in the playbook that creates the digital twin to support this.

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
