### ISSUE TITLE
Digital twin: support to build OOB networks in ACT

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#5567]
### Enhancement summary

We currently deploy an OOB network in ACT to replicate out-of-band type of configurations, where the Management port is on a separate VRF. It would be useful if we can have the ability to define the same via AVD. The ACT topology file is something along this lines:

```
nodes:
  - oob-sw:
      ip_addr: 192.168.0.130
      node_type: veos

links:
- connection:
      - cvp:Management0
      - oob-sw:Ethernet1
  - connection:
      - oob-sw:Ethernet2
      - DC1-SP1:Management1
  - connection:
      - oob-sw:Ethernet3
      - DC1-SP2:Management1
  - connection:
      - oob-sw:Ethernet4
      - DC1-CL1:Management1
```
With the Management port of the switches connected to the Management port of the switches and in this case also to the CVP node.

### Which component of AVD is impacted

eos_designs

### Use case example

Having an OOB network to replicate OOB configurations. Also having local CVP instance to manage the devices via the OOB mgmt interface.

### Describe the solution you would like

Expand the vars in the playbook that creates the digital twin to support this.

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
