### ISSUE TITLE
Digital twin: support for internet access in ACT

### ISSUE THREAD

**Issue by dgonzalez-arista** [aristanetworks/ansible-avd#5568]
### Enhancement summary

By default nodes in ACT does not have internet access, which sometimes might be useful, such as to access the devices externally etc. The following knob allows to set that at the node level:
 ```
nodes:
  - DC1-SP1:
      ip_addr: 192.168.0.100
      node_type: veos
      internet_access: true
  - DC1-SP2:
      ip_addr: 192.168.0.101
      node_type: veos
      internet_access: true
  - DC1-CL1:
      ip_addr: 192.168.0.102
      node_type: veos
      internet_access: true
  - DC1-CL2:
      ip_addr: 192.168.0.103
      node_type: veos
      internet_access: true
```
A similar global knob in AVD that enables/disables the internet access will be useful (i think enabling/disabling for all of them is fine).

### Which component of AVD is impacted

eos_designs

### Use case example

Internet access to manage the devices externally.

### Describe the solution you would like

Expand the vars in the playbook that creates the digital twin to support this internet_access knob.

### Contributing Guide

- [x] I agree to follow this project Code of Conduct
