### ISSUE TITLE
eos_validate role - lo0 reachability - skip l2leaf

### ISSUE THREAD

**Issue by ksator** [aristanetworks/ansible-avd#561]
**Issue Type**

- Role enhancement

The role eos_validate has already a task to validate lo0 reachability between devices that has lo0 configured. 
This issue s to skip l2leaf even if they have lo0 configured (because l2leaf wont adv their lo0)  

replace
```
- name: Gather ip reachability state between devices (loopback0 <-> loopback0)
  eos_command:
    commands: "ping {{ loopback0_address | ipaddr('address')}} source {{ loopback_interfaces.Loopback0.ip_address | ipaddr('address')}} repeat 1"
  loop: "{{ loopback0_reachability.loopback0_range }}"
  loop_control:
    loop_var: loopback0_address
  ignore_errors: "{{ eos_validate_state_validation_mode_loose }}"
  when: |
    (loopback0_reachability.loopback0_range is defined and loopback0_reachability.loopback0_range is not none) and
    (loopback_interfaces.Loopback0.ip_address is defined and loopback_interfaces.Loopback0.ip_address is not none)
  register: loopback0_reachability_state
  tags:
    - loopback0_reachability

```

with
```

- name: Gather ip reachability state between devices (loopback0 <-> loopback0)
  eos_command:
    commands: "ping {{ loopback0_address | ipaddr('address')}} source {{ loopback_interfaces.Loopback0.ip_address | ipaddr('address')}} repeat 1"
  loop: "{{ loopback0_reachability.loopback0_range }}"
  loop_control:
    loop_var: loopback0_address
  ignore_errors: "{{ eos_validate_state_validation_mode_loose }}"
  when: |
    (loopback0_reachability.loopback0_range is defined and loopback0_reachability.loopback0_range is not none) and
    (loopback_interfaces.Loopback0.ip_address is defined and loopback_interfaces.Loopback0.ip_address is not none) and
    (type is defined and type != "l2leaf")
  register: loopback0_reachability_state
  tags:
    - loopback0_reachability

```
