### ISSUE TITLE
Add support for aggregate-addresses for BGP VRF in eos_cli_config_gen

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#565]
**Issue Type**

- Role enhancement

**Is your feature request related to a problem? Please describe.**

When `eos-cli_config_gen` is used in a pure DCI environment, it can be required to configure route aggregation per VRF and not globally. 

**Describe the solution you'd like**

A data model as per this example:

```yaml
vrfs:
  BLUE-C1:
    rd: 1.0.1.1:101
    neighbors:
      10.1.1.0:
        peer_group: OBS_WAN
      10.255.1.1:
        peer_group: WELCOME_ROUTERS
      101.0.3.1:
        peer_group: SEDI
    aggregate_addresses:
      193.1.0.0/16:
        as_set: true
        summary_only: true
        attribute_map: RM-BGP-AGG-APPLY-SET
```

**Additional context**

Required for a customer project.
