### ISSUE TITLE
Manually select VLAN for per VRF MLAG iBGP peering

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#573]
**Issue Type**

- Template enhancement
- Role enhancement
- Documentatin enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

It would be great to have an option if we want to enable this feature with `enable_mlag_ibgp_peering_vrfs: true` so that we can specify exactly which VLAN to be used, and avoid confusion and other problems that could arise.

This is something which is not needed by default for every L3 service, thus gives more control.

Additionally to this that we have:

```
# MLAG internal BGP peering VRFs
mlag_ibgp_peering_vrfs:
  base_vlan: 3900
```

Under each VRF we can have a knob to specify

**Describe the solution you'd like**

```
vrfs:
      Tenant_A_OP_Zone:
        vrf_vni: 10
        enable_mlag_ibgp_peering_vrfs: true
        vlan_mlag_ibgp_peering_vrfs: 3901
```

**Describe alternatives you've considered**

**Additional context**
