### ISSUE TITLE
Storm control with port-channels

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#575]
## Issue Type

- Bug Report
- Documentation Issue Report
- EOS Configuration error

## Summary
When we have port-channels and we call port profiles with storm control, it doesn't take into account the structured config and add it under port-channel.

It works well with physical interfaces.

```
  Ethernet5:
    peer: server03
    peer_interface: Eth1
    peer_type: server
    description: server03_Eth1
    type: switched
    shutdown: false
    mode: trunk
    vlans: 210-211
    storm_control:
      broadcast:
        level: 10
      multicast:
        level: 20
      unknown_unicast:
        level: 15
    channel_group:
      id: 5
      mode: active
    profile: TENANT_B
```

```
interface Port-Channel5
   description server03_PortChannel1
   no shutdown
   switchport
   switchport trunk allowed vlan 210-211
   switchport mode trunk
   mlag 5
```

Working example

```
  Ethernet4:
    peer: server02
    peer_interface: Eth0
    peer_type: server
    description: server02_Eth0
    type: switched
    shutdown: false
    mode: trunk
    vlans: 210-211
    storm_control:
      broadcast:
        level: 10
      multicast:
        level: 20
      unknown_unicast:
        level: 15
    profile: TENANT_B
```

```
interface Ethernet4
   description server02_Eth0
   no shutdown
   switchport
   switchport trunk allowed vlan 210-211
   switchport mode trunk
   storm-control broadcast level 10
   storm-control multicast level 20
   storm-control unknown-unicast level 15
```

### OS / Environment

__EOS Version__

__Cloudvision version__ (optional)

__OS running Ansible__

## Steps to reproduce

```yaml

```

### Expected results

```shell
$
```

### Actual results

```shell

```
