### ISSUE TITLE
Add traffic-policy feature in eos_cli_config_gen

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#578]
**Issue Type**

- Role enhancement

**Is your feature request related to a problem? Please describe.**

Allow configuration of traffic-policy on interface as per EOS documentation: https://eos.arista.com/eos-4-25-0f/support-for-traffic-policy-on-interfaces/

**Describe the solution you'd like**

Implement the following data model to generate EOS configuration

```yaml
traffic_policies:
  ipv4:
    BLUE-C1-POLICY:
      match:
        BLUE-C1-POLICY-01:
          source:
            prefixes:
              - 10.0.0.0/8
              - 192.168.0.0/16
          protocols:
            tcp:
              src_port: "1,10-20"
            icmp:
          actions:
            log: true
            traffic_class: 8
        BLUE-C1-POLICY-02:
          source:
            prefix_lists:
              - PL-BOGONS
          protocols:
            tcp:
              dst_port: "80,443"
            icmp:
          actions:
            count: MyCounter
            dscp: 60
        BLUE-C1-POLICY-02:
          source:
            prefix_lists:
              - PL-BOGONS
          protocols:
            tcp:
          actions:
            count: DROP-COUNTER
            drop: true
```
