### ISSUE TITLE
Allow user to customize outputs folders for all AVD roles

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#585]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Describe the solution you'd like**

Allow user to configure custom folder name for:

- documentation
- intended/structured_configs
- intended/configs
- config_backup

It is already present in build_folder_output but should be applied in all roles.

**Comment by ksator** [comment]
so each role will start with this task: 
```
- name: Include default vars from the role build_output_folders
  include_vars:
    file: ../../build_output_folders/defaults/main.yml
  delegate_to: localhost
  run_once: true
```
and wont have the same variables in its own `defaults/main.yml`

@titom73 is it what we want?

**Comment by titom73** [comment]
I would not do that since it will override any user setting and would lead to an incorrect situation like:

- build_output_folders create user's folders
- AVD use default (non-created) folders

I thought to use the same variable name for folder name across AVD to get consistent folder management.

```yaml
# YAML file in group_vars

# Root directory where to build output structure
root_dir: '{{ inventory_dir }}'

# AVD configurations output
# Main output directory
output_dir_name: 'intended'
output_dir: '{{ root_dir }}/{{ output_dir_name }}'
```

And then in the playbook, call build_output_folders to create `output_dir` and use `output_dir` in expected AVD role.
