### ISSUE TITLE
Event-handler configuration is not following correct EOS structure

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#616]
## Issue Type

- [ ] Bug Report
- [x] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

Event-handler configuration is valid but output is not similar to EOS configuration

## Component Name

`eos_cli_config_gen`

## Steps to reproduce

Use following YAML file

```yaml
### Event Handler ###
event_handlers:
  tracking:
    action_type: bash
    action: /mnt/flash/tracking.sh
    delay: 300
    trigger: on-boot

```

### Expected results

```eos
event-handler tracking
   trigger on-boot
   action bash /mnt/flash/tracking.sh
   delay 300
!
```

### Actual results

```eos
event-handler tracking
   action bash /mnt/flash/tracking.sh
   delay 300
   !
   trigger on-boot
!
```
