### ISSUE TITLE
Update TCAM support in CLI Config Gen to support custom profile

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#620]
**Issue Type**

- [x] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

The current TCAM profile only supports which profile to apply to the system. But some features require to implement a custom TCAM profile.

**Describe the solution you'd like**

```yaml
tcam_profile:
  system: < tcam_profile >
  profiles:
    < profile name >: |
      < multiline EOS TCAM profile >
      < multiline EOS TCAM profile >
      < multiline EOS TCAM profile >
```

It can also work with lookup plugins depending of user's workflow

```yaml
tcam_profile:
  system: < tcam_profile >
  profiles:
    < profile name >: "{{lookup('file', '< path to EOS TCAM configuration >')}}"
```

**Describe alternatives you've considered**

Other option would be to load a snippet from a file to use with `< profile name >` but would be a different process compare to other CLI CONFIG GEN things
