### ISSUE TITLE
Add support for class-map and policy-map for QOS

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#624]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Implement `class-map` and `policy-map` in AVD to produce following configuration

```eos
! Example 1
class-map type qos match-any TEST
   match vlan 10-100
!
! Example 2
class-map type qos match-any TEST
   match cos 7
!
! Example 3
class-map type qos match-any TEST
   match ip access-group TEST
!
policy-map type quality-of-service PM_TEST
   class TEST
      set dscp af11
   !
   class class-default
!
```

**Describe the solution you'd like**

Add support for the following datamodel in `eos_cli_config_gen`

```yaml
class_maps:
  <class-map name>:
    vlan: <str>
    cos: <str>
    ip:
      access_group: <str>
policy_maps:
  qos:
    <PM name>:
      class:
      set:
        dscp: <str dscp field>
        traffic_class: <0-7>
        drop_precedence: < 1-2>

      # Not Implemented
      police: 
        cir:
        rate:
```
