### ISSUE TITLE
Add support for non-standard syslog port and protocol under logging options

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#626]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Some Syslog solutions use a non-standard port to receive packets. EOS CLI supports the selection of protocol and destination port per host. Currently, data model implementation only supports the default destination port.

**Describe the solution you'd like**

Update following data model to support custom protocol & dst port per host:

```yaml
logging:
  vrfs:
    < vrf_name >:
      source_interface: < source_interface_name >
      hosts:
        - < syslog_server_1>
        - < syslog_server_2>
```

2 options might be used:

- Split using a delimiter: `< syslog_server_1 >:< tcp|udp >:< custom_port >`
- Add a full structure under `< syslog_server_x >`

```yaml
logging:
  vrfs:
    < vrf_name >:
      source_interface: < source_interface_name >
      hosts:
        - < syslog_server_1>:
            protocol: < tcp|udp >
            port: < custom_port >
        - < syslog_server_2>
```

**Additional context**

Required for __`FR-PROJECT-02`__
