### ISSUE TITLE
Add support for route summary under router ospf

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#634]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Update existing OSPF data model to support route summary in EOS CLI CONFIG GEN

**Describe the solution you'd like**

Update datamodel to add summary section

```yaml
router_ospf:
  process_ids:
    < process_id >:
      vrf: < vrf_name_for_process_id >
      passive_interface_default: < true | false >
      router_id: < IPv4_address >
      log_adjacency_changes_detail: < true | false >
      bfd_enable: < true | false >
      no_passive_interfaces:
        - < interface_1 >
        - < interface_2 >
      max_lsa: < integer >
      default_information_originate:
        always: true
      summary:
        - prefix: < summary_prefix_01 >
          tag: < string >
          attribute_map: < string >
          not_advertise: < true | false >
        - prefix: < summary_prefix_02 >
        - prefix: < summary_prefix_03 >
      redistribute:
        static:
          route_map: < route_map_name >
        connected:
          route_map: < route_map_name >

```

**Additional context**

Required for __`FR-PROJECT-02`__
