### ISSUE TITLE
eos_cli_config_gen for SNMP local interfaces does not generate correct CLI command

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#638]
- [x] EOS Configuration rendering error

## Summary

eos_cli_config_gen misses to render correct cli command
result is: snmp-server local-interface {'name': 'Management1', 'vrf': 'MGMT'} 

## Component Name
eos_l3ls_evpn, eos_cli_config_gen

## Steps to reproduce

The following snmp_server config in a global_vars file.
Execute ansible-playbook playbooks/DC1-fabric-deploy-cvp.yml --tags build -i inventories/DC1/inventory.yml

```yaml
### SNMP ###
snmp_server:
  local_interfaces:
    - name: Management1
      vrf: MGMT
```

### Expected results

```shell
snmp-server vrf MGMT local-interface Management1
```

### Actual results

```shell
snmp-server local-interface {'name': 'Management1', 'vrf': 'MGMT'}
```

**Comment by titom73** [comment]
Seems to be related to PR https://github.com/aristanetworks/ansible-avd/pull/548 changes

**Comment by titom73** [comment]
Hello @kmueller68 

PR #548 has introduced a breaking change in data-model used in the devel branch and which should be part of the v2.0.0 release.

As per this PR, you should now use the following structure:

```yaml
snmp_server:
  local_interfaces:
    Management1:
      vrf: mgt
    Loopback0:
    Loopback12:
      vrf: test2
```

So in your case, new syntax should be:

```yaml
### SNMP ###
snmp_server:
  local_interfaces:
    Management1:
      vrf: MGMT
```

Since sometimes we need to update the data-model during the development of a new version, so I would recommend using a release branch or a tagged version. In the meantime, we also document breaking changes in the release notes and also provide a migration role when applicable which makes more predictable to upgrade.

If this method is not applicable, you may check PR with tag `data-model change` to see if you need to change your variables: https://github.com/aristanetworks/ansible-avd/labels/data%20model%20change
