### ISSUE TITLE
Support MPLS and IP-VPN on eos_cli_config_gen for DCI use case

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#640]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [x] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Would be great to support variety for DCI uses cases on Border Leaf. This would mean the Leaf to participate as PE in MPLS.

Would need at minimum to support MPLS forwarding, LDP or SR, MPLS IP-VPN (VPNv4) for interworking including D-PATH.

We already have routing basics like OSPF/IS-IS in place, and BGP IPv4/IPv6, including PE-CE scenarios for VRFs.

**Describe the solution you'd like**

MPLS and LDP

```
mpls ip
!
mpls ldp
   router-id {{ ROUTER_ID }}
   interface disabled default
   no shutdown
!
interface Ethernet {{ INTERFACE_NUMBER }}
   mpls ldp interface
!
interface Loopback0 {{ INTERFACE_NUMBER }}
   mpls ldp interface
```

IGP - OSPF MPLS tweaks

```
router ospf {{ PROCESS_ID }}
   router-id {{ ROUTER_ID }}
   auto-cost reference-bandwidth {{ REFERENCE_BW }}
   bfd default
   maximum-paths 16
   passive-interface default
   no passive-interface {{ INTERFACES }}
   network {{ L0_IPV4_ADDRESS }} 0.0.0.0 area {{ AREA }}
   max-metric router-lsa on-startup wait-for-bgp
   mpls ldp sync default
```

IGP interface
```
interface Ethernet {{ INTERFACE_NUMBER }}
   ip ospf network point-to-point
   ip ospf area {{ AREA }}
   ip ospf authentication message-digest
   ip ospf message-digest-key 1 md5 {{ KEY }}
   bfd interval 250 min_rx 250 multiplier 3
```

BGP IP-VPN support

```
router bgp {{ LEAF_ASN }}
   neighbor MPLS-VPN-PEERS peer group
   neighbor MPLS-VPN-PEERS remote-as {{ REMOTE_ASN }}
   neighbor MPLS-VPN-PEERS local-as {{ LOCAL_ASN }} no-prepend replace-as
   neighbor MPLS-VPN-PEERS update-source Loopback0
   neighbor MPLS-VPN-PEERS send-community
   neighbor MPLS-VPN-PEERS maximum-routes 0
   neighbor MPLS-VPN-PEERS password 7 {{ PASSWORD }}
   neighbor {{ ROUTE_REFLECTOR_1 }} peer group MPLS-VPN-PEERS
   neighbor {{ ROUTE_REFLECTOR_2 }} peer group MPLS-VPN-PEERS
   !
   address-family vpn-ipv4   
      neighbor MPLS-VPN-PEERS activate
      neighbor default encapsulation mpls next-hop-self source-interface Loopback0
```

D-PATH

```
router bgp {{ LEAF_ASN }}
 bgp bestpath d-path
 !
 address-family vpn-ipv4
   domain identifier {{ FABRIC_ASN }}: {{ MPLS_DOMAIN }}
 !
 address-family evpn
   domain identifier {{ FABRIC_ASN }}: {{ VXLAN_DOMAIN }}
```

BGP in VRF PE-CE knobs

```
router bgp {{ LEAF_ASN }}
!
   vrf {{ VRF_ID }}
     rd {{ RD }}
     router-id {{ ROUTER_ID }}
     route-target import evpn {{ RT }}
     route-target export evpn {{ RT }}
     route-target import vpn-ipv4 {{ RT }}
     route-target export vpn-ipv4 {{ RT }}
     route-target export vpn-ipv4 route-map option
```

Suggested data models:
```
mpls:
  ip: < true | false >
  ldp:
    interface_disabled_default: < true | false >
    router_id: < string>
    shutdown: < true | false >

ethernet_interfaces:
  mpls:
    ip: < true | false >
    ldp:
      interface: < true | false >

router_bgp:
  bgp:
    bestpath:
      d-path: < true | false >
  peer_groups:
    < peer_group_name_1>:
      local_as: < bgp_as >
  address_family_vpn_ipv4: 
    domain_identifier:  < string >
    peer_groups: < peer_group_name >: 
      activate: < true | false >
    neighbor_default_encapsulation_mpls_next_hop_self:
      source_interface: < interface >
  address_family_evpn: 
    domain_identifier:  < string >

ip_extcommunity_lists_regexp:
  < community_list_name_1 >:
    - type: < permit | deny >
      regexp: "< string >"
```

**Describe alternatives you've considered**

**Additional context**
