### ISSUE TITLE
Storm control with port-channels - wrong CLI syntax  for unknown-unicast

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#642]
## Issue Type

- [x] EOS Configuration rendering error

## Summary

rendering edge port configuration with port-profile including storm-control configuration is working well for single ethernet ports but showing a CLI syntax issue on port-channels for unknown-unicast. It  generates "unknown_unicast" instead of "unknown-unicast"
  

## Component Name
eos_l3ls_evpn 
ansible-avd/ansible_collections/arista/avd/roles/eos_l3ls_evpn/templates/edge_ports/leaf-server-port-channels.j2

## Steps to reproduce

```yaml
port_profiles:
  Tenant_DC_ESX:
    mode: trunk
    native_vlan: '1000'
    vlans: 1000-1200
    spanning_tree_bpdufilter: false
    spanning_tree_portfast: edge
    storm_control:
      broadcast:
        level: 1
        unit: percent
      multicast:
        level: 1
        unit: percent
      unknown_unicast:
        level: 1
        unit: percent

servers:
  server10:
    adapters:
    - profile: Tenant_DC_ESX
      server_ports:
      - Eth0
      - Eth1
      switch_ports:
      - Ethernet9
      - Ethernet9
      switches:
      - leaf-2A
      - leaf-2B
      type: nic
      port_channel:
        description: PortChannelTest
        mode: active
    rack: 2E5

  Host-21-13:
    adapters:
    - profile: Tenant_DC_ESX
      server_ports:
      - Eth0
      switch_ports:
      - Ethernet10
      switches:
      - leaf-2A
      type: nic
    rack: 2E5

```

### Expected results

```shell
$
interface Port-Channel9
   description server10_PortChannelTest
   no shutdown
   switchport
   switchport trunk allowed vlan 1000-1200
   switchport trunk native vlan 1000
   switchport mode trunk
   mlag 9
   spanning-tree portfast
   storm-control broadcast level 1
   storm-control multicast level 1
   storm-control unknown-unicast level 1

interface Ethernet10
   description Host-21-13_Eth0
   no shutdown
   switchport
   switchport trunk allowed vlan 1000-1200
   switchport trunk native vlan 1000
   switchport mode trunk
   spanning-tree portfast
   storm-control broadcast level 1
   storm-control multicast level 1
   storm-control unknown-unicast level 1
```

### Actual results

```shell

interface Port-Channel9
   description server10_PortChannelTest
   no shutdown
   switchport
   switchport trunk allowed vlan 1000-1200
   switchport trunk native vlan 1000
   switchport mode trunk
   mlag 9
   spanning-tree portfast
   storm-control broadcast level 1
   storm-control multicast level 1
   storm-control unknown_unicast level 1
```
