### ISSUE TITLE
Make eos_validation_states independent of structured_configs

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#651]
## Issue Type

- [x] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

When trying to use `eos_validate_state` in conjunction of a `eos_cli_config_gen` only playbook, role fails as it cannot find structured_configs. Indeed, without `eos_l3ls_evpn` there is no reason to move variables to structured_config folder and then loose inheritance from host_vars and group_vars

Issue can be solved by adding following block on top of the main.yml file

```yaml
- name: Check if structure configuration file exists
  tags: [build, provision]
  stat:
    path: '{{ root_dir }}/intended/structured_configs//{{ inventory_hostname }}.yml'
  register: stat_result
  delegate_to: localhost

- name: Include device intended structure configuration variables
  include_vars: '{{ root_dir }}/intended/structured_configs//{{ inventory_hostname }}.yml'
  delegate_to: localhost
  tags: [build, provision]
  when: stat_result.stat.exists
```

## Component Name

```
arista.avd.eos_validate_state
```
