### ISSUE TITLE
Add support for VRF leaking under router general

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#669]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

For a specific project, we need to activate VRF leaking under `router general` which is not supported yet by __arista.avd.eos_cli_config_gen__

**Describe the solution you'd like**

Implement doc and eos template for `router general` with following data model:

```yaml
router_general:
  vrfs:
    < destination vrf >:
      leak:
        source_vrf: < source vrf > 
        policy: < route-map filtering >
```
