### ISSUE TITLE
l3ls: do not create empty SERVERS or TENANTS_NETWORKS containers in CloudVision

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#689]
## Issue Type

- [x] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

When deploying an L2LS fabric using the available roles from ansible-avd there is current a small cosmetic issue as empty folders will be generated on CVP.

Taking the example from https://github.com/arista-netdevops-community/ansible-webinar-february-2020 the provided [inventory.yml](https://github.com/arista-netdevops-community/ansible-webinar-february-2020/blob/master/inventory.yml#L68-L76) will show two additional groups `DC1_TENANTS_NETWORKS` and `DC1_SERVERS`. Those groups are used to apply common configuration (e.g. port profiles and tenants) to all switches.

The downside is that as no device is actually assigned to this container, the container will be empty in CloudVision.

## Component Name

* ansible-avd

## Steps to reproduce

Deploy https://github.com/arista-netdevops-community/ansible-webinar-february-2020 to your CVP instance

### Expected results

Only containers with actual devices assigned to it should be created in CloudVision. If a comntainer has no children (`len(container) == 0`) do not provision it.

**Comment by titom73** [comment]
indentified file: [`cvp-devices.j2`](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_config_deploy_cvp/templates/cvp-devices.j2)

```jinja2
CVP_CONTAINERS:
{% for container_name, container in CVP_VARS.CVP_TOPOLOGY.items() %}
  {{container_name}}:
    parent_container: {{container['parent_container']}}
{%     if hostvars[groups[container_root][0]]['cv_configlets']['containers'][container_name] is defined and hostvars[groups[container_root][0]]['cv_configlets']['containers'][container_name] is iterable %}
    configlets:
{%         for configlet in hostvars[groups[container_root][0]]['cv_configlets']['containers'][container_name] %}
      - {{ configlet }}
{%         endfor %}
{%      endif %}
{% endfor %}
```

Topic:

- Inventory expose inherited host in group (`ansible-inventory -i inventory.yml --list`)
- Require to find a way to identify if host is inherited or declared.

**Comment by titom73** [comment]
Hello @c-po 

I have looked at the data exposed by ansible for the inventory and unfortunately, there is no option to filter group with no device directly attached to a group (inheritance is applied directly)

A L3LEAF device will provide your tenant's group and the same, your tenant's group will list your L3LEAF.

What we do to not create a container for tenant is to structure inventory like below:

```yaml
all:
  children:
    DC1:
      children:
        DC1_FABRIC:
          children:
            DC1_SPINES:
              hosts:
            DC1_LEAFS:
              children:

            DC1_L2LEAFS:
              children:

        DC1_TENANTS_NETWORKS:
          children:
            DC1_LEAFS:
            DC1_L2LEAFS:

        DC1_SERVERS:
          children:
            DC1_LEAFS:
            DC1_L2LEAFS:
```

So AVD l3ls_evpn will work as it should and your `arista.avd.eos_config_deploy_cvp` can be configured to build containers starting at `DC1_FABRIC` and it will ignore groups at same level (`DC1_TENANTS_NETWORKS` and `DC1_SERVERS`)

```yaml
- name: Configuration deployment with CVP
  hosts: AVD-CVP-1
  connection: local
  gather_facts: no
  tasks:
    - name: run CVP provisioning
      import_role:
         name: arista.avd.eos_config_deploy_cvp
      vars:
        # Here we defined what we considered root container in CVP right under TENANT
        container_root: 'DC1_FABRIC' 
        configlets_prefix: 'DC1-AVD'
        device_filter: 'DC1'
        state: present
```

**Comment by melkypie** [comment]
The solution provided won't really work with multiple DC's as you can't really select the container_root so far down. Maybe adding something like `ignore_groups` option in eos_config_deploy_cvp where you could specify the groups for which you do not want containers?

**Comment by ClausHolbechArista** [comment]
Even for multi-dc topologies this can be solved by moving the TENANTS and SERVER groups out of the DC or FABRIC groups. So group of groups should always be put directly under the `all.children`.

```yaml
all:
  children:
    DC1:
      children:
        DC1_FABRIC:
          children:
            DC1_SPINES:
              hosts:
            DC1_LEAFS:
              children:

            DC1_L2LEAFS:
              children:
    DC2:
      children:
        DC2_FABRIC:
          children:
            DC2_SPINES:
              hosts:
            DC2_LEAFS:
              children:

            DC2_L2LEAFS:
              children:

    TENANTS_NETWORKS:
      children:
        DC1_LEAFS:
        DC1_L2LEAFS:
        DC2_LEAFS:
        DC2_L2LEAFS:

    DC1_SERVERS:
      children:
        DC1_LEAFS:
        DC1_L2LEAFS:
    DC2_SERVERS:
      children:
        DC2_LEAFS:
        DC2_L2LEAFS:

```
