### ISSUE TITLE
eos_cli_config_gen router bgp data revisit data model

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#696]
## Issue Type

- [ ] Bug Report
- [x] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

Need to revisit the data model for router bgp vrf definitions in eos_cli_config_gen.

The data model currently provides some abstraction for certain commands and needs to be refactored so that there is no abstraction.

Need to create a dedicated` address-family` section under router bgp vrf definition and support ipv4 and ipv6.
    - `neighbor a.b.c.d activate` should be define under correct address family.
    - `network` should be defined under the address family

The current implementation works, however, it abstracts some of the configurations and doesn't generate matching cli output as per below:

**Current data model:**

```
router_bgp:
  vrfs:
## Tenant_A ##
    TENANT_A_PROJECT01:
      networks:
        10.0.0.0/8:
        100.64.0.0/10:
      neighbors:
        10.2.3.4:
          address_family:
            - ipv4
```

**Desired data model**

```
router_bgp:
  vrfs:
## Tenant_A ##
    TENANT_A_PROJECT01:
    address_families:
      ipv4:   
        neighbors:
          10.2.3.4:
            activate: true
       networks:
          10.0.0.0/8:
          100.64.0.0/10:
```

**Generated:**

```
vrf TENANT_A_PROJECT01
      network 10.0.0.0/8
      network 100.64.0.0/10
      address-family ipv4
         neighbor 10.2.3.4 activate
```

**Desired:**

```
router bgp 65101
   vrf TENANT_A_PROJECT01
      !
      address-family ipv4
         neighbor 10.2.3.4 activate
         network 10.0.0.0/8
         network 100.64.0.0/10
```
