### ISSUE TITLE
extend server port profiles

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#70]
When defining a port-profile, allow a method to add all VLANs that present on the leaf switch.

for example:
```yaml
  VM_Servers:
    mode: trunk
    vlans: "all"
```

This "all" keyword would result in adding all VLANs defined on the switch -> accessible via the `leaf.vlans` key
