### ISSUE TITLE
refactor data model for router bfd

### ISSUE THREAD

**Issue by carlbuchmann** [aristanetworks/ansible-avd#713]
**Issue Type**

- [x] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Refactor router bfd to confirm to  data model standars

Current data model:

```yaml
bfd_multihop:
  interval: < rate in milliseconds >
  min_rx: < rate in milliseconds >
  multiplier: < 3-50 >
```

Proposed data model

```yaml
router_bfd:
  multihop:
    interval: < rate in milliseconds >
    min_rx: < rate in milliseconds >
    multiplier: < 3-50 >
```
