### ISSUE TITLE
When server interface is configured as LAG with no LACP, structured_config is inconsistent

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#723]
## Issue Type

- [x] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

With server port configuration use LAG with no LACP as shown below, structured_configuration is invalid

__Server port configuration__

```yaml
servers:
  My_server:
    rack: DC
    adapters:
      - server_ports: [ Eth3, Eth3 ]
        switch_ports: [ Ethernet1, Ethernet2 ]
        switches: [ xxx, xxx ]
        profile: ALL
        port_channel:
          description: PortChanne1
          mode: on
```

__Result__

```yaml
ethernet_interfaces:
  Ethernet2:
    peer: xxxx
    peer_interface: Eth3
    peer_type: server
    description: My_server
    type: switched
    shutdown: false
    mode: trunk
    vlans: 1-4094
    channel_group:
      id: 1
      mode: 'True'
    profile: ALL
```

And then, EOS configuration is:

```eos
interface Ethernet2
   description xxxx
   no shutdown
   channel-group 1 mode True
!
```

## Component Name

`arista.avd.eos_l3ls_evpn`

## Version

Tested with `devel` branch
