### ISSUE TITLE
Add mac security, ptp to l3_edge feature

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#731]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Similar to qos profile we will need to add under interface the option to have mac security profile or ptp enable.

```
  p2p_links:
      # Unique id per subnet_summary. Used to calculate ip addresses | Required with ip_pool
    - id: < integer - starting from 1 >
      # MAC sec Profile | Optional
      macsec_profile: < macsec_profile_name >
      # PTP | Optional
      ptp_enable: < p2p_profile_name >
```

**Describe alternatives you've considered**

**Additional context**
