### ISSUE TITLE
Resetting CVP via the arista.avd.eos_config_deploy_cvp role fails [devel]

### ISSUE THREAD

**Issue by perimore** [aristanetworks/ansible-avd#752]
## Issue Type

- [x] Bug Report

## Summary
A failure occurs when performing a reset using the playbook below for example using the latest devel version.

## Component Name
eos_config_deploy_cvp

## Steps to reproduce

```yaml
---
- name: Clenup CVP in default configuration
  hosts: cv_server
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  tasks:
    - name: run CVP provisioning
      import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'DC1_FABRIC'
        configlets_prefix: 'DC1-AVD'
        device_filter: 'DC1-'
        state: absent
```

### Expected results

The playbook to perform a reset in CVP of all devices.
```shell
$
```

### Actual results

Reset tasks are created but not executed. The below is output:

```shell
ASK [eos_config_deploy_cvp : Execute pending tasks on cv_server] **************************************************************************************************************************************************************************************************************************************************
fatal: [cv_server]: FAILED! => 
  msg: |-
    The task includes an option with an undefined variable. The error was: 'devices_result' is undefined
  
    The error appears to be in '/projects/ansible-avd/ansible_collections/arista/avd/roles/eos_config_deploy_cvp/tasks/absent.yml': line 20, column 3, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
    - name: "Execute pending tasks on {{ inventory_hostname }}"
      ^ here
    We could be wrong, but this one looks like it might be an issue with
    missing quotes. Always quote template expression brackets when they
    start a value. For instance:
  
        with_items:
          - {{ foo }}
  
    Should be written as:
  
        with_items:
          - "{{ foo }}"
```
