### ISSUE TITLE
Allow leaf devices to not be connected to all spines

### ISSUE THREAD

**Issue by perimore** [aristanetworks/ansible-avd#784]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Leaf devices might not be connected to all spine devices in all cases. One such case is where a customer is sharing a spine with more than two devices between the DC and campus. DC devices will be connected to all spines but campus devices might only be connected to two due to limited uplink capacity or requirement. 

![image](https://user-images.githubusercontent.com/3357565/110632588-b4eac500-819f-11eb-88ba-35eb9c088a02.png)

Running a playbook using variables that describe such a design fails. Below the default l3leaf variables are overridden in the leaf:

```
# Spine Switches
spine:
  platform: vEOS-LAB
  bgp_as: 65001
  # defines the range of acceptable remote ASNs from leaf switches
  leaf_as_range: 65101-65132
  nodes:
    DC1-SPINE01:
      id: 1
      mgmt_ip: 10.73.3.1/16
    DC1-SPINE02:
      id: 2
      mgmt_ip: 10.73.3.2/16

# Leaf switch groups
# A maximum of two nodes can form a leaf group
# When two nodes are in a leaf group this will automatically form mlag pair

l3leaf:
  defaults:
    # virtual router mac for VNIs assigned to Leaf switches
    # format: xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: vEOS-LAB
    bgp_as: 65100
    spines: [DC1-SPINE01, DC1-SPINE02]
    uplink_to_spine_interfaces: [Ethernet1, Ethernet2]
    mlag_interfaces: [Ethernet3, Ethernet4]
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      nodes:
        DC1-LEAF1A:
          id: 1
          mgmt_ip: 10.73.3.3/16
          spines: [DC1-SPINE01]
          spine_interfaces: [Ethernet1]
          uplink_to_spine_interfaces: [Ethernet1]
        DC1-LEAF1B:
          id: 2
          mgmt_ip: 10.73.3.4/16
          spines: [DC1-SPINE01]
          spine_interfaces: [Ethernet2]
          uplink_to_spine_interfaces: [Ethernet1]
```

But this causes an iteration error:

```
TASK [eos_l3ls_evpn : Generate device configuration in structured format (yaml).]
fatal: [DC1-SPINE02 -> localhost]: FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: list object has no element 1'
fatal: [DC1-LEAF1B -> localhost]: FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: list object has no element 1'
fatal: [DC1-LEAF1A -> localhost]: FAILED! => changed=false 
  msg: 'AnsibleUndefinedVariable: list object has no element 1'
ok: [DC1-SPINE01 -> localhost]
ok: [DC1-LEAF2A -> localhost]
```

**Describe the solution you'd like**

We would like to be able to override the leaf defaults that relate to the spine uplinks and allow there to be less uplinks than the number of spines. One possible solution to maybe avoid having to match spine names in the iteration, etc is to skip creating the interface config on the spine and leaf the variable is null, i.e.:

```
l3leaf:
  defaults:
    # virtual router mac for VNIs assigned to Leaf switches
    # format: xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: vEOS-LAB
    bgp_as: 65100
    spines: [DC1-SPINE01, DC1-SPINE02]
    uplink_to_spine_interfaces: [Ethernet1, Ethernet2]
    mlag_interfaces: [Ethernet3, Ethernet4]
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      nodes:
        DC1-LEAF1A:
          id: 1
          mgmt_ip: 10.73.3.3/16
          spines: [DC1-SPINE01, null]
          spine_interfaces: [Ethernet1, null]
          uplink_to_spine_interfaces: [Ethernet1, null]
        DC1-LEAF1B:
          id: 2
          mgmt_ip: 10.73.3.4/16
          spines: [DC1-SPINE01, null]
          spine_interfaces: [Ethernet2, null]
          uplink_to_spine_interfaces: [Ethernet1, null]
```

**Describe alternatives you've considered**

No real alternatives as the customer wants the particular design. They would be happy with omitting the uplinks in the override or filling in with null as above.

**Comment by ClausHolbechArista** [comment]
@perimore 
n PR #932 we are refactoring a lot of the logic, and I believe it should also address this ask. Feel free to try it out before we merge so we can adjust any missing bits. If you write only the the hostnames of the relevant spines in the `spines` variable on your leafs it should work. 
Let me know how it goes. (Please tag me)

Example with your data:
```
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      nodes:
        DC1-LEAF1A:
          id: 1
          mgmt_ip: 10.73.3.3/16
          spines: [DC1-SPINE01]
          spine_interfaces: [Ethernet1]
          uplink_to_spine_interfaces: [Ethernet1]
        DC1-LEAF1B:
          id: 2
          mgmt_ip: 10.73.3.4/16
          spines: [DC1-SPINE01]
          spine_interfaces: [Ethernet2]
          uplink_to_spine_interfaces: [Ethernet1]
```
