### ISSUE TITLE
BGP: add support for IPv6 unicast AF network statement

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#802]
**Issue Type**

- [x] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

As of now it is not possible to render the BGP IPv6 unicast AF `network` statement to announce IPv6 networks.

**Describe the solution you'd like**

Extend the BGP data model in a way which mimics the IPv4 unicast AF implementation.

```yml
router_bgp:
  ...
  address_family_ipv4:
    networks:
      < prefix_ipv4 >:
        route_map: < route_map_name >
    ...
  address_family_ipv6:
    networks:
      < prefix_ipv6 >:
        route_map: < route_map_name >
    ...
```

This will render the EOS configuration:
```
router bgp 65000
   !
   address-family ipv4
      network 10.0.0.0/8
      network 172.16.0.0/12
   !
   address-family ipv6
      network 2001:db8::/32
```
**Describe alternatives you've considered**

There is no alternative ;)

**Additional context**

PR in flight
