### ISSUE TITLE
aaa: support authentication for enable mode

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#804]
**Issue Type**

- [x] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Add support to specify the use of `enable` by a AAA group

**Describe the solution you'd like**

```yaml
aaa_authentication:
  login:
    default: < group group_name | local | none > < group group_name | local | none >
    serial_console: < group group_name | local | none > < group group_name | local | none >
  enable:
    default: < group group_name >
  ...
```

**Describe alternatives you've considered**

Not considered, as all AAA stuff is done via this template

**Additional context**

PR in flight
