### ISSUE TITLE
Enable task execution in cvp_configlet_upload

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#834]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Sometimes, it would be useful to support automatic task execution for lab purpose as it is already defined in `eos_config_deploy_cvp`

**Describe the solution you'd like**

```yaml
tasks:
  - name: upload cvp configlets
    import_role:
        name: arista.avd.cvp_configlet_upload
    vars:
      configlet_directory: 'configlets/'
      file_extension: 'txt'
      configlets_cvp_prefix: 'DC1-AVD'
      execute_tasks: false
```
