### ISSUE TITLE
eos_designs: l3edge: add variable for vrf

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#836]
**Issue Type**

- [x] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Describe the solution you'd like**

eos_designs/l3edge template allows to configure L3 P2P links anywhere in the fabric to any device.
We would need to be able to move such a L3 P2P interface into a certain VRF.
The result should look like this:

```yaml
  Ethernet5:
    peer: core-01
    peer_interface: gi1
    peer_type: other
    description: P2P_LINK_TO_core-01_gi1
    type: routed
    shutdown: false
    mtu: 9000
    ip_address: 10.130.8.46/31
    vrf: Tenant_DC_OUTSIDE
 ```

**Describe alternatives you've considered**

I could set it via customer config in host_vars files, but with this the config is at different places and might lead
to missunderstanding or even loss of information for the users.

custom_structured_configuration_ethernet_interfaces:

```yaml
  Ethernet5:
    vrf: Tenant_DC_OUTSIDE
```

**Additional context**

This might already do what I am watching for:

\avd\roles\eos_designs\templates\l3_edge\switch-l3-edge-p2p-interfaces.j2
{%     if p2p_interface.vrf is arista.avd.defined %}
    vrf: {{ p2p_interface.vrf }}
{%     endif %}

\avd\roles\eos_designs\templates\l3_edge\logic\switch-l3-edge.j2
{%             set p2p_interface.vrf = p2p_link.vrf | arista.avd.default(
                                              p2p_profile.vrf) %}
