### ISSUE TITLE
Configurable MLAG L3 peering and MLAG peer vlan id's

### ISSUE THREAD

**Issue by melkypie** [aristanetworks/ansible-avd#841]
**Issue Type**

- [X] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Allow us to change the vlans for MLAG L3 peering and MLAG peer. Currently they are hard coded as 4093 and 4094. Using configurable values will allow people with existing VXLAN setups to migrate more easily.

**Describe the solution you'd like**

Add new `mlag_l3_peer_vlan_id` and `mlag_peer_vlan_id` options to `eos_designs`

**Describe alternatives you've considered**

Editing the repository myself and keeping a local copy

**Additional context**

**Comment by carlbuchmann** [comment]
@melkypie Thank you for submitting this issue! If you plan on submitting PR for this, let's discuss in this issue the desired data model before you start working on it!

**Comment by melkypie** [comment]
I would suggest that it would be best if we could adjust the current `mlag_ips` to 
```yaml 
mlag:
  leaf_peer_l3:
    ip: x.x.x.x/24
    vlan_id: 4093
  mlag_peer:
    ip: x.x.x.x/24
    vlan_id: 4094
```
However this would introduce a breaking data model change. If that is acceptable I can get a PR up straight away since most of the work I already have done I would just need to adjust the variable names around.

If that would rather not be done, maybe leave mlag_ips as is and add a new mlag data model excluding the ips and leaving just the vlan_ids.

**Comment by ClausHolbechArista** [comment]
For vlan numbers we should add this under the `l3leaf` data model so user can define it under `defaults` or under each `node-group`. 
Ex.
```yaml
l3leaf:
  defaults:
    mlag_peer_vlan: < 0-4094 | default -> 4094 >
    mlag_peer_l3_vlan: < 0-4094 | default -> 4093 >
```
Similar for `l2leaf`.

For the IP part, we should hold back a bit and implement this using IPAM integration.
Until then, you can override the IP in structured_configuration by setting
```yaml
custom_structured_configuration_vlan_interfaces:
  Vlan4094:
    ip_address: x.x.x.x/xx
```
The `custom_structured_configuration` settings will be merged on top of the structured_configuration generated by `eos_designs`.

@melkypie Will this solve the ask until we get IPAM support?
