### ISSUE TITLE
Option to set a specific MLAG port-channel id

### ISSUE THREAD

**Issue by melkypie** [aristanetworks/ansible-avd#848]
**Issue Type**

- [ ] Template enhancement
- [X] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Rather than using the first MLAG Ethernet interface's port to define Port-Channel id, allow us to set a specific one.

**Describe the solution you'd like**

```yaml
mlag:
  port_channel_id: 1111
```

**Describe alternatives you've considered**

Adding it myself and using the role locally

**Additional context**

**Comment by ClausHolbechArista** [comment]
@melkypie 
Best practice would be to match port-channel ID and mlag ID. I suppose you wish to change both of them to the same custom number.
For servers the data model is:
```yaml
    port_channel:
      description: < port_channel_description >
      mode: < active | passive | on >
```
So I would suggest adding an optional `id` field under this and use that for both mlag and port-channel.
