### ISSUE TITLE
IP extcommunity-list to support regex

### ISSUE THREAD

**Issue by onurgashi** [aristanetworks/ansible-avd#849]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

I would like to be able to use regex in extcommunity_lists.

```(config)#ip extcommunity-list ?
  WORD    Community list name
  regexp  Add an expanded community-list entry
```

We only suppport 

```
ip_extcommunity_lists:
  < community_list_name_1 >:
    - type: < permit | deny >
      extcommunities: "< communities as string >"
  < community_list_name_2 >:
    - type: < permit | deny >
      extcommunities: "< communities as string >"
```

So something like this won't work:
ip extcommunity-list regexp EXAMPLE permit RT:65000:[1-9][0-9]{4}_

**Describe the solution you'd like**

This could give a clue on the data model.

```
ip_extcommunity_lists:
         regex:
           < community_list_name_1 >:
               - type: < permit | deny >
                extcommunities: "< communities as string >"
```

**Describe alternatives you've considered**

**Additional context**
