### ISSUE TITLE
Add support for L3 sub-interfaces inside VRFs

### ISSUE THREAD

**Issue by mpergament** [aristanetworks/ansible-avd#857]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [x] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

As of now L3 sub-interfaces cannot be specified under:
```
    Tenant_A_WAN_Zone:
        vrf_vni: 14
        l3_interfaces:
          - interfaces: [ Ethernet7, Ethernet7 ]
            ip_addresses: [10.10.10.10/24, 10.10.20.20/24]
            nodes: [DC1-BL1A, DC1-BL1B]
            mtu: 9000
            description: "test"
```

**Describe the solution you'd like**

Enhance data model to support L3 sub-interfaces
