### ISSUE TITLE
Peer group support in vrf context

### ISSUE THREAD

**Issue by daanvdsanden** [aristanetworks/ansible-avd#874]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**
I would like to use peer groups for BGP peerings in a VRF. 

**Describe the solution you'd like**
An update to the tenant vrf model in `eos_designs`:
```yaml
tenants:
  < tenant_a >:
    vrfs:
      < tenant_a_vrf_1 >:
        bgp_peer_groups:
          < peer_group_name >:
            remote_as: < remote ASN >
            description: < description >
            password: < encrypted password >
            send_community: < standard | extended | large | all >
            next_hop_self: < true | false >
            maximum_routes: < 0-4294967294 >
            default_originate:
              always: < true | false >
            update_source: < interface >
            bfd: < true | false >
            address_families:
              <address_family>:
                activate: < true | false >
            ebgp_multihop: < 1-255 >
            # Nodes is required to restrict configuration of BGP peer groups to certain nodes in the network.
            nodes: [ < node_1 >, < node_2> ]
            # Next hop settings can be either ipv4 or ipv6 for one neighbor, this will be applied by a uniquely generated route-map per neighbor.
            # Next hop takes precedence over route_map_out.
            set_ipv4_next_hop: < IPv4_address >
            set_ipv6_next_hop: < IPv6_address >
            route_map_out: < route-map name >
            route_map_in: < route-map name >
            local_as: < local BGP ASN >
        bgp_peers:
          < neighbor >:
            peer_group: < peer_group_name >
```

**Describe alternatives you've considered**

At the moment I'm using per neighbor configuration. But updating multiple sessions that must have the same settings takes a long time and is error prone. This also makes the VRF tenant yaml more readable.

**Additional context**

~~Add any other context or screenshots about the feature request here.~~
