### ISSUE TITLE
eos_designs: l3ls: port_profiles should support referencing a base port_profile

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#875]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

We have multiple server systems connecting to a l3ls fabric where all of them have a common base configuration inside the `port_profiles`.

As I think that copied code is bad code, It would be super nice to have a way to reference a common, lets call it base profile, which is in turn just another port profile. Or in other works, a port_profile should support having a parent port_profile, so common settings can be inherited.

**Describe the solution you'd like**

Given the current YML definition of:

```yml
# Optional profiles to apply on endpoints facing interfaces
# Each profile can support all or some of the following keys according to your own needs.
# Keys are the same used under  endpoints adapters.
# Keys defined under endpoints Adapters take precedence.
port_profiles:
  < port_profile_1 >:
    speed: < interface_speed | forced interface_speed | auto interface_speed >
    mode: < access | dot1q-tunnel | trunk >
    l2_mtu: < l2_mtu - if defined this profile should only be used for platforms supporting the "l2 mtu" CLI >
    native_vlan: <native vlan number>
    vlans: < vlans as string >
    spanning_tree_portfast: < edge | network >
    spanning_tree_bpdufilter: < true | false >
    spanning_tree_bpduguard: < true | false >
    flowcontrol:
      received: < received | send | on >
    qos_profile: < qos_profile_name >
    ptp:
      enable: < true | false >
    storm_control:
      all:
        level: < Configure maximum storm-control level >
        unit: < percent | pps > | Optional var and is hardware dependant - default is percent)
      broadcast:
        level: < Configure maximum storm-control level >
        unit: < percent | pps > | Optional var and is hardware dependant - default is percent)
      multicast:
        level: < Configure maximum storm-control level >
        unit: < percent | pps > | Optional var and is hardware dependant - default is percent)
      unknown_unicast:
        level: < Configure maximum storm-control level >
        unit: < percent | pps > | Optional var and is hardware dependant - default is percent)
    port_channel:
      description: < port_channel_description >
      mode: < active | passive | on >
      lacp_fallback:
        mode: < static > | Currently only static mode is supported
        timeout: < timeout in seconds > | Optional - default is 90 seconds
```

My idea would be to get the possibility to write:

```yml
port_profiles:
   base_profile_1:
    spanning_tree_bpdufilter: false
    spanning_tree_bpduguard: true
    spanning_tree_portfast: edge
    storm_control:
      broadcast:
        level: 1
        unit: percent
      multicast:
        level: 1
        unit: percent
      unknown-unicast:
        level: 1
        unit: percent

  Tenant_FOO_ESX_HOST:
    parent_profile: base_profile_1
    mode: trunk
    native_vlan: "1021"
    vlans: "1002-1009"

  Tenant_BAR_ESX_HOST:
    parent_profile: base_profile_1
    mode: trunk
    native_vlan: "1021"
    vlans: "1014-1020"
```

This would significantly reduce the amount of copied YML statememnts and places where a human can add unwanted errors.

**Describe alternatives you've considered**

None found

**Additional context**
