### ISSUE TITLE
Option to define custom daemons

### ISSUE THREAD

**Issue by melkypie** [aristanetworks/ansible-avd#884]
**Issue Type**

- [X] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Add the option to define custom daemons other than TerminAttr.

**Describe the solution you'd like**

```yaml
daemons:
  ocprometheus:
    exec: "/usr/bin/ocprometheus --config /usr/bin/ocprometheus.yml"
  daemon2:
    exec: "/usr/bin/daemon2"
```

**Describe alternatives you've considered**

There are none other than adding it myself.

**Additional context**
