### ISSUE TITLE
CLI Config GEN - Traffic Policy engine fails to render some keys

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-avd#886]
## Issue Type

- [x] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

Traffic policy fails to render configuration when `dst_field`, `src_port` and `dst_port` are used.

Findings: `dst_field`, `src_port` and `dst_port` are not rendered correctly due to JINJA syntax error.

## Component Name

`arista.avd.eos_cli_config_gen`

## Steps to reproduce

```yaml
traffic_policies:
  policies:
    TEST:
      matches:
        TERM_1:
          type: ipv4
          protocols:
            udp:
              src_field: "GP_PORT"
        TERM_2:
          type: ipv4
          protocols:
            udp:
              dst_field: "GP_PORT"
```
