### ISSUE TITLE
PBR extension for eos_cli_config_gen

### ISSUE THREAD

**Issue by florianschendel** [aristanetworks/ansible-avd#890]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**
Yes, its currently not possible to use PBR setup with Ansible AVD

**Describe the solution you'd like**
```YML
vlan_interfaces:
  < Vlan_id_1 >:
    service_policy:
      pbr:
        input: < policy-map name >

class_maps:
  pbr:
    < class-map name >:
      ip:
        access_group: < Standard access-list name >

policy_maps:
  pbr:
    < policy-map name >:
      classes:
        < class name >:
          set:
            nexthop: < IPv4_address | IPv6_address >
              recursive: < true | false >
```

```
class-map type pbr match-any PBR-INET-SDWAN-BREAKOUT_EXCLUDE
 10 match ip access-group PBR-INET-SDWAN-BREAKOUT_EXCLUDE
class-map type pbr match-any PBR-INET-SDWAN-BREAKOUT
 10 match ip access-group PBR-INET-SDWAN-BREAKOUT

policy-map type pbr PBR-INET-SDWAN-BREAKOUT
 10 class PBR-INET-SDWAN-BREAKOUT_EXCLUDE
 20 class PBR-INET-SDWAN-BREAKOUT
  set nexthop recursive 192.168.4.2

interface Vlan3012
 service-policy type pbr input PBR-INET-SDWAN-BREAKOUT
```

**Describe alternatives you've considered**
Possible via custom_templates but its only a woraround for us.

@carlbuchmann @titom73 @ClausHolbechArista 
If you can agree to the above data model we can submit as pull requests.

**Comment by c-po** [comment]
+1

**Comment by ClausHolbechArista** [comment]
This part is not valid YAML:
```yaml
           nexthop: < IPv4_address | IPv6_address >
              recursive: < true | false >
```
So I suggest alternative:
```yaml
           nexthop:
              ip_address: < IPv4_address | IPv6_address >
              recursive: < true | false >
```
Other than that +1 from me.
