### ISSUE TITLE
Support for MMU queue profile

### ISSUE THREAD

**Issue by Shinz0n** [aristanetworks/ansible-avd#893]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

As we do have several types of end systems attached to our fabric we need different MMU queue profiles for the corresponding switch port(s) as well as AVD port profiles.

**Describe the solution you'd like**

Allow configuring MMU queue profile (similar to port_profiles) and make it accessible within the port_profiles and servers model of eos_designs role.

```YML
mmu_queue_profiles:
  HIGH:
    queues:
      0:
        - direction: egress
          type: unicast
          reserved: 0
          threshold: 2  
      1:
        - direction: egress
          type: unicast
          reserved: 0
          threshold: 2  
      3:
        - direction: egress
          type: unicast
          reserved: 13312
          threshold: 2  
```

```YML
port_profiles:
  < port_profile_1 >:
    queue_profile: HIGH

```
or

```YML
servers:
  server01:
    rack: RackB
    adapters:
      # Single homed interface from E0 toward DC1-LEAF1A_Eth5
      - endpoint_ports: [ E0 ]
        switch_ports: [ Ethernet5 ]
        switches: [ DC1-LEAF1A ]
        queue_profile: HIGH
```

**Describe alternatives you've considered**

Custom Jinja template or static CVP configlet.

**Additional context**

~Add any other context or screenshots about the feature request here.~

**Comment by ClausHolbechArista** [comment]
@Shinz0n @mpergament 
Since this is very platform specific and potentially with a never ending stream of new "nerd knobs" we would like to solve this is a different way.
We have discussed internally to add something like this to give a high degree of flexibiliy while still abstracting the parts that matter. Let us know what you think.
```yaml
servers:
  server01:
    rack: RackB
    adapters:
      # Single homed interface from E0 toward DC1-LEAF1A_Eth5
      - endpoint_ports: [ E0 ]
        switch_ports: [ Ethernet5 ]
        switches: [ DC1-LEAF1A ]
        # EOS CLI rendered directly on the ethernet interface in the final EOS configuration
        raw_eos_cli: |
          < multiline eos cli >
        # custom structured config added under ethernet_interfaces.<interface> for eos_cli_config_gen
        structured_config: < dictionary >
        port_channel:
          # EOS CLI rendered directly on the port-channel interface in the final EOS configuration
          raw_eos_cli: |
            < multiline eos cli >
          # custom structured config added under port_channel_interfaces.<interface> for eos_cli_config_gen
          structured_config: < dictionary >
```
We would add similar knobs to other sections in the data-model like `tenants.<tenant>.vrfs.<vrf.>.bgp_peers.<bgp_peer>` and `tenants.<tenant>.vrfs.<vrf.>.bgp_peergroups.<bgp_peergroup>` to help with special cases while keeping the `eos_designs` abstraction.
