### ISSUE TITLE
[Feature] Add opportunity to connect border leafs to super spine in 5 clos design

### ISSUE THREAD

**Issue by inetman28** [aristanetworks/ansible-avd#910]
**Issue Type**

- [x] Role enhancement

**Is your feature request related to a problem? Please describe.**

In this time there aren't feature to connect border leaf switches to super spine in 5clos design. We could do it only through l3_edge & dci extension. 

**Describe the solution you'd like**

I would like to have opportunity to connect border leaf switches right to super spine inside 5 clos design. 

**Describe alternatives you've considered**

Now, I created some fake pod for border_leafs with empty spine session like:
```
# blank for edge_leafs
spine:
  bgp_as: 777
  nodes: []
```

and describe two switches with empty spines:
```
# In DC1 we define all variables on specific node / node_group
l3leaf:
  defaults:
    bgp_as: 65555
    virtual_router_mac_address: 00:1c:73:00:dc:01
  node_groups:
    # EDGE LEAF SWITCHES INSIDE DC
    EDGE_LEAFS:
      platform: vEOS-LAB
      spines: []
      uplink_to_spine_interfaces: []
      bgp_as: 65399
      mlag_interfaces: [ Ethernet5, Ethernet6 ]
      mlag_dual_primary_detection: true
      spanning_tree_mode: mstp
      spanning_tree_priority: 4096
      evpn_role: client
      evpn_route_servers: [ DC1-SUPER-SPINE1, DC1-SUPER-SPINE2 ]
      filter:
        tenants: [Tenant_A]
        tags: [zone4]
      nodes:
        DC1-ESW1:
          id: 1
          mgmt_ip: 10.10.10.241/24
          mac_address: '0c:4d:cb:fb:6b:00'
          spine_interfaces: []
        DC1-ESW2:
          id: 2
          mgmt_ip: 10.10.10.242/24
          mac_address: '0c:4d:cb:15:f3:00'
          spine_interfaces: []
```

After that I use section named l3_edge to connect border leafs to super spines:

```
l3_edge:
  p2p_links_ip_pools:
    #pool-leaf: 11.1.0.0/24
    #pool-spine: 11.1.1.0/24
    #pool-super-spine: 11.1.2.0/24
    pool_dc1_esw1_dc1_sspine1: 10.1.2.0/31
    pool_dc1_esw1_dc1_sspine2: 10.1.2.2/31
    pool_dc1_esw2_dc1_sspine1: 10.1.2.4/31
    pool_dc1_esw2_dc1_sspine2: 10.1.2.6/31
  p2p_links_profiles:
    generic-profile:
      mtu: 1499
      bfd: false
      ptp_enable: true
  p2p_links:
    - nodes: [ DC1-ESW1, DC1-SUPER-SPINE1 ]
      id: 1
      interfaces: [ Ethernet9, Ethernet9 ]
      as: [ 65399, 65100 ]
      ip_pool: pool_dc1_esw1_dc1_sspine1
      profile: generic-profile
      include_in_underlay_protocol: true
      #macsec_profile: MACSEC_PROFILE
    - nodes: [ DC1-ESW1, DC1-SUPER-SPINE2 ]
      id: 1
      interfaces: [ Ethernet10, Ethernet10 ]
      as: [ 65399, 65100 ]
      ip_pool: pool_dc1_esw1_dc1_sspine2
      profile: generic-profile
      include_in_underlay_protocol: true
      #macsec_profile: MACSEC_PROFILE
    - nodes: [ DC1-ESW2, DC1-SUPER-SPINE1 ]
      id: 1
      interfaces: [ Ethernet10, Ethernet10 ]
      as: [ 65399, 65100 ]
      ip_pool: pool_dc1_esw2_dc1_sspine1
      profile: generic-profile
      include_in_underlay_protocol: true
      #macsec_profile: MACSEC_PROFILE
    - nodes: [ DC1-ESW2, DC1-SUPER-SPINE2 ]
      id: 1
      interfaces: [ Ethernet9, Ethernet9 ]
      as: [ 65399, 65100 ]
      ip_pool: pool_dc1_esw2_dc1_sspine2
      profile: generic-profile
      include_in_underlay_protocol: true
      #macsec_profile: MACSEC_PROFILE
```

**Additional context**

I think this feature is important in 5clos designs because now we haven't option to connect border leafs to superspine directly like similar l3_leafs. 
in this design there aren't proper path for north to south. Every traffic from another DC or from internet will go through this pod (where border leafs are connected) and utilise links for this pods. This is not correct design in my opinion.
