### ISSUE TITLE
BGP: missing address-family IPv6 prefix-list

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#923]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

It is not possible to declare an IPv6 prefix-list for a BGP neighbor in `eos_cli_config_gen`

**Describe the solution you'd like**

Keep identical syntax to IPv4 feature

```yml
  address_family_ipv6:
    peer_groups:
      < peer_group_name >:
        activate: < true | false >
        prefix_list_in: < prefix_list_name >
        prefix_list_out: < prefix_list_name >
      < peer_group_name >:
        activate: true
    neighbors:
      < neighbor_ip_address>:
        prefix_list_in: < prefix_list_name >
        prefix_list_out: < prefix_list_name >
        activate: < true | false >
```

**Describe alternatives you've considered**

None applicable

**Additional context**

PR in flight
