### ISSUE TITLE
eos_config_deploy_cvp errors if section without children is present in the inventory

### ISSUE THREAD

**Issue by guillaumeVilar** [aristanetworks/ansible-avd#939]
## Issue Type

- [x] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary
If in the inventory, there is no children under a section, the role `eos_config_deploy_cvp` crash with a `AttributeError: 'NoneType' object has no attribute 'items'` error message. 

## Component Name
`arista.avd.eos_config_deploy_cvp`

## Steps to reproduce

Playbook: 
```yaml
- hosts: cv_server
  tasks:
    - name: deploy configuration via CVP
      import_role:
         name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'DC1_FABRIC'
        configlets_prefix: 'DC1-AVD'
        device_filter: 'DC1'
        state: present
        execute_tasks: false
```
Inventory: 
```yaml
    # DC1_Fabric - EVPN Fabric running in home lab
    DC1:
      children:
        DC1_FABRIC:
          children:
            DC1_SPINES:
              hosts:
                DC1-SPINE1:
                  ansible_host: 10.0.0.1
                DC1-SPINE2:
                  ansible_host: 10.0.0.2
            DC1_L3LEAFS:
              children:
                DC1_LEAF1:
                  hosts:
                    DC1-LEAF1A:
                      ansible_host: 10.0.0.3
                    DC1-LEAF1B:
                      ansible_host: 10.0.0.4
            DC1_L2LEAFS:
              children:
```

Here the `DC1_L2LEAFS` var has no children. 

The result of running the role is: 
```
TASK [arista.avd.eos_config_deploy_cvp : generate intented variables] ***************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'items'
fatal: [cv_server]: FAILED! => changed=false 
  module_stderr: |-
    Traceback (most recent call last):
[...]
      File "/var/folders/hd/3g0v07bx6vd9n3tn3ztkc5900000gn/T/ansible_arista.avd.inventory_to_container_payload_9d7az18q/ansible_arista.avd.inventory_to_container_payload.zip/ansible_collections/arista/avd/plugins/modules/inventory_to_container.py", line 332, in get_devices
    AttributeError: 'NoneType' object has no attribute 'items'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
```

Commenting the `DC1_L2LEAFS` section in the inventory solves the issue. 

### Expected results
The role should ignore the empty section in the inventory. 

### Actual results
Error in the role execution.
