### ISSUE TITLE
evpn-overlay peering spine-spine dci no more rendered with commit #932

### ISSUE THREAD

**Issue by kmueller68** [aristanetworks/ansible-avd#943]
## Issue Type

- [x] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

As soon as we use avd devel including commit #932 we are loosing the following cli configuration on our spine dci:

```
router bgp 65101
   <snip>
   neighbor 10.0.254.129 peer group EVPN-OVERLAY-PEERS
   neighbor 10.0.254.129 remote-as 65201
   neighbor 10.0.254.129 description spine-2a7-01.DC.MU
   neighbor 10.0.254.130 peer group EVPN-OVERLAY-PEERS
   neighbor 10.0.254.130 remote-as 65201
   neighbor 10.0.254.130 description spine-2a7-02.DC.MU
```

When I revert to commit #936 right before #932 the cli lines are generated again.

Thie config should be related to the following seeting in the fabric.yml:

```
  nodes:
    spine-1a7-01.DC.MU:
      id: 1
      evpn_route_servers: [spine-2a7-01.DC.MU, spine-2a7-02.DC.MU]
```

## Component Name
eos_designs

## Steps to reproduce

```yaml

```

### Expected results

```shell
$
```

### Actual results

```shell

```
