### ISSUE TITLE
Add support for ip icmp

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#945]
**Issue Type**

- [X] Template enhancement
- [ ] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Introduce Template & Data Model for:
 
ip icmp rate-limit-unreachable
ip icmp redirect
ip icmp source-interface

**Describe the solution you'd like**

```yaml
ip_icmp:
  rate_limit_unreachable: < true | false >
  redirect: <true | false >
  source_interface:
    name: <interface_name >
    vrf: < vrf_name >
```

**Describe alternatives you've considered**

Not many since this follows the current standard.

**Additional context**

N/A
