### ISSUE TITLE
extra whitespace for default vrf

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#949]
## Issue Type

- [ ] Bug Report
- [X] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

Not really a huge issue, but an extra space is inserted in various EOS configuration generated due to the way default vrf (or lack of a vrf in the input) is being output in a template.

## Component Name

eos_cli_config_gen

## Steps to reproduce

Input:

```yaml
ntp_servers:
  local_interface:
    vrf: default # Same output if I comment out this line
    interface Loopback0
nodes:
  - 10.10.10.1
  - 10.10.10.2
```

### Expected results

```eos
ntp local-interface Loopback0
ntp server 10.10.10.1 prefer
ntp server 10.10.10.2
```

### Actual results

```eos
ntp local-interface  Loopback0
ntp server  10.10.10.1 prefer
ntp server  10.10.10.2
```

Again not the end of the world, just two space in front of Loopback and 2 spaces in front of the server IPs.
