### ISSUE TITLE
management_interfaces.gateway not documented & required for doc template, but not config template

### ISSUE THREAD

**Issue by ryanmerolle** [aristanetworks/ansible-avd#952]
## Issue Type

- [ ] Bug Report
- [x] EOS Configuration rendering error
- [X] Documentation Issue Report

## Summary

eos_cli_config_gen missing a required management_interfaces.gateway attribute for documentation generation.

Proposed Fixes:

- The doc template needs to match the config template with regards to attributes required.
- The module README should list the gateway attribute in the data model as it is missing.

## Component Name

eos_cli_config_gen

## Steps to reproduce

```yaml
management_interfaces:
  Management1 :
    description: test
    vrf: MGMT
    ip_address: 10.10.10.100/24
```

### Expected results

Configuration generated & markdown doc generated.

### Actual results

Configuration is generated, but markdown doc task complains about a dict_bject has not defined attribute named gateway.

**Comment by f7t-mp** [comment]
**Role test contains gateway entry:**
[ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/management-interfaces.yml](ansible_collections/arista/avd/molecule/eos_cli_config_gen/inventory/host_vars/management-interfaces.yml)
```
### Management Interfaces ###
management_interfaces:
  Management1:
    description: oob_management
    vrf: MGMT
    ip_address: 10.73.255.122/24
    gateway: 10.73.255.2
    type: oob
  Vlan123:
    description: inband_management
    vrf: default
    ip_address: 10.73.0.123/24
    gateway: 10.73.0.1
    type: inband
```
**Documentation template references gateway:**
[ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/management-interfaces.j2](ansible_collections/arista/avd/roles/eos_cli_config_gen/templates/documentation/management-interfaces.j2)
```
ipv4
| {{ management_interfaces[management_interface].ip_address }} | {{ management_interfaces[management_interface].gateway }} |

vs ipv6

| {%- if management_interfaces[management_interface].ipv6_address is defined and management_interfaces[management_interface].ipv6_address is not none %} {{ management_interfaces[management_interface].ipv6_address }} {% else %} - {% endif %} | {%- if management_interfaces[management_interface].ipv6_gateway is defined and management_interfaces[management_interface].ipv6_gateway is not none %} {{ management_interfaces[management_interface].ipv6_gateway }} {% else %} - {% endif -%} |

```

**Role documentation doesn't list 'gateway' as a variable:**
[https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md#management-interfaces](https://github.com/aristanetworks/ansible-avd/blob/devel/ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md#management-interfaces)
```
management_interfaces:
  < Management_interface_1 >:
    description: < description >
    shutdown: < true | false >
    vrf: < vrf_name >
    ip_address: < IPv4_address/Mask >
    ipv6_enable: < true | false >
    ipv6_address: < IPv6_address/Mask >
    type: < oob | inband | default -> oob >

```
