### ISSUE TITLE
BGP: missing support for default-originate on peer_group neighbor 

### ISSUE THREAD

**Issue by SomaliRaven** [aristanetworks/ansible-avd#964]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

It is not possible to configure a default-originate on peer group neighbors as it is for single neighbors

**Describe the solution you'd like**

Implement default-originate feature the same way for peer_group as for neighbor.

```yaml
  address_family_ipv4:
    networks:
      < prefix_ipv4 >:
        route_map: < route_map_name >
    peer_groups:
      < peer_group_name >:
        route_map_in: < route_map_name >
        route_map_out: < route_map_name >
        activate: < true | false >
      < peer_group_name >:
        activate: < true | false >
        default_originate:
          always: < true | false >
          route_map: < route_map_name >
        prefix_list_in: < prefix_list_name >
        prefix_list_out: < prefix_list_name >
    neighbors:
      < neighbor_ip_address>:
        route_map_in: < route_map_name >
        route_map_out: < route_map_name >
        activate: < true | false >
        prefix_list_in: < prefix_list_name >
        prefix_list_out: < prefix_list_name >
      < neighbor_ip_address>:
        activate: < true | false >
        default_originate:
          always: < true | false >
          route_map: < route_map_name >
```

**Describe alternatives you've considered**

At the moment I'm using per neighbor configuration. But updating multiple sessions that must have the same settings takes a long time and is error prone.

**Additional context**
