### ISSUE TITLE
ethernet-inteface dot1q-tunnel mode is missing access vlan

### ISSUE THREAD

**Issue by jalmargyyk** [aristanetworks/ansible-avd#968]
## Issue Type

- [x] Bug Report

## Summary
When configuring ethernet interface to mode dot1q-tunnel, the S-VLAN (access vlan) is not added to the configuration. Using arista.avd version 2.1.1.

## Component Name
eos_cli_config_gen/templates/eos/ethernet-interfaces.j2

## Steps to reproduce

Add configuration to host_vars:

> 

> 

> 

> 

> 

```yaml
custom_structured_configuration_ethernet_interfaces:
  Eth46:
    description: Foobar
    shutdown: false
    type: switched
    mode: dot1q-tunnel
    vlans: 104
```

### Expected results

```shell
!
interface Eth46
   description Foobar
   no shutdown
   switchport
   switchport mode dot1q-tunnel
   switchport access vlan 104
!
```

### Actual results

```shell
!
interface Eth46
   description Foobar
   no shutdown
   switchport
   switchport mode dot1q-tunnel
!
```
