### ISSUE TITLE
Not possible to extend static_routes yml key by custom_structured_configuration

### ISSUE THREAD

**Issue by c-po** [aristanetworks/ansible-avd#972]
## Issue Type

- [x] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

Given the current style how `static_routes` are defined in the YML definition out of eos_cli_config_gen and eos_designs it is not possible to extend the static routing table by means of `custom_structured_configuration` as `static_routes` are a list and that seems not to work.

## Component Name

* eos_cli_config_gen
* eos_designs 

## Steps to reproduce

```yml
custom_structured_configuration_list_merge: merge
custom_structured_configuration_prefix:
  - common__
  - network_type_common__

network_type_common__static_routes:
  - destination_address_prefix: 10.0.0.0/8
    vrf: DC_PROD
    gateway: 172.29.0.2
  
tenants:
  DC:
    mac_vrf_vni_base: 10000
    vrfs:
      DC_PROD:
        static_routes:
          - destination_address_prefix: 0.0.0.0/0
            gateway: 172.29.0.1
      DC_MGMT:
        static_routes:
          - destination_address_prefix: 0.0.0.0/0
            gateway: 172.29.1.1
```

### Expected results

```shell
ip route vrf DC_MGMT 0.0.0.0/0 172.29.1.1
ip route vrf DC_PROD 0.0.0.0/0 172.29.0.1
ip route vrf DC_PROD 10.0.0.0/8 172.29.0.2
```

### Actual results

```shell
ip route vrf DC_PROD 10.0.0.0/8 172.29.0.2
```
