### ISSUE TITLE
Endpoint adapters with multiple connections does not work correctly if `switches` are not entered in a sorted order

### ISSUE THREAD

**Issue by ClausHolbechArista** [aristanetworks/ansible-avd#977]
## Issue Type

- [x] Bug Report
- [ ] EOS Configuration rendering error
- [ ] Documentation Issue Report

## Summary

Endpoint adapters with multiple connections does not work correctly if `switches` are not entered in a sorted order

## Component Name
`arista.avd.eos_designs`

## Steps to reproduce

Adding extra interfaces to an existing adapter breaks the existing config, and does not render new interfaces correctly

```yaml
  server01_MTU_ADAPTOR_MLAG:
    rack: RackB
    adapters:
      - server_ports: [ Eth6, Eth7, Eth8, Eth9 ]
        switch_ports: [ Ethernet12, Ethernet12, Ethernet13, Ethernet13 ]
        switches: [ DC1-LEAF2A, DC1-LEAF2B, DC1-LEAF2A, DC1-LEAF2B ]
        mtu: 1601
        port_channel:
          description: PortChanne1
          mode: active
```

### Expected results

New interfaces should be added

### Actual results

Existing interfaces got partially changed/overwritten and new interfaces was not added correctly.
Issue is caused by a wrongful `arista.avd.natural_sort` in the template.
