### ISSUE TITLE
Multiple SVI inside same VRF

### ISSUE THREAD

**Issue by inetman28** [aristanetworks/ansible-avd#988]
**Issue Type**

- [x] Template enhancement
- [x] Role enhancement
- [x] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Arista-AVD doesn't create same SVI inside one VRF.

**Describe the solution you'd like**

I would like to have a feature which can create same SVI interface number (same vlan) on different switches. This is powerful in L3 fabric (without L2 VXLAN streaching). In this case we can use 1-4094 VLANs per each switch (or MLAG domain). Also, it makes easier hypervisor provisioning (or loadbalancer, or k8s services), because in diffirent rack we have same SVI number (but of couse, with different ip-network). 

**Describe alternatives you've considered**

I didn't find any alternatives. I am going to make one more role for this ;( If you have any suggestions - please share them

**Additional context**

Now I couldn't create same SVI number inside same VRF but on different switches. Example, what I would like to have:

leaf1: svi 101, net: 192.168.1.0/24, name: leaf1_k8s_prod_pod
leaf2: svi 101, net: 192.168.2.0/24, name: leaf2_k8s_prod_pod
leaf3: svi 101, net: 192.168.3.0/24, name: leaf3_k8s_prod_pod

```
        svis:
          101:
            name: leaf1_k8s_prod_pod
            tags: [leaf1]
            enabled: true
            ip_address_virtual: 192.168.1.1/24

          101:
            name: leaf2_k8s_prod_pod
            tags: [leaf2]
            enabled: true
            ip_address_virtual: 192.168.2.1/24

          101:
            name: leaf3_k8s_prod_pod
            tags: [leaf3]
            enabled: true
            ip_address_virtual: 192.168.3.1/24

```

**Comment by inetman28** [comment]
I've got workaround with host_vars variables. Example below

host_vars/switch1.yml
```
---
custom_structured_configuration_vlan_interfaces:
  Vlan4092:
    shutdown: false
    vrf: INFRA
    ip_address: 10.9.1.146/28
    ip_virtual_router_address: 10.9.1.145


custom_structured_configuration_vlans:
  4092:
    tenant: Tenant_A
    name: TEST
```

**Comment by ClausHolbechArista** [comment]
In PR #900 we will enable you to override the structured_config generate per svi. So you could set:
```yaml
        svis:
          101:
            name: k8s_prod_pod
            enabled: true
            nodes:
              leaf1a:
                structured_config:
                  ip_address_virtual: 192.168.1.1/24
              leaf1b:
                structured_config:
                  ip_address_virtual: 192.168.1.1/24
              leaf2a:
                structured_config:
                  ip_address_virtual: 192.168.2.1/24
              leaf2b:
                structured_config:
                  ip_address_virtual: 192.168.2.1/24
```
