### ISSUE TITLE
fabric documentation directory mismatch (build_output_folders vs eos_designs roles)

### ISSUE THREAD

**Issue by ksator** [aristanetworks/ansible-avd#991]
## Issue Type

- [x] Bug Report

## Summary

fabric documentation directory mismatch (`build_output_folders` vs `eos_designs roles`)

- build_output_folders uses: 
```
# Fabric documentation
fabric_dir_name: 'fabric'
fabric_dir: '{{ documentation_dir }}/{{ fabric_dir_name }}'
```

- eos_designs uses: 
```
    - name: Generate fabric documentation in Markdown Format.
      template:
        src: fabric-documentation.j2
        dest: "{{ root_dir }}/documentation/fabric/{{ fabric_name }}-documentation.md"
        mode: 0664
      changed_when: false
```

By default, it works (both roles will use the same dir .i.e `documentation/fabric`)  

But if you change the value of the variable `fabric_dir_name` then the directory `documentation/fabric/` wont be created by the role `build_output_folders` and  the task `Generate fabric documentation in Markdown Format` of `eos_designs` role will fail

## Component Name

build_output_folders  and eos_designs roles

## Steps to reproduce

But if you change the value of the variable `fabric_dir_name` if a playbook or in a variable file, then the directory `documentation/fabric/` wont be created by the role `build_output_folders` and  the task `Generate fabric documentation in Markdown Format` of `eos_designs` role will fail

### Expected results

both build_output_folders  and eos_designs roles should use the same directory   
we will use `documentation/fabric/`
