### ISSUE TITLE
eos_validate_state role whitelist transceiver vendors

### ISSUE THREAD

**Issue by jalmargyyk** [aristanetworks/ansible-avd#997]
**Issue Type**

- [ ] Template enhancement
- [x] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**
We are using 3rd party optics with a verified vendor from our point of view. eos_validate_state role  reports "transceivers manufacturers" as FAIL.

**Describe the solution you'd like**
 Make it possible to whitelist vendors via a variable.

**Describe alternatives you've considered**

**Additional context**

**Comment by ksator** [comment]
- role:  eos_validate_state  
- task: hardware.yml

current code
```
- name: Gather transceivers inventory
  eos_command:
    commands: "show inventory | json"
  register: inventory
  tags:
    - hardware

- name: Validate transceivers manufacturers
  assert:
    that:
      - "xcvrSlot.value.mfgName in ['Not Present', 'Arastra, Inc.', 'Arista Networks']"
    fail_msg: transceivers manufacturers is "{{ xcvrSlot.value.mfgName }}"
    quiet: true
  loop: "{{ inventory.stdout_lines.0.xcvrSlots | dict2items }}"
  loop_control:
    loop_var: xcvrSlot
  ignore_errors: "{{ eos_validate_state_validation_mode_loose }}"
  register: transceiver_inventory_results
  tags:
    - hardware
```
So this task reports transceivers that are not in this list:   
- 'Not Present'
- 'Arastra, Inc.'
- 'Arista Networks'

The above test is hardcoded in the task.  
It can be moved in a variable (defined in the role/default/main.yml).  
The default value of this list will be the same.
