### ISSUE TITLE
Add ability to set control plane ACL

### ISSUE THREAD

**Issue by melkypie** [aristanetworks/ansible-avd#998]
**Issue Type**

- [ ] Template enhancement
- [X] Role enhancement
- [ ] Documentation enhancement (avd.sh)

**Is your feature request related to a problem? Please describe.**

Some libraries require us to change the default control plane acl to allow ports through (ex. ocprometheus by default requires 8080). 

**Describe the solution you'd like**
Thinking of having a data model such as this
```yaml
system:
  control_plane:
    ipv4_acl: default-with-prometheus in
```

**Describe alternatives you've considered**

Using a custom template

**Additional context**

**Comment by ClausHolbechArista** [comment]
Studying the CLI syntax I suggest:
```yaml
system:
  control_plane:
    ip_access_group_in:
      name: < acl name >
      vrfs:
        < vrf name >:
          name: < acl_name >
```
I considered a dict with the acl name as key, but the same acl can be used on multiple vrfs, so that will not work.
